CREATE INDEX ZALBINKHEO.HPCLAUSEI4 
	ON ZALBINKHEO.HPCLAUSE ( KCATYP ASC , KCAIPB ASC , KCAALX ASC , KCAAVN ASC , KCAETAFF ASC , KCARSQ ASC , KCAOBJ ASC , KCAFOR ASC , KCAOPT ASC , KCAGAR ASC , KCACLNM1 ASC , KCACTX ASC , KCACLNM2 ASC , KCACLNM3 ASC )   
	; 
  
