CREATE INDEX ZALBINKHEO.HPCLAUSEI1 
	ON ZALBINKHEO.HPCLAUSE ( KCATYP ASC , KCAIPB ASC , KCAALX ASC , KCAAVN ASC , KCARSQ ASC , KCAOBJ ASC , KCAFOR ASC , KCAOPT ASC , KCAGAR ASC , KCACTX ASC , KCAGAR ASC , KCACLNM1 ASC , KCACLNM2 ASC , KCACLNM3 ASC )   
	; 
  
