CREATE INDEX ZALBINKHEO.HPCLAUSEI2 
	ON ZALBINKHEO.HPCLAUSE ( KCATYP ASC , KCAIPB ASC , KCAALX ASC , KCAAVN ASC , KCAFOR ASC , KCAOPT ASC , KCAETAFF ASC , KCARSQ ASC , KCAOBJ ASC , KCAGAR ASC , KCACLNM1 ASC , KCACTX ASC , KCACLNM2 ASC , KCACLNM3 ASC )   
	; 
  
