CREATE INDEX ZALBINKHEO.KALCEL0003 
	ON ZALBINKHEO.KALCEL0002 ( KEJNAT ASC , KEJINF1 ASC , KEJINF2 ASC , KEJNATID ASC )   
	; 
  
LABEL ON INDEX ZALBINKHEO.KALCEL0003 
	IS 'Ancien nom KALCELG2 de ZALBINKHEO, propr DAN.' ; 
  
