CREATE INDEX ZALBINKHEO.KALCEL0004 
	ON ZALBINKHEO.KALCEL0002 ( KEJACTG ASC , KEJETAPE ASC , KEJCTX ASC )   
	; 
  
LABEL ON INDEX ZALBINKHEO.KALCEL0004 
	IS 'Ancien nom KALCELG1 de ZALBINKHEO, propr DAN.' ; 
  
