CREATE INDEX ZALBINKHEO.KALCEL0005 
	ON ZALBINKHEO.KALCEL0002 ( KEJACTG ASC , KEJETAPE ASC , KEJCTX ASC )   
	; 
  
LABEL ON INDEX ZALBINKHEO.KALCEL0005 
	IS 'Ancien nom KALCELG3 de ZALBINKHEO, propr DAN.' ; 
  
