CREATE INDEX ZALBINKHEO.KPCLAUSEI14 
	ON ZALBINKHEO.KPCLAUSE ( KCATYP ASC , KCAIPB ASC , KCAALX ASC , KCAETAFF ASC , KCARSQ ASC , KCAOBJ ASC , KCAFOR ASC , KCAOPT ASC , KCAGAR ASC , KCACLNM1 ASC , KCACTX ASC , KCACLNM2 ASC , KCACLNM3 ASC )   
	; 
  
