CREATE INDEX ZALBINKHEO.KPGARH_IDXOPTTYPNIVFORALXSEQIPBCID 
	ON ZALBINKHEO.KPGARA0001 ( KDEOPT ASC , KDETYP ASC , KDENIVEAU ASC , KDEFOR ASC , KDEALX ASC , KDESEQ ASC , KDEIPB ASC , KDEKDCID ASC )   
	; 
  
