CREATE INDEX ZALBINKHEO.KPGARH_IDXOPTTYPNIVFORALXDARSEQIPBCID 
	ON ZALBINKHEO.KPGARA0001 ( KDEOPT ASC , KDETYP ASC , KDENIVEAU ASC , KDEFOR ASC , KDEALX ASC , KDEGARAN ASC , KDESEQ ASC , KDEIPB ASC , KDEKDCID ASC )   
	; 
  
