
namespace OP.DataAccess
{
    internal class HistorizationQueries
    {
        internal static readonly string GetNextIdSP = "SP_NCHRONO";

        internal static readonly string SelectBasicState = @"SELECT PBAVN AS NumeroAvenant, 
    PBETA AS EtatAffaire, 
    PBSIT AS SituationAffaire, 
    PBRSC AS MotifResiliation ,
    CAST ( LPAD(PBSTA, 4, '0') || LPAD(PBSTM, 2, '0') || LPAD(PBSTJ, 2, '0') || '000000' AS TIMESTAMP ) AS DateSituation , 
    PBADH AS LienAdresse 
FROM YPOBASE 
WHERE PBIPB = :CODEOFFRE AND PBALX = :VERSION AND PBTYP = :TYPE ;";

        internal static readonly string GetIdCopy = @"SELECT IFNULL ( KFLIDC , 0 ) FROM KPCOPID 
WHERE KFLIPB = :CODEOFFRE AND KFLALX = :VERSION AND KFLTYP = :TYPE 
AND KFLTAB = :TABLENAME AND KFLIDO = :CODEID ;";

        internal static readonly string GetKpentDcsObs = "SELECT KAAAVDS , 0 FROM KPENT WHERE KAAIPB = :CODEOFFRE AND KAAALX = :VERSION AND KAATYP = :TYPE ; ";
        internal static readonly string GetFrais = "SELECT JDAFR FROM YPRTENT WHERE JDIPB = :CODEOFFRE AND JDALX = :VERSION ;";

        internal static readonly string SelectDateAvenant = @"SELECT 
CAST ( CAST ( IFNULL ( PBAVA * 10000 + PBAVM * 100 + PBAVJ , 0 ) * 1000000 AS VARCHAR(32) ) AS TIMESTAMP ) 
FROM YPOBASE 
WHERE PBIPB = :CODEOFFRE AND PBALX = :VERSION AND PBTYP = :TYPE AND PBAVN = :NUMAVT ; ";
        internal static readonly string GetProchaineEcheance = "SELECT JDPEA , JDPEM , JDPEJ FROM YPRTENT WHERE JDIPB = :CODEOFFRE AND JDALX = :VERSION ;";
        internal static readonly string GetPeriodeBetween = @"SELECT KADPA , KADPM , KADPJ 
FROM YPRTPER 
WHERE KAIPB = :CODEOFFRE AND KAALX = :VERSION AND KARSQ = 0 AND KAFOR = 0 AND KATYP = 1 
AND :DT >= KADPA * 10000 + KADPM * 100 + KADPJ 
AND :DT <= KAFPA * 10000 + KAFPM * 100 + KAPFJ ;";
        internal static readonly string CountCtrlModif = "SELECT COUNT ( * ) FROM KPCTRLA WHERE KGTIPB = :CODEOFFRE AND KGTALX = :VERSION AND KGTTYP = :TYPE ;";
        internal static readonly string CountExistingHisto = @"SELECT COUNT ( * ) FROM YHPBASE 
WHERE PBIPB = :CODEOFFRE AND PBALX = :VERSION AND PBHTY = 'AVN' AND PBHIN = 1 
AND ( ( :TYPEAVT <> '' AND :MODEAVT = 'C' AND :NUMINTERNE <> 0 AND PBAVN >= :AVN ) OR ( :TYPEAVT = '' AND PBAVN = :AVN ) ) ;";

        internal static readonly string PurgeTraces = "DELETE FROM KPAVTRC WHERE KHOIPB = :CODEOFFRE AND KHOALX = :VERSION AND KHOTYP = :TYPE ;";
        internal static readonly string PurgeHistoIds = "DELETE FROM KPCOPID WHERE KFLIPB = :CODEOFFRE AND KFLALX = :VERSION AND KFLTYP = :TYPE ;";
        internal static readonly string PurgeQuittancesAnnulees = "DELETE FROM YWRTANP WHERE WWIPB = :CODEOFFRE AND WWALX = :VERSION ; ";
        internal static readonly string PurgeCtrlEtapes = "DELETE FROM KPCTRLE WHERE KEVIPB = :CODEOFFRE AND KEVALX = :VERSION AND KEVTYP = :TYPE AND KEVETAPE = :ETAPE ; ";
        internal static readonly string PurgeEcheanciers = @"DELETE FROM YPOECHE 
WHERE PIIPB = :CODEOFFRE AND PIALX = :VERSION AND PITYP = :TYPE 
AND ( PIEHE = '1' OR PIEHE = '2' AND PIIPK <> 0 ) ;";

        internal static readonly string PurgeSuspensions = @"DELETE FROM KPSUSP 
WHERE KICIPB = :CODEOFFRE AND KICALX = :VERSION AND KICTYP = :TYPE 
AND KICTYE = 'N' 
AND KICAVN = :NUMINTERNE 
AND KICDEBD * CAST ( 1000000 AS BIGINT ) + KICDEBH > ( IFNULL(:DATEFINGARANTIE,0) * CAST ( 1000000 AS BIGINT ) + IFNULL(:HEUREFINGARANTIE,0) ) ;";
        internal static readonly string PurgeClausesRegul = "DELETE FROM KPCLAUSE WHERE KCAIPB = :CODEOFFRE AND KCAALX = :VERSION AND KCATYP = :TYPE AND KCAETAPE = :ETAPE";
        internal static readonly string[] PurgePrimes = new[] {
            "DELETE FROM YPRIPCM WHERE PNIPB = :CODEOFFRE AND PNALX = :VERSION WITH NC ;",
            "DELETE FROM YPRIPES WHERE PKIPB = :CODEOFFRE AND PKALX = :VERSION WITH NC ;",
            "DELETE FROM YPRIPGA WHERE PLIPB = :CODEOFFRE AND PLALX = :VERSION WITH NC ;",
            "DELETE FROM YPRIPGK WHERE KVIPB = :CODEOFFRE AND KVALX = :VERSION WITH NC ;",
            "DELETE FROM YPRIPPA WHERE POIPB = :CODEOFFRE AND POALX = :VERSION WITH NC ;",
            "DELETE FROM YPRIPPK WHERE KYIPB = :CODEOFFRE AND KYALX = :VERSION WITH NC ;",
            "DELETE FROM YPRIPTA WHERE PTIPB = :CODEOFFRE AND PTALX = :VERSION WITH NC ;",
            "DELETE FROM YPRIPTG WHERE PUIPB = :CODEOFFRE AND PUALX = :VERSION WITH NC ;",
            "DELETE FROM YPRIPTX WHERE PMIPB = :CODEOFFRE AND PMALX = :VERSION WITH NC ;",
            "DELETE FROM YPRIRCM WHERE PNIPB = :CODEOFFRE AND PNALX = :VERSION WITH NC ;",
            "DELETE FROM YPRIRES WHERE PKIPB = :CODEOFFRE AND PKALX = :VERSION WITH NC ;",
            "DELETE FROM YPRIRGA WHERE PLIPB = :CODEOFFRE AND PLALX = :VERSION WITH NC ;",
            "DELETE FROM YPRIRGK WHERE KVIPB = :CODEOFFRE AND KVALX = :VERSION WITH NC ;",
            "DELETE FROM YPRIRPA WHERE POIPB = :CODEOFFRE AND POALX = :VERSION WITH NC ;",
            "DELETE FROM YPRIRPK WHERE KYIPB = :CODEOFFRE AND KYALX = :VERSION WITH NC ;",
            "DELETE FROM YPRIRTA WHERE PTIPB = :CODEOFFRE AND PTALX = :VERSION WITH NC ;",
            "DELETE FROM YPRIRTG WHERE PUIPB = :CODEOFFRE AND PUALX = :VERSION WITH NC ;",
            "DELETE FROM YPRIRTX WHERE PMIPB = :CODEOFFRE AND PMALX = :VERSION WITH NC ;",
        };

        internal static readonly string[] PurgeTempWordDocs = new[] {
            "DELETE FROM KPDOCW WHERE KEQIPB = :CODEOFFRE AND KEQALX = :VERSION AND KEQTYP = :TYPE AND KEQAVN = :AVN ;",
            "DELETE FROM KPDOCLDW WHERE KEMKELID IN ( SELECT KELID FROM KPDOCLW WHERE KELIPB = :CODEOFFRE AND KELALX = :VERSION AND KELTYP = :TYPE AND KELAVN = :AVN ) ;",
            "DELETE FROM KPDOCLW WHERE KELIPB = :CODEOFFRE AND KELALX = :VERSION AND KELTYP = :TYPE AND KELAVN = :AVN ;"
        };

        internal static readonly string GetCodeAdresse = "SELECT PBADH FROM YPOBASE WHERE PBIPB = :CODEOFFRE AND PBALX = :VERSION AND PBTYP = :TYPE ;";

        internal static readonly string CopyYPOBASE = @"INSERT INTO YHPBASE 
( PBIPB , PBALX , PBTYP , PBAVN , PBHIN , PBHIA , PBHIM , PBHIJ , PBHIH , PBHIU , PBTBR , PBIAS , PBREF , PBBRA , PBSBR , PBCAT , PBICT , PBTIL , PBINL , 
PBOCT , PBAD1 , PBAD2 , PBDEP , PBCPO , PBVIL , PBPAY , PBSAA , PBSAM , PBSAJ , PBSAH , PBAPR , PBAPP , PBMO1 , PBMO2 , PBMO3 , PBCLE , PBANT , 
PBCTD , PBCTU , PBAPO , PBDUR , PBREL , PBRLD , PBATT , PBRMP , PBVRF , PBOLV , PBFOA , PBFOM , PBCOU , PBFOE , PBDEV , PBRGT , PBTCO , PBNAT , 
PBDST , PBLIE , PBGES , PBSOU , PBORI , PBMAI , PBEFA , PBEFM , PBEFJ , PBOFF , PBOFV , PBIPA , PBALA , PBECM , PBECJ , PBPCV , PBCTA , PBNRQ , 
PBNPL , PBPER , PBAVC , PBAVA , PBAVM , PBAVJ , PBRSC , PBRSA , PBRSM , PBRSJ , PBMER , PBETA , PBSIT , PBSTA , PBSTM , PBSTJ , PBSTQ , PBEDT , 
PBTAC , PBTAA , PBTAM , PBTAJ , PBCRU , PBCRA , PBCRM , PBCRJ , PBMJU , PBMJA , PBMJM , PBMJJ , PBDEU , PBDEA , PBDEM , PBDEJ , PBCTP , PBEFH , 
PBFEA , PBFEM , PBFEJ , PBFEH , PBSTP , PBNVA , PBFEC , PBPOR , PBCON , PBTTR , PBAVK , PBADH , PBSTF , PBPIM , PBIN5 , PBORK , PBHTY , PBHNA , PBHDT , 
PBHZA ) 
( SELECT PBIPB , PBALX , PBTYP , CAST(:AVN AS INTEGER) , 1 , CAST(:HIA AS INTEGER) , CAST(:HIM AS INTEGER) , CAST(:HIJ AS INTEGER) , CAST(:HIH AS INTEGER) , '' , PBTBR , PBIAS , PBREF , PBBRA , PBSBR , PBCAT , PBICT , PBTIL , PBINL , 
PBOCT , PBAD1 , PBAD2 , PBDEP , PBCPO , PBVIL , PBPAY , PBSAA , PBSAM , PBSAJ , PBSAH , PBAPR , PBAPP , PBMO1 , PBMO2 , PBMO3 , PBCLE , PBANT , 
PBCTD , PBCTU , PBAPO , PBDUR , PBREL , PBRLD , PBATT , PBRMP , PBVRF , PBOLV , PBFOA , PBFOM , PBCOU , PBFOE , PBDEV , PBRGT , PBTCO , PBNAT , 
PBDST , PBLIE , PBGES , PBSOU , PBORI , PBMAI , PBEFA , PBEFM , PBEFJ , PBOFF , PBOFV , PBIPA , PBALA , PBECM , PBECJ , PBPCV , PBCTA , PBNRQ , 
PBNPL , PBPER , PBAVC , PBAVA , PBAVM , PBAVJ , PBRSC , PBRSA , PBRSM , PBRSJ , PBMER , PBETA , PBSIT , PBSTA , PBSTM , PBSTJ , PBSTQ , PBEDT , 
PBTAC , PBTAA , PBTAM , PBTAJ , PBCRU , PBCRA , PBCRM , PBCRJ , PBMJU , PBMJA , PBMJM , PBMJJ , PBDEU , PBDEA , PBDEM , PBDEJ , PBCTP , PBEFH , 
PBFEA , PBFEM , PBFEJ , PBFEH , PBSTP , PBNVA , PBFEC , PBPOR , PBCON , PBTTR , PBAVK , CAST(:NEWCODEADR AS INTEGER) , PBSTF , PBPIM , PBIN5 , PBORK , 'AVN' , 0 , 0 , '' 
FROM YPOBASE WHERE PBIPB = :CODEOFFRE AND PBALX = :VERSION AND PBTYP = :TYPE ) ;";

        internal static readonly string CopyYPRTENT = @"INSERT INTO YHRTENT 
( JDIPB , JDALX , JDAVN , JDHIN , JDSHT , JDENC , JDITC , JDVAL , JDVAA , JDVAW , JDVAT , JDVAU , JDVAH , JDDRQ , JDNBR , JDTXL , JDTRR , JDXCM , 
JDNEX , JDNPA , JDAFC , JDAFR , JDATT , JDCNA , JDCNC , JDINA , JDIND , JDIXC , JDIXF , JDIXL , JDIXP , JDIVO , JDIVA , JDIVW , JDMHT , JDREA , 
JDREB , JDREH , JDDPV , JDGAU , JDGVL , JDGUN , JDPBN , JDPBS , JDPBR , JDPBT , JDPBC , JDPBP , JDPBA , JDRCG , JDRCS , JDCCS , JDCLV , JDAGM , 
JDLCV , JDLCA , JDLCW , JDLCU , JDLCE , JDDPA , JDDPM , JDDPJ , JDFPA , JDFPM , JDFPJ , JDPEA , JDPEM , JDPEJ , JDACQ , JDTMC , 
JDTFO , JDTFT , JDTFF , JDTFP , JDPRO , JDTMI , JDTFM , JDTMA , JDTMG , JDCMC , JDCFO , JDCFT , JDCFH , JDCHT , JDCTT , JDCCP , JDEHH , JDEHC , 
JDSMP , JDIVX , JDTCR , JDNPG , JDEDI , JDEDN , JDEDA , JDEDM , JDEDJ , JDEHI , JDIAX , JDTED , JDDOO , JDRUA , JDRUM , JDRUJ , JDECG , JDECP , 
JDAPT , JDAPR , JDAAT , JDAAR , JDACR , JDACV , JDAXT , JDAXC , JDAXF , JDAXM , JDAXG , JDATA , JDATX , JDAUT , JDAUF ) 
( SELECT JDIPB , JDALX , CAST(:AVN AS INTEGER) , 1 , JDSHT , JDENC , JDITC , JDVAL , JDVAA , JDVAW , JDVAT , JDVAU , JDVAH , JDDRQ , JDNBR , JDTXL , JDTRR , JDXCM , 
JDNEX , JDNPA , JDAFC , JDAFR , JDATT , JDCNA , JDCNC , JDINA , JDIND , JDIXC , JDIXF , JDIXL , JDIXP , JDIVO , JDIVA , JDIVW , JDMHT , JDREA , 
JDREB , JDREH , JDDPV , JDGAU , JDGVL , JDGUN , JDPBN , JDPBS , JDPBR , JDPBT , JDPBC , JDPBP , JDPBA , JDRCG , JDRCS , JDCCS , JDCLV , JDAGM , 
JDLCV , JDLCA , JDLCW , JDLCU , JDLCE , JDDPA , JDDPM , JDDPJ , JDFPA , JDFPM , JDFPJ , JDPEA , JDPEM , JDPEJ , JDACQ , JDTMC , 
JDTFO , JDTFT , JDTFF , JDTFP , JDPRO , JDTMI , JDTFM , JDTMA , JDTMG , JDCMC , JDCFO , JDCFT , JDCFH , JDCHT , JDCTT , JDCCP , JDEHH , JDEHC , 
JDSMP , JDIVX , JDTCR , JDNPG , JDEDI , JDEDN , JDEDA , JDEDM , JDEDJ , JDEHI , JDIAX , JDTED , JDDOO , JDRUA , JDRUM , JDRUJ , JDECG , JDECP , 
JDAPT , JDAPR , JDAAT , JDAAR , JDACR , JDACV , JDAXT , JDAXC , JDAXF , JDAXM , JDAXG , JDATA , JDATX , JDAUT , JDAUF 
FROM YPRTENT WHERE JDIPB = :CODEOFFRE AND JDALX = :VERSION ) ;";

        internal static readonly string CopyKPENT = @"INSERT INTO HPENT 
( KAATYP , KAAIPB , KAAALX , KAAAVN , KAAHIN , KAABONI , KAABONT , KAAANTI , KAADESI , KAAOBSV , KAALCIVALO , KAALCIVALA , KAALCIVALW , KAALCIUNIT , 
KAALCIBASE , KAAKDIID , KAAFRHVALO , KAAFRHVALA , KAAFRHVALW , KAAFRHUNIT , KAAFRHBASE , KAAKDKID , KAAATGLCI , KAAATGKLC , KAAATGCAP , 
KAAATGKCA , KAAATGSUR , KAAATGBCN , KAAATGKBC , KAAATGCRI , KAAATGAPT , KAAATGF , KAAATGAPR , KAAATGTRT , KAAATGTRR , KAAATGTCT , KAAATGTCR , 
KAAATGTFT , KAAATGTCM , KAAATGTFA , KAAATGCTX , KAAATGLCF , KAAATGCAF , KAAATGSUF , KAAATGBCF , KAALCIINA , KAAATGFRR , KAAATGCMT , KAAATGFAT , 
KAAATGBAS , KAAATGKBA , KAAFRHINA , KAAAND , KAADPRJ , KAADSTA , KAAOBSF , KAAOBSA , KAAOBSC , KAAASS , KAAXCMS , KAACNCS , KAACIBLE , KAAMAXA , 
KAAMAXE , KAAIDE , KAAIMED , KAAIMDA , KAAISIN , KAARCP , KAAARTYG ) 
( SELECT KAATYP , KAAIPB , KAAALX , CAST(:AVN AS INTEGER) , 1 , KAABONI , KAABONT , KAAANTI , KAADESI , KAAOBSV , KAALCIVALO , KAALCIVALA , KAALCIVALW , KAALCIUNIT , 
KAALCIBASE , KAAKDIID , KAAFRHVALO , KAAFRHVALA , KAAFRHVALW , KAAFRHUNIT , KAAFRHBASE , KAAKDKID , KAAATGLCI , KAAATGKLC , KAAATGCAP , 
KAAATGKCA , KAAATGSUR , KAAATGBCN , KAAATGKBC , KAAATGCRI , KAAATGAPT , KAAATGF , KAAATGAPR , KAAATGTRT , KAAATGTRR , KAAATGTCT , KAAATGTCR , 
KAAATGTFT , KAAATGTCM , KAAATGTFA , KAAATGCTX , KAAATGLCF , KAAATGCAF , KAAATGSUF , KAAATGBCF , KAALCIINA , KAAATGFRR , KAAATGCMT , KAAATGFAT , 
KAAATGBAS , KAAATGKBA , KAAFRHINA , KAAAND , KAADPRJ , KAADSTA , KAAOBSF , KAAOBSA , KAAOBSC , KAAASS , KAAXCMS , KAACNCS , KAACIBLE , KAAMAXA , 
KAAMAXE , KAAIDE , KAAIMED , KAAIMDA , KAAISIN , KAARCP , KAAARTYG
FROM KPENT WHERE KAAIPB = :CODEOFFRE AND KAAALX = :VERSION AND KAATYP = :TYPE ) ;";

        internal static readonly string CopyYPOCOAS = @"INSERT INTO YHPCOAS 
( PHIPB , PHALX , PHTYP , PHAVN , PHHIN , PHTAP , PHCIE , PHINL , PHPOL , PHAPP , PHCOM , PHTXF , PHAFR , PHEPA , PHEPM , PHEPJ , PHFPA , PHFPM , 
PHFPJ , PHIN5 , PHTAC , PHTAA , PHTAM , PHTAJ ) 
( SELECT PHIPB , PHALX , PHTYP , CAST(:AVN AS INTEGER) , 1 , PHTAP , PHCIE , PHINL , PHPOL , PHAPP , PHCOM , PHTXF , PHAFR , PHEPA , PHEPM , PHEPJ , PHFPA , PHFPM , 
PHFPJ , PHIN5 , PHTAC , PHTAA , PHTAM , PHTAJ 
FROM YPOCOAS WHERE PHIPB = :CODEOFFRE AND PHALX = :VERSION ) ;";

        internal static readonly string CopyYPOASSU = @"INSERT INTO YHPASSU 
( PCIPB , PCALX , PCTYP , PCAVN , PCHIN , PCIAS , PCPRI , PCQL1 , PCQL2 , PCQL3 , PCQLD , PCCNR , PCASS , PCSCP , PCDESI ) 
( SELECT PCIPB , PCALX , PCTYP , CAST(:AVN AS INTEGER) , 1 , PCIAS , PCPRI , PCQL1 , PCQL2 , PCQL3 , PCQLD , PCCNR , PCASS , PCSCP , PCDESI 
FROM YPOASSU WHERE PCIPB = :CODEOFFRE AND PCALX = :VERSION ) ;";

        internal static readonly string CopyYPOASSX = @"INSERT INTO YHPASSX 
( PDIPB , PDALX , PDTYP , PDAVN , PDHIN , PDQL1 , PDQL2 , PDQL3 , PDQLD ) 
( SELECT PDIPB , PDALX , PDTYP , CAST(:AVN AS INTEGER) , 1 , PDQL1 , PDQL2 , PDQL3 , PDQLD 
FROM YPOASSX WHERE PDIPB = :CODEOFFRE AND PDALX = :VERSION ) ;";

        internal static readonly string CopyYPOECHE = @"INSERT INTO YHPECHE 
( PIIPB , PIALX , PITYP , PIAVN , PIHIN , PIEHA , PIEHM , PIEHJ , PIEHE , PIPCR , PIPCC , PIPMR , PIPMC , PIAFR , PIIPK , PIATT ) 
( SELECT PIIPB , PIALX , PITYP , CAST(:AVN AS INTEGER) , 1 , PIEHA , PIEHM , PIEHJ , PIEHE , PIPCR , PIPCC , PIPMR , PIPMC , PIAFR , PIIPK , PIATT 
FROM YPOECHE WHERE PIIPB = :CODEOFFRE AND PIALX = :VERSION ) ;";

        internal static readonly string CopyYPOINTE = @"INSERT INTO YHPINTE 
( PPIPB , PPALX , PPAVN , PPHIN , PPIIN , PPTYI , PPINL , PPPOL , PPSYM ) 
( SELECT PPIPB , PPALX , CAST(:AVN AS INTEGER) , 1 , PPIIN , PPTYI , PPINL , PPPOL , PPSYM 
FROM YPOINTE WHERE PPIPB = :CODEOFFRE AND PPALX = :VERSION ) ;";

        internal static readonly string CopyYPOCONX = @"INSERT INTO YHPCONX 
( PJTYP , PJCCX , PJCNX , PJIPB , PJALX , PJAVN , PJHIN , PJBRA , PJSBR , PJCAT , PJOBS , PJIDE ) 
( SELECT PJTYP , PJCCX , PJCNX , PJIPB , PJALX , CAST(:AVN AS INTEGER) , 1 , PJBRA , PJSBR , PJCAT , PJOBS , PJIDE 
FROM YPOCONX WHERE PJIPB = :CODEOFFRE AND PJALX = :VERSION AND PJTYP = :TYPE ) ;";

        internal static readonly string CopyYPOCOUR = @"INSERT INTO YHPCOUR 
( PFIPB , PFALX , PFTYP , PFAVN , PFHIN , PFCTI , PFICT , PFSAA , PFSAM , PFSAJ , PFSAH , PFSIT , PFSTA , PFSTM , PFSTJ , PFGES , PFSOU , PFCOM , PFOCT , 
PFXCM , PFXCN ) 
( SELECT PFIPB , PFALX , PFTYP , CAST(:AVN AS INTEGER) , 1 , PFCTI , PFICT , PFSAA , PFSAM , PFSAJ , PFSAH , PFSIT , PFSTA , PFSTM , PFSTJ , PFGES , PFSOU , PFCOM , PFOCT , 
PFXCM , PFXCN 
FROM YPOCOUR WHERE PFIPB = :CODEOFFRE AND PFALX = :VERSION ) ;";

        internal static readonly string CopyYPRTRSQ = @"INSERT INTO YHRTRSQ 
( JEIPB , JEALX , JEAVN , JEHIN , JERSQ , JECCH , JEMGD , JEBRA , JESBR , JECAT , JERCS , JECCS , JEVAL , JEVAA , JEVAW , JEVAT , JEVAU , JEVAH , JETEM , 
JEVGD , JEVGU , JEVDA , JEVDM , JEVDJ , JEVDH , JEVFA , JEVFM , JEVFJ , JEVFH , JEOBJ , JEROJ , JERGT , JETRR , JECNA , JEINA , JEIND , JEIXC , JEIXF , 
JEIXL , JEIXP , JEGAU , JEGVL , JEGUN , JEPBN , JEPBS , JEPBR , JEPBT , JEPBC , JEPBP , JEPBA , JECLV , JEAGM , JEIPM , JEIVX , JEDRO , JENBO , JELCV , 
JELCA , JELCW , JELCU , JELCE , JEAVE , JEAVA , JEAVM , JEAVJ , JERUL , JERUT , JEAVF , JEEXT ) 
( SELECT JEIPB , JEALX , CAST(:AVN AS INTEGER) , 1 , JERSQ , JECCH , JEMGD , JEBRA , JESBR , JECAT , JERCS , JECCS , JEVAL , JEVAA , JEVAW , JEVAT , JEVAU , JEVAH , JETEM , 
JEVGD , JEVGU , JEVDA , JEVDM , JEVDJ , JEVDH , JEVFA , JEVFM , JEVFJ , JEVFH , JEOBJ , JEROJ , JERGT , JETRR , JECNA , JEINA , JEIND , JEIXC , JEIXF , 
JEIXL , JEIXP , JEGAU , JEGVL , JEGUN , JEPBN , JEPBS , JEPBR , JEPBT , JEPBC , JEPBP , JEPBA , JECLV , JEAGM , JEIPM , JEIVX , JEDRO , JENBO , JELCV , 
JELCA , JELCW , JELCU , JELCE , JEAVE , JEAVA , JEAVM , JEAVJ , JERUL , JERUT , JEAVF , JEEXT 
FROM YPRTRSQ WHERE JEIPB = :CODEOFFRE AND JEALX = :VERSION ) ;";

        internal static readonly string CopyKPRSQ = @"INSERT INTO HPRSQ 
( KABTYP , KABIPB , KABALX , KABAVN , KABHIN , KABRSQ , KABCIBLE , KABDESC , KABDESI , KABOBSV , KABREPVAL , 
KABREPOBL , KABAPE , KABTRE , KABCLASS , KABNMC01 , KABNMC02 , KABNMC03 , KABNMC04 , 
KABNMC05 , KABMAND , KABMANF , KABDSPP , KABLCIVALO , KABLCIVALA , KABLCIVALW , 
KABLCIUNIT , KABLCIBASE , KABKDIID , KABFRHVALO , KABFRHVALA , KABFRHVALW , 
KABFRHUNIT , KABFRHBASE , KABKDKID , KABNSIR , KABMANDH , KABMANFH , KABSURF , KABVMC , KABPROL , KABPBI ) 
( SELECT KABTYP , KABIPB , KABALX , CAST(:AVN AS INTEGER) , 1 , KABRSQ , KABCIBLE , KABDESC , KABDESI , KABOBSV , KABREPVAL , 
KABREPOBL , KABAPE , KABTRE , KABCLASS , KABNMC01 , KABNMC02 , KABNMC03 , KABNMC04 , 
KABNMC05 , KABMAND , KABMANF , KABDSPP , KABLCIVALO , KABLCIVALA , KABLCIVALW , 
KABLCIUNIT , KABLCIBASE , KABKDIID , KABFRHVALO , KABFRHVALA , KABFRHVALW , 
KABFRHUNIT , KABFRHBASE , KABKDKID , KABNSIR , KABMANDH , KABMANFH , KABSURF , KABVMC , KABPROL , KABPBI 
FROM KPRSQ WHERE KABIPB = :CODEOFFRE AND KABALX = :VERSION AND KABTYP = :TYPE ) ;";

        internal static readonly string CopyYPRTOBJ = @"INSERT INTO YHRTOBJ 
( JGIPB , JGALX , JGAVN , JGHIN , JGRSQ , JGOBJ , JGCCH , JGIGD , JGBRA , JGSBR , JGCAT , JGRCS , JGCCS , JGVAL , JGVAA , JGVAW , JGVAT , JGVAU , 
JGVAH , JGNOJ , JGMMQ , JGMTY , JGMSR , JGMFA , JGTEM , JGVGD , JGVGU , JGVDA , JGVDM , JGVDJ , JGVDH , JGVFA , JGVFM , JGVFJ , JGVFH , JGRGT , 
JGTRR , JGCNA , JGINA , JGIND , JGIXC , JGIXF , JGIXL , JGIXP , JGIVO , JGIVA , JGIVW , JGGAU , JGGVL , JGGUN , JGPBN , JGPBS , JGPBR , JGPBT , 
JGPBC , JGPBP , JGPBA , JGCLV , JGAGM , JGAVE , JGAVA , JGAVM , JGAVJ , JGRUL , JGRUT , JGAVF ) 
( SELECT JGIPB , JGALX , CAST(:AVN AS INTEGER) , 1 , JGRSQ , JGOBJ , JGCCH , JGIGD , JGBRA , JGSBR , JGCAT , JGRCS , JGCCS , JGVAL , JGVAA , JGVAW , JGVAT , JGVAU , 
JGVAH , JGNOJ , JGMMQ , JGMTY , JGMSR , JGMFA , JGTEM , JGVGD , JGVGU , JGVDA , JGVDM , JGVDJ , JGVDH , JGVFA , JGVFM , JGVFJ , JGVFH , JGRGT , 
JGTRR , JGCNA , JGINA , JGIND , JGIXC , JGIXF , JGIXL , JGIXP , JGIVO , JGIVA , JGIVW , JGGAU , JGGVL , JGGUN , JGPBN , JGPBS , JGPBR , JGPBT , 
JGPBC , JGPBP , JGPBA , JGCLV , JGAGM , JGAVE , JGAVA , JGAVM , JGAVJ , JGRUL , JGRUT , JGAVF 
FROM YPRTOBJ WHERE JGIPB = :CODEOFFRE AND JGALX = :VERSION ) ;";

        internal static readonly string CopyKPOBJ = @"INSERT INTO HPOBJ 
( KACTYP , KACIPB , KACALX , KACAVN , KACHIN , KACRSQ , KACOBJ , KACCIBLE , KACINVEN , KACDESC , KACDESI , 
KACOBSV , KACAPE , KACTRE , KACCLASS , KACNMC01 , KACNMC02 , KACNMC03 , KACNMC04 , 
KACNMC05 , KACMAND , KACMANF , KACDSPP , KACLCIVALO , KACLCIVALA , KACLCIVALW , 
KACLCIUNIT , KACLCIBASE , KACKDIID , KACFRHVALO , KACFRHVALA , KACFRHVALW , 
KACFRHUNIT , KACFRHBASE , KACKDKID , KACNSIR , KACMANDH , KACMANFH , KACSURF , KACVMC , KACPROL , KACPBI , KACBRNT , KACBRNC , KACCM2 ) 
( SELECT KACTYP , KACIPB , KACALX , CAST(:AVN AS INTEGER) , 1 , KACRSQ , KACOBJ , KACCIBLE , KACINVEN , KACDESC , KACDESI , 
KACOBSV , KACAPE , KACTRE , KACCLASS , KACNMC01 , KACNMC02 , KACNMC03 , KACNMC04 , 
KACNMC05 , KACMAND , KACMANF , KACDSPP , KACLCIVALO , KACLCIVALA , KACLCIVALW , 
KACLCIUNIT , KACLCIBASE , KACKDIID , KACFRHVALO , KACFRHVALA , KACFRHVALW , 
KACFRHUNIT , KACFRHBASE , KACKDKID , KACNSIR , KACMANDH , KACMANFH , KACSURF , KACVMC , KACPROL , KACPBI , KACBRNT , KACBRNC , KACCM2
FROM KPOBJ WHERE KACIPB = :CODEOFFRE AND KACALX = :VERSION AND KACTYP = :TYPE ) ;";

        internal static readonly string CopyKPIRSOB = @"INSERT INTO HPIRSOB 
( KFATYP , KFAIPB , KFAALX , KFAAVN , KFAHIN , KFARSQ , KFAOBJ , KFANATS , KFANEGA , 
KFAFRQE , KFANBPA , KFANBEX , KFANBVI , KFAGN08 , KFAGN09 , KFAGN10 , 
KFANBIN , KFANBPE , KFAGCT , KFANBEM , KFATYTN , KFANMDF , KFAFENT , KFAFSVT , KFANMSC , KFALABD , KFANAI , KFALMA , KFAIFP ) 
( SELECT KFATYP , KFAIPB , KFAALX , CAST(:AVN AS INTEGER) , 1 , KFARSQ , KFAOBJ , KFANATS , KFANEGA , 
KFAFRQE , KFANBPA , KFANBEX , KFANBVI , KFAGN08 , KFAGN09 , KFAGN10 , 
KFANBIN , KFANBPE , KFAGCT , KFANBEM , KFATYTN , KFANMDF , KFAFENT , KFAFSVT , KFANMSC , KFALABD , KFANAI , KFALMA , KFAIFP 
FROM KPIRSOB WHERE KFAIPB = :CODEOFFRE AND KFAALX = :VERSION AND KFATYP = :TYPE ) ;";

        internal static readonly string CopyKPISVAL = @"INSERT INTO HPISVAL 
( KKCID, KKCTYP, KKCIPB, KKCALX, KKCAVN, KKCHIN, KKCRSQ, KKCOBJ, KKCFOR, KKCOPT, KKCKGBNMID, KKCVDEC, KKCVUN, 
KKCVDATD, KKCVHEUD, KKCVDATF, KKCVHEUF, KKCVTXT, KKCKFBID, KKCISVAL ) 
( SELECT KKCID, KKCTYP, KKCIPB, KKCALX , CAST(:AVN AS INTEGER) , 1 , KKCRSQ, KKCOBJ, KKCFOR, KKCOPT, KKCKGBNMID, KKCVDEC, KKCVUN, 
KKCVDATD, KKCVHEUD, KKCVDATF, KKCVHEUF, KKCVTXT, KKCKFBID, KKCISVAL 
FROM KPISVAL WHERE KKCIPB = :CODEOFFRE AND KKCALX = :VERSION AND KKCTYP = :TYPE ) ;";

        internal static readonly string CopyKPFOR = @"INSERT INTO HPFOR 
	( KDAID , KDAIPB , KDAALX , KDATYP , KDAAVN , KDAHIN , KDAFOR , KDACCH , KDAALPHA , KDABRA , KDACIBLE , KDAKAIID , KDADESC , KDACRU , KDACRD , KDAMAJU , KDAMAJD , KDAFGEN ) 
( SELECT KDAID , KDAIPB , KDAALX , KDATYP , CAST(:AVN AS INTEGER) , 1 , KDAFOR , KDACCH , KDAALPHA , KDABRA , KDACIBLE , KDAKAIID , KDADESC , KDACRU , KDACRD , KDAMAJU , KDAMAJD , KDAFGEN 
FROM KPFOR WHERE KDAIPB = :CODEOFFRE AND KDAALX = :VERSION AND KDATYP = :TYPE ) ;";

        internal static readonly string CopyKPOPT = @"INSERT INTO HPOPT 
	( KDBID , KDBIPB , KDBALX , KDBTYP , KDBAVN , KDBHIN , KDBFOR , KDBKDAID , KDBOPT , KDBDESC , KDBFORR , KDBKDAIDR , KDBSPEID , KDBCRU , KDBCRD , 
		KDBCRH , KDBMAJU , KDBMAJD , KDBMAJH , KDBPAQ , KDBACQ , KDBTMC , KDBTFF , KDBTFP , KDBPRO , KDBTMI , KDBTFM , KDBCMC , KDBCFO , KDBCHT , 
		KDBCTT , KDBCCP , KDBVAL , KDBVAA , KDBVAW , KDBVAT , KDBVAU , KDBVAH , KDBIVO , KDBIVA , KDBIVW , KDBAVE , KDBAVG , KDBECO , KDBAVA , KDBAVM , 
		KDBAVJ , KDBEHH , KDBEHC , KDBEHI , KDBASVALO , KDBASVALA , KDBASVALW , KDBASUNIT , KDBASBASE , KDBGER ) 
( SELECT KDBID , KDBIPB , KDBALX , KDBTYP , CAST(:AVN AS INTEGER) , 1 , KDBFOR , KDBKDAID , KDBOPT , KDBDESC , KDBFORR , KDBKDAIDR , KDBSPEID , KDBCRU , KDBCRD , 
		KDBCRH , KDBMAJU , KDBMAJD , KDBMAJH , KDBPAQ , KDBACQ , KDBTMC , KDBTFF , KDBTFP , KDBPRO , KDBTMI , KDBTFM , KDBCMC , KDBCFO , KDBCHT , 
		KDBCTT , KDBCCP , KDBVAL , KDBVAA , KDBVAW , KDBVAT , KDBVAU , KDBVAH , KDBIVO , KDBIVA , KDBIVW , KDBAVE , KDBAVG , KDBECO , KDBAVA , KDBAVM , 
		KDBAVJ , KDBEHH , KDBEHC , KDBEHI , KDBASVALO , KDBASVALA , KDBASVALW , KDBASUNIT , KDBASBASE , KDBGER 
FROM KPOPT WHERE KDBIPB = :CODEOFFRE AND KDBALX = :VERSION AND KDBTYP = :TYPE ) ;";

        internal static readonly string CopyKPIOPT = @"INSERT INTO HPIOPT 
	( KFCID , KFCIPB , KFCALX , KFCTYP , KFCAVN , KFCHIN , KFCFOR , KFCOPT , KFCKDBID , KFCRRCR , KFCRRC , KFCMNTE , KFCSEUI , KFCSEUR , KFCSEUC , KFCPERR , KFCAUTM , 
		KFCCRD , KFCCRH , KFCMAJU , KFCMAJD , KFCMAJH ) 
( SELECT KFCID , KFCIPB , KFCALX , KFCTYP , CAST(:AVN AS INTEGER) , 1 , KFCFOR , KFCOPT , KFCKDBID , KFCRRCR , KFCRRC , KFCMNTE , KFCSEUI , KFCSEUR , KFCSEUC , KFCPERR , KFCAUTM , 
		KFCCRD , KFCCRH , KFCMAJU , KFCMAJD , KFCMAJH 
FROM KPIOPT WHERE KFCIPB = :CODEOFFRE AND KFCALX = :VERSION AND KFCTYP = :TYPE ) ;";

        internal static readonly string CopyKPINVAPP = @"INSERT INTO HPINVAPP 
( KBGIPB , KBGALX , KBGTYP , KBGAVN , KBGHIN , KBGNUM , KBGKBEID , KBGPERI , KBGRSQ , KBGOBJ , KBGFOR , KBGGAR ) 
( SELECT KBGIPB , KBGALX , KBGTYP , CAST(:AVN AS INTEGER) , 1 , KBGNUM , KBGKBEID , KBGPERI , KBGRSQ , KBGOBJ , KBGFOR , KBGGAR 
FROM KPINVAPP WHERE KBGIPB = :CODEOFFRE AND KBGALX = :VERSION AND KBGTYP = :TYPE ) ;";

        internal static readonly string CopyKPINVEN = @"INSERT INTO HPINVEN 
( KBEID , KBEIPB , KBEALX , KBETYP , KBEAVN , KBEHIN , KBECHR , KBEDESC , KBEKAGID , KBEKADID , KBEREPVAL , KBEVAL , KBEVAA , KBEVAW , KBEVAT , KBEVAU , KBEVAH , KBEIVO , KBEIVA , KBEIVW ) 
( SELECT KBEID , KBEIPB , KBEALX , KBETYP , CAST(:AVN AS INTEGER) , 1 , KBECHR , KBEDESC , KBEKAGID , KBEKADID , KBEREPVAL , KBEVAL , KBEVAA , KBEVAW , KBEVAT , KBEVAU , KBEVAH , KBEIVO , KBEIVA , KBEIVW 
FROM KPINVEN WHERE KBEIPB = :CODEOFFRE AND KBEALX = :VERSION AND KBETYP = :TYPE ) ;";

        internal static readonly string CopyKPOPTD = @"INSERT INTO HPOPTD 
	( KDCID , KDCIPB , KDCALX , KDCTYP , KDCAVN , KDCHIN , KDCFOR , KDCOPT , KDCKDBID , KDCTENG , KDCKAKID , KDCKAEID , KDCKAQID , KDCMODELE , KDCKARID , 
	KDCCRU , KDCCRD , KDCMAJU , KDCMAJD , KDCFLAG ) 
( SELECT KDCID , KDCIPB , KDCALX , KDCTYP , CAST(:AVN AS INTEGER) , 1 , KDCFOR , KDCOPT , KDCKDBID , KDCTENG , KDCKAKID , KDCKAEID , KDCKAQID , KDCMODELE , KDCKARID , 
	KDCCRU , KDCCRD , KDCMAJU , KDCMAJD , KDCFLAG 
FROM KPOPTD WHERE KDCIPB = :CODEOFFRE AND KDCALX = :VERSION AND KDCTYP = :TYPE ) ;";

        internal static readonly string CopyKPOPTAP = @"INSERT INTO HPOPTAP 
	( KDDID , KDDIPB , KDDALX , KDDTYP , KDDAVN , KDDHIN , KDDFOR , KDDOPT , KDDKDBID , KDDPERI , KDDRSQ , KDDOBJ , KDDINVEN , KDDINVEP , KDDCRU , KDDCRD , KDDMAJU , KDDMAJD ) 
( SELECT KDDID , KDDIPB , KDDALX , KDDTYP , CAST(:AVN AS INTEGER) , 1 , KDDFOR , KDDOPT , KDDKDBID , KDDPERI , KDDRSQ , KDDOBJ , KDDINVEN , KDDINVEP , KDDCRU , KDDCRD , KDDMAJU , KDDMAJD 
FROM KPOPTAP WHERE KDDIPB = :CODEOFFRE AND KDDALX = :VERSION AND KDDTYP = :TYPE ) ;";

        internal static readonly string CopyKPGARAN = @"INSERT INTO HPGARAN 
	( KDEID , KDEIPB , KDEALX , KDETYP , KDEAVN , KDEHIN , KDEFOR , KDEOPT , KDEKDCID , KDEGARAN , KDESEQ , KDENIVEAU , KDESEM , KDESE1 , KDETRI , KDENUMPRES , 
	KDEAJOUT , KDECAR , KDENAT , KDEGAN , KDEKDFID , KDEDEFG , KDEKDHID , KDEDATDEB , KDEHEUDEB , KDEDATFIN , KDEHEUFIN , KDEDUREE , KDEDURUNI , KDEPRP , 
	KDETYPEMI , KDEALIREF , KDECATNAT , KDEINA , KDETAXCOD , KDETAXREP , KDECRAVN , KDECRU , KDECRD , KDEMAJAVN , KDEASVALO , KDEASVALA , KDEASVALW , 
	KDEASUNIT , KDEASBASE , KDEASMOD , KDEASOBLI , KDEINVSP , KDEINVEN , KDEWDDEB , KDEWHDEB , KDEWDFIN , KDEWHFIN , KDETCD , KDEMODI , KDEPIND , KDEPCATN , 
	KDEPREF , KDEPPRP , KDEPEMI , KDEPTAXC , KDEPNTM , KDEALA , KDEPALA , KDEALO ) 
( SELECT KDEID , KDEIPB , KDEALX , KDETYP , CAST(:AVN AS INTEGER) , 1 , KDEFOR , KDEOPT , KDEKDCID , KDEGARAN , KDESEQ , KDENIVEAU , KDESEM , KDESE1 , KDETRI , KDENUMPRES , 
	KDEAJOUT , KDECAR , KDENAT , KDEGAN , KDEKDFID , KDEDEFG , KDEKDHID , KDEDATDEB , KDEHEUDEB , KDEDATFIN , KDEHEUFIN , KDEDUREE , KDEDURUNI , KDEPRP , 
	KDETYPEMI , KDEALIREF , KDECATNAT , KDEINA , KDETAXCOD , KDETAXREP , KDECRAVN , KDECRU , KDECRD , KDEMAJAVN , KDEASVALO , KDEASVALA , KDEASVALW , 
	KDEASUNIT , KDEASBASE , KDEASMOD , KDEASOBLI , KDEINVSP , KDEINVEN , KDEWDDEB , KDEWHDEB , KDEWDFIN , KDEWHFIN , KDETCD , KDEMODI , KDEPIND , KDEPCATN , 
	KDEPREF , KDEPPRP , KDEPEMI , KDEPTAXC , KDEPNTM , KDEALA , KDEPALA , KDEALO 
FROM KPGARAN WHERE KDEIPB = :CODEOFFRE AND KDEALX = :VERSION AND KDETYP = :TYPE ) ;";

        internal static readonly string CopyKPGARTAR = @"INSERT INTO HPGARTAR 
	( KDGID , KDGIPB , KDGALX ,KDGTYP ,  KDGAVN , KDGHIN , KDGFOR , KDGOPT , KDGGARAN , KDGKDEID , KDGNUMTAR , KDGLCIMOD , KDGLCIOBL , KDGLCIVALO , KDGLCIVALA , 
	KDGLCIVALW , KDGLCIUNIT , KDGLCIBASE , KDGKDIID , KDGFRHMOD , KDGFRHOBL , KDGFRHVALO , KDGFRHVALA , KDGFRHVALW , KDGFRHUNIT , KDGFRHBASE , KDGKDKID , 
	KDGFMIVALA , KDGFMIVALO , KDGFMIVALW , KDGFMIUNIT , KDGFMIBASE , KDGFMAVALA , KDGFMAVALO , KDGFMAVALW , KDGFMAUNIT , KDGFMABASE , KDGPRIMOD , 
	KDGPRIOBL , KDGPRIVALO , KDGPRIVALA , KDGPRIVALW , KDGPRIUNIT , KDGPRIBASE , KDGMNTBASE , KDGPRIMPRO , KDGTMC , KDGTFF , KDGCMC , KDGCHT , KDGCTT ) 
( SELECT KDGID , KDGIPB , KDGALX ,KDGTYP , CAST(:AVN AS INTEGER) , 1 , KDGFOR , KDGOPT , KDGGARAN , KDGKDEID , KDGNUMTAR , KDGLCIMOD , KDGLCIOBL , KDGLCIVALO , KDGLCIVALA , 
	KDGLCIVALW , KDGLCIUNIT , KDGLCIBASE , 
	CASE WHEN KDGLCIUNIT <> 'CPX' THEN 0 ELSE KDGKDIID END , 
	KDGFRHMOD , KDGFRHOBL , KDGFRHVALO , KDGFRHVALA , KDGFRHVALW , KDGFRHUNIT , KDGFRHBASE , 
	CASE WHEN KDGFRHUNIT <> 'CPX' THEN 0 ELSE KDGKDKID END , 
	KDGFMIVALA , KDGFMIVALO , KDGFMIVALW , KDGFMIUNIT , KDGFMIBASE , KDGFMAVALA , KDGFMAVALO , KDGFMAVALW , KDGFMAUNIT , KDGFMABASE , KDGPRIMOD , 
	KDGPRIOBL , KDGPRIVALO , KDGPRIVALA , KDGPRIVALW , KDGPRIUNIT , KDGPRIBASE , KDGMNTBASE , KDGPRIMPRO , KDGTMC , KDGTFF , KDGCMC , KDGCHT , KDGCTT 
FROM KPGARTAR WHERE KDGIPB = :CODEOFFRE AND KDGALX = :VERSION AND KDGTYP = :TYPE ) ;";

        internal static readonly string CopyKPGARAP = @"INSERT INTO HPGARAP 
	( KDFID , KDFIPB , KDFALX , KDFTYP , KDFAVN , KDFHIN , KDFFOR , KDFOPT , KDFGARAN , KDFKDEID , KDFGAN , KDFPERI , KDFRSQ , KDFOBJ , KDFINVEN , KDFINVEP , 
	KDFCRU , KDFCRD , KDFMAJU , KDFMAJD , KDFPRV , KDFPRA , KDFPRW , KDFPRU , KDFTYC , KDFMNT ) 
( SELECT KDFID , KDFIPB , KDFALX , KDFTYP , CAST(:AVN AS INTEGER) , 1 , KDFFOR , KDFOPT , KDFGARAN , KDFKDEID , KDFGAN , KDFPERI , KDFRSQ , KDFOBJ , KDFINVEN , KDFINVEP , 
	KDFCRU , KDFCRD , KDFMAJU , KDFMAJD , KDFPRV , KDFPRA , KDFPRW , KDFPRU , KDFTYC , KDFMNT 
FROM KPGARAP WHERE KDFIPB = :CODEOFFRE AND KDFALX = :VERSION AND KDFTYP = :TYPE ) ;";

        internal static readonly string CopyKPIRSGA = @"INSERT INTO HPIRSGA 
	( KFDIPB , KFDALX , KFDTYP , KFDAVN , KFDHIN , KFDFOR , KFDOPT , KFDCRD , KFDCRH , KFDMAJU , KFDMAJD , KFDMAJH , KFDAN02 , KFDAN03 , KFDBO01 , KFDBO02 , KFDBO03 , 
	KFDIM08 , KFDIM09 , KFDIM10 , KFDNBGR , KFDEFFV , KFDCNVD , KFDFRDM , KFDSORN , KFDSORD , KFDSORR , KFD05 , KFD06 , KFD07 , KFD08 , KFD09 , KFDIA01 , KFDIA02 , KFDIA03 , 
	KFDIARA17 , KFDRSAT , KFDRCPS , KFDRCPF , KFDRCPD , KFDRASB , KFDRASL , KFDRASS , KFDCOTNB , KFDCOTMT , KFDMNT , KFDMNTNB , KFDMNTMT , KFDRGU , KFDNBJI , KFDAN04 , 
	KFDGARAV , KFDVOLAV , KFDVOLAP , KFDLMA , KFDMXM , KFDRAY , KFDAN05 , KFDRAY5 , KFDAN06 , KFDAN07 , KFDCLAL ) 
( SELECT KFDIPB , KFDALX , KFDTYP , CAST(:AVN AS INTEGER) , 1 , KFDFOR , KFDOPT , KFDCRD , KFDCRH , KFDMAJU , KFDMAJD , KFDMAJH , KFDAN02 , KFDAN03 , KFDBO01 , KFDBO02 , KFDBO03 , 
	KFDIM08 , KFDIM09 , KFDIM10 , KFDNBGR , KFDEFFV , KFDCNVD , KFDFRDM , KFDSORN , KFDSORD , KFDSORR , KFD05 , KFD06 , KFD07 , KFD08 , KFD09 , KFDIA01 , KFDIA02 , KFDIA03 , 
	KFDIARA17 , KFDRSAT , KFDRCPS , KFDRCPF , KFDRCPD , KFDRASB , KFDRASL , KFDRASS , KFDCOTNB , KFDCOTMT , KFDMNT , KFDMNTNB , KFDMNTMT , KFDRGU , KFDNBJI , KFDAN04 , 
	KFDGARAV , KFDVOLAV , KFDVOLAP , KFDLMA , KFDMXM , KFDRAY , KFDAN05 , KFDRAY5 , KFDAN06 , KFDAN07 , KFDCLAL 
	FROM KPIRSGA WHERE KFDIPB = :CODEOFFRE AND KFDALX = :VERSION AND KFDTYP = :TYPE ) ;";

        internal static readonly string CopyKPINVED = @"INSERT INTO HPINVED 
( KBFID , KBFIPB , KBFALX , KBFTYP , KBFAVN , KBFHIN , KBFKBEID , KBFNUMLGN , KBFDESC , KBFKADID , KBFSITE , KBFNTLI , KBFCP , KBFVILLE , KBFADH , KBFDATDEB , 
KBFDEBHEU , KBFDATFIN , KBFFINHEU , KBFMNT1 , KBFMNT2 , KBFNBEVN , KBFNBPER , KBFNOM , KBFDATNAI , KBFFONC , KBFCDEC , KBFCIP , KBFACCS , KBFAVPR , KBFMSR , KBFCMAT , KBFSEX , KBFMDQ , KBFMDA , KBFACTP , KBFKADFH , KBFEXT , 
KBFMNT3 , KBFMNT4 , KBFQUA , KBFREN , KBFRLO ) 
( SELECT KBFID , KBFIPB , KBFALX , KBFTYP , CAST(:AVN AS INTEGER) , 1 , KBFKBEID , KBFNUMLGN , KBFDESC , KBFKADID , KBFSITE , KBFNTLI , KBFCP , KBFVILLE , KBFADH , KBFDATDEB , 
KBFDEBHEU , KBFDATFIN , KBFFINHEU , KBFMNT1 , KBFMNT2 , KBFNBEVN , KBFNBPER , KBFNOM , KBFDATNAI , KBFFONC , KBFCDEC , KBFCIP , KBFACCS , KBFAVPR , KBFMSR , KBFCMAT , KBFSEX , KBFMDQ , KBFMDA , KBFACTP , KBFKADFH , KBFEXT , 
KBFMNT3 , KBFMNT4 , KBFQUA , KBFREN , KBFRLO 
FROM KPINVED WHERE KBFIPB = :CODEOFFRE AND KBFALX = :VERSION AND KBFTYP = :TYPE ) ;";

        internal static readonly string CopyKPCLAUSE = @"INSERT INTO HPCLAUSE 
( KCAID , KCATYP , KCAIPB , KCAALX , KCAAVN , KCAHIN , KCAETAPE , KCAPERI , KCARSQ , KCAOBJ , KCAINVEN , KCAINLGN , KCAFOR , KCAOPT , KCAGAR , KCACTX , KCAAJT , 
KCANTA , KCAKDUID , KCACLNM1 , KCACLNM2 , KCACLNM3 , KCAVER , KCATXL , KCAMER , KCADOC , KCACHI , KCACHIS , KCAIMP , KCACXI , KCAIAN , KCAIAC , KCASIT , 
KCASITD , KCAAVNC , KCACRD , KCAAVNM , KCAMAJD , KCASPA , KCATYPO , KCAAIM , KCATAE , KCAELGO , KCAELGI , KCAXTL , KCATYPD , KCAETAFF , KCAXTLM ) 
( SELECT KCAID , KCATYP , KCAIPB , KCAALX , CAST(:AVN AS INTEGER) , 1 , KCAETAPE , KCAPERI , KCARSQ , KCAOBJ , KCAINVEN , KCAINLGN , KCAFOR , KCAOPT , KCAGAR , KCACTX , KCAAJT , 
KCANTA , KCAKDUID , KCACLNM1 , KCACLNM2 , KCACLNM3 , KCAVER , KCATXL , KCAMER , KCADOC , KCACHI , KCACHIS , KCAIMP , KCACXI , KCAIAN , KCAIAC , KCASIT , 
KCASITD , KCAAVNC , KCACRD , KCAAVNM , KCAMAJD , KCASPA , KCATYPO , KCAAIM , KCATAE , KCAELGO , KCAELGI , KCAXTL , KCATYPD , KCAETAFF , KCAXTLM 
FROM KPCLAUSE 
WHERE KCAIPB = :CODEOFFRE AND KCAALX = :VERSION AND KCATYP = :TYPE ) ;";

        internal static readonly string CopyKPCOTGA = @"INSERT INTO HPCOTGA 
( KDNID , KDNTYP , KDNIPB , KDNALX , KDNAVN , KDNHIN , KDNFOR , KDNFOA , KDNOPT , KDNGARAN , KDNKDEID , KDNNUMTAR , KDNKDGID , KDNTAROK , KDNKDMID , KDNRSQ , KDNTRI , 
KDNHT , KDNHF , KDNKH , KDNMHT , KDNKHT , KDNMTX , KDNKTX , KDNTTC , KDNTTF , KDNMTT , KDNKTC , KDNCOT , KDNKCO , KDNCNAMHT , KDNCNAKHT , KDNCNAMTX , KDNCNAKTX , 
KDNCNAMTT , KDNCNAKTT , KDNCNACOM , KDNCNAKCM , KDNATGMHT , KDNATGKHT , KDNATGMTX , KDNATGKTX , KDNATGMTT , KDNATGKTT ) 
( SELECT KDNID , KDNTYP , KDNIPB , KDNALX , CAST(:AVN AS INTEGER) , 1 , KDNFOR , KDNFOA , KDNOPT , KDNGARAN , KDNKDEID , KDNNUMTAR , KDNKDGID , KDNTAROK , KDNKDMID , KDNRSQ , KDNTRI , 
KDNHT , KDNHF , KDNKH , KDNMHT , KDNKHT , KDNMTX , KDNKTX , KDNTTC , KDNTTF , KDNMTT , KDNKTC , KDNCOT , KDNKCO , KDNCNAMHT , KDNCNAKHT , KDNCNAMTX , KDNCNAKTX , 
KDNCNAMTT , KDNCNAKTT , KDNCNACOM , KDNCNAKCM , KDNATGMHT , KDNATGKHT , KDNATGMTX , KDNATGKTX , KDNATGMTT , KDNATGKTT 
FROM KPCOTGA WHERE KDNIPB = :CODEOFFRE AND KDNALX = :VERSION AND KDNTYP = :TYPE ) ";

        internal static readonly string CopyKPCOTIS = @"INSERT INTO HPCOTIS 
( KDMID , KDMTAP , KDMTYP , KDMIPB , KDMALX , KDMAVN , KDMHIN , KDMATGMHT , KDMATGKHT , KDMATGMTX , KDMATGKTX , KDMATGMTT , KDMATGKTT , KDMATGCOT , KDMATGKCO , KDMCNABAS , 
KDMCNAKBS , KDMCNAMHT , KDMCNAKHT , KDMCNAMTX , KDMCNAKTX , KDMCNAMTT , KDMCNAKTT , KDMCNACOB , KDMCNACNC , KDMCNATXF , KDMCNACNM , KDMCNACMF , KDMCNAKCM , KDMGARMHT , 
KDMGARMTX , KDMGARMTT , KDMHFMHT , KDMHFFLAG , KDMHFMHF , KDMHFMTX , KDMHFMTT , KDMAFRB , KDMAFR , KDMKFA , KDMAFT , KDMKFT , KDMFGA , KDMKFG , KDMMHT , KDMMHFLAG , 
KDMMHF , KDMKHT , KDMMTX , KDMKTX , KDMMTT , KDMMTFLAG , KDMTTF , KDMKTT , KDMCOB , KDMCOM , KDMCMF , KDMCOT , KDMCOF , KDMKCO , KDMCOEFC )	
( SELECT KDMID , KDMTAP , KDMTYP , KDMIPB , KDMALX , CAST(:AVN AS INTEGER) , 1 , KDMATGMHT , KDMATGKHT , KDMATGMTX , KDMATGKTX , KDMATGMTT , KDMATGKTT , KDMATGCOT , KDMATGKCO , KDMCNABAS , 
KDMCNAKBS , KDMCNAMHT , KDMCNAKHT , KDMCNAMTX , KDMCNAKTX , KDMCNAMTT , KDMCNAKTT , KDMCNACOB , KDMCNACNC , KDMCNATXF , KDMCNACNM , KDMCNACMF , KDMCNAKCM , KDMGARMHT , 
KDMGARMTX , KDMGARMTT , KDMHFMHT , KDMHFFLAG , KDMHFMHF , KDMHFMTX , KDMHFMTT , KDMAFRB , KDMAFR , KDMKFA , KDMAFT , KDMKFT , KDMFGA , KDMKFG , KDMMHT , KDMMHFLAG , 
KDMMHF , KDMKHT , KDMMTX , KDMKTX , KDMMTT , KDMMTFLAG , KDMTTF , KDMKTT , KDMCOB , KDMCOM , KDMCMF , KDMCOT , KDMCOF , KDMKCO , KDMCOEFC 
FROM KPCOTIS WHERE KDMIPB = :CODEOFFRE AND KDMALX = :VERSION AND KDMTYP = :TYPE ) ";

        internal static readonly string CopyKPCTRL = @"INSERT INTO HPCTRL 
( KEUID , KEUTYP , KEUIPB , KEUALX , KEUAVN , KEUHIN , KEUETAPE , KEUETORD , KEUORDR , KEUPERI , KEURSQ , KEUOBJ , KEUINVEN , KEUINLGN , KEUFOR , KEUOPT , KEUGAR , 
KEUMSG , KEUNIVM , KEUCRU , KEUCRD , KEUCRH ) 
( SELECT KEUID , KEUTYP , KEUIPB , KEUALX , CAST(:AVN AS INTEGER) , 1 , KEUETAPE , KEUETORD , KEUORDR , KEUPERI , KEURSQ , KEUOBJ , KEUINVEN , KEUINLGN , KEUFOR , KEUOPT , KEUGAR , 
KEUMSG , KEUNIVM , KEUCRU , KEUCRD , KEUCRH 
FROM KPCTRL WHERE KEUIPB = :CODEOFFRE AND KEUALX = :VERSION AND KEUTYP = :TYPE ) ;";

        internal static readonly string CopyKPCTRLE = @"INSERT INTO HPCTRLE 
( KEVTYP , KEVIPB , KEVALX , KEVAVN , KEVHIN , KEVETAPE , KEVETORD , KEVORDR , KEVPERI , KEVRSQ , KEVOBJ , KEVKBEID , KEVFOR , KEVOPT , KEVNIVM , KEVCRU , KEVCRD , 
KEVCRH , KEVMAJU , KEVMAJD , KEVMAJH , KEVTAG ) 
( SELECT KEVTYP , KEVIPB , KEVALX , CAST(:AVN AS INTEGER) , 1 , KEVETAPE , KEVETORD , KEVORDR , KEVPERI , KEVRSQ , KEVOBJ , KEVKBEID , KEVFOR , KEVOPT , KEVNIVM , KEVCRU , KEVCRD , 
KEVCRH , KEVMAJU , KEVMAJD , KEVMAJH , KEVTAG 
FROM KPCTRLE WHERE KEVIPB = :CODEOFFRE AND KEVALX = :VERSION AND KEVTYP = :TYPE ) ;";

        internal static readonly string CopyKPDESI = @"INSERT INTO HPDESI 
( KADCHR , KADIPB , KADALX , KADTYP , KADAVN , KADHIN , KADPERI , KADRSQ , KADOBJ , KADDESI ) 
( SELECT KADCHR , KADIPB , KADALX , KADTYP , CAST(:AVN AS INTEGER) , 1 , KADPERI , KADRSQ , KADOBJ , KADDESI 
FROM KPDESI WHERE KADIPB = :CODEOFFRE AND KADALX = :VERSION AND KADTYP = :TYPE ) ;";

        internal static readonly string CopyKPENG = @"INSERT INTO HPENG 
( KDOID , KDOIPB , KDOALX , KDOTYP , KDOAVN , KDOHIN , KDOECO , KDOACT , KDOENGID , KDODATD , KDODATF , KDOCRU , KDOCRD , KDOMAJU , KDOMAJD , KDONPL , KDOAPP , 
	KDOENG , KDOENA , KDOOBSV , KDOPCV , KDOLCT , KDOLCA , KDOCAT , KDOCAA ) 
( SELECT KDOID , KDOIPB , KDOALX , KDOTYP , CAST(:AVN AS INTEGER) , 1 , KDOECO , KDOACT , KDOENGID , KDODATD , KDODATF , KDOCRU , KDOCRD , KDOMAJU , KDOMAJD , KDONPL , KDOAPP , 
	KDOENG , KDOENA , KDOOBSV , KDOPCV , KDOLCT , KDOLCA , KDOCAT , KDOCAA
FROM KPENG 
WHERE KDOIPB = :CODEOFFRE AND KDOALX = :VERSION AND KDOTYP = :TYPE ) ;";

        internal static readonly string CopyKPENGFAM = @"INSERT INTO HPENGFAM 
( KDPID , KDPIPB , KDPALX , KDPTYP , KDPAVN , KDPHIN , KDPKDOID , KDPFAM , KDPENG , KDPENA , KDPCRU , KDPCRD , KDPMAJU , KDPMAJD , KDPLCT , KDPLCA , KDPCAT , KDPCAA ) 
( SELECT KDPID , KDPIPB , KDPALX , KDPTYP , CAST(:AVN AS INTEGER) , 1 , KDPKDOID , KDPFAM , KDPENG , KDPENA , KDPCRU , KDPCRD , KDPMAJU , KDPMAJD , KDPLCT , KDPLCA , KDPCAT , KDPCAA
FROM KPENGFAM 
WHERE KDPIPB = :CODEOFFRE AND KDPALX = :VERSION AND KDPTYP = :TYPE ) ;";

        internal static readonly string CopyKPENGGAR = @"INSERT INTO HPENGGAR 
( KDSID , KDSIPB , KDSALX , KDSTYP , KDSAVN , KDSHIN , KDSRSQ , KDSFAM , KDSVEN , KDSKDRID , KDSGARAN , KDSENGOK , KDSLCI , KDSSMP , KDSSMPF , KDSSMPU , KDSSMPR , KDSCRU , 
    KDSCRD , KDSMAJU , KDSMAJD , KDSKDOID , KDSCAT ) 
( SELECT KDSID , KDSIPB , KDSALX , KDSTYP , CAST(:AVN AS INTEGER) , 1 , KDSRSQ , KDSFAM , KDSVEN , KDSKDRID , KDSGARAN , KDSENGOK , KDSLCI , KDSSMP , KDSSMPF , KDSSMPU , KDSSMPR , KDSCRU , 
    KDSCRD , KDSMAJU , KDSMAJD , KDSKDOID , KDSCAT 
FROM KPENGGAR 
WHERE KDSIPB = :CODEOFFRE AND KDSALX = :VERSION AND KDSTYP = :TYPE ) ;";
        internal static readonly string CopyKPENGRSQ = @"INSERT INTO HPENGRSQ 
( KDRID , KDRIPB , KDRALX , KDRTYP , KDRAVN , KDRHIN , KDRRSQ , KDRKDQID , KDRFAM , KDRVEN , KDRLCI , KDRSMP , KDRENGC , KDRENGF , KDRENGOK , KDRCRU , KDRCRD , KDRMAJU , 
    KDRMAJD , KDRKDOID , KDRCAT , KDRSMF ) 
( SELECT KDRID , KDRIPB , KDRALX , KDRTYP , CAST(:AVN AS INTEGER) , 1 , KDRRSQ , KDRKDQID , KDRFAM , KDRVEN , KDRLCI , KDRSMP , KDRENGC , KDRENGF , KDRENGOK , KDRCRU , KDRCRD , KDRMAJU , 
    KDRMAJD , KDRKDOID , KDRCAT , KDRSMF 
FROM KPENGRSQ 
WHERE KDRIPB = :CODEOFFRE AND KDRALX = :VERSION AND KDRTYP = :TYPE ) ;";

        internal static readonly string CopyKPENGVEN = @"INSERT INTO HPENGVEN 
( KDQID , KDQIPB , KDQALX , KDQTYP , KDQAVN , KDQHIN , KDQKDPID , KDQFAM , KDQVEN , KDQENGC , KDQENGF , KDQENGOK , KDQCRU , KDQCRD , KDQMAJU , KDQMAJD , KDQLCT , KDQCAT , KDQKDOID ) 
( SELECT KDQID , KDQIPB , KDQALX , KDQTYP , CAST(:AVN AS INTEGER) , 1 , KDQKDPID , KDQFAM , KDQVEN , KDQENGC , KDQENGF , KDQENGOK , KDQCRU , KDQCRD , KDQMAJU , KDQMAJD , KDQLCT , KDQCAT , KDQKDOID 
FROM KPENGVEN 
WHERE KDQIPB = :CODEOFFRE AND KDQALX = :VERSION AND KDQTYP = :TYPE ) ;";

        internal static readonly string CopyKPEXPFRH = @"INSERT INTO HPEXPFRH 
( KDKID , KDKIPB , KDKALX , KDKTYP , KDKAVN , KDKHIN , KDKFHE , KDKDESC , KDKDESI , KDKORI , KDKMODI ) 
( SELECT KDKID , KDKIPB , KDKALX , KDKTYP , CAST(:AVN AS INTEGER) , 1 , KDKFHE , KDKDESC , KDKDESI , KDKORI , KDKMODI 
FROM KPEXPFRH WHERE KDKIPB = :CODEOFFRE AND KDKALX = :VERSION AND KDKTYP = :TYPE ) ;";

        internal static readonly string CopyKPEXPFRHD = @"INSERT INTO HPEXPFRHD 
( KDLID , KDLKDKID , KDLORDRE , KDLFHVAL , KDLFHVAU , KDLFHBASE , KDLIND , KDLIVO , KDLFHMINI , KDLFHMAXI , KDLLIMDEB , KDLLIMFIN , KDLAVN , KDLHIN ) 
( SELECT KDLID , KDLKDKID , KDLORDRE , KDLFHVAL , KDLFHVAU , KDLFHBASE , KDLIND , KDLIVO , KDLFHMINI , KDLFHMAXI , KDLLIMDEB , KDLLIMFIN , CAST(:AVN AS INTEGER), 1 
FROM KPEXPFRHD 
INNER JOIN KPEXPFRH ON KDLKDKID = KDKID 
AND KDKIPB = :CODEOFFRE AND KDKALX = :VERSION AND KDKTYP = :TYPE ) ;";

        internal static readonly string CopyKPEXPLCI = @"INSERT INTO HPEXPLCI 
( KDIID , KDIIPB , KDIALX , KDITYP , KDIAVN , KDIHIN , KDILCE , KDIDESC , KDIDESI , KDIORI , KDIMODI ) 
( SELECT KDIID , KDIIPB , KDIALX , KDITYP , CAST(:AVN AS INTEGER) , 1 , KDILCE , KDIDESC , KDIDESI , KDIORI , KDIMODI 
FROM KPEXPLCI WHERE KDIIPB = :CODEOFFRE AND KDIALX = :VERSION AND KDITYP = :TYPE ) ;";

        internal static readonly string CopyKPEXPLCID = @"INSERT INTO HPEXPLCID 
( KDJID , KDJKDIID , KDJORDRE , KDJLCVAL , KDJLCVAU , KDJLCBASE , KDJLOVAL , KDJLOVAU , KDJLOBASE , KDJAVN , KDJHIN ) 
( SELECT KDJID , KDJKDIID , KDJORDRE , KDJLCVAL , KDJLCVAU , KDJLCBASE , KDJLOVAL , KDJLOVAU , KDJLOBASE , CAST(:AVN AS INTEGER), 1 
FROM KPEXPLCI 
INNER JOIN KPEXPLCID ON KDJKDIID = KDIID 
AND KDIIPB = :CODEOFFRE AND KDIALX = :VERSION AND KDITYP = :TYPE ) ;";

        internal static readonly string CopyKPMATFF = @"INSERT INTO HPMATFF 
( KEAIPB , KEAALX , KEATYP , KEAAVN , KEAHIN , KEACHR , KEAFOR , KEAOPT , KEAKDBID , KEAKDAID ) 
( SELECT KEAIPB , KEAALX , KEATYP , CAST(:AVN AS INTEGER) , 1 , KEACHR , KEAFOR , KEAOPT , KEAKDBID , KEAKDAID 
FROM KPMATFF WHERE KEAIPB = :CODEOFFRE AND KEAALX = :VERSION AND KEATYP = :TYPE ) ;";

        internal static readonly string CopyKPMATFL = @"INSERT INTO HPMATFL 
( KECIPB , KECALX , KECTYP , KECAVN , KECHIN , KECKEACHR , KECKEBCHR , KECICO ) 
( SELECT KECIPB , KECALX , KECTYP , CAST(:AVN AS INTEGER) , 1 , KECKEACHR , KECKEBCHR , KECICO 
FROM KPMATFL WHERE KECIPB = :CODEOFFRE AND KECALX = :VERSION AND KECTYP = :TYPE ) ;";

        internal static readonly string CopyKPMATFR = @"INSERT INTO HPMATFR 
( KEBIPB , KEBALX , KEBTYP , KEBAVN , KEBHIN , KEBCHR , KEBTYE , KEBRSQ , KEBOBJ , KEBINV , KEBVID ) 
( SELECT KEBIPB , KEBALX , KEBTYP , CAST(:AVN AS INTEGER) , 1 , KEBCHR , KEBTYE , KEBRSQ , KEBOBJ , KEBINV , KEBVID 
FROM KPMATFR WHERE KEBIPB = :CODEOFFRE AND KEBALX = :VERSION AND KEBTYP = :TYPE ) ;";

        internal static readonly string CopyKPMATGG = @"INSERT INTO HPMATGG 
( KEEIPB , KEEALX , KEETYP , KEEAVN , KEEHIN , KEECHR , KEETYE , KEEKDCID , KEEVOLET , KEEKAKID , KEEBLOC , KEEKAEID , KEEGARAN , KEESEQ , KEENIV , KEEVID ) 
( SELECT KEEIPB , KEEALX , KEETYP , CAST(:AVN AS INTEGER) , 1 , KEECHR , KEETYE , KEEKDCID , KEEVOLET , KEEKAKID , KEEBLOC , KEEKAEID , KEEGARAN , KEESEQ , KEENIV , KEEVID 
FROM KPMATGG WHERE KEEIPB = :CODEOFFRE AND KEEALX = :VERSION AND KEETYP = :TYPE ) ;";

        internal static readonly string CopyKPMATGL = @"INSERT INTO HPMATGL 
( KEFIPB , KEFALX , KEFTYP , KEFAVN , KEFHIN , KEFKEDCHR , KEFKEECHR , KEFICO ) 
( SELECT KEFIPB , KEFALX , KEFTYP , CAST(:AVN AS INTEGER) , 1 , KEFKEDCHR , KEFKEECHR , KEFICO 
FROM KPMATGL WHERE KEFIPB = :CODEOFFRE AND KEFALX = :VERSION AND KEFTYP = :TYPE ) ;";

        internal static readonly string CopyKPMATGR = @"INSERT INTO HPMATGR 
( KEDIPB , KEDALX , KEDTYP , KEDAVN , KEDHIN , KEDCHR , KEDRSQ ) 
( SELECT KEDIPB , KEDALX , KEDTYP , CAST(:AVN AS INTEGER) , 1 , KEDCHR , KEDRSQ 
FROM KPMATGR WHERE KEDIPB = :CODEOFFRE AND KEDALX = :VERSION AND KEDTYP = :TYPE ) ;";

        internal static readonly string CopyKPOBSV = @"INSERT INTO HPOBSV ( KAJCHR , KAJTYP , KAJIPB , KAJALX , KAJAVN , KAJHIN , KAJTYPOBS , KAJOBSV ) 
( SELECT KAJCHR , KAJTYP , KAJIPB , KAJALX , CAST(:AVN AS INTEGER) , 1 , KAJTYPOBS , KAJOBSV 
FROM KPOBSV WHERE KAJIPB = :CODEOFFRE AND KAJALX = :VERSION AND KAJTYP = :TYPE ) ;";

        internal static readonly string CopyKPODBLS = @"INSERT INTO HPODBLS 
( KAFID , KAFTYP , KAFIPB , KAFALX , KAFAVN , KAFHIN , KAFICT , KAFSOU , KAFSAID , KAFSAIH , KAFSIT , KAFSITD , KAFSITH , KAFSITU , KAFCRD , KAFCRH , KAFCRU , KAFACT , KAFMOT ) 
( SELECT KAFID , KAFTYP , KAFIPB , KAFALX , CAST(:AVN AS INTEGER) , 1 , KAFICT , KAFSOU , KAFSAID , KAFSAIH , KAFSIT , KAFSITD , KAFSITH , KAFSITU , KAFCRD , KAFCRH , KAFCRU , KAFACT , KAFMOT 
FROM KPODBLS WHERE KAFIPB = :CODEOFFRE AND KAFALX = :VERSION AND KAFTYP = :TYPE ) ;";

        internal static readonly string CopyKPOPP = @"INSERT INTO HPOPP 
( KFPID , KFPTYP , KFPIPB , KFPALX , KFPAVN , KFPHIN , KFPIDCB , KFPTFI , KFPDESI , KFPREF , KFPDECH , KFPMNT , KFPCRU , KFPCRD , KFPCRH , KFPMAJU , KFPMAJD , KFPMAJH , KFPTDS , KFPTYI ) 
( SELECT KFPID , KFPTYP , KFPIPB , KFPALX , CAST(:AVN AS INTEGER) , 1 , KFPIDCB , KFPTFI , KFPDESI , KFPREF , KFPDECH , KFPMNT , KFPCRU , KFPCRD , KFPCRH , KFPMAJU , KFPMAJD , KFPMAJH , KFPTDS , KFPTYI 
FROM KPOPP WHERE KFPIPB = :CODEOFFRE AND KFPALX = :VERSION AND KFPTYP = :TYPE ) ;";

        internal static readonly string CopyKPOPPAP = @"INSERT INTO HPOPPAP 
( KFQID , KFQTYP , KFQIPB , KFQALX , KFQAVN , KFQHIN , KFQKFPID , KFQPERI , KFQRSQ , KFQOBJ , KFQCRU , KFQCRD , KFQMAJU , KFQMAJD ) 
( SELECT KFQID , KFQTYP , KFQIPB , KFQALX , CAST(:AVN AS INTEGER) , 1 , KFQKFPID , KFQPERI , KFQRSQ , KFQOBJ , KFQCRU , KFQCRD , KFQMAJU , KFQMAJD 
FROM KPOPPAP WHERE KFQIPB = :CODEOFFRE AND KFQALX = :VERSION AND KFQTYP = :TYPE ) ;";

        internal static readonly string CopyKPTRACE = @"INSERT INTO HPTRACE 
( KCCID , KCCTYP , KCCIPB , KCCALX , KCCAVN , KCCHIN , KCCETAPE , KCCPERI , KCCRSQ , KCCOBJ , KCCINVEN , KCCFOR , KCCOPT , KCCGAR , KCCSIT , KCCSITD , KCCSITH , KCCCRU , 
KCCCRD , KCCCRH , KCCMAJU , KCCMAJD , KCCMAJH ) 
( SELECT KCCID , KCCTYP , KCCIPB , KCCALX , CAST(:AVN AS INTEGER) , 1 , KCCETAPE , KCCPERI , KCCRSQ , KCCOBJ , KCCINVEN , KCCFOR , KCCOPT , KCCGAR , KCCSIT , KCCSITD , KCCSITH , KCCCRU , 
KCCCRD , KCCCRH , KCCMAJU , KCCMAJD , KCCMAJH 
FROM KPTRACE WHERE KCCIPB = :CODEOFFRE AND KCCALX = :VERSION AND KCCTYP = :TYPE ) ;";

        internal static readonly string CopyKPVALID = @"INSERT INTO HPVALID 
( KEXID , KEXTYP , KEXIPB , KEXALX , KEXAVN , KEXHIN , KEXCRVA , KEXLIB , KEXNIV ) 
( SELECT KEXID , KEXTYP , KEXIPB , KEXALX , CAST(:AVN AS INTEGER) , 1 , KEXCRVA , KEXLIB , KEXNIV 
FROM KPVALID WHERE KEXIPB = :CODEOFFRE AND KEXALX = :VERSION AND KEXTYP = :TYPE ) ;";

        internal static readonly string CopyKJOBSORTI = @"INSERT INTO HJOBSORTI 
( IPB, ALX, TYP, AVN, HIN, RSQ, OBJ, FORM, OPT, GARAN, DATEDEB, HEUREDEB, DATEFIN, HEUREFIN, SORTI ) 
( SELECT IPB, ALX, TYP, CAST(:AVN AS INTEGER), 1, RSQ, OBJ, FORM, OPT, GARAN, DATEDEB, HEUREDEB, DATEFIN, HEUREFIN, SORTI 
FROM KJOBSORTI 
WHERE ( IPB , ALX , TYP ) = ( :CODEOFFRE , :VERSION , :TYPE ) ) ;";

        internal static readonly string ResetKPCLAUSE = @"UPDATE KPCLAUSE 
SET KCAXTLM = 'N' 
WHERE KCAIPB = :CODEOFFRE AND KCAALX = :VERSION AND KCATYP = :TYPE ; ";

        internal static readonly string CleanupActeGestionKPCLAUSE = @"DELETE FROM KPCLAUSE 
WHERE KCAIPB = :CODEOFFRE AND KCAALX = :VERSION AND KCATYP = :TYPE AND (
KCAPERI IN ('AVNRM','AVNRS','ATTES','REGUL')
OR 
KCAETAPE IN ('AVNRM','AVNRS','ATTES','REGUL')
); ";

        internal static readonly string CopyExtraTablesKheops = "SP_HCOPYEXTRAKHEOTBL";
        internal static readonly string CopyAdresses = "SP_HCOPYADR";
        internal static readonly string SetDatesAvn = "SP_HUPDATEAVNDATES";
        internal static readonly string SetDates = "SP_SETDATES";

        internal static readonly string UpdateAvnYPOBASE = @"UPDATE YPOBASE 
SET PBETA = 'N' , PBSIT = :SIT , PBAVN = :NUMINTERNE , PBEDT = 'N' , PBTAC = 'N' , PBTAA = 0 , PBTAM = 0 , PBTAJ = 0 , 
PBTTR = :TYPEAVT , PBMJA = :YEARNOW , PBMJM = :MONTHNOW , PBMJJ = :DAYNOW , PBMJU = :USER , PBAVA = :YEAR , PBAVM = :MONTH , PBAVJ = :DAY , 
PBAVK = :NUMAVT , PBAVC = :AVC , PBRSC = '' , 
PBSTA = :YEARSIT , PBSTM = :MONTHSIT , PBSTJ = :DAYSIT 
WHERE PBIPB = :CODEOFFRE AND PBALX = :VERSION AND PBTYP = :TYPE ; ";

        internal static readonly string UpdateAvnREVYPOBASE = @"UPDATE YPOBASE 
SET PBETA = 'N' , PBSIT = :SIT , PBAVN = :NUMINTERNE , PBEDT = 'N' , PBTAC = 'N' , PBTAA = 0 , PBTAM = 0 , PBTAJ = 0 , 
PBTTR = :TYPEAVT , PBMJA = :YEARNOW , PBMJM = :MONTHNOW , PBMJJ = :DAYNOW , PBMJU = :USER , PBAVA = :YEAR , PBAVM = :MONTH , PBAVJ = :DAY , 
PBAVK = :NUMAVT , PBAVC = :AVC , PBRSC = '' , 
PBSTA = :YEARSIT , PBSTM = :MONTHSIT , PBSTJ = :DAYSIT , PBFEA = :PBFEA , PBFEM = :PBFEM , PBFEJ = :PBFEJ , PBFEH = :PBFEH
WHERE PBIPB = :CODEOFFRE AND PBALX = :VERSION AND PBTYP = :TYPE ; ";

        internal static readonly string UpdateRegulYPOBASE = @"UPDATE YPOBASE
SET PBETA = 'N' , PBAVN = :NUMINTERNE , PBEDT = 'N' , PBTAC = 'N' , PBTAA = 0 , PBTAM = 0 , PBTAJ = 0 , 
PBTTR = :TYPEAVT , PBMJA = :YEARNOW , PBMJM = :MONTHNOW , PBMJJ = :DAYNOW , PBMJU = :USER , 
PBAVK = :NUMAVT , PBAVC = 'M3' 
WHERE PBIPB = :CODEOFFRE AND PBALX = :VERSION AND PBTYP = :TYPE ; ";

        internal static readonly string UpdateResilYPOBASE = @"UPDATE YPOBASE 
SET PBETA = 'N' , PBAVN = :NUMINTERNE , PBEDT = 'N' , PBTAC = 'N' , PBTAA = 0 , PBTAM = 0 , PBTAJ = 0 , PBTTR = :TYPEAVT , 
    PBSTA = :YEARNOW , PBSTM = :MONTHNOW , PBSTJ = :DAYNOW , PBMJA = :YEARNOW , PBMJM = :MONTHNOW , PBMJJ = :DAYNOW , 
	PBFEA = :YEARRSL , PBFEM = :MONTHRSL , PBFEJ = :DAYRSL , PBFEH = :HEURERSL , 
	PBSIT = 'X' , PBMJU = :USER , 
	PBRSA = :YEARRSL , PBRSM = :MONTHRSL , PBRSJ = :DAYRSL , PBAVA = :YEARAVN , PBAVM = :MONTHAVN , PBAVJ = :DAYAVN , PBAVK = :NUMAVT , PBAVC = 'RS' , PBRSC = :MOTIF ,
    PBCTD = 0 , PBCTU = '' 
WHERE PBIPB = :CODEOFFRE AND PBALX = :VERSION AND PBTYP = :TYPE ;";

        internal static readonly string UpdateMotifResil = @"UPDATE YPOBASE SET PBRSC = :MOTIF 
WHERE ( PBIPB , PBALX , PBTYP ) = ( :CODEOFFRE , :VERSION , :TYPE ) ;";

        internal static readonly string UpdateAvnYPRTENT = @"UPDATE YPRTENT 
SET JDTED = 'ST' , JDDOO = '' 
WHERE JDIPB = :CODEOFFRE AND JDALX = :VERSION ; ";

        internal static readonly string CancelProchaineEcheance = "UPDATE YPRTENT SET JDPEA = 0 , JDPEM = 0 , JDPEJ = 0 WHERE JDIPB = :CODEOFFRE AND JDALX = :VERSION ;";
        internal static readonly string CloturerExcercice = @"UPDATE YPRTENT 
SET JDDPA = :PERYEAR , JDDPM = :PERMONTH , JDDPJ = :PERDAY , 
    JDFPA = :YEARRSL , JDFPM = :MONTHRSL , JDFPJ = :DAYRSL 
WHERE JDIPB = :CODEOFFRE AND JDALX = :VERSION ;";

        internal static readonly string LibererGaranties = "SP_HLIBERERGAR";
        internal static readonly string SetSuspension = @"UPDATE KPSUSP 
SET KICREVD = :DATEDEBAVT , 
	KICREVH = :HEUREDEBAVT , 
	KICMJU = :USER , 
	KICMJD = :DATENOW , 
	KICMJH = :HEURENOW , 
    KICACA = 'N', 
    KICSIT = 'N'
WHERE KICSIT = 'A' 
AND KICAVN = ( :NUMINTERNE - 1 )
AND KICIPK = :NUMPRIME
AND KICNUR != 0 
AND KICIPB = :CODEOFFRE 
AND KICALX = :VERSION 
AND KICTYP = :TYPE ;";

        internal static readonly string AddCtrlDateAvn = @"INSERT INTO KPCTRLA 
( KGTIPB , KGTALX , KGTTYP , KGTETAPE , KGTLIB , KGTCRU , KGTCRD , KGTCRH , KGTMAJU , KGTMAJD , KGTMAJH ) 
VALUES 
( :CODEOFFRE , :VERSION, :TYPE , 'GEN' , 'Date d''avenant' , :USER , :DATENOW , 0 , :USER , :DATENOW , 0 ) ;";

        internal static readonly string AddAdresseCopy = @"INSERT INTO YADRESS 
( ABPCHR , ABPLG3 , ABPNUM , ABPEXT , ABPLBN , ABPLG4 , ABPL4F , ABPLG5 , ABPDP6 , ABPCP6 , ABPVI6 , 
	ABPCDX , ABPCEX , ABPL6F , ABPPAY , ABPLOC , ABPMAT , ABPRET , ABPERR , ABPMJU , ABPMJA , ABPMJM , ABPMJJ , ABPVIX )
( SELECT CAST (:NEWCODEADR AS INTEGER), ABPLG3 , ABPNUM , ABPEXT , ABPLBN , ABPLG4 , ABPL4F , ABPLG5 , ABPDP6 , ABPCP6 , ABPVI6 , 
	ABPCDX , ABPCEX , ABPL6F , ABPPAY , ABPLOC , ABPMAT , ABPRET , ABPERR , ABPMJU , ABPMJA , ABPMJM , ABPMJJ , ABPVIX 
	FROM YADRESS WHERE ABPCHR = :LIENADR ) ;";

        internal static readonly string AddDesignation = @"INSERT INTO KPDESI 
( KADIPB , KADALX , KADTYP , KADCHR , KADPERI , KADRSQ , KADOBJ , KADDESI ) 
VALUES 	( :CODEOFFRE , :VERSION , :TYPE , :CHR , '' , 0 , 0 , :DESI ) ;";

        internal static readonly string UpdateDesignation = "UPDATE KPDESI SET KADDESI = :DESI WHERE KADCHR = :CHR ;";

        internal static readonly string AddObservations = @"INSERT INTO KPOBSV 
( KAJIPB , KAJALX , KAJTYP , KAJCHR , KAJTYPOBS , KAJOBSV ) 
VALUES ( :CODEOFFRE , :VERSION , :TYPE, :CHR , 'GENERALE' , :OBSERVATIONS ) ;";

        internal static readonly string UpdateObservations = "UPDATE KPOBSV SET KAJOBSV = :OBSERVATIONS WHERE KAJCHR = :CHR ;";
        internal static readonly string UpdateKpentDcsObs = @"UPDATE KPENT 
SET KAAAVDS = :CODEDESCR 
WHERE KAAIPB = :CODEOFFRE AND KAAALX = :VERSION AND KAATYP = :TYPE ;";

        internal static readonly string UpdateKpentFrais = @"UPDATE KPENT 
SET KAAAVH = :HEUREAVN , KAAAFS = :CODEFRAIS 
WHERE KAAIPB = :CODEOFFRE AND KAAALX = :VERSION AND KAATYP = :TYPE ;";

        internal static readonly string UpdateKpentRemiseEnVigueur = @"UPDATE KPENT 
SET KAAAVH = :HEUREAVN , KAAAFS = :CODEFRAIS, KAARSDD = :DATEFINGARANTIE , KAARSDH = :HEUREFINGARANTIE
WHERE KAAIPB = :CODEOFFRE AND KAAALX = :VERSION AND KAATYP = :TYPE ;";

        internal static readonly string AddSuspension = @"INSERT INTO KPSUSP 
( KICIPB , KICALX , KICTYP , KICID , KICTYE , KICIPK , KICNUR , KICORI , 
	KICDEBM , KICDEBD , KICDEBH , KICFINM , KICFIND , KICFINH , KICRSAD , 
	KICRSAH , KICREVD , KICREVH , KICCRU , KICCRD , KICCRH , KICAVN , KICMJU , KICMJD , KICMJH , KICSIT , 
	KICSTU , KICSTD , KICSTH , KICACA ) 
VALUES 
( :CODEOFFRE , :VERSION , :TYPE , :CODESUSP , 'N' , 0 , 0 , 'AVNRM' , 
	'AVNRM' , :DATEFINEFFET , :HEUREFINEFFET , '' , :DATERV , :HEURERV , 0 , 
	0 , 0 , 0 , :USER , :DATENOW , :HEURENOW , :NUMINTERNE , :USER , :DATENOW , :HEURENOW , 'A' , 
	:USER , :DATENOW , :HEURENOW , 'N' ) ;";
    }
}
