
namespace ALBINGIA.Framework.Common.Constants {
    public enum AlbParameterName {
        _hidden = 0,
        AVNID,
        AVNIDEXTERNE,
        AVNTYPE,
        AVNTYPERESIL,
        AVNMODE,
        IGNOREREADONLY,
        FORCEREADONLY,
        MODENAVIG,
        ACCESSMODEENG,
        AVNREFRESHUSERUPDATE,
        ORIGINPAGE,
        ORIGINID,
        OBJETSORTI,
        VALIDATION,
        ATTESTID,
        REGULEID,
        LOTID,
        RSQID,
        GARID,
        REGULGARID,
        ACTEGESTIONREGULE,
        REGULMOD,
        REGULTYP,
        REGULNIV,
        REGULAVN,
        LUSR,
        BRANCHEOFFRE,
        TEMPLATEID,
        CONTEXTCLAUSIER,
        COPY_ADR_FROM_HEADER,
        PROVENANCE
    }
}