CREATE OR REPLACE PROCEDURE [ENVCIBLE] . SP_COPIEDOCEXT_DOC ( 
	IN P_CODESOURCE CHAR ( 9 ) , 
	IN P_VERSIONSOURCE INTEGER , 
	IN P_TYPESOURCE CHAR ( 1 ) ,
	IN P_OLDCHEMIN CHAR ( 255 ) ,
	IN P_NEWCHEMIN CHAR ( 255 ) ,
	IN P_DATESYSTEME CHAR ( 8 ) , 
	IN P_USER CHAR ( 15 ) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC [ENVCIBLE] . SP_COPIEDOCEXT_DOC 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31 , 31 , 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
	
	DECLARE V_NEWID INTEGER DEFAULT 0 ;
	DECLARE V_NEWNAME CHAR(255) DEFAULT '' ;
	DECLARE V_OLDCHEMIN VARCHAR(255) DEFAULT '' ;
	DECLARE V_NEWCHEMIN VARCHAR(255) DEFAULT '' ;

	set V_OLDCHEMIN = LOWER(TRIM(P_OLDCHEMIN));
	SET V_NEWCHEMIN = LOWER(TRIM(P_NEWCHEMIN));
	-- Nettoyage de la table KPCOPDC
	DELETE FROM [ENVCIBLE] . KPCOPDC WHERE KHQIPB = P_CODESOURCE;
		
	-- Recopie du contenu de la table KPDOCEXT source vers la cible des documents (canevas)
	-- remplacement présente dans KPDOCEXT/KERCHM
	
	FOR LOOP_CNVDOC AS FREE_LIST CURSOR FOR 
		SELECT KERID , KERTYP , KERIPB , KERALX , KERSUA , KERNUM , KERSBR , KERSERV , KERACTG , KERAVN , KERORD , KERTYPO , KERLIB , KERNOM ,  KERCHM , KERSTU , KERSIT , KERSTD , KERSTH , KERCRU , KERCRD , KERCRH , KERREF 
		FROM [ENVSOURCE].KPDOCEXT 
		WHERE KERIPB = P_CODESOURCE AND KERALX = P_VERSIONSOURCE AND KERTYP = P_TYPESOURCE 
	DO 
		IF POSITION ( V_OLDCHEMIN IN LOWER( KERCHM ) ) = 1 THEN 
			
			SET V_NEWNAME = ( V_NEWCHEMIN || SUBSTR( TRIM(KERCHM) , length(V_OLDCHEMIN)+1, length(TRIM(KERCHM)) - length(V_OLDCHEMIN) ));

			CALL [ENVCIBLE] . SP_NCHRONO ( 'KERID' , V_NEWID ) ; 
			
			INSERT INTO [ENVCIBLE].KPDOCEXT ( KERID , KERTYP , KERIPB , KERALX , KERSUA , KERNUM , KERSBR , KERSERV , KERACTG , KERAVN , KERORD , KERTYPO , KERLIB , KERNOM , KERCHM , KERSTU , KERSIT , KERSTD , KERSTH , KERCRU , KERCRD , KERCRH , KERREF )
			VALUES ( V_NEWID , KERTYP , KERIPB , KERALX , KERSUA , KERNUM , KERSBR , KERSERV , KERACTG , KERAVN , KERORD , KERTYPO , KERLIB , KERNOM , V_NEWNAME, KERSTU , KERSIT , KERSTD , KERSTH , KERCRU , KERCRD , KERCRH , KERREF );
						
			-- Alimenter la table KPCOPDC à partir de [ENVCIBLE].KPDOCEXT
			INSERT INTO [ENVCIBLE] . KPCOPDC ( KHQTYP , KHQIPB , KHQALX , KHQAVN , KHQOLDC , KHQCODE , KHQNOMD , KHQTABLE , KHQOLDID )
			VALUES ( P_TYPESOURCE , P_CODESOURCE , P_VERSIONSOURCE , 0 , KERCHM , V_NEWID , V_NEWNAME , 'KPDOCEXT' , 0 );
		END IF;
	END FOR ;	
	
	-- Mise à jour KPCLAUSE avec le nouvel ID
	UPDATE [ENVCIBLE] . KPCLAUSE SET KCATXL = V_NEWID WHERE KCAIPB = P_CODESOURCE AND KCAALX = P_VERSIONSOURCE AND KCATYP = P_TYPESOURCE;
	
END P1