CREATE OR REPLACE PROCEDURE [ENVCIBLE].SP_DELETEOFFRE_DOC ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) ) 
	LANGUAGE SQL 
	SPECIFIC [ENVCIBLE].SP_DELETEOFFRE_DOC 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
FOR LOOP_POBASE AS FREE_LIST CURSOR FOR 
SELECT PBADH ADRID FROM [ENVCIBLE] . YPOBASE WHERE PBIPB = P_CODEOFFRE AND PBALX = P_VERSION AND PBTYP = P_TYPE 
DO 
DELETE FROM [ENVCIBLE] . YADRESS WHERE ABPCHR = ADRID ; 
DELETE FROM [ENVCIBLE] . YPOBASE WHERE PBIPB = P_CODEOFFRE AND PBALX = P_VERSION AND PBTYP = P_TYPE ; 
END FOR ; 
  
DELETE FROM [ENVCIBLE] . YPRTENT WHERE JDIPB = P_CODEOFFRE AND JDALX = P_VERSION ; 
DELETE FROM [ENVCIBLE] . KPENT WHERE KAAIPB = P_CODEOFFRE AND KAAALX = P_VERSION AND KAATYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . YPOCOAS WHERE PHIPB = P_CODEOFFRE AND PHALX = P_VERSION ;  -- AND PHTYP = P_TYPE; 
DELETE FROM [ENVCIBLE] . YPOASSU WHERE PCIPB = P_CODEOFFRE AND PCALX = P_VERSION ;  -- AND PCTYP = P_TYPE;    
DELETE FROM [ENVCIBLE] . YPOASSX WHERE PDIPB = P_CODEOFFRE AND PDALX = P_VERSION ;  -- AND PDTYP = P_TYPE;   
DELETE FROM [ENVCIBLE] . YPOCOUR WHERE PFIPB = P_CODEOFFRE AND PFALX = P_VERSION ;  -- AND PFTYP = P_TYPE;     
DELETE FROM [ENVCIBLE] . YPRTRSQ WHERE JEIPB = P_CODEOFFRE AND JEALX = P_VERSION ;  -- AND JETYP = P_TYPE;      
DELETE FROM [ENVCIBLE] . KPRSQ WHERE KABIPB = P_CODEOFFRE AND KABALX = P_VERSION AND KABTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . YPRTOBJ WHERE JGIPB = P_CODEOFFRE AND JGALX = P_VERSION ;  -- AND JGTYP = P_TYPE;     
FOR CURSOR_ADR AS FREE_LIST CURSOR FOR 
SELECT JFADH ADRID FROM [ENVCIBLE] . YPRTADR WHERE JFIPB = P_CODEOFFRE AND JFALX = P_VERSION  --AND JFTYP = P_TYPE 
DO 
DELETE FROM [ENVCIBLE] . YADRESS WHERE ABPCHR = ADRID ; 
DELETE FROM [ENVCIBLE] . YPRTADR WHERE JFIPB = P_CODEOFFRE AND JFALX = P_VERSION ;  -- AND JFTYP = P_TYPE;            
END FOR ; 
  
DELETE FROM [ENVCIBLE] . KPOBJ WHERE KACIPB = P_CODEOFFRE AND KACALX = P_VERSION AND KACTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPFOR WHERE KDAIPB = P_CODEOFFRE AND KDAALX = P_VERSION AND KDATYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPOPT WHERE KDBIPB = P_CODEOFFRE AND KDBALX = P_VERSION AND KDBTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPOPTD WHERE KDCIPB = P_CODEOFFRE AND KDCALX = P_VERSION AND KDCTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPOPTDW WHERE KDCIPB = P_CODEOFFRE AND KDCALX = P_VERSION AND KDCTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPOPTAP WHERE KDDIPB = P_CODEOFFRE AND KDDALX = P_VERSION AND KDDTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPOPTAPW WHERE KDDIPB = P_CODEOFFRE AND KDDALX = P_VERSION AND KDDTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPGARAN WHERE KDEIPB = P_CODEOFFRE AND KDEALX = P_VERSION AND KDETYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPGARAH WHERE KDEIPB = P_CODEOFFRE AND KDEALX = P_VERSION AND KDETYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPGARAW WHERE KDEIPB = P_CODEOFFRE AND KDEALX = P_VERSION AND KDETYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPGARTAR WHERE KDGIPB = P_CODEOFFRE AND KDGALX = P_VERSION AND KDGTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPGARTAW WHERE KDGIPB = P_CODEOFFRE AND KDGALX = P_VERSION AND KDGTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPGARAP WHERE KDFIPB = P_CODEOFFRE AND KDFALX = P_VERSION AND KDFTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPINVEN WHERE KBEIPB = P_CODEOFFRE AND KBEALX = P_VERSION AND KBETYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPINVED WHERE KBFIPB = P_CODEOFFRE AND KBFALX = P_VERSION AND KBFTYP = P_TYPE ; 

-- Suppression dans KPDOCEXT
DELETE FROM [ENVCIBLE].KPDOCEXT WHERE KERIPB = P_CODEOFFRE AND KERALX = P_VERSION AND KERTYP = P_TYPE ; 
  
FOR LOOP_CLAUSE AS FREE_LIST CURSOR FOR 
SELECT KCAID ID , KCATXL TXL FROM [ENVCIBLE] . KPCLAUSE WHERE KCAIPB = P_CODEOFFRE AND KCAALX = P_VERSION AND KCATYP = P_TYPE 
DO 
IF ( TXL != 0 ) THEN 
DELETE FROM [ENVCIBLE] . KPCLATXT WHERE KFOID = TXL ; 
END IF ; 
DELETE FROM [ENVCIBLE] . KPCLAUSE WHERE KCAID = ID ; 
END FOR ; 
  
FOR LOOP_CLAUSW AS FREE_LIST CURSOR FOR 
SELECT KCBTXL TXL FROM [ENVCIBLE] . KPCLAUSW WHERE KCBIPB = P_CODEOFFRE AND KCBALX = P_VERSION AND KCBTYP = P_TYPE 
DO 
IF ( TXL != 0 ) THEN 
DELETE FROM [ENVCIBLE] . KPCLATXT WHERE KFOID = TXL ; 
END IF ; 
END FOR ; 
DELETE FROM [ENVCIBLE] . KPCLAUSW WHERE KCBIPB = P_CODEOFFRE AND KCBALX = P_VERSION AND KCBTYP = P_TYPE ; 
  
DELETE FROM [ENVCIBLE] . KPCOTGA WHERE KDNIPB = P_CODEOFFRE AND KDNALX = P_VERSION AND KDNTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPCOTIS WHERE KDMIPB = P_CODEOFFRE AND KDMALX = P_VERSION AND KDMTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPCTRL WHERE KEUIPB = P_CODEOFFRE AND KEUALX = P_VERSION AND KEUTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPCTRLE WHERE KEVIPB = P_CODEOFFRE AND KEVALX = P_VERSION AND KEVTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPDESI WHERE KADIPB = P_CODEOFFRE AND KADALX = P_VERSION AND KADTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPENG WHERE KDOIPB = P_CODEOFFRE AND KDOALX = P_VERSION AND KDOTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPENGFAM WHERE KDPIPB = P_CODEOFFRE AND KDPALX = P_VERSION AND KDPTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPENGGAR WHERE KDSIPB = P_CODEOFFRE AND KDSALX = P_VERSION AND KDSTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPENGRSQ WHERE KDRIPB = P_CODEOFFRE AND KDRALX = P_VERSION AND KDRTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPENGVEN WHERE KDQIPB = P_CODEOFFRE AND KDQALX = P_VERSION AND KDQTYP = P_TYPE ; 
  
FOR LOOP_EXPFRH AS FREE_LIST CURSOR FOR 
SELECT KDKID ID FROM [ENVCIBLE] . KPEXPFRH WHERE KDKIPB = P_CODEOFFRE AND KDKALX = P_VERSION AND KDKTYP = P_TYPE 
DO 
DELETE FROM [ENVCIBLE] . KPEXPFRHD WHERE KDLKDKID = ID ; 
DELETE FROM [ENVCIBLE] . KPEXPFRH WHERE KDKID = ID ; 
END FOR ; 
  
FOR LOOP_EXPLCI AS FREE_LIST CURSOR FOR 
SELECT KDIID ID FROM [ENVCIBLE] . KPEXPLCI WHERE KDIIPB = P_CODEOFFRE AND KDIALX = P_VERSION AND KDITYP = P_TYPE 
DO 
DELETE FROM [ENVCIBLE] . KPEXPLCID WHERE KDJKDIID = ID ; 
DELETE FROM [ENVCIBLE] . KPEXPLCI WHERE KDIID = ID ; 
END FOR ; 
  
DELETE FROM [ENVCIBLE] . KPIOPT WHERE KFCIPB = P_CODEOFFRE AND KFCALX = P_VERSION AND KFCTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPIRSGA WHERE KFDIPB = P_CODEOFFRE AND KFDALX = P_VERSION AND KFDTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPIRSOB WHERE KFAIPB = P_CODEOFFRE AND KFAALX = P_VERSION AND KFATYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPMATFF WHERE KEAIPB = P_CODEOFFRE AND KEAALX = P_VERSION AND KEATYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPMATFL WHERE KECIPB = P_CODEOFFRE AND KECALX = P_VERSION AND KECTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPMATFR WHERE KEBIPB = P_CODEOFFRE AND KEBALX = P_VERSION AND KEBTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPMATGG WHERE KEEIPB = P_CODEOFFRE AND KEEALX = P_VERSION AND KEETYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPMATGL WHERE KEFIPB = P_CODEOFFRE AND KEFALX = P_VERSION AND KEFTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPMATGR WHERE KEDIPB = P_CODEOFFRE AND KEDALX = P_VERSION AND KEDTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPOBSV WHERE KAJIPB = P_CODEOFFRE AND KAJALX = P_VERSION AND KAJTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPODBLS WHERE KAFIPB = P_CODEOFFRE AND KAFALX = P_VERSION AND KAFTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPOPP WHERE KFPIPB = P_CODEOFFRE AND KFPALX = P_VERSION AND KFPTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPOPPAP WHERE KFQIPB = P_CODEOFFRE AND KFQALX = P_VERSION AND KFQTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPTRACE WHERE KCCIPB = P_CODEOFFRE AND KCCALX = P_VERSION AND KCCTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPVALID WHERE KEXIPB = P_CODEOFFRE AND KEXALX = P_VERSION AND KEXTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPINVAPP WHERE KBGIPB = P_CODEOFFRE AND KBGALX = P_VERSION AND KBGTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . YPOECHE WHERE PIIPB = P_CODEOFFRE AND PIALX = P_VERSION ;  -- AND PITYP = P_TYPE;      
DELETE FROM [ENVCIBLE] . YPOINTE WHERE PPIPB = P_CODEOFFRE AND PPALX = P_VERSION ;  -- AND PPTYP = P_TYPE;    
DELETE FROM [ENVCIBLE] . YPRTAVT WHERE KHIPB = P_CODEOFFRE AND KHALX = P_VERSION ;  -- AND KHTYP = P_TYPE;   
DELETE FROM [ENVCIBLE] . YORTCLA WHERE QEIPB = P_CODEOFFRE AND QEALX = P_VERSION ;  -- AND QETYP = P_TYPE;   
DELETE FROM [ENVCIBLE] . YORTCLV WHERE QFIPB = P_CODEOFFRE AND QFALX = P_VERSION ;  -- AND QFTYP = P_TYPE;   
DELETE FROM [ENVCIBLE] . YPRTDES WHERE JIIPB = P_CODEOFFRE AND JIALX = P_VERSION ;  -- AND JITYP = P_TYPE;        
DELETE FROM [ENVCIBLE] . YPRTFNC WHERE JNIPB = P_CODEOFFRE AND JNALX = P_VERSION ;  -- AND JNTYP = P_TYPE;    
DELETE FROM [ENVCIBLE] . YPRTFOO WHERE JPIPB = P_CODEOFFRE AND JPALX = P_VERSION ;  -- AND JPTYP = P_TYPE;      
--DELETE FROM [ENVCIBLE] . YPRTFOR WHERE JOIPB = P_CODEOFFRE AND JOALX = P_VERSION ;  -- AND JOTYP = P_TYPE;    
DELETE FROM [ENVCIBLE] . YPRTFRH WHERE JJIPB = P_CODEOFFRE AND JJALX = P_VERSION ;  -- AND JJTYP = P_TYPE;       
DELETE FROM [ENVCIBLE] . YPRTFRT WHERE JLIPB = P_CODEOFFRE AND JLALX = P_VERSION ;  -- AND JLTYP = P_TYPE;      
DELETE FROM [ENVCIBLE] . YPRTGAA WHERE JRIPB = P_CODEOFFRE AND JRALX = P_VERSION ;  -- AND JRTYP = P_TYPE;     
DELETE FROM [ENVCIBLE] . YPRTGAR WHERE JHIPB = P_CODEOFFRE AND JHALX = P_VERSION ;  -- AND JHTYP = P_TYPE;     
DELETE FROM [ENVCIBLE] . YPRTGAV WHERE JQIPB = P_CODEOFFRE AND JQALX = P_VERSION ;  -- AND JQTYP = P_TYPE;    
DELETE FROM [ENVCIBLE] . YPRTLCI WHERE JKIPB = P_CODEOFFRE AND JKALX = P_VERSION ;  -- AND JKTYP = P_TYPE;      
DELETE FROM [ENVCIBLE] . YPRTLCT WHERE JMIPB = P_CODEOFFRE AND JMALX = P_VERSION ;  -- AND JMTYP = P_TYPE;   
DELETE FROM [ENVCIBLE] . YPRTOBT WHERE KFIPB = P_CODEOFFRE AND KFALX = P_VERSION ;  -- AND KFTYP = P_TYPE;     
DELETE FROM [ENVCIBLE] . YPOCONX WHERE PJIPB = P_CODEOFFRE AND PJALX = P_VERSION AND PJTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KWADR WHERE W3IPB = P_CODEOFFRE AND W3ALX = P_VERSION AND W3TYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPCTRLA WHERE KGTIPB = P_CODEOFFRE AND KGTALX = P_VERSION AND KGTTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KCANEV WHERE KGOCNVA = P_CODEOFFRE AND KGOTYP = P_TYPE ; 
DELETE FROM [ENVCIBLE] . KPINTER WHERE KHBIPB = P_CODEOFFRE AND KHBALX = P_VERSION AND KHBTYP = P_TYPE ; 
  
END P1