CREATE PROCEDURE SP_ADDCNX ( 
	IN P_ID_OFFRE_CONNEXE CHAR(9) , 
	IN P_TYPE_OFFRE_CONNEXE CHAR(1) , 
	IN P_ID_ALIMENT_CONNEXE NUMERIC(5, 0) , 
	IN P_BRANCHE_CONNEXE CHAR(2) , 
	IN P_SOUS_BRANCHE_CONNEXE CHAR(3) , 
	IN P_CAT_CONNEXE CHAR(5) , 
	IN P_ID_OFFRE_COURANT CHAR(9) , 
	IN P_TYPE_OFFRE_COURANT CHAR(1) , 
	IN P_ID_ALIMENT_COURANT NUMERIC(5, 0) , 
	IN P_BRANCHE_COURANT CHAR(2) , 
	IN P_SOUS_BRANCHE_COURANT CHAR(3) , 
	IN P_CAT_COURANT CHAR(5) , 
	IN P_TYPE_CONNEXITE CHAR(2) , 
	IN P_NUM_CONNEXITE DECIMAL(7, 0) , 
	IN P_OBSV CHAR(5000) , 
	IN P_CODE_OBSV INTEGER , 
	IN P_MODE CHAR(1) , 
	OUT P_ERREUR CHAR(128) ) 
	LANGUAGE SQL 
	SPECIFIC SP_ADDCNX 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
DECLARE V_CODEOBSV INTEGER DEFAULT 0 ; 
IF ( P_MODE = 'U' ) THEN 
--Mise a jour de l'observation dans la table KPOBSV                                                                                                       
UPDATE KPOBSV 
SET KAJOBSV = TRIM ( P_OBSV ) 
WHERE KAJCHR = P_CODE_OBSV ; 
--Insertion de la connexite dans la table YPOCONX 
INSERT INTO YPOCONX ( PJIPB , PJALX , PJTYP , PJCCX , PJCNX , PJBRA , PJSBR , PJCAT , PJOBS ) 
VALUES ( P_ID_OFFRE_CONNEXE , P_ID_ALIMENT_CONNEXE , P_TYPE_OFFRE_CONNEXE , P_TYPE_CONNEXITE , P_NUM_CONNEXITE , P_BRANCHE_CONNEXE , P_SOUS_BRANCHE_CONNEXE , P_CAT_CONNEXE , P_CODE_OBSV ) ; 
--Mise a jour des liens vers la table KPOBSV                                                     
--UPDATE YPOCONX SET PJOBS =P_CODE_OBSV 
--WHERE PJTYP=P_TYPE_OFFRE_CONNEXE AND PJCCX =P_TYPE_CONNEXITE AND PJCNX =P_NUM_CONNEXITE; 
ELSE 
  
--Creation de l'observation dans la table KPOBSV              
CALL SP_NCHRONO ( 'KAJCHR' , V_CODEOBSV ) ; 
  
--Insertion de l'observation KPOBSV 
INSERT INTO KPOBSV ( KAJCHR , KAJTYP , KAJIPB , KAJALX , KAJTYPOBS , KAJOBSV ) 
VALUES ( V_CODEOBSV , P_TYPE_OFFRE_COURANT , P_ID_OFFRE_COURANT , P_ID_ALIMENT_COURANT , 'GENERALE' , TRIM ( P_OBSV ) ) ; 
--Mise a jour de l'observation dans la table KPOBSV                                                                                                  
UPDATE KPOBSV 
SET KAJOBSV = TRIM ( P_OBSV ) 
WHERE KAJCHR = P_CODE_OBSV ; 
--Insertion de deux connexités dans la table YPOCONX 
INSERT INTO YPOCONX ( PJIPB , PJALX , PJTYP , PJCCX , PJCNX , PJBRA , PJSBR , PJCAT , PJOBS ) 
VALUES ( P_ID_OFFRE_CONNEXE , P_ID_ALIMENT_CONNEXE , P_TYPE_OFFRE_CONNEXE , P_TYPE_CONNEXITE 
, P_NUM_CONNEXITE , P_BRANCHE_CONNEXE , P_SOUS_BRANCHE_CONNEXE , P_CAT_CONNEXE , V_CODEOBSV ) ; 
INSERT INTO YPOCONX ( PJIPB , PJALX , PJTYP , PJCCX , PJCNX , PJBRA , PJSBR , PJCAT , PJOBS ) 
VALUES ( P_ID_OFFRE_COURANT , P_ID_ALIMENT_COURANT , P_TYPE_OFFRE_COURANT , P_TYPE_CONNEXITE 
, P_NUM_CONNEXITE , P_BRANCHE_COURANT , P_SOUS_BRANCHE_COURANT , P_CAT_COURANT , V_CODEOBSV ) ; 
  
END IF ; 
  
END P1  ; 
  

  

