CREATE PROCEDURE SP_ADDCOAS ( 
	IN P_TYPE_OFFRE CHAR(1) , 
	IN P_ID_OFFRE CHAR(9) , 
	IN P_ID_ALIMENT INTEGER , 
	IN P_CODE_COMPAGNIE CHAR(6) , 
	IN P_NOM_COMPAGNIE CHAR(128) , 
	IN P_CODEINTERLOCUTEUR INTEGER , 
	IN P_REFERENCE_POLICE CHAR(25) , 
	IN P_PART_ASSUREUR DECIMAL(5, 2) , 
	IN P_FRAIS_ACC DECIMAL(5, 2) , 
	IN P_DATE_DA INTEGER , 
	IN P_DATE_DM INTEGER , 
	IN P_DATE_DJ INTEGER , 
	IN P_DATE_FA INTEGER , 
	IN P_DATE_FM INTEGER , 
	IN P_DATE_FJ INTEGER , 
	IN P_FRAISAPEALB DECIMAL(5, 2) , 
	IN P_COMMAPERITEUR DECIMAL(5, 2) , 
	IN P_TYPE_OPERATION CHAR(1) , 
	OUT P_ERREUR CHAR(256) ) 
	LANGUAGE SQL 
	SPECIFIC SP_ADDCOAS 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
	DECLARE V_ASSUREUR_COUNT INTEGER DEFAULT 0 ;	 
	DECLARE V_COMPAGNIE_COUNT INTEGER DEFAULT 0 ; 
	DECLARE V_PART_ALBINGIA DECIMAL ( 5 , 2 ) DEFAULT 0.0 ; 
	DECLARE V_PART_COUVERTE DECIMAL ( 5 , 2 ) DEFAULT 0.0 ; 
	DECLARE V_TOTAL_ACTUEL DECIMAL ( 5 , 2 ) DEFAULT 0.0 ; 
	DECLARE V_ANCIENNE_PART DECIMAL ( 5 , 2 ) DEFAULT 0.0 ; 
	 
	SELECT COUNT ( * ) NBLIGNE INTO V_ASSUREUR_COUNT 
		FROM YPOBASE BASE 
			INNER JOIN YPOCOAS COASSUREUR ON BASE . PBIPB = COASSUREUR . PHIPB 
			INNER JOIN YCOMPA COMPAGNIES ON COASSUREUR . PHCIE = COMPAGNIES . CIICI 
			LEFT JOIN YCOMPAL INTERLOCUTEURS ON COASSUREUR . PHIN5 = INTERLOCUTEURS . CLIN5 AND COASSUREUR . PHCIE = INTERLOCUTEURS . CLICI 
		WHERE BASE . PBIPB = P_ID_OFFRE AND ( PBNPL = 'A' OR PBNPL = 'E' ) 
			AND COASSUREUR . PHTAP = 'C' AND PHALX = P_ID_ALIMENT 
			AND PHTYP = P_TYPE_OFFRE AND PHCIE = P_CODE_COMPAGNIE ; 
	 
	 
	SELECT SUM ( PHAPP ) INTO V_TOTAL_ACTUEL 
		FROM YPOCOAS 
		WHERE PHTYP = P_TYPE_OFFRE AND PHIPB = P_ID_OFFRE AND PHALX = P_ID_ALIMENT AND PHTAP = 'C' 
		GROUP BY PHIPB ; 
	 
	SELECT PBAPP , PBPCV INTO V_PART_ALBINGIA , V_PART_COUVERTE 
		FROM YPOBASE BASE 
		WHERE BASE . PBIPB = P_ID_OFFRE AND BASE . PBTYP = P_TYPE_OFFRE 
			AND BASE . PBALX = P_ID_ALIMENT AND ( PBNPL = 'A' OR PBNPL = 'E' ) ; 
	 
	IF ( P_TYPE_OPERATION = 'U' ) THEN 
	 
		IF ( V_ASSUREUR_COUNT = 1 ) THEN 
			SELECT PHAPP INTO V_ANCIENNE_PART 
				FROM YPOCOAS 
				WHERE PHTYP = P_TYPE_OFFRE AND PHIPB = P_ID_OFFRE AND PHALX = P_ID_ALIMENT AND PHCIE = P_CODE_COMPAGNIE ; 
	 
			 --SLA 03.03.2015 : désactivation du contrôle à l'enregistrement du coass, voir bug 1309 
			 --IF ( V_TOTAL_ACTUEL + P_PART_ASSUREUR + V_PART_ALBINGIA - V_ANCIENNE_PART > V_PART_COUVERTE ) THEN 
			 --	SET P_ERREUR = 'La somme du total des parts et de la part Albingia ne peut pas être supérieure à la part couverte' ; 
			 --ELSE 
				UPDATE YPOCOAS SET 
					PHPOL = P_REFERENCE_POLICE , PHIN5 = P_CODEINTERLOCUTEUR , PHAPP = P_PART_ASSUREUR , PHAFR = P_FRAIS_ACC , 
					PHEPA = P_DATE_DA , PHEPM = P_DATE_DM , PHEPJ = P_DATE_DJ , PHFPA = P_DATE_FA , PHFPM = P_DATE_FM , PHFPJ = P_DATE_FJ , PHTXF = P_FRAISAPEALB , 
					PHCOM = P_COMMAPERITEUR 
				WHERE PHTYP = P_TYPE_OFFRE AND PHIPB = P_ID_OFFRE AND PHTAP = 'C' AND PHALX = P_ID_ALIMENT AND PHCIE = P_CODE_COMPAGNIE ; 
	 
				SET P_ERREUR = '' ; 
			 --END IF ; 
		ELSE 
			SET P_ERREUR = 'Aucune mise à jour, le co-assureur n''existe pas' ; 
		END IF ; 
	END IF ; 
	IF ( P_TYPE_OPERATION = 'I' ) THEN 
	 --SLA 03.03.2015 : désactivation du contrôle à l'enregistrement du coass, voir bug 1309 
		 --IF ( V_TOTAL_ACTUEL + P_PART_ASSUREUR + V_PART_ALBINGIA > V_PART_COUVERTE ) THEN 
		 --	SET P_ERREUR = 'La somme du total des parts et de la part Albingia ne peut pas être supérieure à la part couverte' ; 
		 --ELSE 
			IF ( V_ASSUREUR_COUNT = 0 ) THEN 
				SELECT COUNT ( * ) NBLIGN INTO V_COMPAGNIE_COUNT 
					FROM YCOMPA 
					WHERE CIICI = P_CODE_COMPAGNIE ;  --AND CINOM = P_NOM_COMPAGNIE ; 
				IF ( V_COMPAGNIE_COUNT = 1 ) THEN 
					INSERT INTO YPOCOAS 
						( PHTYP , PHIPB , PHALX , PHTAP , PHCIE , PHIN5 , PHPOL , PHAPP , PHAFR , PHEPA , PHEPM , PHEPJ , PHFPA , PHFPM , PHFPJ , PHTXF , PHCOM ) 
					VALUES 
						( P_TYPE_OFFRE , P_ID_OFFRE , P_ID_ALIMENT , 'C' , P_CODE_COMPAGNIE , P_CODEINTERLOCUTEUR , P_REFERENCE_POLICE , P_PART_ASSUREUR , P_FRAIS_ACC , 
							P_DATE_DA , P_DATE_DM , P_DATE_DJ , P_DATE_FA , P_DATE_FM , P_DATE_FJ , P_FRAISAPEALB , P_COMMAPERITEUR ) ; 
					SET P_ERREUR = '' ; 
				END IF ; 
			ELSE 
				SET P_ERREUR = 'Aucune mise à jour, le co-assureur existe déjà pour ce contrat' ; 
			END IF ; 
		 --END IF ; 
	END IF ; 
END P1  ; 
  

  

