CREATE PROCEDURE SP_AVENANTRACE ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_PERIMETRE CHAR(10) , 
	IN P_CODERISQUE INTEGER , 
	IN P_CODEOBJET INTEGER , 
	IN P_CODEFORMULE INTEGER , 
	IN P_CODEOPTION INTEGER , 
	IN P_ETAPE CHAR(10) , 
	IN P_CHAMP CHAR(20) , 
	IN P_ACTION CHAR(1) , 
	IN P_OLDVAL CHAR(100) , 
	IN P_NEWVAL CHAR(100) , 
	IN P_AVNOBLIG CHAR(1) , 
	IN P_OPERATION CHAR(20) , 
	IN P_USER CHAR(10) , 
	IN P_DATENOW INTEGER , 
	IN P_HEURENOW INTEGER ) 
	LANGUAGE SQL 
	SPECIFIC SP_AVENANTRACE 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
	DECLARE V_TRACEID INTEGER DEFAULT 0 ; 
	CALL SP_NCHRONO ( 'KHOID' , V_TRACEID ) ; 
  
	INSERT INTO KPAVTRC 
		( KHOID , KHOTYP , KHOIPB , KHOALX , KHOPERI , 
			KHORSQ , KHOOBJ , KHOFOR , KHOOPT , 
			KHOETAPE , KHOCHAM , KHOACT , KHOANV , KHONVV , 
			KHOAVO , KHOOEF , KHOCRU , KHOCRD , KHOCRH ) 
	VALUES 
		( V_TRACEID , P_TYPE , P_CODEOFFRE , P_VERSION , P_PERIMETRE , 
			P_CODERISQUE , P_CODEOBJET , P_CODEFORMULE , P_CODEOPTION , 
			P_ETAPE , P_CHAMP , P_ACTION , P_OLDVAL , P_NEWVAL , P_AVNOBLIG , 
			P_OPERATION , P_USER , P_DATENOW , P_HEURENOW ) ; 
	 
END P1  ; 
  

  

