CREATE PROCEDURE SP_ADDVALEUR ( 
	IN P_CONCEPT CHAR(5) , 
	IN P_FAMILLE CHAR(5) , 
	IN P_VALEUR CHAR(15) , 
	IN P_LIB_COURT CHAR(20) , 
	IN P_LIB_LONG CHAR(40) , 
	IN P_DESC1 CHAR(70) , 
	IN P_DESC2 CHAR(70) , 
	IN P_DESC3 CHAR(70) , 
	IN P_VALNUM1 NUMERIC(15, 3) , 
	IN P_VALNUM2 NUMERIC(15, 3) , 
	IN P_ALPHA1 CHAR(15) , 
	IN P_ALPHA2 CHAR(15) , 
	IN P_FILTRE CHAR(10) , 
	IN P_RESTRICTION CHAR(1) , 
	IN P_MODE CHAR(1) , 
	OUT P_ERREUR CHAR(256) ) 
	LANGUAGE SQL 
	SPECIFIC SP_ADDVALEUR 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
	DECLARE V_COUNT INTEGER DEFAULT 0 ; 
  
	IF ( P_MODE = 'I' ) THEN 
		SELECT COUNT ( * ) INTO V_COUNT FROM YYYYPAR WHERE TCON = P_CONCEPT AND TFAM = P_FAMILLE AND TCOD = P_VALEUR ; 
  
		IF ( V_COUNT = 0 ) THEN 
			INSERT INTO YYYYPAR 
				( TCON , TFAM , TCOD , TPLIB , TPLIL , TPCN1 , TPCN2 , TPCA1 , TPCA2 , TFILT , TPTYP ) 
			VALUES 
				( P_CONCEPT , P_FAMILLE , P_VALEUR , P_LIB_COURT , P_LIB_LONG , P_VALNUM1 , P_VALNUM2 , P_ALPHA1 , P_ALPHA2 , P_FILTRE , P_RESTRICTION ) ; 
			 
			INSERT INTO YYYYPAL 
				( TCON , TFAM , TCOD , TXORD , TXTXT ) 
			VALUES 
				( P_CONCEPT , P_FAMILLE , P_VALEUR , 1 , P_DESC1 ) ; 
  
			INSERT INTO YYYYPAL 
				( TCON , TFAM , TCOD , TXORD , TXTXT ) 
			VALUES 
				( P_CONCEPT , P_FAMILLE , P_VALEUR , 2 , P_DESC2 ) ; 
			 
			INSERT INTO YYYYPAL 
				( TCON , TFAM , TCOD , TXORD , TXTXT ) 
			VALUES 
				( P_CONCEPT , P_FAMILLE , P_VALEUR , 3 , P_DESC3 ) ; 
		ELSE 
			SET P_ERREUR = 'Aucune mise à jour, cette valeur existe déjà pour cette famille.' ; 
		END IF ; 
	END IF ; 
	 
	IF ( P_MODE = 'U' ) THEN 
		SELECT COUNT ( * ) INTO V_COUNT FROM YYYYPAR WHERE TCON = P_CONCEPT AND TFAM = P_FAMILLE AND TCOD = P_VALEUR ; 
		IF ( V_COUNT = 1 ) THEN 
			UPDATE YYYYPAR 
				SET TPLIB = P_LIB_COURT , TPLIL = P_LIB_LONG , TPCN1 = P_VALNUM1 , TPCN2 = P_VALNUM2 , TPCA1 = P_ALPHA1 , 
					TPCA2 = P_ALPHA2 , TFILT = P_FILTRE , TPTYP = P_RESTRICTION 
			WHERE TCON = P_CONCEPT AND TFAM = P_FAMILLE AND TCOD = P_VALEUR ; 
  
			/* DÉSIGNATION LIGNE 1 */ 
			SET V_COUNT = 0 ; 
			SELECT COUNT ( * ) INTO V_COUNT FROM YYYYPAL WHERE TCON = P_CONCEPT AND TFAM = P_FAMILLE AND TCOD = P_VALEUR AND TXORD = 1 ; 
			IF ( V_COUNT = 1 ) THEN 
				UPDATE YYYYPAL SET TXTXT = P_DESC1 WHERE TCON = P_CONCEPT AND TFAM = P_FAMILLE AND TCOD = P_VALEUR AND TXORD = 1 ; 
			ELSE 
				INSERT INTO YYYYPAL 
					( TCON , TFAM , TCOD , TXORD , TXTXT ) 
				VALUES 
					( P_CONCEPT , P_FAMILLE , P_VALEUR , 1 , P_DESC1 ) ; 
			END IF ; 
			 
			/* DÉSIGNATION LIGNE 2 */ 
			SET V_COUNT = 0 ; 
			SELECT COUNT ( * ) INTO V_COUNT FROM YYYYPAL WHERE TCON = P_CONCEPT AND TFAM = P_FAMILLE AND TCOD = P_VALEUR AND TXORD = 2 ; 
			IF ( V_COUNT = 1 ) THEN 
				UPDATE YYYYPAL SET TXTXT = P_DESC2 WHERE TCON = P_CONCEPT AND TFAM = P_FAMILLE AND TCOD = P_VALEUR AND TXORD = 2 ; 
			ELSE 
				INSERT INTO YYYYPAL 
					( TCON , TFAM , TCOD , TXORD , TXTXT ) 
				VALUES 
					( P_CONCEPT , P_FAMILLE , P_VALEUR , 2 , P_DESC2 ) ; 
			END IF ; 
			 
			/* DÉSIGNATION LIGNE 3 */ 
			SET V_COUNT = 0 ; 
			SELECT COUNT ( * ) INTO V_COUNT FROM YYYYPAL WHERE TCON = P_CONCEPT AND TFAM = P_FAMILLE AND TCOD = P_VALEUR AND TXORD = 3 ; 
			IF ( V_COUNT = 1 ) THEN 
				UPDATE YYYYPAL SET TXTXT = P_DESC3 WHERE TCON = P_CONCEPT AND TFAM = P_FAMILLE AND TCOD = P_VALEUR AND TXORD = 3 ; 
			ELSE 
				INSERT INTO YYYYPAL 
					( TCON , TFAM , TCOD , TXORD , TXTXT ) 
				VALUES 
					( P_CONCEPT , P_FAMILLE , P_VALEUR , 3 , P_DESC3 ) ; 
			END IF ; 
		ELSE 
			SET P_ERREUR = 'Aucune mise à jour, cette valeur n''existe pas dans cette famille' ; 
		END IF ; 
	END IF ; 
END P1  ; 
  

  

