CREATE PROCEDURE SP_ADDFAMILLE ( 
	IN P_CONCEPT CHAR(5) , 
	IN P_FAMILLE CHAR(5) , 
	IN P_LIB_FAMILLE CHAR(35) , 
	IN P_LONGUEUR INTEGER , 
	IN P_TYPE_FAMILLE CHAR(1) , 
	IN P_BLANC CHAR(1) , 
	IN P_LIB_COURT_1 CHAR(15) , 
	IN P_LIB_LONG_1 CHAR(35) , 
	IN P_TYPE_1 CHAR(1) , 
	IN P_NB_DEC_1 INTEGER , 
	IN P_LIB_COURT_2 CHAR(15) , 
	IN P_LIB_LONG_2 CHAR(35) , 
	IN P_TYPE_2 CHAR(1) , 
	IN P_NB_DEC_2 INTEGER , 
	IN P_LIB_COURT_ALPHA_1 CHAR(15) , 
	IN P_LIB_LONG_ALPHA_1 CHAR(35) , 
	IN P_LIB_COURT_ALPHA_2 CHAR(15) , 
	IN P_LIB_LONG_ALPHA_2 CHAR(35) , 
	IN P_TYPE_RESTR CHAR(1) , 
	IN P_MODE CHAR(1) , 
	OUT P_ERREUR CHAR(256) ) 
	LANGUAGE SQL 
	SPECIFIC SP_ADDFAMILLE 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
DECLARE V_COUNT INTEGER DEFAULT 0 ; 
  
IF ( P_MODE = 'I' ) THEN 
  
SELECT COUNT ( * ) INTO V_COUNT 
FROM YYYYPFA 
WHERE TCON = P_CONCEPT 
AND TFAM = P_FAMILLE ; 
  
IF ( V_COUNT = 0 ) THEN 
  
INSERT INTO YYYYPFA 
( TCON , TFAM , TFLIB , TFLGR , TFLN1 , TFLN2 , TFLA1 , TFLA2 , TFGN1 , TFGN2 , 
TFGA1 , TFGA2 , TFTZ1 , TFTZ2 , TFND1 , TFND2 , TFTYP , TFTAN , TFBLC ) 
VALUES 
( P_CONCEPT , P_FAMILLE , P_LIB_FAMILLE , P_LONGUEUR , P_LIB_COURT_1 , P_LIB_COURT_2 , 
P_LIB_COURT_ALPHA_1 , P_LIB_COURT_ALPHA_2 , P_LIB_LONG_1 , P_LIB_LONG_2 , 
P_LIB_LONG_ALPHA_1 , P_LIB_LONG_ALPHA_2 , P_TYPE_1 , P_TYPE_2 , P_NB_DEC_1 , P_NB_DEC_2 , 
P_TYPE_RESTR , P_TYPE_FAMILLE , P_BLANC ) ; 
  
ELSE 
SET P_ERREUR = 'Aucune mise à jour, cette famille existe déjà pour ce concept.' ; 
END IF ; 
  
  
END IF ; 
IF ( P_MODE = 'U' ) THEN 
  
SELECT COUNT ( * ) INTO V_COUNT 
FROM YYYYPFA 
WHERE TCON = P_CONCEPT 
AND TFAM = P_FAMILLE ; 
  
IF ( V_COUNT = 1 ) THEN 
UPDATE YYYYPFA 
SET TFLIB = P_LIB_FAMILLE , 
TFLGR = P_LONGUEUR , 
TFLN1 = P_LIB_COURT_1 , 
TFLN2 = P_LIB_COURT_2 , 
TFLA1 = P_LIB_COURT_ALPHA_1 , 
TFLA2 = P_LIB_COURT_ALPHA_2 , 
TFGN1 = P_LIB_LONG_1 , 
TFGN2 = P_LIB_LONG_2 , 
TFGA1 = P_LIB_LONG_ALPHA_1 , 
TFGA2 = P_LIB_LONG_ALPHA_2 , 
TFTZ1 = P_TYPE_1 , 
TFTZ2 = P_TYPE_2 , 
TFND1 = P_NB_DEC_1 , 
TFND2 = P_NB_DEC_2 , 
TFTYP = P_TYPE_RESTR , 
TFTAN = P_TYPE_FAMILLE , 
TFBLC = P_BLANC 
WHERE TCON = P_CONCEPT 
AND TFAM = P_FAMILLE ; 
  
ELSE 
SET P_ERREUR = 'Aucune mise à jour, cette famille n''existe pas dans ce concept' ; 
END IF ; 
  
END IF ; 
  
  
END P1  ; 
  

  

