CREATE PROCEDURE SP_ADDCOURT ( 
	IN P_ID_OFFRE CHAR(9) , 
	IN P_TYPE_OFFRE CHAR(1) , 
	IN P_ID_ALIMENT NUMERIC(5, 0) , 
	IN P_TYPE_COURTIER CHAR(1) , 
	IN P_ID_COURTIER NUMERIC(5, 0) , 
	IN P_COMMISSION DECIMAL(5, 2) , 
	IN P_MODE_ CHAR(1) , 
	OUT P_ERREUR CHAR(128) ) 
	LANGUAGE SQL 
	SPECIFIC SP_ADDCOURT 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
DECLARE V_COURTIER_COUNT INTEGER DEFAULT 0 ; 
DECLARE V_TOTAL_ACTUEL DECIMAL ( 5 , 2 ) DEFAULT 0.0 ; 
DECLARE V_ANCIENNE_COMMISSION DECIMAL ( 5 , 2 ) DEFAULT 0.0 ; 
	SELECT COUNT ( * ) INTO V_COURTIER_COUNT 
	FROM 
	YPOBASE BASE 
	INNER JOIN YPOCOUR YP ON YP . PFIPB = BASE . PBIPB AND YP . PFALX = BASE . PBALX AND YP . PFTYP = BASE . PBTYP	 
	LEFT JOIN YCOURTI YCT ON YCT . TCICT = YP . PFICT 
	LEFT JOIN YCOURTN YCTI ON YCTI . TNICT = YP . PFICT AND YCTI . TNXN5 = 0 AND YCTI . TNTNM = 'A' 
	WHERE PBTYP = P_TYPE_OFFRE 
	AND PBALX = P_ID_ALIMENT 
	AND PBIPB = P_ID_OFFRE AND PFICT = P_ID_COURTIER ; 
		 
	SELECT SUM ( PFCOM ) INTO V_TOTAL_ACTUEL 
	FROM YPOCOUR 
	WHERE PFTYP = P_TYPE_OFFRE 
		AND PFIPB = P_ID_OFFRE 
		AND PFALX = P_ID_ALIMENT 
	GROUP BY PFIPB ; 
  
IF ( P_MODE_ = 'U' ) THEN 
  
			IF ( V_COURTIER_COUNT = 1 ) THEN			 
								SELECT PFCOM INTO V_ANCIENNE_COMMISSION 
				FROM YPOCOUR 
				WHERE PFTYP = P_TYPE_OFFRE 
				AND PFIPB = P_ID_OFFRE 
				AND PFALX = P_ID_ALIMENT 
				AND PFICT = P_ID_COURTIER ;	 
		 
				IF ( V_TOTAL_ACTUEL + P_COMMISSION - V_ANCIENNE_COMMISSION > 100 ) THEN					 
					SET P_ERREUR = 'La somme des % de commissions ne peut pas être supérieure à 100' ; 
				ELSE 
				UPDATE YPOCOUR 
				SET PFCOM = P_COMMISSION 
WHERE PFICT = P_ID_COURTIER AND PFIPB = P_ID_OFFRE AND PFALX = P_ID_ALIMENT AND PFTYP = P_TYPE_OFFRE ;	 
						 
				SET P_ERREUR = '' ; 
				END IF ; 
			ELSE 
				SET P_ERREUR = 'Aucune mise à jour, le co-courtier n''existe pas' ; 
			END IF ;	 
END IF ;	 
	IF ( P_MODE_ = 'I' ) THEN		 
	IF ( V_TOTAL_ACTUEL + P_COMMISSION > 100 ) THEN 
			SET P_ERREUR = 'La somme des % de commissions ne peut pas être supérieure à 100' ; 
		ELSE		 
			IF ( V_COURTIER_COUNT = 0 ) THEN				 
													 
			INSERT INTO YPOCOUR ( PFTYP , PFIPB , PFALX , PFCTI , PFICT , PFSAA , PFSAM , PFSAJ , PFSAH , PFSIT , PFSTA , PFSTM , PFSTJ , 
PFCOM , PFXCM , PFXCN ) 
VALUES ( P_TYPE_OFFRE , P_ID_OFFRE , P_ID_ALIMENT , 
P_TYPE_COURTIER , P_ID_COURTIER , '0' , '0' , '0' , '0' , 'A' , 
YEAR ( CURRENT DATE ) , MONTH ( CURRENT DATE ) , DAY ( CURRENT DATE ) , P_COMMISSION , '0' , '0' ) ;	 
	SET P_ERREUR = '' ;	 
	ELSE SET P_ERREUR = 'Le courtier existe déjà' ; 
			END IF ; 
		END IF ;	 
END IF ; 
END P1  ; 
  

  

