CREATE PROCEDURE SP_ARBRESV ( 
	IN P_TYPE CHAR(1) , 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_ETAPE CHAR(10) , 
	IN P_NUMETAPE INTEGER , 
	IN P_ORDRE INTEGER , 
	IN P_PERIMETRE CHAR(10) , 
	IN P_CODERSQ INTEGER , 
	IN P_CODEOBJ INTEGER , 
	IN P_CODEINVEN INTEGER , 
	IN P_CODEFOR INTEGER , 
	IN P_CODEOPT INTEGER , 
	IN P_NIVCLSST CHAR(1) , 
	IN P_USER CHAR(10) , 
	IN P_DATESYSTEME INTEGER , 
	IN P_HEURESYSTEME INTEGER , 
	IN P_PASSTAG CHAR(1) , 
	IN P_PASSTAGCLAUSE CHAR(1) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_ARBRESV 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
DECLARE V_COUNTTRACE INTEGER DEFAULT 0 ; 
  
  
SELECT COUNT ( * ) INTO V_COUNTTRACE FROM KPCTRLE 
WHERE KEVTYP = P_TYPE AND KEVIPB = P_CODEOFFRE AND KEVALX = P_VERSION AND KEVETAPE = P_ETAPE 
AND KEVRSQ = P_CODERSQ AND KEVOBJ = P_CODEOBJ AND KEVFOR = P_CODEFOR AND KEVOPT = P_CODEOPT AND KEVPERI =  P_PERIMETRE; 
  
IF ( V_COUNTTRACE = 0 ) THEN 
INSERT INTO KPCTRLE 
( KEVTYP , KEVIPB , KEVALX , KEVETAPE , KEVETORD , KEVORDR , KEVPERI , KEVRSQ , KEVOBJ , KEVKBEID , KEVFOR , KEVOPT , 
KEVNIVM , KEVCRU , KEVCRD , KEVCRH , KEVMAJU , KEVMAJD , KEVMAJH , KEVTAG , KEVTAGC ) 
VALUES 
( P_TYPE , P_CODEOFFRE , P_VERSION , P_ETAPE , P_NUMETAPE , P_ORDRE , P_PERIMETRE , P_CODERSQ , P_CODEOBJ , P_CODEINVEN , P_CODEFOR , P_CODEOPT , 
P_NIVCLSST , P_USER , P_DATESYSTEME , P_HEURESYSTEME , P_USER , P_DATESYSTEME , P_HEURESYSTEME , P_PASSTAG , P_PASSTAGCLAUSE ) ; 
ELSE 
UPDATE KPCTRLE 
SET KEVMAJU = P_USER , KEVMAJD = P_DATESYSTEME , KEVMAJH = P_HEURESYSTEME , KEVTAG = P_PASSTAG , KEVTAGC = P_PASSTAGCLAUSE 
WHERE KEVTYP = P_TYPE AND KEVIPB = P_CODEOFFRE AND KEVALX = P_VERSION AND KEVETAPE = P_ETAPE AND KEVPERI =  P_PERIMETRE 
AND KEVRSQ = P_CODERSQ AND KEVOBJ = P_CODEOBJ AND KEVFOR = P_CODEFOR AND KEVOPT = P_CODEOPT ; 
END IF ; 
  
END P1  ; 
  

  

