CREATE PROCEDURE SP_ADDOPP ( 
	IN P_TYPE_OFFRE CHAR(1) , 
	IN P_ID_OFFRE CHAR(9) , 
	IN P_VERSION_OFFRE INTEGER , 
	IN P_CODE_RISQUE INTEGER , 
	IN P_OPP_KPOPP_REF INTEGER , 
	IN P_OPP_DESCRIPTION CHAR(128) , 
	IN P_OPP_KPDESI_REF INTEGER , 
	IN P_OPP_CODE_ORGANISME INTEGER , 
	IN P_OPP_TYPEFINANCEMENT CHAR(3) , 
	IN P_OPP_REFERENCE CHAR(40) , 
	IN P_OPP_ECHEANCE INTEGER , 
	IN P_OPP_MONTANT DECIMAL(13, 2) , 
	IN P_OPP_LISTOBJ CHAR(128) , 
	IN P_OPP_PERI CHAR(2) , 
	IN P_CREA_USER CHAR(10) , 
	IN P_CREA_DATE INTEGER , 
	IN P_CREA_HEURE INTEGER , 
	IN P_MAJ_USER CHAR(10) , 
	IN P_MAJ_DATE INTEGER , 
	IN P_MAJ_HEURE INTEGER , 
	IN P_TYPE_OPERATION CHAR(1) , 
	IN P_TYPEDEST CHAR(2) ) 
	LANGUAGE SQL 
	SPECIFIC SP_ADDOPP 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
	DECLARE V_KPOPPAP_REF INTEGER DEFAULT 0 ; 
	DECLARE V_TYPEINTERVENANT CHAR ( 2 ) DEFAULT '' ; 
	 
	IF ( TRIM ( P_TYPEDEST ) = 'IN' ) THEN 
		SELECT INTYI INTO V_TYPEINTERVENANT FROM YINTERV WHERE INIIN = P_OPP_CODE_ORGANISME ; 
	ELSE 
		SET V_TYPEINTERVENANT = 'AS' ; 
	END IF ; 
  
	IF ( P_TYPE_OPERATION = 'I' ) THEN 
  
		IF ( P_OPP_DESCRIPTION <> '' ) THEN 
			CALL SP_NCHRONO ( 'KADCHR' , P_OPP_KPDESI_REF ) ; 
			INSERT INTO KPDESI 
				( KADCHR , KADTYP , KADIPB , KADALX , KADRSQ , KADOBJ , KADDESI ) 
			VALUES 
				( P_OPP_KPDESI_REF , P_TYPE_OFFRE , P_ID_OFFRE , P_VERSION_OFFRE , P_CODE_RISQUE , 0 , P_OPP_DESCRIPTION ) ; 
		END IF ; 
		CALL SP_NCHRONO ( 'KFPID' , P_OPP_KPOPP_REF ) ; 
	 
		INSERT INTO KPOPP 
			( KFPID , KFPTYP , KFPIPB , KFPALX , KFPIDCB , KFPTFI , KFPDESI , KFPREF , 
				KFPDECH , KFPMNT , KFPCRU , KFPCRD , KFPCRH , KFPMAJU , KFPMAJD , KFPMAJH , 
				KFPTDS , KFPTYI ) 
		VALUES 
			( P_OPP_KPOPP_REF , P_TYPE_OFFRE , P_ID_OFFRE , P_VERSION_OFFRE , P_OPP_CODE_ORGANISME , 
				P_OPP_TYPEFINANCEMENT , P_OPP_KPDESI_REF , P_OPP_REFERENCE , P_OPP_ECHEANCE , P_OPP_MONTANT , 
				P_CREA_USER , P_CREA_DATE , P_CREA_HEURE , P_MAJ_USER , P_MAJ_DATE , P_MAJ_HEURE , 
				P_TYPEDEST , V_TYPEINTERVENANT ) ; 
		 
		IF ( P_OPP_PERI = 'RQ' ) THEN 
			CALL SP_NCHRONO ( 'KFQID' , V_KPOPPAP_REF ) ; 
			INSERT INTO KPOPPAP 
				( KFQID , KFQTYP , KFQIPB , KFQALX , KFQKFPID , KFQPERI , KFQRSQ , 
					KFQOBJ , KFQCRU , KFQCRD , KFQMAJU , KFQMAJD ) 
			VALUES 
				( V_KPOPPAP_REF , P_TYPE_OFFRE , P_ID_OFFRE , P_VERSION_OFFRE , 
					P_OPP_KPOPP_REF , P_OPP_PERI , P_CODE_RISQUE , 0 , 
					P_CREA_USER , P_CREA_DATE , P_MAJ_USER , P_MAJ_DATE ) ; 
		ELSE 
			IF ( P_OPP_PERI = 'OB' ) THEN 
				P2 : BEGIN ATOMIC 
					DECLARE V_OBJ_LEFT VARCHAR ( 128 ) DEFAULT '' ; 
					DECLARE V_OBJ_RIGHT VARCHAR ( 128 ) DEFAULT '' ; 
					DECLARE V_LISTOBJ VARCHAR ( 128 ) DEFAULT '' ; 
					DECLARE V_COUNT INTEGER DEFAULT 0 ; 
  
					SET V_LISTOBJ = P_OPP_LISTOBJ ; 
					 
					CALL SP_SPLIT ( V_LISTOBJ , ';' , 'L' , V_OBJ_LEFT ) ; 
					CALL SP_SPLIT ( V_LISTOBJ , ';' , 'R' , V_OBJ_RIGHT ) ; 
					 
					WHILE ( TRIM ( V_OBJ_LEFT ) != '' ) DO 
						CALL SP_NCHRONO ( 'KFQID' , V_KPOPPAP_REF ) ; 
						 
						INSERT INTO KPOPPAP 
							( KFQID , KFQTYP , KFQIPB , KFQALX , KFQKFPID , KFQPERI , KFQRSQ , 
								KFQOBJ , KFQCRU , KFQCRD , KFQMAJU , KFQMAJD ) 
						VALUES 
							( V_KPOPPAP_REF , P_TYPE_OFFRE , P_ID_OFFRE , P_VERSION_OFFRE , 
								P_OPP_KPOPP_REF , P_OPP_PERI , P_CODE_RISQUE , TRIM ( V_OBJ_LEFT ) , 
								P_CREA_USER , P_CREA_DATE , P_MAJ_USER , P_MAJ_DATE ) ; 
						 
						SET V_LISTOBJ = V_OBJ_RIGHT ; 
						CALL SP_SPLIT ( V_LISTOBJ , ';' , 'L' , V_OBJ_LEFT ) ; 
						CALL SP_SPLIT ( V_LISTOBJ , ';' , 'R' , V_OBJ_RIGHT ) ; 
					END WHILE ; 
				END P2 ; 
			END IF ; 
		END IF ; 
	END IF ; 
	 
	IF ( P_TYPE_OPERATION = 'U' ) THEN 
		IF ( P_OPP_KPDESI_REF <> 0 ) THEN 
			IF ( P_OPP_DESCRIPTION <> '' ) THEN 
				UPDATE KPDESI 
					SET KADDESI = P_OPP_DESCRIPTION 
				WHERE KADCHR = P_OPP_KPDESI_REF AND KADTYP = P_TYPE_OFFRE AND KADIPB = P_ID_OFFRE AND KADALX = P_VERSION_OFFRE AND KADRSQ = P_CODE_RISQUE ; 
			ELSE 
				DELETE FROM KPDESI 
				WHERE KADCHR = P_OPP_KPDESI_REF AND KADTYP = P_TYPE_OFFRE AND KADIPB = P_ID_OFFRE AND KADALX = P_VERSION_OFFRE AND KADRSQ = P_CODE_RISQUE ; 
				SET P_OPP_KPDESI_REF = 0 ; 
			END IF ; 
		ELSE 
			IF ( P_OPP_DESCRIPTION <> '' ) THEN 
				CALL SP_NCHRONO ( 'KADCHR' , P_OPP_KPDESI_REF ) ; 
				INSERT INTO KPDESI 
					( KADCHR , KADTYP , KADIPB , KADALX , KADRSQ , KADOBJ , KADDESI ) 
				VALUES 
					( P_OPP_KPDESI_REF , P_TYPE_OFFRE , P_ID_OFFRE , P_VERSION_OFFRE , P_CODE_RISQUE , 0 , P_OPP_DESCRIPTION ) ; 
			END IF ; 
		END IF ; 
  
		UPDATE KPOPP 
			SET KFPIDCB = P_OPP_CODE_ORGANISME , 
				KFPTFI = P_OPP_TYPEFINANCEMENT , 
				KFPDESI = P_OPP_KPDESI_REF , 
				KFPREF = P_OPP_REFERENCE , 
				KFPDECH = P_OPP_ECHEANCE , 
				KFPMNT = P_OPP_MONTANT , 
				KFPMAJU = P_MAJ_USER , 
				KFPMAJD = P_MAJ_DATE , 
				KFPMAJH = P_MAJ_HEURE , 
				KFPTYI = V_TYPEINTERVENANT 
		WHERE KFPID = P_OPP_KPOPP_REF AND KFPTYP = P_TYPE_OFFRE AND KFPIPB = P_ID_OFFRE AND KFPALX = P_VERSION_OFFRE ; 
  
		DELETE FROM KPOPPAP WHERE KFQKFPID = P_OPP_KPOPP_REF ; 
  
		IF ( P_OPP_PERI = 'RQ' ) THEN 
			CALL SP_NCHRONO ( 'KFQID' , V_KPOPPAP_REF ) ; 
			INSERT INTO KPOPPAP 
				( KFQID , KFQTYP , KFQIPB , KFQALX , KFQKFPID , KFQPERI , KFQRSQ , 
					KFQOBJ , KFQCRU , KFQCRD , KFQMAJU , KFQMAJD ) 
			VALUES 
				( V_KPOPPAP_REF , P_TYPE_OFFRE , P_ID_OFFRE , P_VERSION_OFFRE , 
					P_OPP_KPOPP_REF , P_OPP_PERI , P_CODE_RISQUE , 0 , 
					P_CREA_USER , P_CREA_DATE , P_MAJ_USER , P_MAJ_DATE ) ; 
		ELSE 
			IF ( P_OPP_PERI = 'OB' ) THEN 
				P3 : BEGIN ATOMIC 
					DECLARE V_OBJ_LEFT VARCHAR ( 128 ) DEFAULT '' ; 
					DECLARE V_OBJ_RIGHT VARCHAR ( 128 ) DEFAULT '' ; 
					DECLARE V_LISTOBJ VARCHAR ( 128 ) DEFAULT '' ; 
					DECLARE V_COUNT INTEGER DEFAULT 0 ; 
					 
					SET V_LISTOBJ = P_OPP_LISTOBJ ; 
					 
					CALL SP_SPLIT ( V_LISTOBJ , ';' , 'L' , V_OBJ_LEFT ) ; 
					CALL SP_SPLIT ( V_LISTOBJ , ';' , 'R' , V_OBJ_RIGHT ) ; 
					 
					WHILE ( TRIM ( V_OBJ_LEFT ) != '' ) DO 
						CALL SP_NCHRONO ( 'KFQID' , V_KPOPPAP_REF ) ; 
						 
						INSERT INTO KPOPPAP 
							( KFQID , KFQTYP , KFQIPB , KFQALX , KFQKFPID , KFQPERI , KFQRSQ , 
								KFQOBJ , KFQCRU , KFQCRD , KFQMAJU , KFQMAJD ) 
						VALUES 
							( V_KPOPPAP_REF , P_TYPE_OFFRE , P_ID_OFFRE , P_VERSION_OFFRE , 
								P_OPP_KPOPP_REF , P_OPP_PERI , P_CODE_RISQUE , TRIM ( V_OBJ_LEFT ) , 
								P_CREA_USER , P_CREA_DATE , P_MAJ_USER , P_MAJ_DATE ) ; 
						 
						SET V_LISTOBJ = V_OBJ_RIGHT ; 
						CALL SP_SPLIT ( V_LISTOBJ , ';' , 'L' , V_OBJ_LEFT ) ; 
						CALL SP_SPLIT ( V_LISTOBJ , ';' , 'R' , V_OBJ_RIGHT ) ; 
					END WHILE ; 
				END P3 ; 
			END IF ; 
		END IF ; 
	END IF ; 
	 
	IF ( P_TYPE_OPERATION = 'D' ) THEN 
	 
		DELETE FROM KPDESI 
		WHERE KADCHR = P_OPP_KPDESI_REF AND KADTYP = P_TYPE_OFFRE AND KADIPB = P_ID_OFFRE AND KADALX = P_VERSION_OFFRE AND KADRSQ = P_CODE_RISQUE ; 
		 
		DELETE FROM KPOPPAP 
		WHERE KFQKFPID = P_OPP_KPOPP_REF ; 
		 
		DELETE FROM KPOPP 
		WHERE KFPID = P_OPP_KPOPP_REF AND KFPTYP = P_TYPE_OFFRE AND KFPIPB = P_ID_OFFRE AND KFPALX = P_VERSION_OFFRE ; 
	 
	END IF ; 
END P1  ; 
  

  

