CREATE PROCEDURE SP_ADDMOUVTGAR ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_CODERSQ INTEGER , 
	IN P_CODEFOR INTEGER , 
	IN P_CODEGAR CHAR(10) , 
	IN P_IDREGUL INTEGER , 
	IN P_DATEDEB INTEGER , 
	IN P_DATEFIN INTEGER , 
	IN P_MHT DECIMAL(11, 2) , 
	IN P_MTX DECIMAL(11, 2) ,
	IN P_MULTIRC CHAR(1) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_ADDMOUVTGAR 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 	
  
	DECLARE V_COUNT INTEGER DEFAULT 0 ; 
	DECLARE V_QUERY VARCHAR ( 15000 ) DEFAULT '' ; 
	DECLARE V_KHYID INTEGER DEFAULT 0 ; 
	DECLARE CURSOMOUVT CURSOR FOR	 
  
	SELECT KHXID CODE , KHXSIT SITUATION , KHXDEBP DATEDEB , KHXFINP DATEFIN , 
		CASE WHEN NULLIF ( KHXCU2 , '' ) IS NULL THEN KHXBAS ELSE KHXCA2 END ASSIETTE , 
		CASE WHEN NULLIF ( KHXCU2 , '' ) IS NULL THEN CASE WHEN KHXBAU = 'D' THEN KHXBAM ELSE KHXBAT END ELSE CASE WHEN KHXCU2 = 'D' THEN KHXCP2 ELSE KHXCT2 END END TAUXFORFAITHTVALEUR , 
		CASE WHEN NULLIF ( KHXCU2 , '' ) IS NULL THEN KHXBAU ELSE KHXCU2 END TAUXFORFAITHTUNITE , KHXMHT MONTANTREGULHF 
	FROM KPRGUG 
	WHERE KHXRSQ = P_CODERSQ AND KHXFOR = P_CODEFOR AND KHXGARAN = P_CODEGAR AND KHXKHWID = P_IDREGUL ;

	IF (P_MULTIRC = 'O') THEN
		FOR LOOP_GAR AS FREE_LIST CURSOR FOR 
			SELECT KHYTYP TYP , KHYIPB IPB , KHYALX ALX , KHYRSQ RSQ , KHYFOR FORM , KHYKDEID KDEID , 
				KHYGARAN GARAN , KHYTRG TRG , KHYNPE NPE , KHYVEN VEN , KHYCAF CAF , KHYCAU CAU , KHYCAE CAE , 
				KHYCNH CNH , KHYCNT CNT , KHYGRM GRM , KHYDM2 DM2 , KHYDT2 DT2 , KHYCOE COE , KHYCA1 CA1 , KHYCT1 CT1 , KHYCU1 CU1 , KHYCP1 CP1 , 
				KHYCX1 CX1 , KHYCA2 CA2 , KHYCT2 CT2 , KHYCU2 CU2 , KHYCP2 CP2 , KHYCX2 CX2 , KHYAJU AJU , KHYLMR LMR , KHYMBA MBA , KHYTEN TEN , 
				KHYBRG BRG , KHYBRL BRL , KHYBAS BAS , KHYBAT BAT , KHYBAU BAU , KHYBAM BAM , 
				KHYXF1 XF1 , KHYXB1 XB1 , KHYXM1 XM1 , KHYXF2 XF2 , KHYXB2 XB2 , KHYXM2 XM2 , KHYXF3 XF3 , KHYXB3 XB3 , KHYXM3 XM3 , KHYREG REG , 
				KHYPEI PEI , KHYKEA KEA , KHYPBP PBP , KHYKTD KTD , 
				KHYASV ASV , KHYPBT PBT , KHYSIP SIP , KHYPBS PBS , KHYRIS RIS , KHYPBR PBR , KHYRIA RIA 
			FROM KPRGUWP k WHERE EXISTS (	
				SELECT KHYTYP , KHYIPB , KHYALX , KHYRSQ , KHYFOR , KHYKDEID , min(KHYDEBP) TOTO 
				FROM KPRGUWP k2 
				WHERE TRIM ( KHYIPB ) = P_CODEOFFRE AND KHYALX = P_VERSION AND KHYTYP = P_TYPE AND KHYRSQ = P_CODERSQ AND KHYFOR = P_CODEFOR AND KHYGARAN IN ( 'RCFR' , 'RCEX' , 'RCUS' )
					AND ((KHYDEBP BETWEEN P_DATEDEB AND P_DATEFIN) OR (KHYFINP BETWEEN P_DATEDEB AND P_DATEFIN)) 
					AND ( k.KHYTYP , k.KHYIPB , k.KHYALX , k.KHYRSQ , k.KHYFOR , k.KHYKDEID ) = ( k2.KHYTYP , k2.KHYIPB , k2.KHYALX , k2.KHYRSQ , k2.KHYFOR , k2.KHYKDEID )
				GROUP BY KHYTYP , KHYIPB , KHYALX , KHYRSQ , KHYFOR , KHYKDEID 
				HAVING (k.KHYDEBP = min(k2.KHYDEBP))
			)
		DO 

			CALL SP_NCHRONO ( 'KHXID' , V_KHYID ) ; 
				
			INSERT INTO KPRGUG ( KHXID , KHXKHWID , KHXTYP , KHXIPB , KHXALX , KHXRSQ , KHXFOR , KHXKDEID , 
				KHXGARAN , KHXDEBP , KHXFINP , KHXSIT , KHXTRG , KHXNPE , KHXVEN , KHXCAF , KHXCAU , KHXCAE , KHXMHC , KHXFRC , KHXFR0 , KHXMHT , KHXMTX , KHXMTT , 
				KHXCNH , KHXCNT , KHXGRM , KHXPRO , KHXECH , KHXECT , KHXEMH , KHXEMT , KHXDM1 , KHXDT1 , KHXDM2 , KHXDT2 , KHXCOE , KHXCA1 , KHXCT1 , KHXCU1 , KHXCP1 , 
				KHXCX1 , KHXCA2 , KHXCT2 , KHXCU2 , KHXCP2 , KHXCX2 , KHXAJU , KHXLMR , KHXMBA , KHXTEN , KHXHON , KHXHOX , KHXBRG , KHXBRL , KHXBAS , KHXBAT , KHXBAU , KHXBAM , 
				KHXXF1 , KHXXB1 , KHXXM1 , KHXXF2 , KHXXB2 , KHXXM2 , KHXXF3 , KHXXB3 , KHXXM3 , KHXREG , KHXPEI , KHXKEA , KHXPBP , KHXKTD , KHXASV , KHXPBT , KHXSIP , KHXPBS , KHXRIS , KHXPBR , KHXRIA ) 
			VALUES 
				(V_KHYID , P_IDREGUL , TYP , IPB , ALX , RSQ , FORM , KDEID , 
				GARAN , P_DATEDEB , P_DATEFIN , 'N' , TRG , NPE , VEN , CAF , CAU , CAE , 0 , 'N' , 'N' , 0 , 0 , 0 , 
				CNH , CNT , GRM , 0 , P_MHT , P_MTX , 0 , 0 , P_MHT , P_MTX , DM2 , DT2 , COE , CA1 , CT1 , CU1 , CP1 , 
				CX1 , CA2 , CT2 , CU2 , CP2 , CX2 , AJU , LMR , MBA , TEN , 0 , '' , BRG , BRL , BAS , BAT , BAU , BAM , 
				XF1 , XB1 , XM1 , XF2 , XB2 , XM2 , XF3 , XB3 , XM3 , REG , PEI , KEA , PBP , KTD , 
				ASV , PBT , SIP , PBS , RIS , PBR , RIA ); 
				
		END FOR;
	ELSE
	
		CALL SP_NCHRONO ( 'KHXID' , V_KHYID ) ; 
			
		INSERT INTO KPRGUG ( KHXID , KHXKHWID , KHXTYP , KHXIPB , KHXALX , KHXRSQ , KHXFOR , KHXKDEID , 
			KHXGARAN , KHXDEBP , KHXFINP , KHXSIT , KHXTRG , KHXNPE , KHXVEN , KHXCAF , KHXCAU , KHXCAE , KHXMHC , KHXFRC , KHXFR0 , KHXMHT , KHXMTX , KHXMTT , 
			KHXCNH , KHXCNT , KHXGRM , KHXPRO , KHXECH , KHXECT , KHXEMH , KHXEMT , KHXDM1 , KHXDT1 , KHXDM2 , KHXDT2 , KHXCOE , KHXCA1 , KHXCT1 , KHXCU1 , KHXCP1 , 
			KHXCX1 , KHXCA2 , KHXCT2 , KHXCU2 , KHXCP2 , KHXCX2 , KHXAJU , KHXLMR , KHXMBA , KHXTEN , KHXHON , KHXHOX , KHXBRG , KHXBRL , KHXBAS , KHXBAT , KHXBAU , KHXBAM , 
			KHXXF1 , KHXXB1 , KHXXM1 , KHXXF2 , KHXXB2 , KHXXM2 , KHXXF3 , KHXXB3 , KHXXM3 , KHXREG , KHXPEI , KHXKEA , KHXPBP , KHXKTD , KHXASV , KHXPBT , KHXSIP , KHXPBS , KHXRIS , KHXPBR , KHXRIA ) 

		SELECT V_KHYID , P_IDREGUL , KHYTYP , KHYIPB , KHYALX , KHYRSQ , KHYFOR , KHYKDEID , 
			KHYGARAN , P_DATEDEB , P_DATEFIN , 'N' , KHYTRG , KHYNPE , KHYVEN , KHYCAF , KHYCAU , KHYCAE , 0 , 'N' , 'N' , 0 , 0 , 0 , 
			KHYCNH , KHYCNT , KHYGRM , 0 , P_MHT , P_MTX , 0 , 0 , P_MHT , P_MTX , KHYDM2 , KHYDT2 , KHYCOE , KHYCA1 , KHYCT1 , KHYCU1 , KHYCP1 , 
			KHYCX1 , KHYCA2 , KHYCT2 , KHYCU2 , KHYCP2 , KHYCX2 , KHYAJU , KHYLMR , KHYMBA , KHYTEN , 0 , '' , KHYBRG , KHYBRL , KHYBAS , KHYBAT , KHYBAU , KHYBAM , 
			KHYXF1 , KHYXB1 , KHYXM1 , KHYXF2 , KHYXB2 , KHYXM2 , KHYXF3 , KHYXB3 , KHYXM3 , KHYREG , KHYPEI , KHYKEA , KHYPBP , KHYKTD , 
			KHYASV , KHYPBT , KHYSIP , KHYPBS , KHYRIS , KHYPBR , KHYRIA 
				 
		FROM KPRGUWP  k WHERE EXISTS (	
			SELECT KHYTYP , KHYIPB , KHYALX , KHYRSQ , KHYFOR , KHYKDEID , min(KHYDEBP) TOTO 
			FROM KPRGUWP k2 
			WHERE TRIM ( KHYIPB ) = P_CODEOFFRE AND KHYALX = P_VERSION AND KHYTYP = P_TYPE AND KHYRSQ = P_CODERSQ AND KHYFOR = P_CODEFOR AND KHYGARAN IN ( 'RCFR' , 'RCEX' , 'RCUS' )
				AND ((KHYDEBP BETWEEN P_DATEDEB AND P_DATEFIN) OR (KHYFINP BETWEEN P_DATEDEB AND P_DATEFIN)) 
				AND ( k.KHYTYP , k.KHYIPB , k.KHYALX , k.KHYRSQ , k.KHYFOR , k.KHYKDEID ) = ( k2.KHYTYP , k2.KHYIPB , k2.KHYALX , k2.KHYRSQ , k2.KHYFOR , k2.KHYKDEID )
			GROUP BY KHYTYP , KHYIPB , KHYALX , KHYRSQ , KHYFOR , KHYKDEID 
			HAVING (k.KHYDEBP = min(k2.KHYDEBP))
		);
		 
	END IF;

	OPEN CURSOMOUVT ; 
	 
  
END P1  ; 
  

  

