CREATE OR REPLACE PROCEDURE SP_ADR(
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_NEWVERSION INTEGER , 
	IN P_CODECONTRAT CHAR(9) , 
	IN P_VERSCONTRAT INTEGER , 
	IN P_TRAITEMENT CHAR(1) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
	DECLARE V_NEWCODEADR INTEGER DEFAULT 0 ; 
	DECLARE V_CODEOFFRE VARCHAR ( 9 ) DEFAULT '' ; 
	DECLARE V_VERSOFFRE INTEGER DEFAULT 0 ; 

	SET P_CODEOFFRE = LPAD ( TRIM ( P_CODEOFFRE ) , 9 , ' ');
	SET P_CODECONTRAT = LPAD ( TRIM ( P_CODECONTRAT ) , 9 , ' ');
	 
	SET V_CODEOFFRE = P_CODEOFFRE ; 
	SET V_VERSOFFRE = P_NEWVERSION ; 
	 
	IF ( P_TRAITEMENT = 'P' ) THEN 
		SET V_CODEOFFRE = P_CODECONTRAT ; 
		SET V_VERSOFFRE = P_VERSCONTRAT ; 
	END IF ; 
	 
	IF ( P_TRAITEMENT = 'V' ) THEN 
		FOR LOOP_ADRVERS AS FREE_LIST CURSOR FOR 
			SELECT JFADH CODEADR FROM YPRTADR WHERE  JFIPB = P_CODEOFFRE AND JFALX = P_VERSION 
		DO 
			IF ( CODEADR != 0 ) THEN 
				CALL SP_SECOPID ( P_CODEOFFRE , P_VERSION , P_TYPE , 'YADRESS' , CODEADR , V_NEWCODEADR ) ; 
				IF ( V_NEWCODEADR = 0 ) THEN 
					CALL SP_YCHRONO ( 'ADRESSE_CHRONO' , V_NEWCODEADR ) ; 
					CALL SP_INCOPID ( P_CODEOFFRE , P_VERSION , P_TYPE , 'YADRESS' , CODEADR , V_NEWCODEADR ) ; 
				END IF ; 
				 
				INSERT INTO YPRTADR 
				( SELECT V_CODEOFFRE , V_VERSOFFRE , JFRSQ , JFOBJ , JFAD1 , JFAD2 , JFDEP , JFCPO , JFVIL , JFPAY , V_NEWCODEADR 
					FROM YPRTADR 
					WHERE JFADH = CODEADR ) ; 
			END IF ; 
		END FOR ; 
	ELSE 
		FOR LOOP_ADR AS FREE_LIST CURSOR FOR 
			SELECT JFADH CODEADR FROM YPRTADR 
					INNER JOIN KPOFRSQ ON  JFIPB = KFIIPB AND JFALX = KFIALX AND JFRSQ = KFIRSQ AND JFOBJ = KFIOBJ 
							AND KFIPOG = V_CODEOFFRE AND KFIALG = V_VERSOFFRE 
				WHERE JFIPB = P_CODEOFFRE AND JFALX = P_VERSION 
		DO 
			IF ( CODEADR != 0 ) THEN 
				CALL SP_SECOPID ( P_CODEOFFRE , P_VERSION , P_TYPE , 'YADRESS' , CODEADR , V_NEWCODEADR ) ; 
				IF ( V_NEWCODEADR = 0 ) THEN 
					CALL SP_YCHRONO ( 'ADRESSE_CHRONO' , V_NEWCODEADR ) ; 
					CALL SP_INCOPID ( P_CODEOFFRE , P_VERSION , P_TYPE , 'YADRESS' , CODEADR , V_NEWCODEADR ) ; 
				END IF ; 
				 
				INSERT INTO YPRTADR 
				( SELECT V_CODEOFFRE , V_VERSOFFRE , JFRSQ , JFOBJ , JFAD1 , JFAD2 , JFDEP , JFCPO , JFVIL , JFPAY , V_NEWCODEADR 
					FROM YPRTADR 
					WHERE JFADH = CODEADR ) ; 
			END IF ; 
		END FOR ; 
	END IF ; 
  
END P1 ;
