CREATE PROCEDURE SP_ADDFAMILLEREASSURANCE ( 
	IN P_GARANTIE CHAR(10) , 
	IN P_CODE_BRANCHE CHAR(2) , 
	IN P_CODE_SOUS_BRANCHE CHAR(3) , 
	IN P_CODE_CATEGORIE CHAR(5) , 
	IN P_CODE_FAMILLE CHAR(6) , 
	IN P_CODE_BRANCHE_ANCIEN CHAR(2) , 
	IN P_CODE_SOUS_BRANCHE_ANCIEN CHAR(3) , 
	IN P_CODE_CATEGORIE_ANCIEN CHAR(5) , 
	IN P_CODE_FAMILLE_ANCIEN CHAR(6) , 
	IN P_MODE CHAR(1) , 
	OUT P_ERREUR CHAR(256) ) 
	LANGUAGE SQL 
	SPECIFIC SP_ADDFAMILLEREASSURANCE 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
DECLARE V_COUNT INTEGER DEFAULT 0 ; 
  
IF ( P_MODE = 'I' ) THEN 
  
SELECT COUNT ( * ) INTO V_COUNT 
FROM KGARFAM 
WHERE GVGAR = P_GARANTIE AND GVBRA = P_CODE_BRANCHE AND GVSBR = P_CODE_SOUS_BRANCHE AND GVCAT = P_CODE_CATEGORIE ; 
  
IF ( V_COUNT = 0 ) THEN 
INSERT INTO KGARFAM 
( GVGAR , GVBRA , GVSBR , GVCAT , GVFAM ) 
VALUES 
( P_GARANTIE , P_CODE_BRANCHE , P_CODE_SOUS_BRANCHE , P_CODE_CATEGORIE , P_CODE_FAMILLE ) ; 
  
ELSE 
SET P_ERREUR = 'Aucune mise à jour, cette famille de réassurance existe déjà pour cette garantie' ; 
END IF ; 
  
  
END IF ; 
IF ( P_MODE = 'U' ) THEN 
  
SELECT COUNT ( * ) INTO V_COUNT 
FROM KGARFAM 
WHERE GVGAR = P_GARANTIE AND GVBRA = P_CODE_BRANCHE_ANCIEN AND GVSBR = P_CODE_SOUS_BRANCHE_ANCIEN AND GVCAT = P_CODE_CATEGORIE_ANCIEN ; 
  
IF ( V_COUNT = 1 ) THEN 
SELECT COUNT ( * ) INTO V_COUNT 
FROM KGARFAM 
WHERE GVGAR = P_GARANTIE AND GVBRA = P_CODE_BRANCHE AND GVSBR = P_CODE_SOUS_BRANCHE AND GVCAT = P_CODE_CATEGORIE ; 
  
IF ( V_COUNT = 0 ) THEN 
DELETE FROM KGARFAM 
WHERE GVGAR = P_GARANTIE AND GVBRA = P_CODE_BRANCHE_ANCIEN AND GVSBR = P_CODE_SOUS_BRANCHE_ANCIEN AND GVCAT = P_CODE_CATEGORIE_ANCIEN ; 
INSERT INTO KGARFAM 
( GVGAR , GVBRA , GVSBR , GVCAT , GVFAM ) 
VALUES 
( P_GARANTIE , P_CODE_BRANCHE , P_CODE_SOUS_BRANCHE , P_CODE_CATEGORIE , P_CODE_FAMILLE ) ; 
ELSE 
SET P_ERREUR = 'Aucune mise à jour, cette famille de réassurance existe déjà pour cette garantie' ; 
END IF ; 
ELSE 
SET P_ERREUR = 'Aucune mise à jour, cette famille de réassurance n''existe pas' ; 
END IF ; 
  
END IF ; 
  
END P1  ; 
  

  

