CREATE PROCEDURE SP_BUILDJOINYPAR ( 
	IN P_TYPEJOIN CHAR(5) , 
	IN P_CON CHAR(5) , 
	IN P_FAM CHAR(5) , 
	IN P_ALIAS CHAR(20) , 
	IN P_OTHERCRITERIA CHAR(500) , 
	OUT P_RETURN CHAR(1000) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_BUILDJOINYPAR 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
  
SET P_RETURN = TRIM ( P_TYPEJOIN ) CONCAT ' JOIN YYYYPAR ' ; 
  
IF ( P_ALIAS != '' ) THEN 
SET P_RETURN = TRIM ( P_RETURN ) CONCAT ' ' CONCAT TRIM ( P_ALIAS ) ; 
END IF ; 
  
SET P_RETURN = TRIM ( P_RETURN ) CONCAT ' ON *.TCON = ''' CONCAT TRIM ( P_CON ) CONCAT ''' AND *.TFAM = ''' CONCAT TRIM ( P_FAM ) CONCAT ''' ' ; 
  
IF ( P_OTHERCRITERIA != '' ) THEN 
SET P_RETURN = TRIM ( P_RETURN ) CONCAT ' ' CONCAT TRIM ( P_OTHERCRITERIA ) ; 
END IF ; 
  
IF ( P_ALIAS != '' ) THEN 
SET P_RETURN = REPLACE ( TRIM ( P_RETURN ) , '*.' , TRIM ( P_ALIAS ) CONCAT '.' ) ; 
ELSE 
SET P_RETURN = REPLACE ( TRIM ( P_RETURN ) , '*.' , '' ) ; 
END IF ; 
  
SET P_RETURN = TRIM ( P_RETURN ) ; 
  
  
END P1  ; 
  

  

