CREATE PROCEDURE SP_CREATEDOCUMENTCLAUSE ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_ETAPE CHAR(10) , 
	IN P_IDCLAUSE INTEGER , 
	IN P_NAMEDOC CHAR(60) , 
	IN P_PATHDOC CHAR(150) , 
	IN P_CREATEDOC CHAR(1) , 
	OUT P_IDDOC INTEGER ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_CREATEDOCUMENTCLAUSE 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
	DECLARE V_COUNT INTEGER DEFAULT 0 ; 
	DECLARE V_IDDOC INTEGER DEFAULT 0 ; 
	DECLARE V_ACTGES CHAR ( 10 ) DEFAULT '' ; 
	 
	 
	IF ( P_TYPE = 'O' ) THEN 
		SET V_ACTGES = 'OFFRE' ; 
	END IF ; 
	IF ( P_TYPE = 'P' ) THEN 
		SET V_ACTGES = 'AFFNOUV' ; 
	END IF ; 
	 
	SET P_IDDOC = 0 ; 
	 
	 
	SELECT COUNT ( * ) INTO V_COUNT FROM KPDOC INNER JOIN KPCLAUSE ON KEQID = KCATXL WHERE KCAID = P_IDCLAUSE ;  -- WHERE TRIM ( KEQIPB ) = TRIM ( P_CODEOFFRE ) AND KEQALX = P_VERSION AND KEQTYP = P_TYPE AND TRIM ( KEQSERV ) = 'PRODU' AND TRIM ( KEQACTG ) = V_ACTGES AND TRIM ( KEQETAP ) = TRIM ( P_ETAPE ) ; 
	IF ( V_COUNT = 0 ) THEN 
		CALL SP_NCHRONO ( 'KEQID' , V_IDDOC ) ; 
		INSERT INTO KPDOC 
			( KEQID , KEQTYP , KEQIPB , KEQALX , KEQSERV , KEQACTG , KEQETAP , KEQTDOC , KEQAJT , KEQNOM , KEQCHM ) 
		VALUES 
			( V_IDDOC , P_TYPE , P_CODEOFFRE , P_VERSION , 'PRODU' , TRIM ( V_ACTGES ) , TRIM ( P_ETAPE ) , 'LIBRE' , 'O' , P_NAMEDOC , P_PATHDOC ) ; 
	ELSE 
		IF ( TRIM ( P_CREATEDOC ) != 'C' ) THEN 
			SELECT KEQID INTO V_IDDOC FROM KPDOC INNER JOIN KPCLAUSE ON KEQID = KCATXL WHERE KCAID = P_IDCLAUSE ;  -- WHERE TRIM ( KEQIPB ) = TRIM ( P_CODEOFFRE ) AND KEQALX = P_VERSION AND KEQTYP = P_TYPE AND TRIM ( KEQSERV ) = 'PRODU' AND TRIM ( KEQACTG ) = V_ACTGES AND TRIM ( KEQETAP ) = TRIM ( P_ETAPE ) ; 
			UPDATE KPDOC SET KEQNOM = P_NAMEDOC , KEQCHM = P_PATHDOC WHERE KEQID = V_IDDOC ; 
		END IF ; 
	END IF ;	 
	SET P_IDDOC = V_IDDOC ; 
	 
END P1  ; 
  

  

