CREATE OR REPLACE PROCEDURE SP_COPOP(
	IN P_CODEOFFRE VARCHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_COPYCODEOFFRE CHAR(9) , 
	IN P_COPYTYPE VARCHAR(9) , 
	IN P_COPYVERSION INTEGER ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
DECLARE V_CODEOFFRE VARCHAR ( 9 ) DEFAULT '' ; 
DECLARE V_OPP_KPOPP_REF_NEW INTEGER DEFAULT 0 ; 
DECLARE V_KPOPPAP_REF_NEW INTEGER DEFAULT 0 ; 

SET P_CODEOFFRE = LPAD ( TRIM ( P_CODEOFFRE ) , 9 , ' ') ;
SET P_COPYCODEOFFRE = LPAD ( TRIM ( P_COPYCODEOFFRE ) , 9 , ' ') ;


/* COPIE KPOPP */ 
  
FOR LOOP_OPP AS FREE_LIST CURSOR FOR 
  
	SELECT KFPID V_OPP_KPOPP_REF , KFPTYP V_KFPTYP , KFPIPB , KFPALX , KFPIDCB V_KFPIDCB , KFPTFI V_KFPTFI , KFPDESI V_KFPDESI , KFPREF V_KFPREF , 
	KFPDECH V_KFPDECH , KFPMNT V_KFPMNT , KFPCRU V_KFPCRU , KFPCRD V_KFPCRD , KFPCRH V_KFPCRH , KFPMAJU V_KFPMAJU , KFPMAJD V_KFPMAJD , KFPMAJH V_KFPMAJH , KFPTDS V_KFPTDS , KFPTYI V_KFPTYI 
	FROM KPOPP 
	WHERE KFPIPB = P_CODEOFFRE AND KFPALX = P_VERSION AND KFPTYP = P_TYPE 
	
			DO 
			CALL SP_NCHRONO ( 'KFPID' , V_OPP_KPOPP_REF_NEW ) ; 
				
		INSERT INTO KPOPP 
		( KFPID , KFPTYP , KFPIPB , KFPALX , KFPIDCB , KFPTFI , KFPDESI , KFPREF , KFPDECH , KFPMNT , KFPCRU , KFPCRD , KFPCRH , KFPMAJU , KFPMAJD , KFPMAJH , KFPTDS , KFPTYI ) 
		VALUES 
		( V_OPP_KPOPP_REF_NEW , P_COPYTYPE , P_COPYCODEOFFRE , P_COPYVERSION , V_KFPIDCB , V_KFPTFI , V_KFPDESI , V_KFPREF , V_KFPDECH , V_KFPMNT , V_KFPCRU , V_KFPCRD , V_KFPCRH , V_KFPMAJU , V_KFPMAJD , V_KFPMAJH , V_KFPTDS , V_KFPTYI ) ; 
		
		
		/* COPIE KPOPPAP */ 
		
		FOR LOOP_OPPAP AS FREE_LIST CURSOR FOR 
		SELECT KFQID V_KPOPPAP_REF , KFQTYP V_KFQTYP , KFQIPB , KFQALX , KFQKFPID V_KFQKFPID , KFQPERI V_KFQPERI , KFQRSQ V_KFQRSQ , KFQOBJ V_KFQOBJ , KFQCRU V_KFQCRU , KFQCRD V_KFQCRD , KFQMAJU V_KFQMAJU , KFQMAJD V_KFQMAJD 
		FROM KPOPPAP 
		WHERE KFQKFPID = V_OPP_KPOPP_REF 
			DO 
				CALL SP_NCHRONO ( 'KFQID' , V_KPOPPAP_REF_NEW ) ; 
			
		INSERT INTO KPOPPAP 
		( KFQID , KFQTYP , KFQIPB , KFQALX , KFQKFPID , KFQPERI , KFQRSQ , KFQOBJ , KFQCRU , KFQCRD , KFQMAJU , KFQMAJD ) 
		VALUES 
		( V_KPOPPAP_REF_NEW , P_COPYTYPE , P_COPYCODEOFFRE , P_COPYVERSION 
		, V_OPP_KPOPP_REF_NEW , V_KFQPERI , V_KFQRSQ , V_KFQOBJ , V_KFQCRU , V_KFQCRD , V_KFQMAJU , V_KFQMAJD ) ; 
		END FOR ; 
			
	END FOR ; 
END P1 ;
  

  

