CREATE OR REPLACE PROCEDURE SP_CREATECTRL ( 
	IN P_CODE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_ETAPE CHAR(10) , 
	IN P_ORDREETAPE INTEGER , 
	IN P_PERIMETRE CHAR(10) , 
	IN P_RISQUE INTEGER , 
	IN P_OBJET INTEGER , 
	IN P_IDINVENT INTEGER , 
	IN P_LGNINVENT INTEGER , 
	IN P_FORMULE INTEGER , 
	IN P_OPTION INTEGER , 
	IN P_GARANTIE CHAR(10) , 
	IN P_MESSAGE CHAR(100) , 
	IN P_NIVEAU CHAR(1) , 
	IN P_USER CHAR(10) , 
	IN P_DATE INTEGER , 
	IN P_HEURE INTEGER ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_CREATECTRL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
	 
	DECLARE V_NEWIDCTRL INTEGER DEFAULT 0 ; 
	DECLARE V_MAXORDRETAPE INTEGER DEFAULT 0 ; 
	 
	 --Récupération ID unique 
	CALL SP_NCHRONO ( 'KEUID' , V_NEWIDCTRL ) ; 
	 
	 --Récupération N° ordre dans étape 
	SELECT IFNULL ( MAX ( KEUORDR ) , 0 ) + 1 INTO V_MAXORDRETAPE FROM KPCTRL ; 
	 
	 --Enregistrement du contrôle 
	INSERT INTO KPCTRL 
	( KEUID , KEUTYP , KEUIPB , KEUALX , KEUETAPE , KEUETORD , KEUORDR , KEUPERI , KEURSQ , KEUOBJ , KEUINVEN , KEUINLGN , KEUFOR , KEUOPT , KEUGAR , KEUMSG , KEUNIVM , KEUCRU , KEUCRD , KEUCRH ) 
	VALUES 
	( V_NEWIDCTRL , P_TYPE , P_CODE , P_VERSION , P_ETAPE , P_ORDREETAPE , V_MAXORDRETAPE , P_PERIMETRE , P_RISQUE , P_OBJET , P_IDINVENT , P_LGNINVENT , P_FORMULE , P_OPTION , 
	P_GARANTIE , P_MESSAGE , P_NIVEAU , P_USER , P_DATE , P_HEURE ) ; 
		 
	END P1  ; 
  

  

