CREATE OR REPLACE PROCEDURE SP_CREATEOFFRE_ADR ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_BATIMENT CHAR(32) , 
	IN P_NUMVOIE CHAR(10) , 
	IN P_NUMVOIE2 CHAR(15) , 
	IN P_EXTVOIE CHAR(1) , 
	IN P_VOIE CHAR(32) , 
	IN P_BP CHAR(32) , 
	IN P_LOC CHAR(5) , 
	IN P_DEP CHAR(2) , 
	IN P_CP CHAR(5) , 
	IN P_VILLE CHAR(26) , 
	IN P_VOIECOMPLETE CHAR(32) , 
	IN P_VILLECOMPLETE CHAR(32) , 
	IN P_CPX CHAR(5) , 
	IN P_VILLEX CHAR(32) , 
	IN P_MATHEX INTEGER , 
	IN P_ISADDRESSEMPTY INTEGER,
	IN P_HASADRESSE CHAR(1) , 
	IN P_ADRCHRONO INTEGER , 
	IN P_LATITUDE NUMERIC(10, 7) , 
	IN P_LONGITUDE NUMERIC(10, 7) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_CREATEOFFRE_ADR
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	DBGVIEW = *SOURCE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
	DECLARE V_ADRCHR CHAR ( 40 ) DEFAULT '' ; 
	
	DECLARE V_NBLIGNE INTEGER DEFAULT 0 ; 
	DECLARE V_NBRSQ INTEGER DEFAULT 0 ; 
	DECLARE V_NBOBJ INTEGER DEFAULT 0 ; 
	
	DECLARE V_CODERSQ INTEGER DEFAULT 0 ; 	
	DECLARE V_CODEOBJ INTEGER DEFAULT 0 ; 
	
	DECLARE V_CHR_FOR_AFFECTATION INTEGER DEFAULT 0 ;
	DECLARE V_CHR INTEGER DEFAULT 0 ; 	
	DECLARE V_NUMCHR CHAR ( 40 ) DEFAULT '' ; 
	
	DECLARE V_NUMVOIE INTEGER DEFAULT 0 ; 
	DECLARE V_CP INTEGER DEFAULT 0 ; 
	DECLARE V_CPX INTEGER DEFAULT 0 ; 
	
	
	DECLARE V_ACTION_YADRESS CHAR (6) DEFAULT '';
	DECLARE V_ACTION_YPRTADR CHAR (12) DEFAULT '';
	
		-- ============= START REFACTO ADRESSE ================
		 --Max distance yet 
		 -- TRAITEMENT DE L'ADRESSE 
		 --Preparation des variables pour YADRESS  
		SET V_NUMVOIE = CAST ( ('0' CONCAT TRIM ( P_NUMVOIE )) AS INTEGER ) ; 
		SET V_CP = CAST ( ('0' CONCAT TRIM ( P_CP )) AS INTEGER ) ; 
		SET V_CPX = CAST ( ('0' CONCAT TRIM ( P_CPX )) AS INTEGER );
		
		-- Bug100: Refactoring into function call to set address 
		
		
		IF ( P_HASADRESSE = 'O' ) THEN 
		
			SET V_NBLIGNE = 0 ; 
			SELECT COUNT ( * ) INTO V_NBLIGNE FROM YPOBASE 
			WHERE PBIPB = P_CODEOFFRE AND PBALX = P_VERSION AND PBTYP = P_TYPE ;
			
			IF ( V_NBLIGNE > 0 ) THEN
				-- ENREGISTREMENT DANS YADRESS 
				SET V_NBLIGNE = 0 ;
				SELECT COUNT ( * ) INTO V_NBLIGNE FROM YADRESS
				WHERE ABPCHR = P_ADRCHRONO ;
				IF ( V_NBLIGNE != 0 ) THEN
					IF ( P_ISADDRESSEMPTY = 0 ) THEN
						SET V_ACTION_YADRESS = 'UPDATE';	
					ELSE
						SET V_ACTION_YADRESS = 'DELETE';
					END IF ;
				ELSE
					IF ( P_ISADDRESSEMPTY = 0 ) THEN
						IF ( P_ADRCHRONO = 0 ) THEN
							CALL SP_YCHRONO ( 'ADRESSE_CHRONO' , V_ADRCHR ) ;
							SET P_ADRCHRONO = CAST ( V_ADRCHR AS INTEGER ) ;
						END IF ;
						
						SET V_ACTION_YADRESS = 'CREATE';	
					END IF ;
				END IF ;
				
			END IF ;
			
			 
			IF ( P_ISADDRESSEMPTY = 0 ) THEN 
				SET V_CHR_FOR_AFFECTATION = P_ADRCHRONO;
			END IF ;
			
			CALL SP_UPDATE_ADR ( V_ACTION_YADRESS, P_NUMVOIE, P_NUMVOIE2 , P_CP, P_CPX, P_ADRCHRONO, V_CP, V_CPX, 
				P_BATIMENT, P_EXTVOIE, P_VOIE, P_BP, P_LOC, P_DEP, P_VILLE, P_VOIECOMPLETE, P_VILLECOMPLETE, 
				P_VILLEX, P_MATHEX, 1, '', P_CODEOFFRE, P_VERSION, P_TYPE, V_CODERSQ, V_CODEOBJ, 0, 'UPDATE_SET', V_CHR_FOR_AFFECTATION, P_DEP, P_CP,P_LATITUDE, P_LONGITUDE);

			SET V_ACTION_YADRESS = '';
			SET V_CHR_FOR_AFFECTATION = 0;
			/* ----------------------------------------------- */ 
			/* MODIFICATION DE LA SAUVEGARDE DE L'ADRESSE V4.1 */ 
			/* ----------------------------------------------- */ 

			SELECT COUNT ( * ) INTO V_NBRSQ FROM YPRTRSQ WHERE JEIPB = P_CODEOFFRE AND JEALX = P_VERSION ; 
			
			IF ( V_NBRSQ = 1 ) THEN /* SI MONO-RISQUE */ 
				SET V_CODERSQ = 0 ; 
				SET V_CHR = 0 ; 

				SELECT JERSQ , IFNULL ( JFADH , - 1 ) INTO V_CODERSQ , V_CHR 
				FROM YPRTRSQ 
				LEFT JOIN YPRTADR ON JFIPB = JEIPB AND JFALX = JEALX AND JFRSQ = JERSQ AND JFOBJ = 0 
				WHERE JEIPB = P_CODEOFFRE AND JEALX = P_VERSION ; 
				
				IF ( V_CHR > 0 ) THEN 
					IF ( P_ISADDRESSEMPTY = 0 ) THEN 
						SET V_ACTION_YPRTADR = 'UPDATE_WHERE';
						SET V_ACTION_YADRESS = 'UPDATE';
						SET V_CHR_FOR_AFFECTATION = V_CHR;
					ELSE 
						SET V_ACTION_YPRTADR = 'UPDATE_SET';
						SET V_ACTION_YADRESS = 'DELETE';
					END IF ; 					
				ELSE 
					IF ( V_CHR < 0 ) THEN 
						IF ( P_ISADDRESSEMPTY = 0 ) THEN 
							CALL SP_YCHRONO ( 'ADRESSE_CHRONO' , V_NUMCHR ) ; 
							SET V_CHR = CAST ( V_NUMCHR AS INTEGER ) ; 

							SET V_ACTION_YPRTADR = 'CREATE';
							SET V_ACTION_YADRESS = 'CREATE';
							SET V_CHR_FOR_AFFECTATION = V_CHR;
						ELSE 
							SET V_ACTION_YPRTADR = 'CREATE';
						END IF ; 
					ELSE 
						IF ( P_ISADDRESSEMPTY = 0 ) THEN 
							CALL SP_YCHRONO ( 'ADRESSE_CHRONO' , V_NUMCHR ) ; 
							SET V_CHR = CAST ( V_NUMCHR AS INTEGER ) ; 

							SET V_ACTION_YPRTADR = 'UPDATE_SET';
							SET V_ACTION_YADRESS = 'CREATE';
							SET V_CHR_FOR_AFFECTATION = V_CHR;
						ELSE 
							SET V_ACTION_YPRTADR = 'UPDATE_WHERE';
						END IF ;						
					END IF ; 
				END IF ; 
				
				CALL SP_UPDATE_ADR ( V_ACTION_YADRESS, P_NUMVOIE , P_NUMVOIE2 , P_CP, P_CPX, V_CHR, V_CP, V_CPX, 
				P_BATIMENT, P_EXTVOIE, P_VOIE, P_BP, P_LOC, P_DEP, P_VILLE, P_VOIECOMPLETE, P_VILLECOMPLETE, 
				P_VILLEX, P_MATHEX, 1, V_ACTION_YPRTADR, P_CODEOFFRE, P_VERSION, P_TYPE, V_CODERSQ, 0, V_CHR_FOR_AFFECTATION, '' , 0, '', '',P_LATITUDE, P_LONGITUDE);
				------------------- ******************* -----------------------------------------------------
				SET V_ACTION_YPRTADR = '';
				SET V_ACTION_YADRESS = '';
				SET V_CHR_FOR_AFFECTATION = 0;
				
				SELECT COUNT ( * ) INTO V_NBOBJ FROM YPRTOBJ WHERE JGIPB = P_CODEOFFRE AND JGALX = P_VERSION ; 
				IF ( V_NBOBJ = 1 ) THEN /* SI MONO-OBJET */ 
					SET V_CODEOBJ = 0 ; 
					SET V_CHR = 0 ; 

					SELECT JGOBJ , IFNULL ( JFADH , 0 ) INTO V_CODEOBJ , V_CHR 
					FROM YPRTOBJ 
						LEFT JOIN YPRTADR ON JFIPB = JGIPB AND JFALX = JGALX AND JFRSQ = JGRSQ AND JFOBJ = JGOBJ 
					WHERE JGIPB = P_CODEOFFRE AND JGALX = P_VERSION AND JGRSQ = V_CODERSQ ; 

					IF ( V_CHR > 0 ) THEN 
						IF ( P_ISADDRESSEMPTY = 0 ) THEN 							
							SET V_ACTION_YPRTADR = 'UPDATE_WHERE';
							SET V_ACTION_YADRESS = 'UPDATE';
							SET V_CHR_FOR_AFFECTATION = V_CHR;
						ELSE 
							SET V_ACTION_YPRTADR = 'UPDATE_SET';
							SET V_ACTION_YADRESS = 'DELETE';
						END IF ; 

					ELSE 
						IF ( P_ISADDRESSEMPTY = 0 ) THEN 
							SET V_NUMCHR = '';
							CALL SP_YCHRONO ( 'ADRESSE_CHRONO' , V_NUMCHR ) ; 
							SET V_CHR = CAST ( V_NUMCHR AS INTEGER ) ; 
							 
							IF ( NOT EXISTS ( SELECT 1 FROM YPRTADR WHERE JFIPB = P_CODEOFFRE AND JFALX = P_VERSION AND JFRSQ = V_CODERSQ AND JFOBJ = V_CODEOBJ FETCH FIRST 1 ROW ONLY ) ) THEN 
								SET V_ACTION_YPRTADR = 'CREATE';
							ELSE 
								SET V_ACTION_YPRTADR = 'UPDATE_SET';
							END IF ; 
							
							SET V_ACTION_YADRESS = 'CREATE';
							SET V_CHR_FOR_AFFECTATION = V_CHR;
						ELSE 
							IF ( NOT EXISTS ( SELECT 1 FROM YPRTADR WHERE JFADH = 0 AND JFIPB = P_CODEOFFRE AND JFALX = P_VERSION AND JFRSQ = V_CODERSQ AND JFOBJ = V_CODEOBJ FETCH FIRST 1 ROW ONLY ) ) THEN 
								SET V_ACTION_YPRTADR = 'CREATE'; 
							ELSE 
								SET V_ACTION_YPRTADR = 'UPDATE_WHERE'; 
							END IF ; 
						END IF ; 
					END IF ; 
				END IF ; 
				
				
				CALL SP_UPDATE_ADR ( V_ACTION_YADRESS, P_NUMVOIE , P_NUMVOIE2 , P_CP, P_CPX, V_CHR, V_CP, V_CPX, 
				P_BATIMENT, P_EXTVOIE, P_VOIE, P_BP, P_LOC, P_DEP, P_VILLE, P_VOIECOMPLETE, P_VILLECOMPLETE, 
				P_VILLEX, P_MATHEX, 1, V_ACTION_YPRTADR, P_CODEOFFRE, P_VERSION, P_TYPE, V_CODERSQ, V_CODEOBJ, V_CHR_FOR_AFFECTATION, '', 0, '', '',P_LATITUDE, P_LONGITUDE);
			END IF ; 
			/* ------------------------------------------------------ */ 
			/* FIN DE MODIFICATION DE LA SAUVEGARDE DE L'ADRESSE V4.1 */ 
			/* ------------------------------------------------------ */ 
  
		END IF ; 
  
		-- ============= END REFACTO ADRESSE ================
	
	END P1;
