CREATE PROCEDURE SP_CONTRATCOPIE ( 
	IN P_CODECONTRAT CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_COPYCODECONTRAT CHAR(9) , 
	IN P_COPYVERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_DATESYSTEME CHAR(8) , 
	IN P_USER CHAR(15) , 
	IN P_TRAITEMENT CHAR(1) , 
	IN P_MODECOPY CHAR(7) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_CONTRATCOPIE 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
--Appel la procédure de copie d'offre pour le moment 
--TODO : customisation pour les contrats et les templates 
CALL SP_OFCOPIE ( P_CODECONTRAT , P_VERSION , P_COPYCODECONTRAT , P_COPYVERSION , P_TYPE , P_DATESYSTEME , P_USER , P_TRAITEMENT , P_MODECOPY ) ; 
  
END P1  ; 
  

  

