CREATE PROCEDURE SP_CANAFNO ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_CANAFNO 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
DELETE FROM KPOFRSQ WHERE KFIIPB = P_CODEOFFRE AND KFIALX = P_VERSION ; 
DELETE FROM KPOFOPT WHERE KFJIPB = P_CODEOFFRE AND KFJALX = P_VERSION ; 
DELETE FROM KPOFTAR WHERE KFKIPB = P_CODEOFFRE AND KFKALX = P_VERSION ; 

END P1  ; 