CREATE OR REPLACE PROCEDURE SP_CINTERV(
	IN P_CODEOFFRESOURCE CHAR(9) , 
	IN P_VERSIONSOURCE INTEGER , 
	IN P_TYPESOURCE CHAR(1) , 
	IN P_CODEDESTINATION CHAR(9) , 
	IN P_VERSIONDESTINATION INTEGER , 
	IN P_TYPEDESTINATION CHAR(1) , 
	IN P_MODECOPY CHAR(7) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
	DECLARE V_NEWCODEINTER INTEGER DEFAULT 0 ; 

	SET P_CODEOFFRESOURCE = LPAD ( TRIM ( P_CODEOFFRESOURCE ) , 9 , ' ') ;
	SET P_CODEDESTINATION = LPAD ( TRIM ( P_CODEDESTINATION ) , 9 , ' ') ;

			 
	FOR LOOP_INTER AS FREE_LIST CURSOR FOR 
		SELECT KHBID CODEINTER , KHBTYI TYPEINTER , KHBIIN IDINTERV , KHBINL CODEINTERLOC , KHBREF REFINTERV , KHBPRP PRINCIPAL , KHBMDC MEDECIN FROM KPINTER				 
		WHERE KHBIPB = P_CODEOFFRESOURCE AND KHBALX = P_VERSIONSOURCE AND KHBTYP = P_TYPESOURCE 
	DO 
		IF ( CODEINTER != 0 ) THEN 
			CALL SP_SECOPID ( P_CODEOFFRESOURCE , P_VERSIONSOURCE , P_TYPESOURCE , 'KPINTER' , CODEINTER , V_NEWCODEINTER ) ; 
			IF ( V_NEWCODEINTER = 0 ) THEN 
				CALL SP_NCHRONO ( 'KHBID' , V_NEWCODEINTER ) ; 
				CALL SP_INCOPID ( P_CODEOFFRESOURCE , P_VERSIONSOURCE , P_TYPESOURCE , 'KPINTER' , CODEINTER , V_NEWCODEINTER ) ; 
			END IF ; 
			 
			IF ( ( TRIM ( P_MODECOPY ) = 'VERSION' ) OR ( TRIM ( P_MODECOPY ) = 'AFFNOUV' ) OR ( TRIM ( P_MODECOPY ) = 'CNVA' ) ) THEN 
				INSERT INTO KPINTER 
				( SELECT V_NEWCODEINTER , P_TYPEDESTINATION , P_CODEDESTINATION , P_VERSIONDESTINATION , TYPEINTER , IDINTERV , CODEINTERLOC , REFINTERV , 0 , PRINCIPAL , MEDECIN 
					FROM KPINTER 
					WHERE KHBID = CODEINTER ) ;				 
			ELSE 
				INSERT INTO KPINTER 
				( SELECT V_NEWCODEINTER , P_TYPEDESTINATION , P_CODEDESTINATION , P_VERSIONDESTINATION , TYPEINTER , IDINTERV , CODEINTERLOC , '' , 0 , PRINCIPAL , MEDECIN 
					FROM KPINTER 
					WHERE KHBID = CODEINTER ) ; 
			END IF ; 
		END IF ; 
	END FOR ; 
  
END P1  ; 
  

  

