CREATE PROCEDURE SP_COPYMODELEGAR ( 
	IN P_CODE CHAR(15) ,  
	IN P_CODECOPIE CHAR(15) )
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_COPYMODELEGAR 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
DECLARE V_COUNT INTEGER DEFAULT 0 ; 
DECLARE V_COUNTCOPIE INTEGER DEFAULT 0 ; 
DECLARE V_DESCCOPIE CHAR ( 30 ) DEFAULT '' ; 

DECLARE V_NEWSEQ1 INTEGER DEFAULT 0 ; 
DECLARE V_NEWSEQ2 INTEGER DEFAULT 0 ; 
DECLARE V_NEWSEQ3 INTEGER DEFAULT 0 ; 
DECLARE V_NEWSEQ4 INTEGER DEFAULT 0 ; 

SELECT COUNT(*) INTO V_COUNT FROM YPLMGA WHERE D1MGA = P_CODE;
SELECT COUNT(*) INTO V_COUNTCOPIE FROM YPLMGA WHERE D1MGA = P_CODECOPIE;
IF (V_COUNT = 1 AND V_COUNTCOPIE = 0) THEN
	-- Insertion du nouveau modèle dans YPLMGA
	SELECT CONCAT('Copie de ', D1LIB) INTO V_DESCCOPIE FROM YPLMGA WHERE D1MGA = P_CODE;
	INSERT INTO YPLMGA (D1MGA, D1LIB)
	VALUES (P_CODECOPIE, V_DESCCOPIE);

	-- Boucle sur les garantie de niveau 1
	FOR V_GARNIV1 AS SELECT C2SEQ 
	FROM YPLTGAR 
	WHERE C2MGA = P_CODE AND C2NIV = 1 
	DO 
		CALL SP_NCHRONO ( 'C2SEQ' , V_NEWSEQ1 ); 
		--SELECT B9SEQ INTO V_NEWSEQ1 FROM YALBINFILE.YPLCHRO WHERE B9OBE = 'YPLTGAR';
		--UPDATE YALBINFILE.YPLCHRO SET B9SEQ = B9SEQ + 1 WHERE B9OBE = 'YPLTGAR';

		INSERT INTO YPLTGAR (C2SEQ, C2MGA, C2OBE, C2NIV, C2GAR, C2ORD, C2LIB, C2SEM, C2CAR, C2NAT, C2INA, C2CNA, C2TAX, 
		C2ALT, C2TRI, C2SE1, C2SCR, C2PRP, C2TCD, C2MRF, C2NTM, C2MAS)
		SELECT V_NEWSEQ1, P_CODECOPIE, C2OBE, C2NIV, C2GAR, C2ORD, C2LIB, 0, C2CAR, C2NAT, C2INA, C2CNA, C2TAX, 
		C2ALT, C2TRI, 0, C2SCR, C2PRP, C2TCD, C2MRF, C2NTM, C2MAS
		FROM YPLTGAR
		WHERE C2SEQ = V_GARNIV1.C2SEQ;

		-- Insertion des LCI niv 1
		INSERT INTO YPLTGAL (C4SEQ, C4TYP, C4BAS, C4VAL, C4UNT, C4MAJ, C4OBL, C4ALA)
		SELECT V_NEWSEQ1, C4TYP, C4BAS, C4VAL, C4UNT, C4MAJ, C4OBL, C4ALA
		FROM YPLTGAL
		WHERE C4SEQ = V_GARNIV1.C2SEQ;

		-- Boucle sur les garantie de niveau 2
		FOR V_GARNIV2 AS SELECT C2SEQ 
		FROM YPLTGAR 
		WHERE C2MGA = P_CODE AND C2NIV = 2 AND C2SEM = V_GARNIV1.C2SEQ 
		DO 
			CALL SP_NCHRONO ( 'C2SEQ' , V_NEWSEQ2 ); 
			--SELECT B9SEQ INTO V_NEWSEQ2 FROM YALBINFILE.YPLCHRO WHERE B9OBE = 'YPLTGAR';
			--UPDATE YALBINFILE.YPLCHRO SET B9SEQ = B9SEQ + 1 WHERE B9OBE = 'YPLTGAR';

			INSERT INTO YPLTGAR (C2SEQ, C2MGA, C2OBE, C2NIV, C2GAR, C2ORD, C2LIB, C2SEM, C2CAR, C2NAT, C2INA, C2CNA, C2TAX, 
			C2ALT, C2TRI, C2SE1, C2SCR, C2PRP, C2TCD, C2MRF, C2NTM, C2MAS)
			SELECT V_NEWSEQ2, P_CODECOPIE, C2OBE, C2NIV, C2GAR, C2ORD, C2LIB, V_NEWSEQ1, C2CAR, C2NAT, C2INA, C2CNA, C2TAX, 
			C2ALT, C2TRI, V_NEWSEQ1, C2SCR, C2PRP, C2TCD, C2MRF, C2NTM, C2MAS
			FROM YPLTGAR
			WHERE C2SEQ = V_GARNIV2.C2SEQ;
	
			-- Insertion des LCI niv 2
			INSERT INTO YPLTGAL (C4SEQ, C4TYP, C4BAS, C4VAL, C4UNT, C4MAJ, C4OBL, C4ALA)
			SELECT V_NEWSEQ2, C4TYP, C4BAS, C4VAL, C4UNT, C4MAJ, C4OBL, C4ALA
			FROM YPLTGAL
			WHERE C4SEQ = V_GARNIV2.C2SEQ;
	
			-- Boucle sur les garantie de niveau 3
			FOR V_GARNIV3 AS SELECT C2SEQ 
			FROM YPLTGAR 
			WHERE C2MGA = P_CODE AND C2NIV = 3 AND C2SEM = V_GARNIV2.C2SEQ 
			DO 
				CALL SP_NCHRONO ( 'C2SEQ' , V_NEWSEQ3 ); 
				--SELECT B9SEQ INTO V_NEWSEQ3 FROM YALBINFILE.YPLCHRO WHERE B9OBE = 'YPLTGAR';
				--UPDATE YALBINFILE.YPLCHRO SET B9SEQ = B9SEQ + 1 WHERE B9OBE = 'YPLTGAR';
	
				INSERT INTO YPLTGAR (C2SEQ, C2MGA, C2OBE, C2NIV, C2GAR, C2ORD, C2LIB, C2SEM, C2CAR, C2NAT, C2INA, C2CNA, C2TAX, 
				C2ALT, C2TRI, C2SE1, C2SCR, C2PRP, C2TCD, C2MRF, C2NTM, C2MAS)
				SELECT V_NEWSEQ3, P_CODECOPIE, C2OBE, C2NIV, C2GAR, C2ORD, C2LIB, V_NEWSEQ2, C2CAR, C2NAT, C2INA, C2CNA, C2TAX, 
				C2ALT, C2TRI, V_NEWSEQ1, C2SCR, C2PRP, C2TCD, C2MRF, C2NTM, C2MAS
				FROM YPLTGAR
				WHERE C2SEQ = V_GARNIV3.C2SEQ;
		
				-- Insertion des LCI niv 3
				INSERT INTO YPLTGAL (C4SEQ, C4TYP, C4BAS, C4VAL, C4UNT, C4MAJ, C4OBL, C4ALA)
				SELECT V_NEWSEQ3, C4TYP, C4BAS, C4VAL, C4UNT, C4MAJ, C4OBL, C4ALA
				FROM YPLTGAL
				WHERE C4SEQ = V_GARNIV3.C2SEQ;
		
				-- Boucle sur les garantie de niveau 4
				FOR V_GARNIV4 AS SELECT C2SEQ 
				FROM YPLTGAR 
				WHERE C2MGA = P_CODE AND C2NIV = 4 AND C2SEM = V_GARNIV3.C2SEQ 
				DO 
					CALL SP_NCHRONO ( 'C2SEQ' , V_NEWSEQ4 ); 
					--SELECT B9SEQ INTO V_NEWSEQ4 FROM YALBINFILE.YPLCHRO WHERE B9OBE = 'YPLTGAR';
					--UPDATE YALBINFILE.YPLCHRO SET B9SEQ = B9SEQ + 1 WHERE B9OBE = 'YPLTGAR';
		
					INSERT INTO YPLTGAR (C2SEQ, C2MGA, C2OBE, C2NIV, C2GAR, C2ORD, C2LIB, C2SEM, C2CAR, C2NAT, C2INA, C2CNA, C2TAX, 
					C2ALT, C2TRI, C2SE1, C2SCR, C2PRP, C2TCD, C2MRF, C2NTM, C2MAS)
					SELECT V_NEWSEQ4, P_CODECOPIE, C2OBE, C2NIV, C2GAR, C2ORD, C2LIB, V_NEWSEQ3, C2CAR, C2NAT, C2INA, C2CNA, C2TAX, 
					C2ALT, C2TRI, V_NEWSEQ1, C2SCR, C2PRP, C2TCD, C2MRF, C2NTM, C2MAS
					FROM YPLTGAR
					WHERE C2SEQ = V_GARNIV4.C2SEQ;
			
					-- Insertion des LCI niv 4
					INSERT INTO YPLTGAL (C4SEQ, C4TYP, C4BAS, C4VAL, C4UNT, C4MAJ, C4OBL, C4ALA)
					SELECT V_NEWSEQ4, C4TYP, C4BAS, C4VAL, C4UNT, C4MAJ, C4OBL, C4ALA
					FROM YPLTGAL
					WHERE C4SEQ = V_GARNIV4.C2SEQ;
				
				END FOR;
			
			END FOR;
		
		END FOR;
	
	END FOR;
END IF;

  
  
END P1  ;

