CREATE OR REPLACE PROCEDURE SP_COPIEDOCEXT(
	IN P_CODESOURCE CHAR(9) , 
	IN P_VERSIONSOURCE INTEGER , 
	IN P_TYPESOURCE CHAR(1) , 
	IN P_CODEDEST CHAR(9) , 
	IN P_VERSIONDEST INTEGER , 
	IN P_TYPEDEST CHAR(1) , 
	IN P_MODECOPY CHAR(7) , 
	IN P_DATESYSTEME CHAR(8) , 
	IN P_USER CHAR(15) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
	 
	DECLARE V_NEWID INTEGER DEFAULT 0 ; 
	DECLARE V_NEWCHEMIN CHAR ( 255 ) DEFAULT '' ; 
	DECLARE V_NEWNOM CHAR ( 255 ) DEFAULT '' ; 
	 
	DECLARE V_SOURCEIPBALXTYP CHAR ( 15 ) DEFAULT '' ; 
	DECLARE V_DESTIPBALXTYP CHAR ( 15 ) DEFAULT '' ; 
	 
	DECLARE V_SOURCEIPBALX CHAR ( 15 ) DEFAULT '' ; 
	DECLARE V_DESTIPBALX CHAR ( 15 ) DEFAULT '' ; 
	 
	DECLARE V_COUNT INTEGER DEFAULT 0 ; 

	SET P_CODESOURCE = LPAD ( TRIM ( P_CODESOURCE ) , 9 , ' ') ;
	SET P_CODEDEST = LPAD ( TRIM ( P_CODEDEST ) , 9 , ' ') ;
	 
	FOR LOOP_DOC AS FREE_LIST CURSOR FOR 
		SELECT KERID V_KERID , KERTYP V_KERTYP , KERIPB V_KERIPB , KERALX V_KERALX , KERSUA V_KERSUA , KERNUM V_KERNUM , KERSBR V_KERSBR , 
			KERSERV V_KERSERV , KERACTG V_KERACTG , KERAVN V_KERAVN , KERORD V_KERORD , KERTYPO V_KERTYPO , KERLIB V_KERLIB , KERNOM V_KERNOM , 
			KERCHM V_KERCHM , KERSTU V_KERSTU , KERSIT V_KERSIT , KERSTD V_KERSTD , KERSTH V_KERSTH , KERCRU V_KERCRU , KERCRD V_KERCRD , 
			KERCRH V_KERCRH , KERREF V_KERREF 
		FROM KPDOCEXT 
		WHERE  KERIPB = P_CODESOURCE AND KERTYP = P_TYPESOURCE AND KERALX = P_VERSIONSOURCE 
	DO 
		 --Vérif existence de ce document externe dans la table temporaire (cas copie clause pj, déjà géré dans copie clause) 
		SELECT COUNT ( * ) INTO V_COUNT FROM KPCOPDC WHERE KHQOLDID = V_KERID AND KHQTABLE = 'KPDOCEXT' ; 
		 
		IF ( V_COUNT = 0 ) THEN 
			CALL SP_NCHRONO ( 'KERID' , V_NEWID ) ; 
			 
			SET V_SOURCEIPBALXTYP = TRIM ( P_CODESOURCE ) CONCAT '__' CONCAT RIGHT ( REPEAT ( '0' , 4 ) || P_VERSIONSOURCE , 4 ) CONCAT '__' CONCAT P_TYPESOURCE ; 
			SET V_DESTIPBALXTYP = TRIM ( P_CODEDEST ) CONCAT '__' CONCAT RIGHT ( REPEAT ( '0' , 4 ) || P_VERSIONDEST , 4 ) CONCAT '__' CONCAT P_TYPEDEST ;	 
			 
			SET V_NEWCHEMIN = REPLACE ( LOWER ( V_KERCHM ) , TRIM ( LOWER ( V_SOURCEIPBALXTYP ) ) , TRIM ( LOWER ( V_DESTIPBALXTYP ) ) ) ; 
			SET V_NEWNOM = REPLACE ( LOWER ( V_KERNOM ) , TRIM ( LOWER ( V_SOURCEIPBALXTYP ) ) , TRIM ( LOWER ( V_DESTIPBALXTYP ) ) ) ; 
			 
			SET V_SOURCEIPBALXTYP = TRIM ( P_CODESOURCE ) CONCAT '_' CONCAT RIGHT ( REPEAT ( '0' , 4 ) || P_VERSIONSOURCE , 4 ) CONCAT '_' CONCAT P_TYPESOURCE ; 
			SET V_DESTIPBALXTYP = TRIM ( P_CODEDEST ) CONCAT '_' CONCAT RIGHT ( REPEAT ( '0' , 4 ) || P_VERSIONDEST , 4 ) CONCAT '_' CONCAT P_TYPEDEST ;	 
			 
			SET V_NEWCHEMIN = REPLACE ( LOWER ( V_NEWCHEMIN ) , TRIM ( LOWER ( V_SOURCEIPBALXTYP ) ) , TRIM ( LOWER ( V_DESTIPBALXTYP ) ) ) ; 
			SET V_NEWNOM = REPLACE ( LOWER ( V_NEWNOM ) , TRIM ( LOWER ( V_SOURCEIPBALXTYP ) ) , TRIM ( LOWER ( V_DESTIPBALXTYP ) ) ) ; 
			 
			SET V_SOURCEIPBALXTYP = TRIM ( P_CODESOURCE ) CONCAT '__' CONCAT P_VERSIONSOURCE CONCAT '__' CONCAT P_TYPESOURCE ; 
			SET V_DESTIPBALXTYP = TRIM ( P_CODEDEST ) CONCAT '__' CONCAT P_VERSIONDEST CONCAT '__' CONCAT P_TYPEDEST ;	 
			 
			SET V_NEWCHEMIN = REPLACE ( LOWER ( V_NEWCHEMIN ) , TRIM ( LOWER ( V_SOURCEIPBALXTYP ) ) , TRIM ( LOWER ( V_DESTIPBALXTYP ) ) ) ; 
			SET V_NEWNOM = REPLACE ( LOWER ( V_NEWNOM ) , TRIM ( LOWER ( V_SOURCEIPBALXTYP ) ) , TRIM ( LOWER ( V_DESTIPBALXTYP ) ) ) ; 
			 
			SET V_SOURCEIPBALXTYP = TRIM ( P_CODESOURCE ) CONCAT '_' CONCAT P_VERSIONSOURCE CONCAT '_' CONCAT P_TYPESOURCE ; 
			SET V_DESTIPBALXTYP = TRIM ( P_CODEDEST ) CONCAT '_' CONCAT P_VERSIONDEST CONCAT '_' CONCAT P_TYPEDEST ;	 
			 
			INSERT INTO KPDOCEXT 
				( KERID , KERTYP , KERIPB , KERALX , KERSUA , KERNUM , KERSBR , KERSERV , KERACTG , KERAVN , KERORD , KERTYPO , 
				KERLIB , KERNOM , KERCHM , KERSTU , KERSIT , KERSTD , KERSTH , KERCRU , KERCRD , KERCRH , KERREF ) 
			VALUES 
				( V_NEWID , P_TYPEDEST , P_CODEDEST , P_VERSIONDEST , V_KERSUA , V_KERNUM , V_KERSBR , V_KERSERV , V_KERACTG , V_KERAVN , V_KERORD , V_KERTYPO , 
				V_KERLIB , V_NEWNOM , V_NEWCHEMIN , P_USER , V_KERSIT , P_DATESYSTEME , 0 , P_USER , P_DATESYSTEME , 0 , V_KERREF ) ; 
			 
			INSERT INTO KPCOPDC 
				( KHQIPB , KHQALX , KHQTYP , KHQAVN , KHQOLDC , KHQCODE , KHQNOMD , KHQTABLE ) 
			VALUES 
				( P_CODEDEST , P_VERSIONDEST , P_TYPEDEST , 0 , TRIM ( V_KERCHM ) , V_NEWID , TRIM ( V_NEWCHEMIN ) , 'KPDOCEXT' ) ; 
		END IF ; 
	END FOR ; 
  
END P1  ; 
  

  

