CREATE PROCEDURE SP_COFVERI ( 
	IN P_CODECONTRAT CHAR(9) , 
	IN P_VERSIONCONTRAT INTEGER , 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_CODEFOR INTEGER , 
	IN P_CODEOPT INTEGER , 
	IN P_GUIDFOR INTEGER , 
	IN P_GUIDOPT INTEGER , 
	IN P_GUIDVOL INTEGER , 
	OUT P_CHECK CHAR(1) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_COFVERI 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
SET P_CHECK = '' ; 
  
SELECT IFNULL ( KFJSEL , '' ) INTO P_CHECK 
FROM KPOFOPT 
WHERE KFJPOG = P_CODECONTRAT AND KFJALG = P_VERSIONCONTRAT AND KFJIPB = P_CODEOFFRE AND KFJALX = P_VERSION AND KFJTENG = P_TYPE 
AND KFJFOR = P_CODEFOR AND KFJOPT = P_CODEOPT AND KFJKDAID = P_GUIDFOR AND KFJKDBID = P_GUIDOPT AND KFJKAKID = P_GUIDVOL ; 
  
END P1  ; 
  

  

