CREATE PROCEDURE SP_CHANGECODETAXE ( 
	IN P_CODEAFFAIRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) ) 
	LANGUAGE SQL 
	SPECIFIC SP_CHANGECODETAXE 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
	DECLARE V_COUNT INTEGER DEFAULT 0 ; 
	 
	SET V_COUNT = 0 ; 
	 
	SELECT COUNT ( * ) INTO V_COUNT 
		FROM KPOPTAP 
			INNER JOIN KPIRSOB ON KFAIPB = KDDIPB AND KFAALX = KDDALX AND KFATYP = KDDTYP 
		WHERE TRIM ( KDDIPB ) = TRIM ( P_CODEAFFAIRE ) AND KDDALX = P_VERSION AND KDDTYP = P_TYPE AND KFAQMD = 'O' ; 
		 
	FOR LOOPGAR AS FREE_LIST CURSOR FOR 
		SELECT KDEID GARID , KDEGARAN CODEGAR , KDETAXCOD TAXECODE , GAIFC INFOCOMP 
		FROM KPOPTAP 
			INNER JOIN KPOPTD ON KDDKDBID = KDCKDBID 
			INNER JOIN KPGARAN ON KDCID = KDEKDCID 
			INNER JOIN KGARAN ON GAGAR = KDEGARAN 
		WHERE TRIM ( KDDIPB ) = TRIM ( P_CODEAFFAIRE ) AND KDDALX = P_VERSION AND KDDTYP = P_TYPE 
	DO 
		IF ( V_COUNT > 0 ) THEN /* SI PRÉSENCE D'UN QUESTIONNAIRE MÉDICAL */ 
			IF ( TRIM ( INFOCOMP ) = 'Q' AND TRIM ( TAXECODE ) = 'IN' ) THEN 
				/* MISE À JOUR DE LA PRÉSENCE DE QUESTIONNAIRE MÉDICAL POUR LA GARANTIE */ 
				UPDATE KPGARAN SET KDETAXCOD = 'IQ' WHERE KDEID = GARID ; 
				UPDATE KPGARAH SET KDETAXCOD = 'IQ' WHERE KDEID = GARID ; 
				UPDATE KPGARAW SET KDETAXCOD = 'IQ' WHERE KDEID = GARID ; 
			END IF ; 
		ELSE /* NON PRÉSENCE DE QUESTIONNAIRE MÉDICAL */ 
			IF ( TRIM ( INFOCOMP ) = 'Q' AND TRIM ( TAXECODE ) = 'IQ' ) THEN 
				/* MISE À JOUR DE LA NON PRÉSENCE DE QUESTIONNAIRE MÉDICAL POUR LA GARANTIE */ 
				UPDATE KPGARAN SET KDETAXCOD = 'IN' WHERE KDEID = GARID ; 
				UPDATE KPGARAH SET KDETAXCOD = 'IN' WHERE KDEID = GARID ; 
				UPDATE KPGARAW SET KDETAXCOD = 'IN' WHERE KDEID = GARID ; 
			END IF ; 
		END IF ; 
	END FOR ; 
  
END P1  ; 
  

  

