CREATE PROCEDURE SP_CONFIRMREPRISE ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_CODEAVN INTEGER , 
	IN P_TYPEAVT CHAR(5) , 
	IN P_ETAT CHAR(1) , 
	IN P_USER CHAR(10) , 
	IN P_YEARNOW INTEGER , 
	IN P_MONTHNOW INTEGER , 
	IN P_DAYNOW INTEGER , 
	IN P_MINUTENOW INTEGER , 
	IN P_CODETRAITEMENT CHAR(5) , 
	IN P_LIBTRAITEMENT CHAR(30) , 
	IN P_ACTEGESTION CHAR(1) ) 
	LANGUAGE SQL 
	SPECIFIC SP_CONFIRMREPRISE 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
	 
	DECLARE V_PERIODICITE CHAR ( 1 ) DEFAULT '' ; 
  
	UPDATE YPOBASE 
		SET PBETA = P_ETAT , PBMJU = P_USER , PBMJA = P_YEARNOW , PBMJM = P_MONTHNOW , PBMJJ = P_DAYNOW 
		WHERE TRIM ( PBIPB ) = TRIM ( P_CODEOFFRE ) AND PBALX = P_VERSION AND PBTYP = P_TYPE AND PBAVN = P_CODEAVN ; 
		 
	IF ( P_CODEAVN != 0 ) THEN 
		INSERT INTO YWRTANP 
			( WWIPB , WWALX , WWIPK ) 
			( SELECT PKIPB , PKALX , PKIPK FROM YPRIMES 
				WHERE TRIM ( PKIPB ) = TRIM ( P_CODEOFFRE ) AND PKALX = P_VERSION AND PKAVN = P_CODEAVN 
					AND PKSIT NOT IN ( 'X' , 'W' ) AND PKOPE <> 20 ) ; 
	ELSE 
		DELETE FROM YPOECHE WHERE TRIM ( PIIPB ) = TRIM ( P_CODEOFFRE ) AND PIALX = P_VERSION AND PITYP = P_TYPE ; 
		SET V_PERIODICITE = '' ; 
		SELECT PBPER INTO V_PERIODICITE FROM YPOBASE WHERE TRIM ( PBIPB ) = TRIM ( P_CODEOFFRE ) AND PBALX = P_VERSION AND PBTYP = P_TYPE ; 
		IF ( V_PERIODICITE = 'E' ) THEN 
			UPDATE YPOBASE SET PBPER = 'U' WHERE TRIM ( PBIPB ) = TRIM ( P_CODEOFFRE ) AND PBALX = P_VERSION AND PBTYP = P_TYPE ; 
		END IF ; 
	END IF ; 
	 
	IF ( TRIM ( P_TYPEAVT ) = 'REGUL' OR TRIM ( P_TYPEAVT ) = 'AVNRG' ) THEN 
		UPDATE KPRGU 
			SET KHWETA = P_ETAT , KHWMAJU = P_USER , KHWMAJD = ( P_YEARNOW * 10000 + P_MONTHNOW * 100 + P_DAYNOW ) 
		WHERE TRIM ( KHWIPB ) = TRIM ( P_CODEOFFRE ) AND KHWALX = P_VERSION AND KHWTYP = P_TYPE AND KHWAVN = P_CODEAVN ; 
	END IF ; 
	 
	INSERT INTO YPOTRAC 
		( PYTYP , PYIPB , PYALX , PYAVN , PYTTR , PYVAG , PYTRA , PYTRM , PYTRJ , PYTRH , 
			PYLIB , PYINF , PYSDA , PYSDM , PYSDJ , PYSFA , PYSFM , PYSFJ , PYMJU , PYMJA , PYMJM , PYMJJ , PYMJH ) 
	VALUES 
		( P_TYPE , P_CODEOFFRE , P_VERSION , P_CODEAVN , P_CODETRAITEMENT , P_ACTEGESTION , P_YEARNOW , P_MONTHNOW , P_DAYNOW , P_MINUTENOW , 
			P_LIBTRAITEMENT , 'I' , 0 , 0 , 0 , 0 , 0 , 0 , P_USER , P_YEARNOW , P_MONTHNOW , P_DAYNOW , P_MINUTENOW ) ;	 
	 
END P1  ; 
  

  

