CREATE OR REPLACE PROCEDURE SP_CORQOB ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_CODECONTRAT CHAR(9) , 
	IN P_VERSIONCONTRAT INTEGER ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_CORQOB 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
DECLARE CURSOR_LSTRSQOBJ CURSOR FOR 
SELECT KFIPOG CODECONTRAT , KFIALG VERSCONTRAT , KFITYE TYPEENREG , KFIRSQ CODERSQ , KFIOBJ CODEOBJ , KFISEL CHECKROW , KABDESC LIBELLE 
FROM KPOFRSQ 
INNER JOIN KPRSQ ON KABIPB = KFIIPB AND KABALX = KFIALX AND KABRSQ = KFIRSQ 
WHERE KFIIPB = P_CODEOFFRE AND KFIALX = P_VERSION AND KFITYE = 'R' AND KFIPOG = P_CODECONTRAT AND KFIALG = P_VERSIONCONTRAT 
UNION 
SELECT KFIPOG CODECONTRAT , KFIALG VERSCONTRAT , KFITYE TYPEENREG , KFIRSQ CODERSQ , KFIOBJ CODEOBJ , KFISEL CHECKROW , KACDESC LIBELLE 
FROM KPOFRSQ 
INNER JOIN KPOBJ ON KACIPB = KFIIPB AND KACALX = KFIALX AND KACRSQ = KFIRSQ AND KACOBJ = KFIOBJ 
WHERE KFIIPB = P_CODEOFFRE AND KFIALX = P_VERSION AND KFITYE = 'O' AND KFIPOG = P_CODECONTRAT AND KFIALG = P_VERSIONCONTRAT 
ORDER BY CODERSQ , CODEOBJ ; 
  
IF NOT EXISTS ( SELECT 1 FROM KPOFRSQ WHERE KFIIPB = P_CODEOFFRE AND KFIALX = P_VERSION AND KFIPOG = P_CODECONTRAT AND KFIALG = P_VERSIONCONTRAT ) THEN
	CALL SP_CORISQUE ( P_CODEOFFRE , P_VERSION , P_CODECONTRAT , P_VERSIONCONTRAT ) ; 
END IF ;
  
OPEN CURSOR_LSTRSQOBJ ; 
  
END P1  ; 
  

  

