CREATE OR REPLACE PROCEDURE SP_CKPENT(
	IN P_CODEOFFRE VARCHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE VARCHAR(1) , 
	IN P_CODECONTRAT VARCHAR(9) , 
	IN P_NEWVERSION INTEGER , 
	IN P_TRAITEMENT VARCHAR(1) , 
	IN P_MODECOPY CHAR(7) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
	DECLARE V_COUNTROW INTEGER DEFAULT 0 ; 
	 
	DECLARE V_KPDESI INTEGER DEFAULT 0 ; 
	DECLARE V_NEWKPDESI INTEGER DEFAULT 0 ; 
	DECLARE V_KPOBSV INTEGER DEFAULT 0 ; 
	DECLARE V_KPOBSA INTEGER DEFAULT 0 ; 
	DECLARE V_KPOBSC INTEGER DEFAULT 0 ; 
	DECLARE V_KPOBSF INTEGER DEFAULT 0 ; 
	DECLARE V_NEWKPOBSV INTEGER DEFAULT 0 ; 
	DECLARE V_NEWKPOBSA INTEGER DEFAULT 0 ; 
	DECLARE V_NEWKPOBSC INTEGER DEFAULT 0 ; 
	DECLARE V_NEWKPOBSF INTEGER DEFAULT 0 ; 
	DECLARE V_KPEXPLCI INTEGER DEFAULT 0 ; 
	DECLARE V_NEWKPEXPLCI INTEGER DEFAULT 0 ; 
	DECLARE V_KPEXPFRH INTEGER DEFAULT 0 ; 
	DECLARE V_NEWKPEXPFRH INTEGER DEFAULT 0 ; 
	DECLARE V_KAAAND INTEGER DEFAULT 0 ; 
	DECLARE V_NEWKAAAND INTEGER DEFAULT 0 ; 
	 
	DECLARE V_INSTYPE VARCHAR ( 1 ) DEFAULT '' ; 
	DECLARE V_INSCODE VARCHAR ( 9 ) DEFAULT '' ; 
	 
	SET P_CODEOFFRE = LPAD ( TRIM ( P_CODEOFFRE ) , 9 , ' ') ;
	SET P_CODECONTRAT = LPAD ( TRIM ( P_CODECONTRAT ) , 9 , ' ') ;

	SET V_INSTYPE = P_TYPE ; 
	SET V_INSCODE = P_CODEOFFRE ; 
	 
	SELECT KAADESI , KAAOBSV , KAAOBSA , KAAOBSC , KAAKDIID , KAAKDKID , KAAAND , KAAOBSF INTO V_KPDESI , V_KPOBSV , V_KPOBSA , V_KPOBSC , V_KPEXPLCI , V_KPEXPFRH , V_KAAAND , V_KPOBSF 
	FROM KPENT 
	WHERE KAATYP = P_TYPE AND KAAIPB = P_CODEOFFRE AND KAAALX = P_VERSION ; 
	 
	 
	IF ( V_KPDESI != 0 ) THEN 
		CALL SP_SECOPID ( P_CODEOFFRE , P_VERSION , P_TYPE , 'KADCHR' , V_KPDESI , V_NEWKPDESI ) ; 
		IF ( V_NEWKPDESI = 0 ) THEN 
			/* MODIFICATION DU 22-04-2015 */ 
			/* CALL SP_NCHRONO ( 'KAADESI' , V_NEWKPDESI ) ;  */ 
			CALL SP_NCHRONO ( 'KADCHR' , V_NEWKPDESI ) ; 
			CALL SP_INCOPID ( P_CODEOFFRE , P_VERSION , P_TYPE , 'KADCHR' , V_KPDESI , V_NEWKPDESI ) ; 
		END IF ; 
	END IF ; 
	 
	-- IF ( V_KPOBSV != 0 AND TRIM ( P_MODECOPY ) != 'CNVA' AND TRIM ( P_MODECOPY ) != 'OFFRE' ) THEN 
	IF ( V_KPOBSV != 0 AND TRIM ( P_MODECOPY ) != 'OFFRE' ) THEN 
		CALL SP_SECOPID ( P_CODEOFFRE , P_VERSION , P_TYPE , 'KAJCHR' , V_KPOBSV , V_NEWKPOBSV ) ; 
		IF ( V_NEWKPOBSV = 0 ) THEN 
			CALL SP_NCHRONO ( 'KAJCHR' , V_NEWKPOBSV ) ; 
			CALL SP_INCOPID ( P_CODEOFFRE , P_VERSION , P_TYPE , 'KAJCHR' , V_KPOBSV , V_NEWKPOBSV ) ; 
		END IF ; 
	END IF ; 
	-- IF ( V_KPOBSA != 0 AND TRIM ( P_MODECOPY ) != 'CNVA' AND TRIM ( P_MODECOPY ) != 'OFFRE' ) THEN 
	IF ( V_KPOBSA != 0 AND TRIM ( P_MODECOPY ) != 'OFFRE' ) THEN 
		CALL SP_SECOPID ( P_CODEOFFRE , P_VERSION , P_TYPE , 'KAJCHR' , V_KPOBSA , V_NEWKPOBSA ) ; 
		IF ( V_NEWKPOBSA = 0 ) THEN 
			CALL SP_NCHRONO ( 'KAJCHR' , V_NEWKPOBSA ) ; 
			CALL SP_INCOPID ( P_CODEOFFRE , P_VERSION , P_TYPE , 'KAJCHR' , V_KPOBSA , V_NEWKPOBSA ) ; 
		END IF ; 
	END IF ; 
	-- IF ( V_KPOBSC != 0 AND TRIM ( P_MODECOPY ) != 'CNVA' AND TRIM ( P_MODECOPY ) != 'OFFRE' ) THEN 
	IF ( V_KPOBSC != 0 AND TRIM ( P_MODECOPY ) != 'OFFRE' ) THEN 
		CALL SP_SECOPID ( P_CODEOFFRE , P_VERSION , P_TYPE , 'KAJCHR' , V_KPOBSC , V_NEWKPOBSC ) ; 
		IF ( V_NEWKPOBSC = 0 ) THEN 
			CALL SP_NCHRONO ( 'KAJCHR' , V_NEWKPOBSC ) ; 
			CALL SP_INCOPID ( P_CODEOFFRE , P_VERSION , P_TYPE , 'KAJCHR' , V_KPOBSC , V_NEWKPOBSC ) ; 
		END IF ; 
	END IF ; 
	IF ( TRIM ( P_MODECOPY ) = 'OFFRE' ) THEN 
		SELECT KAAOBSV INTO V_NEWKPOBSV 
		FROM KPENT 
		WHERE KAATYP = P_TYPE AND KAAIPB = P_CODECONTRAT AND KAAALX = P_NEWVERSION ; 
	END IF ; 
	 
	IF ( V_KPEXPLCI != 0 ) THEN 
		CALL SP_SECOPID ( P_CODEOFFRE , P_VERSION , P_TYPE , 'KDIID' , V_KPEXPLCI , V_NEWKPEXPLCI ) ; 
		IF ( V_NEWKPEXPLCI = 0 ) THEN 
			CALL SP_NCHRONO ( 'KDIID' , V_NEWKPEXPLCI ) ; 
			CALL SP_INCOPID ( P_CODEOFFRE , P_VERSION , P_TYPE , 'KDIID' , V_KPEXPLCI , V_NEWKPEXPLCI ) ; 
		END IF ; 
	END IF ; 
	 
	IF ( V_KPEXPFRH != 0 ) THEN 
		CALL SP_SECOPID ( P_CODEOFFRE , P_VERSION , P_TYPE , 'KDKID' , V_KPEXPFRH , V_NEWKPEXPFRH ) ; 
		IF ( V_NEWKPEXPFRH = 0 ) THEN 
			CALL SP_NCHRONO ( 'KDKID' , V_NEWKPEXPFRH ) ; 
			CALL SP_INCOPID ( P_CODEOFFRE , P_VERSION , P_TYPE , 'KDKID' , V_KPEXPFRH , V_NEWKPEXPFRH ) ; 
		END IF ; 
	END IF ; 
	 
	IF ( P_TRAITEMENT = 'P' ) THEN 
		IF ( V_KAAAND != 0 ) THEN 
			CALL SP_SECOPID ( P_CODEOFFRE , P_VERSION , P_TYPE , 'KADCHR' , V_KAAAND , V_NEWKAAAND ) ; 
			IF ( V_NEWKAAAND = 0 ) THEN 
				/* MODIFICATION DU 22-04-2015 */ 
				/* CALL SP_NCHRONO ( 'KAAAND' , V_NEWKAAAND ) ;  */ 
				CALL SP_NCHRONO ( 'KADCHR' , V_NEWKAAAND ) ; 
				CALL SP_INCOPID ( P_CODEOFFRE , P_VERSION , P_TYPE , 'KADCHR' , V_KAAAND , V_NEWKAAAND ) ; 
			END IF ; 
		END IF ; 
		SET V_INSTYPE = 'P' ; 
		SET V_INSCODE = P_CODECONTRAT ; 
	END IF ; 
	 
	IF ( P_MODECOPY != 'OFFRE' OR ( P_TRAITEMENT != 'C' AND P_TRAITEMENT != 'N' ) ) THEN 
		IF ( V_KPOBSF != 0 ) THEN 
			CALL SP_SECOPID ( P_CODEOFFRE , P_VERSION , P_TYPE , 'KAJCHR' , V_KPOBSF , V_NEWKPOBSF ) ; 
			IF ( V_NEWKPOBSF = 0 ) THEN 
				CALL SP_NCHRONO ( 'KAJCHR' , V_NEWKPOBSF ) ; 
				CALL SP_INCOPID ( P_CODEOFFRE , P_VERSION , P_TYPE , 'KAJCHR' , V_KPOBSF , V_NEWKPOBSF ) ; 
			END IF ; 
		END IF ; 
	END IF ; 
	 
	IF ( P_TRAITEMENT = 'N' ) THEN 
		SET V_INSCODE = P_CODECONTRAT ; 
	END IF ; 
	 
	IF ( TRIM ( P_MODECOPY ) = 'VERSION' ) THEN 
		INSERT INTO KPENT 
		( KAATYP , KAAIPB , KAAALX , KAABONI , KAABONT , KAAANTI , KAADESI , KAAOBSV , KAALCIVALO , KAALCIVALA , 
		KAALCIVALW , KAALCIUNIT , KAALCIBASE , KAAKDIID , KAAFRHVALO , KAAFRHVALA , KAAFRHVALW , KAAFRHUNIT , 
		KAAFRHBASE , KAAKDKID , KAAATGLCI , KAAATGKLC , KAAATGCAP , KAAATGKCA , KAAATGSUR , KAAATGBCN , KAAATGKBC , 
		KAAATGCRI , KAAATGAPT , KAAATGF , KAAATGAPR , KAAATGTRT , KAAATGTRR , KAAATGTCT , KAAATGTCR , KAAATGTFT , 
		KAAATGTCM , KAAATGTFA , KAAATGCTX , KAAATGLCF , KAAATGCAF , KAAATGSUF , KAAATGBCF , KAALCIINA , KAAATGFRR , 
		KAAATGCMT , KAAATGFAT , KAAATGBAS , KAAATGKBA , KAAFRHINA , KAAAND , KAADPRJ , KAADSTA , KAAOBSF , KAAOBSA , KAAOBSC , KAAASS , KAAAFS , 
		KAAXCMS , KAACNCS , KAACIBLE , KAAMAXA , KAAMAXE , KAAIDE , KAAIMED , KAAIMDA , KAAISIN , KAARCP, KAAPAQ ) 
		( SELECT V_INSTYPE , V_INSCODE , P_NEWVERSION , KAABONI , KAABONT , KAAANTI , V_NEWKPDESI , V_NEWKPOBSV , KAALCIVALO , KAALCIVALA , 
		KAALCIVALW , KAALCIUNIT , KAALCIBASE , V_NEWKPEXPLCI , KAAFRHVALO , KAAFRHVALA , KAAFRHVALW , KAAFRHUNIT , 
		KAAFRHBASE , V_NEWKPEXPFRH , KAAATGLCI , KAAATGKLC , KAAATGCAP , KAAATGKCA , KAAATGSUR , KAAATGBCN , KAAATGKBC , 
		KAAATGCRI , KAAATGAPT , KAAATGF , KAAATGAPR , KAAATGTRT , KAAATGTRR , KAAATGTCT , KAAATGTCR , KAAATGTFT , 
		KAAATGTCM , KAAATGTFA , KAAATGCTX , KAAATGLCF , KAAATGCAF , KAAATGSUF , KAAATGBCF , KAALCIINA , KAAATGFRR , 
		KAAATGCMT , KAAATGFAT , KAAATGBAS , KAAATGKBA , KAAFRHINA , KAAAND , 0 , KAADSTA , V_NEWKPOBSF , V_NEWKPOBSA , V_NEWKPOBSC , KAAASS , KAAAFS , 
		KAAXCMS , KAACNCS , KAACIBLE , KAAMAXA , KAAMAXE , KAAIDE , KAAIMED , KAAIMDA , KAAISIN , KAARCP, KAAPAQ
		FROM KPENT 
		WHERE KAATYP = P_TYPE AND KAAIPB = P_CODEOFFRE AND KAAALX = P_VERSION ) ; 
	ELSE 
		IF ( TRIM ( P_MODECOPY ) = 'AFFNOUV' ) THEN 
			INSERT INTO KPENT 
			( KAATYP , KAAIPB , KAAALX , KAABONI , KAABONT , KAAANTI , KAADESI , KAAOBSV , KAALCIVALO , KAALCIVALA , 
			KAALCIVALW , KAALCIUNIT , KAALCIBASE , KAAKDIID , KAAFRHVALO , KAAFRHVALA , KAAFRHVALW , KAAFRHUNIT , 
			KAAFRHBASE , KAAKDKID , KAAATGLCI , KAAATGKLC , KAAATGCAP , KAAATGKCA , KAAATGSUR , KAAATGBCN , KAAATGKBC , 
			KAAATGCRI , KAAATGAPT , KAAATGF , KAAATGAPR , KAAATGTRT , KAAATGTRR , KAAATGTCT , KAAATGTCR , KAAATGTFT , 
			KAAATGTCM , KAAATGTFA , KAAATGCTX , KAAATGLCF , KAAATGCAF , KAAATGSUF , KAAATGBCF , KAALCIINA , KAAATGFRR , 
			KAAATGCMT , KAAATGFAT , KAAATGBAS , KAAATGKBA , KAAFRHINA , KAAAND , KAADPRJ , KAADSTA , KAAOBSF , KAAOBSA , KAAOBSC , KAAASS , KAAAFS , 
			KAAXCMS , KAACNCS , KAACIBLE , KAAMAXA , KAAMAXE , KAAIDE , KAAIMED , KAAIMDA , KAAISIN , KAARCP, KAAPAQ ) 
			( SELECT V_INSTYPE , V_INSCODE , P_NEWVERSION , KAABONI , KAABONT , KAAANTI , V_NEWKPDESI , V_NEWKPOBSV , KAALCIVALO , KAALCIVALA , 
			KAALCIVALW , KAALCIUNIT , KAALCIBASE , V_NEWKPEXPLCI , KAAFRHVALO , KAAFRHVALA , KAAFRHVALW , KAAFRHUNIT , 
			KAAFRHBASE , V_NEWKPEXPFRH , KAAATGLCI , KAAATGKLC , KAAATGCAP , KAAATGKCA , KAAATGSUR , KAAATGBCN , KAAATGKBC , 
			KAAATGCRI , KAAATGAPT , KAAATGF , KAAATGAPR , KAAATGTRT , KAAATGTRR , KAAATGTCT , KAAATGTCR , KAAATGTFT , 
			KAAATGTCM , KAAATGTFA , KAAATGCTX , KAAATGLCF , 0 , KAAATGSUF , KAAATGBCF , KAALCIINA , KAAATGFRR , 
			KAAATGCMT , KAAATGFAT , KAAATGBAS , KAAATGKBA , KAAFRHINA , 0 , 0 , 0 , V_NEWKPOBSF , V_NEWKPOBSA , V_NEWKPOBSC , KAAASS , KAAAFS , 
			KAAXCMS , KAACNCS , KAACIBLE , KAAMAXA , KAAMAXE , KAAIDE , KAAIMED , KAAIMDA , KAAISIN , KAARCP, KAAPAQ 
			FROM KPENT 
			WHERE KAATYP = P_TYPE AND KAAIPB = P_CODEOFFRE AND KAAALX = P_VERSION ) ;	 
		 
		ELSE 
			 
			INSERT INTO KPENT 
			( KAATYP , KAAIPB , KAAALX , KAABONI , KAABONT , KAAANTI , KAADESI , KAAOBSV , KAALCIVALO , KAALCIVALA , 
			KAALCIVALW , KAALCIUNIT , KAALCIBASE , KAAKDIID , KAAFRHVALO , KAAFRHVALA , KAAFRHVALW , KAAFRHUNIT , 
			KAAFRHBASE , KAAKDKID , KAAATGLCI , KAAATGKLC , KAAATGCAP , KAAATGKCA , KAAATGSUR , KAAATGBCN , KAAATGKBC , 
			KAAATGCRI , KAAATGAPT , KAAATGF , KAAATGAPR , KAAATGTRT , KAAATGTRR , KAAATGTCT , KAAATGTCR , KAAATGTFT , 
			KAAATGTCM , KAAATGTFA , KAAATGCTX , KAAATGLCF , KAAATGCAF , KAAATGSUF , KAAATGBCF , KAALCIINA , KAAATGFRR , 
			KAAATGCMT , KAAATGFAT , KAAATGBAS , KAAATGKBA , KAAFRHINA , KAAAND , KAADPRJ , KAADSTA , KAAOBSF , KAAOBSA , KAAOBSC , KAAASS , KAAAFS , 
			KAAXCMS , KAACNCS , KAACIBLE , KAAMAXA , KAAMAXE , KAAIDE , KAAIMED , KAAIMDA , KAAISIN , KAARCP, KAAPAQ ) 
			( SELECT V_INSTYPE , V_INSCODE , P_NEWVERSION , '' , 0 , '' , V_NEWKPDESI , V_NEWKPOBSV , KAALCIVALO , KAALCIVALA , 
			KAALCIVALW , KAALCIUNIT , KAALCIBASE , V_NEWKPEXPLCI , KAAFRHVALO , KAAFRHVALA , KAAFRHVALW , KAAFRHUNIT , 
			KAAFRHBASE , V_NEWKPEXPFRH , KAAATGLCI , KAAATGKLC , KAAATGCAP , KAAATGKCA , KAAATGSUR , KAAATGBCN , KAAATGKBC , 
			KAAATGCRI , KAAATGAPT , KAAATGF , KAAATGAPR , KAAATGTRT , KAAATGTRR , KAAATGTCT , KAAATGTCR , KAAATGTFT , 
			KAAATGTCM , KAAATGTFA , KAAATGCTX , KAAATGLCF , 0 , KAAATGSUF , KAAATGBCF , KAALCIINA , KAAATGFRR , 
			KAAATGCMT , KAAATGFAT , KAAATGBAS , KAAATGKBA , KAAFRHINA , 0 , 0 , 0 , V_NEWKPOBSF , V_NEWKPOBSA , V_NEWKPOBSC , 'O' , KAAAFS , 
			KAAXCMS , KAACNCS , KAACIBLE , KAAMAXA , KAAMAXE , KAAIDE , KAAIMED , KAAIMDA , '' , KAARCP , KAAPAQ
			FROM KPENT 
			WHERE KAATYP = P_TYPE AND KAAIPB = P_CODEOFFRE AND KAAALX = P_VERSION ) ;	 
		 
		END IF ; 
	END IF ; 
  
END P1  ; 
  

  

