CREATE PROCEDURE SP_COUNT_PRENEURS_ASSURANCES ( 
	IN P_CODE INTEGER , 
	IN P_NOM CHAR(40) , 
	IN P_CP CHAR(5) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_COUNT_PRENEURS_ASSURANCES 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX 
	P1 : BEGIN ATOMIC 

DECLARE V_QUERY VARCHAR ( 8000 ) DEFAULT '' ; 
DECLARE V_SELECT_YASSNOM VARCHAR ( 500 ) DEFAULT '' ; 
DECLARE V_SELECT_YASSNOM1 VARCHAR ( 500 ) DEFAULT '' ; 
DECLARE V_SELECT_YASSURE VARCHAR ( 500 ) DEFAULT '' ; 
DECLARE V_SELECT_YADRESS VARCHAR ( 500 ) DEFAULT '' ; 
DECLARE V_SORT_COLUMN VARCHAR ( 128 ) DEFAULT '' ; 
DECLARE CURSOR1 CURSOR WITH RETURN FOR SQL_STATEMENT ; 

SET V_SELECT_YASSNOM = '( SELECT ANNOM, ANIAS, ANORD FROM YASSNOM WHERE ANINL = 0 AND ANTNM = ''A'' ) NOMS' ; 
SET V_SELECT_YASSNOM1 = '( SELECT ANIAS ANIAS1, ANNOM ANNOM1 FROM YASSNOM WHERE ANINL = 0 AND ANTNM = ''S'' ) NOMS1' ; 
SET V_SELECT_YASSURE = '( SELECT ASIAS, ASADH, ASAD1, ASAD2, ASSIR FROM YASSURE ) ASR' ; 
SET V_SELECT_YADRESS = 'SELECT ABPDP6, ABPCP6, ABPCHR, ABPVI6 FROM YADRESS' ; 
IF P_CP = '' THEN
    SET V_SELECT_YADRESS = ' LEFT JOIN ( ' || V_SELECT_YADRESS || ' ) ADR' ;
ELSE 
    SET V_SELECT_YADRESS = ' INNER JOIN ( ' || V_SELECT_YADRESS || ' WHERE ( LPAD( ABPDP6 , 2 , ''0'') || LPAD( CAST ( ABS ( ABPCP6 ) AS VARCHAR ( 3 ) ) , 3 , ''0'') ) LIKE ''' || TRIM ( P_CP ) || '%'' ) ADR';
END IF ;

SET V_QUERY = 'SELECT COUNT( DISTINCT ASIAS ) 
FROM ' || V_SELECT_YASSNOM || ' 
LEFT JOIN ' || V_SELECT_YASSNOM1 || ' ON ANIAS1 = ANIAS AND ANNOM1 <> ANNOM 
INNER JOIN ' || V_SELECT_YASSURE || ' ON ASIAS = ANIAS ' 
|| V_SELECT_YADRESS || ' ON ASADH = ABPCHR ' ; 

IF P_CODE > 0 THEN 
    SET V_QUERY = V_QUERY || ' WHERE ANIAS = ' || P_CODE ; 
ELSEIF P_NOM <> '' THEN 
        SET V_QUERY = V_QUERY || ' WHERE ( ANNOM LIKE ''' || TRIM ( P_NOM ) || '%''' || ' OR ANNOM1 LIKE ''' || TRIM ( P_NOM ) || '%'' )' ;
END IF ;

PREPARE SQL_STATEMENT FROM V_QUERY ; 
OPEN CURSOR1 ; 

END P1 ; 
