CREATE OR REPLACE PROCEDURE SP_CLASSCONTSANSSUITE ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) ,
	IN P_USER CHAR(10) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_CLASSCONTSANSSUITE
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
  DECLARE V_SSOUS CHAR(10) DEFAULT '';
DECLARE V_SSAFF INTEGER DEFAULT 0;
DECLARE V_LIBELLE CHAR(10) DEFAULT '';

-- UPDATE Information du contrat (situation, date fin effet ...)
UPDATE YPOBASE SET PBSIT = 'W', PBFEA = PBEFA, PBFEM = PBEFM, PBFEJ = PBEFJ, PBRSA = 0, PBRSM = 0, PBRSJ = 0, PBRSC = ''
WHERE PBIPB = P_CODEOFFRE AND PBALX = P_VERSION;

-- Suppression des lignes dans YPOSTAT et YLGNSTP
SELECT SSOUS, SSAFF INTO V_SSOUS, V_SSAFF FROM YSTAPRO WHERE SSIPW = P_CODEOFFRE AND SSALW = P_VERSION;
DELETE FROM YSTAPRO WHERE SSIPW = P_CODEOFFRE AND SSALW = P_VERSION;
DELETE FROM YLGNSTP WHERE SLSOU = V_SSOUS AND SLAFF = V_SSAFF;

-- UPDATE Information de YAPRMAN
UPDATE YAPRMAN SET ABRATT = 0, ABRMNT = 0, ABRPHH = 0 WHERE ABRIPB = P_CODEOFFRE AND ABRALX = P_VERSION;

-- Récupération du libellé dans YYYYPAR
SELECT TPLIB INTO V_LIBELLE FROM YYYYPAR WHERE TCON = 'PRODU' AND TFAM = 'PYTTR' AND TCOD = 'HASSU';

-- Insertion dans YPOTRAC
INSERT INTO YPOTRAC (PYTYP, PYALX, PYIPB, PYTTR, PYVAG, PYORD, PYINF, PYLIB, PYMJU, PYMJA, PYMJM, PYMJJ, PYMJH)
VALUES (P_TYPE, P_VERSION, P_CODEOFFRE, 'HASSU', 'I', 1, 'I', V_LIBELLE, P_USER, YEAR(CURRENT_DATE), MONTH(CURRENT_DATE), DAY(CURRENT_DATE), HOUR(CURRENT_TIME) CONCAT MINUTE(CURRENT_TIME));

  
END P1  ;

