CREATE PROCEDURE SP_COMAJ ( 
	IN P_CODECONTRAT CHAR(9) , 
	IN P_VERSIONCONTRAT INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_CODERSQ INTEGER , 
	IN P_CODEOBJ INTEGER , 
	IN P_CHECK CHAR(1) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_COMAJ 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
DECLARE V_NBOBJCHECKED INTEGER DEFAULT 0 ; 
DECLARE V_CHECKRSQ CHAR ( 1 ) DEFAULT '' ; 
  
IF ( P_TYPE = 'R' ) THEN 
UPDATE KPOFRSQ 
SET KFISEL = P_CHECK 
WHERE KFIPOG = P_CODECONTRAT AND KFIALG = P_VERSIONCONTRAT AND KFIRSQ = P_CODERSQ ; 
ELSE 
IF ( P_TYPE = 'O' ) THEN 
UPDATE KPOFRSQ 
SET KFISEL = P_CHECK 
WHERE KFIPOG = P_CODECONTRAT AND KFIALG = P_VERSIONCONTRAT AND KFITYE = P_TYPE AND KFIRSQ = P_CODERSQ AND KFIOBJ = P_CODEOBJ ; 
  
SELECT COUNT ( * ) INTO V_NBOBJCHECKED FROM KPOFRSQ 
WHERE KFIPOG = P_CODECONTRAT AND KFIALG = P_VERSIONCONTRAT 
AND KFIRSQ = P_CODERSQ AND KFITYE = 'O' AND KFISEL = 'O' ; 
  
IF ( V_NBOBJCHECKED = 0 ) THEN 
SET V_CHECKRSQ = 'N' ; 
ELSE 
SET V_CHECKRSQ = 'O' ; 
END IF ; 
  
UPDATE KPOFRSQ 
SET KFISEL = V_CHECKRSQ 
WHERE KFIPOG = P_CODECONTRAT AND KFIALG = P_VERSIONCONTRAT 
AND KFIRSQ = P_CODERSQ AND KFITYE = 'R' ; 
END IF ; 
END IF ; 
  
END P1  ; 
  

  

