CREATE PROCEDURE SP_COTARIF ( 
	IN P_CODECONTRAT CHAR(9) , 
	IN P_VERSIONCONTRAT INTEGER ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_COTARIF 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
DECLARE V_SELTAR INTEGER DEFAULT 0 ; 
DECLARE V_CHECKTAR VARCHAR ( 1 ) DEFAULT 'N' ; 
  
DECLARE CURSTARIF CURSOR FOR 
SELECT KFKFOR CODEFORM , C2GAR CODEGARAN , GADES DESCGARAN , KDAALPHA LETTREFORM , 
KFKNUMTAR CODETARIF , KFKKDGID GUIDTARIF , 
KDGLCIVALO LCIVAL , KDGLCIUNIT LCIUNIT , KDGLCIBASE LCITYPE , KDGKDIID IDLCICPX , 
KDGFRHVALO FRHVAL , KDGFRHUNIT FRHUNIT , KDGFRHBASE FRHTYPE , KDGKDKID IDFRHCPX , 
KDEASVALO ASSVAL , KDEASUNIT ASSUNIT , KDEASBASE ASSTYPE , 
KDGPRIVALO PRIVAL , KDGPRIUNIT PRIUNIT , KDGPRIBASE PRITYPE , KDGPRIMPRO PRIMPRO , KFKSEL CHECKROWDB 
FROM KPOFTAR 
INNER JOIN KPFOR ON KFKIPB = KDAIPB AND KFKALX = KDAALX AND KFKFOR = KDAFOR 
INNER JOIN KPGARTAR ON KFKIPB = KDGIPB AND KFKALX = KDGALX AND KFKFOR = KDGFOR AND KFKKDGID = KDGID 
INNER JOIN KPGARAN ON KDGKDEID = KDEID 
INNER JOIN ZALBINKMOD . YPLTGAR ON KDESEQ = C2SEQ AND KDENIVEAU = C2NIV 
INNER JOIN KGARAN ON C2GAR = GAGAR 
WHERE KFKPOG = P_CODECONTRAT AND KFKALG = P_VERSIONCONTRAT ; 
  
FOR LOOP_TAR AS FREE_LIST CURSOR FOR 
SELECT DISTINCT KFJPOG CODECONTRAT , KFJALG VERSCONTRAT , KFJIPB CODEOFFRE , KFJALX VERS , KDGFOR CODEFORM , KDGOPT CODEOPT , 
KDGGARAN CODEGARAN , KDGNUMTAR NUMTARIF , KDGID GUIDTARIF , KDETRI 
FROM KPOFOPT 
INNER JOIN ( SELECT KDEIPB , KDEALX , KDETYP , KDEFOR , KDEOPT , KDEID , KDETRI 
FROM KPGARAN J 
INNER JOIN KPGARTAR T ON J . KDEID = T . KDGKDEID 
GROUP BY J . KDEIPB , J . KDEALX , J . KDETYP , J . KDEFOR , J . KDEOPT , J . KDEID , J . KDETRI 
HAVING COUNT ( * ) > 1 ) GARAN ON KFJIPB = GARAN . KDEIPB AND KFJALX = GARAN . KDEALX AND GARAN . KDETYP = 'O' AND KFJFOR = GARAN . KDEFOR AND KFJOPT = GARAN . KDEOPT 
INNER JOIN KPGARTAR ON GARAN . KDEID = KDGKDEID 
WHERE KFJPOG = P_CODECONTRAT AND KFJALG = P_VERSIONCONTRAT AND KFJTENG = 'V' AND KFJSEL = 'O' 
ORDER BY KDETRI 
DO 
SELECT IFNULL ( KFKKDGID , 0 ) INTO V_SELTAR FROM KPOFTAR WHERE KFKGARAN = CODEGARAN AND KFKNUMTAR = NUMTARIF AND KFKPOG = P_CODECONTRAT AND KFKALG = P_VERSIONCONTRAT ; 
IF ( V_SELTAR = 0 ) THEN 
IF ( NUMTARIF = 1 ) THEN 
SET V_CHECKTAR = 'O' ; 
END IF ; 
  
INSERT INTO KPOFTAR 
( KFKPOG , KFKALG , KFKIPB , KFKALX , KFKFOR , KFKOPT , KFKGARAN , KFKNUMTAR , KFKKDGID , KFKSEL ) 
VALUES 
( CODECONTRAT , VERSCONTRAT , CODEOFFRE , VERS , CODEFORM , CODEOPT , CODEGARAN , NUMTARIF , GUIDTARIF , V_CHECKTAR ) ; 
END IF ; 
  
SET V_SELTAR = 0 ; 
SET V_CHECKTAR = 'N' ; 
END FOR ; 
  
OPEN CURSTARIF ; 
  
END P1  ; 
  

  

