CREATE PROCEDURE SP_DELROWDETAILEXPRCOMPLEXE ( 
	IN P_IDEXPR INTEGER , 
	IN P_TYPEEXPCOMPLEXE CHAR(9) , 
	IN P_IDROWEXPR INTEGER ) 
	LANGUAGE SQL 
	SPECIFIC SP_DELROWDETAILEXPRCOMPLEXE 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
IF ( P_TYPEEXPCOMPLEXE = 'LCI' ) THEN 
DELETE FROM KEXPLCID WHERE KHHID = P_IDROWEXPR AND KHHKHGID = P_IDEXPR ; 
END IF ; 
  
IF ( P_TYPEEXPCOMPLEXE = 'FRANCHISE' ) THEN 
DELETE FROM KEXPFRHD WHERE KHFID = P_IDROWEXPR AND KHFKHEID = P_IDEXPR ; 
END IF ; 
  
END P1  ; 
  

  

