CREATE PROCEDURE SP_DELFORM ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_CODEFORMULE INTEGER , 
	IN P_TYPEDEL CHAR(1) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_DELFORM 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
	 
	SET P_CODEOFFRE = LPAD ( RTRIM ( P_CODEOFFRE ) , 9 , ' ' ) ; 
	 
	DELETE FROM KPOPTAP WHERE KDDIPB = P_CODEOFFRE AND KDDALX = P_VERSION AND KDDTYP = P_TYPE AND KDDFOR = P_CODEFORMULE ; 
	DELETE FROM KPOPTAPW WHERE KDDIPB = P_CODEOFFRE AND KDDALX = P_VERSION AND KDDTYP = P_TYPE AND KDDFOR = P_CODEFORMULE ; 
	 
	DELETE FROM KPCOTGA WHERE KDNIPB = P_CODEOFFRE AND KDNALX = P_VERSION AND KDNTYP = P_TYPE AND KDNFOR = P_CODEFORMULE ; 
	DELETE FROM KPCTRL WHERE KEUIPB = P_CODEOFFRE AND KEUALX = P_VERSION AND KEUTYP = P_TYPE AND KEUFOR = P_CODEFORMULE AND KEUETAPE = 'FOR' ; 
	DELETE FROM KPCTRLE WHERE KEVIPB = P_CODEOFFRE AND KEVALX = P_VERSION AND KEVTYP = P_TYPE AND KEVFOR = P_CODEFORMULE AND KEVETAPE = 'OPT' ; 
	DELETE FROM KPGARAN WHERE KDEIPB = P_CODEOFFRE AND KDEALX = P_VERSION AND KDETYP = P_TYPE AND KDEFOR = P_CODEFORMULE ; 
	DELETE FROM KPGARAH WHERE KDEIPB = P_CODEOFFRE AND KDEALX = P_VERSION AND KDETYP = P_TYPE AND KDEFOR = P_CODEFORMULE ; 
	DELETE FROM KPGARAW WHERE KDEIPB = P_CODEOFFRE AND KDEALX = P_VERSION AND KDETYP = P_TYPE AND KDEFOR = P_CODEFORMULE ; 
	DELETE FROM KPGARAP WHERE KDFIPB = P_CODEOFFRE AND KDFALX = P_VERSION AND KDFTYP = P_TYPE AND KDFFOR = P_CODEFORMULE ; 
	DELETE FROM KPGARTAR WHERE KDGIPB = P_CODEOFFRE AND KDGALX = P_VERSION AND KDGTYP = P_TYPE AND KDGFOR = P_CODEFORMULE ; 
	DELETE FROM KPGARTAW WHERE KDGIPB = P_CODEOFFRE AND KDGALX = P_VERSION AND KDGTYP = P_TYPE AND KDGFOR = P_CODEFORMULE ; 
	 
	FOR LOOP_INVEN AS FREE_LIST CURSOR FOR 
		SELECT KBGKBEID INVENID FROM KPINVAPP WHERE KBGIPB = P_CODEOFFRE AND KBGALX = P_VERSION AND KBGTYP = P_TYPE AND KBGFOR = P_CODEFORMULE 
	DO 
		DELETE FROM KPINVEN WHERE KBEID = INVENID ; 
		DELETE FROM KPINVED WHERE KBFKBEID = INVENID ; 
	END FOR ; 
	 
	DELETE FROM KPINVAPP WHERE KBGIPB = P_CODEOFFRE AND KBGALX = P_VERSION AND KBGTYP = P_TYPE AND KBGFOR = P_CODEFORMULE ; 
	DELETE FROM KPIRSGA WHERE KFDIPB = P_CODEOFFRE AND KFDALX = P_VERSION AND KFDTYP = P_TYPE AND KFDFOR = P_CODEFORMULE ; 
	DELETE FROM KPISVAL WHERE KKCIPB = P_CODEOFFRE AND KKCALX = P_VERSION AND KKCTYP = P_TYPE AND KKCFOR = P_CODEFORMULE ; 
	 
	IF ( P_TYPEDEL = 'C' ) THEN 
	 
		DELETE FROM KPCLAUSE WHERE KCAIPB = P_CODEOFFRE AND KCAALX = P_VERSION AND KCATYP = P_TYPE AND KCAFOR = P_CODEFORMULE ; 
		DELETE FROM KPCLAUSW WHERE KCBIPB = P_CODEOFFRE AND KCBALX = P_VERSION AND KCBTYP = P_TYPE AND KCBFOR = P_CODEFORMULE ; 
		DELETE FROM KPIOPT WHERE KFCIPB = P_CODEOFFRE AND KFCALX = P_VERSION AND KFCTYP = P_TYPE AND KFCFOR = P_CODEFORMULE ; 
		DELETE FROM KPOPTD WHERE KDCIPB = P_CODEOFFRE AND KDCALX = P_VERSION AND KDCTYP = P_TYPE AND KDCFOR = P_CODEFORMULE ; 
		DELETE FROM KPOPTDW WHERE KDCIPB = P_CODEOFFRE AND KDCALX = P_VERSION AND KDCTYP = P_TYPE AND KDCFOR = P_CODEFORMULE ; 
		DELETE FROM KPTRACE WHERE KCCIPB = P_CODEOFFRE AND KCCALX = P_VERSION AND KCCTYP = P_TYPE AND KCCFOR = P_CODEFORMULE ; 
		DELETE FROM KPFOR WHERE KDAIPB = P_CODEOFFRE AND KDAALX = P_VERSION AND KDATYP = P_TYPE AND KDAFOR = P_CODEFORMULE ; 
		DELETE FROM KPOPT WHERE KDBIPB = P_CODEOFFRE AND KDBALX = P_VERSION AND KDBTYP = P_TYPE AND KDBFOR = P_CODEFORMULE ; 
	 
	END IF ; 
	 
	IF ( P_TYPEDEL = 'R' ) THEN 
	 
		DELETE FROM KPCLAUSE WHERE KCAIPB = P_CODEOFFRE AND KCAALX = P_VERSION AND KCATYP = P_TYPE AND KCAFOR = P_CODEFORMULE AND KCAGAR <> '' ; 
		DELETE FROM KPCLAUSW WHERE KCBIPB = P_CODEOFFRE AND KCBALX = P_VERSION AND KCBTYP = P_TYPE AND KCBFOR = P_CODEFORMULE AND KCBGAR <> '' ; 
		DELETE FROM KPFOR WHERE KDAIPB = P_CODEOFFRE AND KDAALX = P_VERSION AND KDATYP = P_TYPE AND KDAFOR = P_CODEFORMULE ; 
		DELETE FROM KPOPT WHERE KDBIPB = P_CODEOFFRE AND KDBALX = P_VERSION AND KDBTYP = P_TYPE AND KDBFOR = P_CODEFORMULE ; 
		DELETE FROM KPOPTD WHERE KDCIPB = P_CODEOFFRE AND KDCALX = P_VERSION AND KDCTYP = P_TYPE AND KDCFOR = P_CODEFORMULE ; 
		DELETE FROM KPOPTDW WHERE KDCIPB = P_CODEOFFRE AND KDCALX = P_VERSION AND KDCTYP = P_TYPE AND KDCFOR = P_CODEFORMULE ; 
	 
	END IF ; 
	 
END P1  ; 
  

  

