CREATE PROCEDURE SP_DELCNXENG ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION NUMERIC(5, 0) , 
	IN P_TYPE CHAR(1) ) 
	LANGUAGE SQL 
	SPECIFIC SP_DELCNXENG 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
DECLARE V_PJIDE INTEGER DEFAULT 0 ; 
DECLARE V_PJCNX INTEGER DEFAULT 0 ; 
DECLARE V_COUNTCNX INTEGER DEFAULT 0 ; 
  
  
  
	SELECT PJIDE , PJCNX INTO V_PJIDE , V_PJCNX 
	FROM YPOCONX 
	WHERE TRIM ( PJIPB ) = TRIM ( P_CODEOFFRE ) AND PJALX = P_VERSION AND PJTYP = P_TYPE AND PJCCX = 20 ; 
	 
	DELETE FROM YPOCONX 
	WHERE PJIPB = P_CODEOFFRE AND PJALX = P_VERSION AND PJTYP = P_TYPE ; 
  
	SELECT COUNT ( * ) INTO V_COUNTCNX 
	FROM YPOCONX 
	WHERE PJCNX = V_PJCNX ; 
  
	IF ( V_COUNTCNX = 1 ) THEN 
  
		DELETE FROM YPOCONX 
		WHERE PJCNX = V_PJCNX ; 
  
		DELETE FROM KPENGFAM 
		WHERE KDPKDOID IN ( SELECT KIEKDOID FROM KPENGCNX WHERE KIEPJID = V_PJIDE ) ; 
  
		DELETE FROM KPENG 
		WHERE KDOID IN ( SELECT KIEKDOID FROM KPENGCNX WHERE KIEPJID = V_PJIDE ) ; 
  
		DELETE FROM KPENGCNX 
		WHERE KIEPJID = V_PJIDE ; 
  
	ELSE 
  
		DELETE FROM KPENGFAM	 
		WHERE KDPFAM IN ( SELECT DISTINCT KDPFAM 
						FROM KPENGFAM 
						WHERE KDPIPB = P_CODEOFFRE AND KDPALX = P_VERSION AND KDPTYP = P_TYPE 
							 
						AND KDPFAM NOT IN 
						( SELECT DISTINCT KDPFAM 
							FROM YPOCONX 
								INNER JOIN KPENGFAM ON KDPIPB = PJIPB AND KDPALX = PJALX AND KDPTYP = PJTYP 
							WHERE PJCNX = V_PJCNX AND PJIPB <> P_CODEOFFRE AND PJALX <> P_VERSION AND PJTYP <> P_TYPE )							 
						) 
						 
		AND KDPKDOID IN ( SELECT KIEKDOID FROM KPENGCNX WHERE KIEPJID = V_PJIDE ) ; 
  
  
	END IF ; 
	 
END P1  ; 
  

  

