CREATE PROCEDURE SP_DELETEMOUVTPERIOD ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_CODERSQ INTEGER , 
	IN P_CODEFOR INTEGER , 
	IN P_IDGAR NUMERIC(15, 0) , 
	IN P_CODEREGULE NUMERIC(15, 0) , 
	IN P_CODE NUMERIC(15, 0) , 
	IN P_MULTIRC CHAR(1) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_DELETEMOUVTPERIOD 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
DECLARE CURSOMOUVT CURSOR FOR					 
SELECT KHXID CODE , KHXSIT SITUATION , KHXDEBP DATEDEB , KHXFINP DATEFIN , 
CASE WHEN NULLIF ( KHXCU2 , '' ) IS NULL THEN KHXBAS ELSE KHXCA2 END ASSIETTE , 
CASE WHEN NULLIF ( KHXCU2 , '' ) IS NULL THEN CASE WHEN KHXBAU = 'D' THEN KHXBAM ELSE KHXBAT END ELSE CASE WHEN KHXCU2 = 'D' THEN KHXCP2 ELSE KHXCT2 END END TAUXFORFAITHTVALEUR , 
CASE WHEN NULLIF ( KHXCU2 , '' ) IS NULL THEN KHXBAU ELSE KHXCU2 END TAUXFORFAITHTUNITE , KHXMHT MONTANTREGULHF 
FROM KPRGUG 
WHERE KHXIPB = P_CODEOFFRE AND KHXALX = P_VERSION AND KHXTYP = P_TYPE AND KHXRSQ = P_CODERSQ AND KHXFOR = P_CODEFOR AND KHXKHWID = P_CODEREGULE AND KHXKDEID = P_IDGAR ; 
  
IF ( P_MULTIRC = 'O' ) THEN 
	DELETE FROM KPRGUG WHERE KHXID IN ( 
		SELECT G . KHXID 
		FROM KPRGUG G 
		INNER JOIN ( 
			SELECT KHXDEBP DB , KHXFINP FN FROM KPRGUG WHERE KHXID = P_CODE 
		) P 
		ON G . KHXKHWID = P_CODEREGULE 
		AND G . KHXRSQ = P_CODERSQ 
		AND G . KHXGARAN IN ( 'RCFR' , 'RCUS' , 'RCEX' ) 
		AND G . KHXDEBP = P . DB 
		AND G . KHXFINP = P . FN 
	) ; 
ELSE 
	DELETE FROM KPRGUG WHERE KHXID = P_CODE ; 
END IF ; 
  
IF ( NOT EXISTS ( SELECT 1 FROM KPRGUG WHERE KHXIPB = P_CODEOFFRE AND KHXALX = P_VERSION AND KHXTYP = P_TYPE AND KHXRSQ = P_CODERSQ AND KHXKHWID = P_CODEREGULE AND KHXSIT = 'V' ) ) THEN 
	UPDATE KPRGUR 
	SET KILSIT = 'N' 
	WHERE KILRSQ = P_CODERSQ AND KILKHWID = P_CODEREGULE ; 
END IF ; 
  
OPEN CURSOMOUVT ; 
	 
  
END P1  ;

