CREATE PROCEDURE SP_DELETEPERIOD ( 
	IN P_REGULEID INTEGER ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_DELETEPERIOD 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
		
		
		DELETE FROM KPRGUG WHERE KHXKHWID = P_REGULEID ;	 
		DELETE FROM KPRGUR WHERE KILKHWID = P_REGULEID ;	 
		UPDATE KPRGU 
				SET KHWAVND = 0 , KHWEXE = 0 , KHWDEBP = 0 , KHWFINP = 0 , KHWIPK = 0 , KHWICT = 0 , KHWICC = 0 , 
					KHWXCM = 0 , KHWCNC = 0 , KHWENC = '' , KHWAFC = '' , KHWAFR = 0 , KHWATT = '' , KHWMHT = 0 , KHWCNH = 0 , KHWGRG = 0 , KHWTTT = 0 , KHWMTT = 0 , KHWSTU = '' , 
					KHWSTD = 0 , KHWSTH = 0 , KHWCRU = '' , KHWCRD = 0 , KHWMAJU = '' , KHWMAJD = 0 , KHWAVP = 0 , KHWDESI = 0 , KHWOBSV = 0 , KHWOBSC = 0 , KHWMTF = '' ,
					KHWSRIM = 0 , KHWEMD = 0 , KHWCOT = 0 , KHWSCHG = 0 , KHWSIDF = 0 , KHWSREC = 0, KHWSPRO = 0, KHWSPRE = 0 , KHWMHC = 0 ,
					KHWPBT = 0 , KHWPBA = 0 , KHWPBS = 0 , KHWPBR = 0 , KHWPBP = 0 , KHWPBTR = 0
				WHERE KHWID = P_REGULEID ; 
END P1  ; 
  

  
 

