CREATE PROCEDURE SP_DELETEGRILLE ( 
	IN P_CODEGRILLE CHAR(15) ) 
	LANGUAGE SQL 
	SPECIFIC SP_DELETEGRILLE 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
	DELETE FROM KNMVALF WHERE KHKNMG = P_CODEGRILLE ; 
	DELETE FROM KNMGRI WHERE KHJNMG = P_CODEGRILLE ; 
  
END P1  ; 
  

  

