CREATE PROCEDURE SP_DELOFFRE ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_DELOFFRE 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
DECLARE V_CODECIBLE CHAR ( 10 ) DEFAULT '' ; 
DECLARE V_BRANCHE CHAR ( 2 ) DEFAULT '' ; 
FOR CURSOR_RSQ AS FREE_LIST CURSOR FOR 
SELECT KABRSQ P_CODERSQ 
FROM KPRSQ 
WHERE KABTYP = P_TYPE AND KABIPB = P_CODEOFFRE AND KABALX = P_VERSION 
DO 
CALL SP_DELRSQ ( P_CODEOFFRE , P_VERSION , P_TYPE , P_CODERSQ ) ; 
END FOR 
; 
  
FOR CURSOR_RSQ1 AS FREE_LIST CURSOR FOR 
SELECT KDAFOR CODE_FORMULE 
FROM KPFOR 
WHERE KDAIPB = P_CODEOFFRE AND KDAALX = P_VERSION AND KDATYP = P_TYPE 
DO 
CALL SP_DELFORM ( P_CODEOFFRE , P_VERSION , P_TYPE , CODE_FORMULE , 'C' ) ; 
END FOR ; 
SELECT KAACIBLE INTO V_CODECIBLE FROM KPENT WHERE KAAIPB = P_CODEOFFRE AND KAAALX = P_VERSION AND KAATYP = P_TYPE ; 
SELECT PBTBR INTO V_CODECIBLE FROM YPOBASE WHERE PBIPB = P_CODEOFFRE AND PBALX = P_VERSION AND PBTYP = P_TYPE ; 
  
INSERT INTO KPRSQ 
( KABIPB , KABALX , KABTYP , KABRSQ , KABCIBLE , KABDESC ) 
VALUES 
( P_CODEOFFRE , P_VERSION , P_TYPE , 1 , V_CODECIBLE , '' ) ; 
  
INSERT INTO YPRTRSQ 
( JEIPB , JEALX , JERSQ , JECCH , JEBRA ) VALUES 
( P_CODEOFFRE , P_VERSION , 1 , 1 , V_BRANCHE ) ; 
  
INSERT INTO KPOBJ 
( KACIPB , KACALX , KACTYP , KACRSQ , KACOBJ , KACCIBLE , KACDESC ) 
VALUES ( P_CODEOFFRE , P_VERSION , P_TYPE , 1 , 1 , V_CODECIBLE , '' ) ; 
  
INSERT INTO YPRTOBJ ( JGIPB , JGALX , JGRSQ , JGOBJ , JGCCH , JGBRA ) 
VALUES ( P_CODEOFFRE , P_VERSION , 1 , 1 , 1 , V_BRANCHE ) ; 
END P1  ; 
  

  

