CREATE PROCEDURE SP_DELETELINEGRILLE ( 
	IN P_CODEGRILLE CHAR(15) , 
	IN P_LINEID INTEGER ) 
	LANGUAGE SQL 
	SPECIFIC SP_DELETELINEGRILLE 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
	CASE P_LINEID 
		WHEN 1 THEN 
			UPDATE KNMGRI SET KHJTYPO1 = '' , KHJLIB1 = '' , KHJLIEN1 = '' , KHJVALF1 = '' WHERE KHJNMG = TRIM ( P_CODEGRILLE ) ; 
		WHEN 2 THEN 
			UPDATE KNMGRI SET KHJTYPO2 = '' , KHJLIB2 = '' , KHJLIEN2 = '' , KHJVALF2 = '' WHERE KHJNMG = TRIM ( P_CODEGRILLE ) ; 
		WHEN 3 THEN 
			UPDATE KNMGRI SET KHJTYPO3 = '' , KHJLIB3 = '' , KHJLIEN3 = '' , KHJVALF3 = '' WHERE KHJNMG = TRIM ( P_CODEGRILLE ) ; 
		WHEN 4 THEN 
			UPDATE KNMGRI SET KHJTYPO4 = '' , KHJLIB4 = '' , KHJLIEN4 = '' , KHJVALF4 = '' WHERE KHJNMG = TRIM ( P_CODEGRILLE ) ; 
		WHEN 5 THEN 
			UPDATE KNMGRI SET KHJTYPO5 = '' , KHJLIB5 = '' , KHJLIEN5 = '' , KHJVALF5 = '' WHERE KHJNMG = TRIM ( P_CODEGRILLE ) ; 
	END CASE ; 
  
	DELETE FROM KNMVALF WHERE KHKNMG = TRIM ( P_CODEGRILLE ) AND KHKNIV = P_LINEID ; 
  
END P1  ; 
  

  

