CREATE PROCEDURE SP_DPOPTAP ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_NEWIDFORMULE INTEGER , 
	IN P_CODEOPTION INTEGER , 
	IN P_NEWCODEOPTION INTEGER , 
	IN P_DATESYSTEME CHAR(8) , 
	IN P_USER CHAR(15) , 
	IN P_TRAITEMENT CHAR(1) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_DPOPTAP 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
DECLARE V_NEWCODEINVEN INTEGER DEFAULT 0 ; 
DECLARE V_NEWCODEAPP INTEGER DEFAULT 0 ; 
DECLARE V_NEWLIENKPOPT INTEGER DEFAULT 0 ; 
  
FOR LOOP_APP AS FREE_LIST CURSOR FOR 
SELECT KDDID CODEAPP , KDDINVEN CODEINVEN FROM KPOPTAP 
WHERE KDDKDBID = P_CODEOPTION 
DO 
CALL SP_NCHRONO ( 'KDDID' , V_NEWCODEAPP ) ; 
  
IF ( CODEINVEN != 0 ) THEN 
CALL SP_SECOPID ( P_CODEOFFRE , P_VERSION , P_TYPE , 'KBEID' , CODEINVEN , V_NEWCODEINVEN ) ; 
END IF ; 
  
INSERT INTO KPOPTAP 
( SELECT V_NEWCODEAPP , P_TYPE , P_CODEOFFRE , P_VERSION , P_NEWIDFORMULE , KDDOPT , P_NEWCODEOPTION , KDDPERI , KDDRSQ , 
KDDOBJ , V_NEWCODEINVEN , KDDINVEP , P_USER , P_DATESYSTEME , P_USER , P_DATESYSTEME 
FROM KPOPTAP WHERE KDDID = CODEAPP ) ; 
  
UPDATE KPOPTAP SET KDDID = 210781 WHERE KDDID = 14714 ; 
/* DELETE FROM KPOPTAP WHERE KDDID = CODEAPP; */ 
  
END FOR ; 
  
END P1  ; 
  

  

