CREATE PROCEDURE SP_DELETENOMENCLATURE ( 
	IN P_IDNOMENCLATURE INTEGER ) 
	LANGUAGE SQL 
	SPECIFIC SP_DELETENOMENCLATURE 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
	DECLARE V_TYPOLOGIE CHAR ( 15 ) DEFAULT '' ; 
	DECLARE V_COUNT INTEGER DEFAULT 0 ; 
	 
	SELECT KHITYPO INTO V_TYPOLOGIE FROM KNMREF WHERE KHIID = P_IDNOMENCLATURE ; 
	 
	DELETE FROM KNMREF WHERE KHIID = P_IDNOMENCLATURE ; 
	 
	SET V_COUNT = V_COUNT + 1 ; 
	FOR LOOP_DEL AS FREE_LIST CURSOR FOR 
		SELECT KHIID IDREF FROM KNMREF WHERE TRIM ( KHITYPO ) = TRIM ( V_TYPOLOGIE ) ORDER BY KHINORD 
	DO 
		UPDATE KNMREF SET KHINORD = V_COUNT WHERE KHIID = IDREF ; 
		SET V_COUNT = V_COUNT + 1 ; 
	END FOR ; 
  
END P1  ; 
  

  

