CREATE PROCEDURE SP_DELETEREGULE ( 
	IN P_CODECONTRAT CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_REGULEID INTEGER ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_DELETEREGULE 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
	DECLARE V_QUERY VARCHAR ( 15000 ) DEFAULT '' ; 
	DECLARE V_JOINYPAR VARCHAR ( 1000 ) DEFAULT '' ; 
	DECLARE CURSOR_REGULE CURSOR WITH RETURN FOR SQL_STATEMENT ; 
	 
	SET V_QUERY = 'SELECT KHWID NUMREG, KHWAVN CODEAVN, KHWTTR CODETRAITEMENT, TRAITEMENT.TPLIB LIBTRAITEMENT, 
                        KHWDEBP DATEDEB, KHWFINP DATEFIN, KHWETA CODEETAT, KHWSIT CODESITUATION, SITUATION.TPLIB LIBSITUATION, 
                        KHWSTD DATESIT, KHWSTH HEURESIT, KHWSTU USERSIT,
	                    IFNULL(PKIPK, 0) NUMQUITT, IFNULL(PKSIT, '''') CODEETATQUITT, IFNULL(ETATQUITT.TPLIB, '''') LIBETATQUITT
                    FROM KPRGU
	                    LEFT JOIN YPRIMES ON PKIPB = KHWIPB AND PKALX = KHWALX AND PKIPK = KHWIPK ' ; 
  
	CALL SP_BUILDJOINYPAR ( 'LEFT' , 'PRODU' , 'PBTTR' , 'TRAITEMENT' , ' AND TRAITEMENT.TCOD = KHWTTR' , V_JOINYPAR ) ; 
	SET V_QUERY = TRIM ( V_QUERY ) CONCAT ' ' CONCAT TRIM ( V_JOINYPAR ) ; 
	CALL SP_BUILDJOINYPAR ( 'LEFT' , 'KHEOP' , 'RGUST' , 'SITUATION' , ' AND SITUATION.TCOD = KHWSIT' , V_JOINYPAR ) ; 
	SET V_QUERY = TRIM ( V_QUERY ) CONCAT ' ' CONCAT TRIM ( V_JOINYPAR ) ; 
	CALL SP_BUILDJOINYPAR ( 'LEFT' , 'PRODU' , 'PKSIT' , 'ETATQUITT' , ' AND ETATQUITT.TCOD = PKSIT' , V_JOINYPAR ) ; 
	SET V_QUERY = TRIM ( V_QUERY ) CONCAT ' ' CONCAT TRIM ( V_JOINYPAR ) CONCAT ' WHERE KHWTYP = ''' CONCAT P_TYPE CONCAT ''' AND KHWALX = ' CONCAT P_VERSION CONCAT ' AND TRIM(KHWIPB) = TRIM(''' CONCAT P_CODECONTRAT CONCAT ''') ORDER BY KHWDEBP DESC' ; 
  
	DELETE FROM KPRGU WHERE KHWID = P_REGULEID ; 
	DELETE FROM KPRGUG WHERE KHXKHWID = P_REGULEID ; 
	DELETE FROM KPRGUWP WHERE KHYIPB = P_CODECONTRAT AND KHYALX = P_VERSION AND KHYTYP = P_TYPE;
  
	PREPARE SQL_STATEMENT FROM V_QUERY ; 
	OPEN CURSOR_REGULE ; 
	 
END P1  ; 
  

  

