CREATE PROCEDURE SP_DELGARANTIEINVEN ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_PERI CHAR(2) , 
	IN P_CODE_FORMULE INTEGER , 
	IN P_CODE_GARANTIE CHAR(10) , 
	IN P_CODE_INVEN NUMERIC(15, 0) , 
	OUT P_ERREUR CHAR(128) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_DELGARANTIEINVEN 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
DECLARE V_COUNT INTEGER DEFAULT 0 ; 
--Suppression du lien 
DELETE FROM KPINVAPP WHERE 
KBGTYP = P_TYPE AND KBGIPB = P_CODEOFFRE AND KBGALX = P_VERSION AND KBGPERI = P_PERI AND KBGFOR = P_CODE_FORMULE AND KBGGAR = P_CODE_GARANTIE ; 
--Recherche si inventaire encore lié 
SELECT COUNT ( * ) INTO V_COUNT 
FROM KPINVAPP WHERE KBGKBEID = P_CODE_INVEN ; 
IF ( V_COUNT = 0 ) THEN 
DELETE FROM KPINVED WHERE KBFKBEID = P_CODE_INVEN ; 
DELETE FROM KPINVEN WHERE KBEID = P_CODE_INVEN ; 
END IF ; 
  
END P1  ; 
  

  

