CREATE PROCEDURE SP_DELCNX ( 
	IN P_ID_OFFRE_CONNEXE CHAR(9) , 
	IN P_ALIMENT_CONNEXE NUMERIC(5, 0) , 
	IN P_TYPE_OFFRE_CONNEXE CHAR(1) , 
	IN P_TYPE_CONNEXITE CHAR(2) , 
	IN P_NUM_CONNEXITE DECIMAL(7, 0) , 
	IN P_IDE NUMERIC(15, 0) , 
	IN P_MAJ_USER CHAR(10) , 
	IN P_MAJ_DATE INTEGER , 
	OUT P_ERREUR CHAR(128) ) 
	LANGUAGE SQL 
	SPECIFIC SP_DELCNX 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
DECLARE V_NBR_CONNEXITE INTEGER DEFAULT 0 ; 
DELETE FROM YPOCONX WHERE 
PJIPB = P_ID_OFFRE_CONNEXE AND PJALX = P_ALIMENT_CONNEXE AND PJTYP = P_TYPE_OFFRE_CONNEXE AND PJCCX = P_TYPE_CONNEXITE AND PJCNX = P_NUM_CONNEXITE ; 
--Mettre à jour KPENG   
IF ( P_IDE != 0 ) THEN 
UPDATE KPENG SET KDOMAJU = P_MAJ_USER , KDOMAJD = P_MAJ_DATE WHERE KDOID = P_IDE ; 
END IF ; 
--Ménage dans YPOCONX si un contrat reste 'Orphelin'                  
SELECT COUNT ( * ) INTO V_NBR_CONNEXITE FROM YPOCONX 
WHERE PJTYP = P_TYPE_OFFRE_CONNEXE AND PJCCX = P_TYPE_CONNEXITE AND PJCNX = P_NUM_CONNEXITE ; 
IF ( V_NBR_CONNEXITE = 1 ) THEN 
DELETE FROM YPOCONX 
WHERE PJTYP = P_TYPE_OFFRE_CONNEXE AND PJCCX = P_TYPE_CONNEXITE AND PJCNX = P_NUM_CONNEXITE ; 
END IF ; 
END P1  ; 
  

  

