CREATE PROCEDURE SP_DELETELOTDOCUMENTSGESTION ( 
	IN P_CODELOT INTEGER ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_DELETELOTDOCUMENTSGESTION 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
	 
	DECLARE V_DOCID INTEGER DEFAULT 0 ; 
	SET V_DOCID = 0 ; 
	 
	SELECT KEMTYPL INTO V_DOCID FROM KPDOCLDW WHERE KEMID = P_CODELOT ; 
	IF ( V_DOCID > 0 ) THEN 
		DELETE FROM KPDOCW WHERE KEQID = V_DOCID ; 
	END IF ; 
	 
	DELETE FROM KPDOCLDW WHERE KEMID = P_CODELOT ; 
	 
/* 	DELETE FROM KPDOCLDW     
	WHERE KEMKELID = P_CODELOT ;     
	     
	DELETE FROM KPDOCLW     
	WHERE KELID = P_CODELOT ;     
 */	 
	END P1  ; 
  

  

