CREATE PROCEDURE SP_DELTYPEVALEUR ( 
	IN P_ID CHAR(15) , 
	IN P_MODE CHAR(20) ) 
	LANGUAGE SQL 
	SPECIFIC SP_DELTYPEVALEUR 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
  
IF ( P_MODE = 'TypeValeur' ) THEN 
  
DELETE FROM KTYPVALD 
WHERE KGMTYVAL = P_ID ; 
  
DELETE FROM KTYPVAL 
WHERE KGLTYVAL = P_ID ; 
  
  
ELSE 
IF ( P_MODE = 'TypeValeurCompatible' ) THEN 
  
DELETE FROM KTYPVALD 
WHERE KGMID = P_ID ; 
  
END IF ; 
  
END IF ; 
  
END P1  ; 
  

  

