CREATE PROCEDURE SP_DELPARAMCFC ( 
	IN P_ORIGINE CHAR(10) , 
	IN P_CONCEPT CHAR(5) , 
	IN P_FAMILLE CHAR(5) , 
	IN P_CODE CHAR(15) , 
	OUT P_ERREUR CHAR(256) ) 
	LANGUAGE SQL 
	SPECIFIC SP_DELPARAMCFC 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
	DECLARE V_COUNT INTEGER DEFAULT 0 ; 
	 
	IF ( P_ORIGINE = 'CODE' ) THEN 
		SELECT COUNT ( * ) INTO V_COUNT FROM YYYYPAR WHERE TCON = P_CONCEPT AND TFAM = P_FAMILLE AND TRIM ( TCOD ) = TRIM ( P_CODE ) ; 
		 
		IF ( V_COUNT > 0 ) THEN 
			DELETE FROM YYYYPAR WHERE TCON = P_CONCEPT AND TFAM = P_FAMILLE AND TRIM ( TCOD ) = TRIM ( P_CODE ) ; 
			DELETE FROM YYYYPAL WHERE TCON = P_CONCEPT AND TFAM = P_FAMILLE AND TRIM ( TCOD ) = TRIM ( P_CODE ) ; 
		ELSE 
			SET P_ERREUR = 'Aucune mise à jour, ce code n''existe plus.' ; 
		END IF ; 
	END IF ; 
  
	IF ( P_ORIGINE = 'FAMILLE' ) THEN 
		SELECT COUNT ( * ) INTO V_COUNT FROM YYYYPFA WHERE TCON = P_CONCEPT AND TFAM = P_FAMILLE ; 
	 
		IF ( V_COUNT > 0 ) THEN 
			DELETE FROM YYYYPAL WHERE TCON = P_CONCEPT AND TFAM = P_FAMILLE ; 
			DELETE FROM YYYYPAR WHERE TCON = P_CONCEPT AND TFAM = P_FAMILLE ; 
			DELETE FROM YYYYPFA WHERE TCON = P_CONCEPT AND TFAM = P_FAMILLE ; 
		ELSE 
			SET P_ERREUR = 'Aucune mise à jour, cette famille n''existe plus.' ; 
		END IF ; 
	END IF ; 
	 
	IF ( P_ORIGINE = 'CONCEPT' ) THEN 
		SELECT COUNT ( * ) INTO V_COUNT FROM YYYYPCO WHERE TCON = P_CONCEPT ; 
	 
		IF ( V_COUNT > 0 ) THEN 
			DELETE FROM YYYYPAL WHERE TCON = P_CONCEPT ; 
			DELETE FROM YYYYPAR WHERE TCON = P_CONCEPT ; 
			DELETE FROM YYYYPFA WHERE TCON = P_CONCEPT ; 
			DELETE FROM YYYYPCO WHERE TCON = P_CONCEPT ; 
		ELSE 
			SET P_ERREUR = 'Aucune mise à jour, ce concept n''existe plus.' ; 
		END IF ; 
	END IF ; 
	 
  
END P1  ; 
  

  

