CREATE PROCEDURE SP_DELGARLISTINVENTAIRES ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_PERI CHAR(2) , 
	IN P_CODE_FORMULE INTEGER , 
	IN P_CODE_GARANTIES CHAR(100) , 
	IN P_CODE_INVENS CHAR(100) , 
	OUT P_ERREUR CHAR(128) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_DELGARLISTINVENTAIRES 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
DECLARE V_COUNT INTEGER DEFAULT 0 ; 
  
DECLARE V_OBJ_LEFT VARCHAR ( 100 ) DEFAULT '' ; 
DECLARE V_OBJ_RIGHT VARCHAR ( 100 ) DEFAULT '' ; 
  
DECLARE V_CODE_GARANTIES VARCHAR ( 100 ) DEFAULT '' ; 
DECLARE V_CODE_INVENS VARCHAR ( 100 ) DEFAULT '' ; 
  
--Suppression du lien 
CALL SP_SPLIT ( P_CODE_GARANTIES , ';' , 'L' , V_OBJ_LEFT ) ; 
CALL SP_SPLIT ( P_CODE_GARANTIES , ';' , 'R' , V_OBJ_RIGHT ) ; 
  
WHILE ( TRIM ( V_OBJ_LEFT ) != '**fin' ) DO 
  
DELETE FROM KPINVAPP WHERE 
KBGTYP = P_TYPE AND KBGIPB = P_CODEOFFRE AND KBGALX = P_VERSION AND KBGPERI = P_PERI AND KBGFOR = P_CODE_FORMULE AND KBGGAR = TRIM ( V_OBJ_LEFT ) ; 
  
SET V_CODE_GARANTIES = V_OBJ_RIGHT ; 
CALL SP_SPLIT ( V_CODE_GARANTIES , ';' , 'L' , V_OBJ_LEFT ) ; 
CALL SP_SPLIT ( V_CODE_GARANTIES , ';' , 'R' , V_OBJ_RIGHT ) ; 
  
END WHILE ; 
  
  
--Recherche si inventaire encore lié 
CALL SP_SPLIT ( P_CODE_INVENS , ';' , 'L' , V_OBJ_LEFT ) ; 
CALL SP_SPLIT ( P_CODE_INVENS , ';' , 'R' , V_OBJ_RIGHT ) ; 
  
WHILE ( TRIM ( V_OBJ_LEFT ) != '**fin' ) DO 
  
SELECT COUNT ( * ) INTO V_COUNT 
FROM KPINVAPP WHERE KBGKBEID = TRIM ( V_OBJ_LEFT ) ; 
IF ( V_COUNT = 0 ) THEN 
DELETE FROM KPINVED WHERE KBFKBEID = TRIM ( V_OBJ_LEFT ) ; 
DELETE FROM KPINVEN WHERE KBEID = TRIM ( V_OBJ_LEFT ) ; 
END IF ; 
  
SET V_CODE_INVENS = V_OBJ_RIGHT ; 
CALL SP_SPLIT ( V_CODE_INVENS , ';' , 'L' , V_OBJ_LEFT ) ; 
CALL SP_SPLIT ( V_CODE_INVENS , ';' , 'R' , V_OBJ_RIGHT ) ; 
  
END WHILE ; 
  
  
  
END P1  ; 
  

  

