CREATE PROCEDURE SP_DELLISTINVENTAIRES ( 
	IN P_CODE_INVENS CHAR(5000) , 
	OUT P_ERREUR CHAR(128) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_DELLISTINVENTAIRES 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
DECLARE V_OBJ_LEFT VARCHAR ( 5000 ) DEFAULT '' ; 
DECLARE V_OBJ_RIGHT VARCHAR ( 5000 ) DEFAULT '' ; 
DECLARE V_CODE_INVENS VARCHAR ( 5000 ) DEFAULT '' ; 
  
CALL SP_SPLIT ( P_CODE_INVENS , ';' , 'L' , V_OBJ_LEFT ) ; 
CALL SP_SPLIT ( P_CODE_INVENS , ';' , 'R' , V_OBJ_RIGHT ) ; 
  
WHILE ( TRIM ( V_OBJ_LEFT ) != '**fin' ) DO 
  
DELETE FROM KPINVAPP WHERE KBGKBEID = TRIM ( V_OBJ_LEFT ) ; 
DELETE FROM KPINVED WHERE KBFKBEID = TRIM ( V_OBJ_LEFT ) ; 
DELETE FROM KPINVEN WHERE KBEID = TRIM ( V_OBJ_LEFT ) ; 
  
SET V_CODE_INVENS = V_OBJ_RIGHT ; 
CALL SP_SPLIT ( V_CODE_INVENS , ';' , 'L' , V_OBJ_LEFT ) ; 
CALL SP_SPLIT ( V_CODE_INVENS , ';' , 'R' , V_OBJ_RIGHT ) ; 
  
END WHILE ; 
  
END P1  ; 
  

  

