CREATE PROCEDURE SP_DELETEOFFRE ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) ) 
	LANGUAGE SQL 
	SPECIFIC SP_DELETEOFFRE 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
FOR LOOP_POBASE AS FREE_LIST CURSOR FOR 
SELECT PBADH ADRID FROM YPOBASE WHERE TRIM ( PBIPB ) = TRIM ( P_CODEOFFRE ) AND PBALX = P_VERSION AND PBTYP = P_TYPE 
DO 
DELETE FROM YADRESS WHERE ABPCHR = ADRID ; 
DELETE FROM YPOBASE WHERE TRIM ( PBIPB ) = TRIM ( P_CODEOFFRE ) AND PBALX = P_VERSION AND PBTYP = P_TYPE ; 
END FOR ; 
  
DELETE FROM YPRTENT WHERE TRIM ( JDIPB ) = TRIM ( P_CODEOFFRE ) AND JDALX = P_VERSION ; 
DELETE FROM KPENT WHERE TRIM ( KAAIPB ) = TRIM ( P_CODEOFFRE ) AND KAAALX = P_VERSION AND KAATYP = P_TYPE ; 
DELETE FROM YPOCOAS WHERE TRIM ( PHIPB ) = TRIM ( P_CODEOFFRE ) AND PHALX = P_VERSION ;  -- AND PHTYP = P_TYPE; 
DELETE FROM YPOASSU WHERE TRIM ( PCIPB ) = TRIM ( P_CODEOFFRE ) AND PCALX = P_VERSION ;  -- AND PCTYP = P_TYPE;     
DELETE FROM YPOASSX WHERE TRIM ( PDIPB ) = TRIM ( P_CODEOFFRE ) AND PDALX = P_VERSION ;  -- AND PDTYP = P_TYPE;   
DELETE FROM YPOCOUR WHERE TRIM ( PFIPB ) = TRIM ( P_CODEOFFRE ) AND PFALX = P_VERSION ;  -- AND PFTYP = P_TYPE;     
DELETE FROM YPRTRSQ WHERE TRIM ( JEIPB ) = TRIM ( P_CODEOFFRE ) AND JEALX = P_VERSION ;  -- AND JETYP = P_TYPE;      
DELETE FROM KPRSQ WHERE TRIM ( KABIPB ) = TRIM ( P_CODEOFFRE ) AND KABALX = P_VERSION AND KABTYP = P_TYPE ; 
DELETE FROM YPRTOBJ WHERE TRIM ( JGIPB ) = TRIM ( P_CODEOFFRE ) AND JGALX = P_VERSION ;  -- AND JGTYP = P_TYPE;     
FOR CURSOR_ADR AS FREE_LIST CURSOR FOR 
SELECT JFADH ADRID FROM YPRTADR WHERE TRIM ( JFIPB ) = TRIM ( P_CODEOFFRE ) AND JFALX = P_VERSION  --AND JFTYP = P_TYPE 
DO 
DELETE FROM YADRESS WHERE ABPCHR = ADRID ; 
DELETE FROM YPRTADR WHERE TRIM ( JFIPB ) = TRIM ( P_CODEOFFRE ) AND JFALX = P_VERSION ;  -- AND JFTYP = P_TYPE;            
END FOR ; 
  
DELETE FROM KPOBJ WHERE TRIM ( KACIPB ) = TRIM ( P_CODEOFFRE ) AND KACALX = P_VERSION AND KACTYP = P_TYPE ; 
DELETE FROM KPFOR WHERE TRIM ( KDAIPB ) = TRIM ( P_CODEOFFRE ) AND KDAALX = P_VERSION AND KDATYP = P_TYPE ; 
DELETE FROM KPOPT WHERE TRIM ( KDBIPB ) = TRIM ( P_CODEOFFRE ) AND KDBALX = P_VERSION AND KDBTYP = P_TYPE ; 
DELETE FROM KPOPTD WHERE TRIM ( KDCIPB ) = TRIM ( P_CODEOFFRE ) AND KDCALX = P_VERSION AND KDCTYP = P_TYPE ; 
DELETE FROM KPOPTDW WHERE TRIM ( KDCIPB ) = TRIM ( P_CODEOFFRE ) AND KDCALX = P_VERSION AND KDCTYP = P_TYPE ; 
DELETE FROM KPOPTAP WHERE TRIM ( KDDIPB ) = TRIM ( P_CODEOFFRE ) AND KDDALX = P_VERSION AND KDDTYP = P_TYPE ; 
DELETE FROM KPOPTAPW WHERE TRIM ( KDDIPB ) = TRIM ( P_CODEOFFRE ) AND KDDALX = P_VERSION AND KDDTYP = P_TYPE ; 
DELETE FROM KPGARAN WHERE TRIM ( KDEIPB ) = TRIM ( P_CODEOFFRE ) AND KDEALX = P_VERSION AND KDETYP = P_TYPE ; 
DELETE FROM KPGARAH WHERE TRIM ( KDEIPB ) = TRIM ( P_CODEOFFRE ) AND KDEALX = P_VERSION AND KDETYP = P_TYPE ; 
DELETE FROM KPGARAW WHERE TRIM ( KDEIPB ) = TRIM ( P_CODEOFFRE ) AND KDEALX = P_VERSION AND KDETYP = P_TYPE ; 
DELETE FROM KPGARTAR WHERE TRIM ( KDGIPB ) = TRIM ( P_CODEOFFRE ) AND KDGALX = P_VERSION AND KDGTYP = P_TYPE ; 
DELETE FROM KPGARTAW WHERE TRIM ( KDGIPB ) = TRIM ( P_CODEOFFRE ) AND KDGALX = P_VERSION AND KDGTYP = P_TYPE ; 
DELETE FROM KPGARAP WHERE TRIM ( KDFIPB ) = TRIM ( P_CODEOFFRE ) AND KDFALX = P_VERSION AND KDFTYP = P_TYPE ; 
DELETE FROM KPINVEN WHERE TRIM ( KBEIPB ) = TRIM ( P_CODEOFFRE ) AND KBEALX = P_VERSION AND KBETYP = P_TYPE ; 
DELETE FROM KPINVED WHERE TRIM ( KBFIPB ) = TRIM ( P_CODEOFFRE ) AND KBFALX = P_VERSION AND KBFTYP = P_TYPE ; 
  
FOR LOOP_CLAUSE AS FREE_LIST CURSOR FOR 
SELECT KCAID ID , KCATXL TXL FROM KPCLAUSE WHERE TRIM ( KCAIPB ) = TRIM ( P_CODEOFFRE ) AND KCAALX = P_VERSION AND KCATYP = P_TYPE 
DO 
IF ( TXL != 0 ) THEN 
DELETE FROM KPCLATXT WHERE KFOID = TXL ; 
END IF ; 
DELETE FROM KPCLAUSE WHERE KCAID = ID ; 
END FOR ; 
  
FOR LOOP_CLAUSW AS FREE_LIST CURSOR FOR 
SELECT KCBTXL TXL FROM KPCLAUSW WHERE TRIM ( KCBIPB ) = TRIM ( P_CODEOFFRE ) AND KCBALX = P_VERSION AND KCBTYP = P_TYPE 
DO 
IF ( TXL != 0 ) THEN 
DELETE FROM KPCLATXT WHERE KFOID = TXL ; 
END IF ; 
END FOR ; 
DELETE FROM KPCLAUSW WHERE TRIM ( KCBIPB ) = TRIM ( P_CODEOFFRE ) AND KCBALX = P_VERSION AND KCBTYP = P_TYPE ; 
  
DELETE FROM KPCOTGA WHERE TRIM ( KDNIPB ) = TRIM ( P_CODEOFFRE ) AND KDNALX = P_VERSION AND KDNTYP = P_TYPE ; 
DELETE FROM KPCOTIS WHERE TRIM ( KDMIPB ) = TRIM ( P_CODEOFFRE ) AND KDMALX = P_VERSION AND KDMTYP = P_TYPE ; 
DELETE FROM KPCTRL WHERE TRIM ( KEUIPB ) = TRIM ( P_CODEOFFRE ) AND KEUALX = P_VERSION AND KEUTYP = P_TYPE ; 
DELETE FROM KPCTRLE WHERE TRIM ( KEVIPB ) = TRIM ( P_CODEOFFRE ) AND KEVALX = P_VERSION AND KEVTYP = P_TYPE ; 
DELETE FROM KPDESI WHERE TRIM ( KADIPB ) = TRIM ( P_CODEOFFRE ) AND KADALX = P_VERSION AND KADTYP = P_TYPE ; 
DELETE FROM KPENG WHERE TRIM ( KDOIPB ) = TRIM ( P_CODEOFFRE ) AND KDOALX = P_VERSION AND KDOTYP = P_TYPE ; 
DELETE FROM KPENGFAM WHERE TRIM ( KDPIPB ) = TRIM ( P_CODEOFFRE ) AND KDPALX = P_VERSION AND KDPTYP = P_TYPE ; 
DELETE FROM KPENGGAR WHERE TRIM ( KDSIPB ) = TRIM ( P_CODEOFFRE ) AND KDSALX = P_VERSION AND KDSTYP = P_TYPE ; 
DELETE FROM KPENGRSQ WHERE TRIM ( KDRIPB ) = TRIM ( P_CODEOFFRE ) AND KDRALX = P_VERSION AND KDRTYP = P_TYPE ; 
DELETE FROM KPENGVEN WHERE TRIM ( KDQIPB ) = TRIM ( P_CODEOFFRE ) AND KDQALX = P_VERSION AND KDQTYP = P_TYPE ; 
  
FOR LOOP_EXPFRH AS FREE_LIST CURSOR FOR 
SELECT KDKID ID FROM KPEXPFRH WHERE TRIM ( KDKIPB ) = TRIM ( P_CODEOFFRE ) AND KDKALX = P_VERSION AND KDKTYP = P_TYPE 
DO 
DELETE FROM KPEXPFRHD WHERE KDLKDKID = ID ; 
DELETE FROM KPEXPFRH WHERE KDKID = ID ; 
END FOR ; 
  
FOR LOOP_EXPLCI AS FREE_LIST CURSOR FOR 
SELECT KDIID ID FROM KPEXPLCI WHERE TRIM ( KDIIPB ) = TRIM ( P_CODEOFFRE ) AND KDIALX = P_VERSION AND KDITYP = P_TYPE 
DO 
DELETE FROM KPEXPLCID WHERE KDJKDIID = ID ; 
DELETE FROM KPEXPLCI WHERE KDIID = ID ; 
END FOR ; 
  
DELETE FROM KPIOPT WHERE TRIM ( KFCIPB ) = TRIM ( P_CODEOFFRE ) AND KFCALX = P_VERSION AND KFCTYP = P_TYPE ; 
DELETE FROM KPIRSGA WHERE TRIM ( KFDIPB ) = TRIM ( P_CODEOFFRE ) AND KFDALX = P_VERSION AND KFDTYP = P_TYPE ; 
DELETE FROM KPIRSOB WHERE TRIM ( KFAIPB ) = TRIM ( P_CODEOFFRE ) AND KFAALX = P_VERSION AND KFATYP = P_TYPE ; 
DELETE FROM KPISVAL WHERE TRIM ( KKCIPB ) = TRIM ( P_CODEOFFRE ) AND KKCALX = P_VERSION AND KKCTYP = P_TYPE ;
DELETE FROM KPMATFF WHERE TRIM ( KEAIPB ) = TRIM ( P_CODEOFFRE ) AND KEAALX = P_VERSION AND KEATYP = P_TYPE ; 
DELETE FROM KPMATFL WHERE TRIM ( KECIPB ) = TRIM ( P_CODEOFFRE ) AND KECALX = P_VERSION AND KECTYP = P_TYPE ; 
DELETE FROM KPMATFR WHERE TRIM ( KEBIPB ) = TRIM ( P_CODEOFFRE ) AND KEBALX = P_VERSION AND KEBTYP = P_TYPE ; 
DELETE FROM KPMATGG WHERE TRIM ( KEEIPB ) = TRIM ( P_CODEOFFRE ) AND KEEALX = P_VERSION AND KEETYP = P_TYPE ; 
DELETE FROM KPMATGL WHERE TRIM ( KEFIPB ) = TRIM ( P_CODEOFFRE ) AND KEFALX = P_VERSION AND KEFTYP = P_TYPE ; 
DELETE FROM KPMATGR WHERE TRIM ( KEDIPB ) = TRIM ( P_CODEOFFRE ) AND KEDALX = P_VERSION AND KEDTYP = P_TYPE ; 
DELETE FROM KPOBSV WHERE TRIM ( KAJIPB ) = TRIM ( P_CODEOFFRE ) AND KAJALX = P_VERSION AND KAJTYP = P_TYPE ; 
DELETE FROM KPODBLS WHERE TRIM ( KAFIPB ) = TRIM ( P_CODEOFFRE ) AND KAFALX = P_VERSION AND KAFTYP = P_TYPE ; 
DELETE FROM KPOPP WHERE TRIM ( KFPIPB ) = TRIM ( P_CODEOFFRE ) AND KFPALX = P_VERSION AND KFPTYP = P_TYPE ; 
DELETE FROM KPOPPAP WHERE TRIM ( KFQIPB ) = TRIM ( P_CODEOFFRE ) AND KFQALX = P_VERSION AND KFQTYP = P_TYPE ; 
DELETE FROM KPTRACE WHERE TRIM ( KCCIPB ) = TRIM ( P_CODEOFFRE ) AND KCCALX = P_VERSION AND KCCTYP = P_TYPE ; 
DELETE FROM KPVALID WHERE TRIM ( KEXIPB ) = TRIM ( P_CODEOFFRE ) AND KEXALX = P_VERSION AND KEXTYP = P_TYPE ; 
DELETE FROM KPINVAPP WHERE TRIM ( KBGIPB ) = TRIM ( P_CODEOFFRE ) AND KBGALX = P_VERSION AND KBGTYP = P_TYPE ; 
DELETE FROM YPOECHE WHERE TRIM ( PIIPB ) = TRIM ( P_CODEOFFRE ) AND PIALX = P_VERSION ;  -- AND PITYP = P_TYPE;      
DELETE FROM YPOINTE WHERE TRIM ( PPIPB ) = TRIM ( P_CODEOFFRE ) AND PPALX = P_VERSION ;  -- AND PPTYP = P_TYPE;    
DELETE FROM YPRTAVT WHERE TRIM ( KHIPB ) = TRIM ( P_CODEOFFRE ) AND KHALX = P_VERSION ;  -- AND KHTYP = P_TYPE;   
DELETE FROM YORTCLA WHERE TRIM ( QEIPB ) = TRIM ( P_CODEOFFRE ) AND QEALX = P_VERSION ;  -- AND QETYP = P_TYPE;   
DELETE FROM YORTCLV WHERE TRIM ( QFIPB ) = TRIM ( P_CODEOFFRE ) AND QFALX = P_VERSION ;  -- AND QFTYP = P_TYPE;   
DELETE FROM YPRTDES WHERE TRIM ( JIIPB ) = TRIM ( P_CODEOFFRE ) AND JIALX = P_VERSION ;  -- AND JITYP = P_TYPE;        
DELETE FROM YPRTFNC WHERE TRIM ( JNIPB ) = TRIM ( P_CODEOFFRE ) AND JNALX = P_VERSION ;  -- AND JNTYP = P_TYPE;    
DELETE FROM YPRTFOO WHERE TRIM ( JPIPB ) = TRIM ( P_CODEOFFRE ) AND JPALX = P_VERSION ;  -- AND JPTYP = P_TYPE;      
--DELETE FROM YPRTFOR WHERE TRIM ( JOIPB ) = TRIM ( P_CODEOFFRE ) AND JOALX = P_VERSION ;  -- AND JOTYP = P_TYPE;    
DELETE FROM YPRTFRH WHERE TRIM ( JJIPB ) = TRIM ( P_CODEOFFRE ) AND JJALX = P_VERSION ;  -- AND JJTYP = P_TYPE;       
DELETE FROM YPRTFRT WHERE TRIM ( JLIPB ) = TRIM ( P_CODEOFFRE ) AND JLALX = P_VERSION ;  -- AND JLTYP = P_TYPE;      
DELETE FROM YPRTGAA WHERE TRIM ( JRIPB ) = TRIM ( P_CODEOFFRE ) AND JRALX = P_VERSION ;  -- AND JRTYP = P_TYPE;     
DELETE FROM YPRTGAR WHERE TRIM ( JHIPB ) = TRIM ( P_CODEOFFRE ) AND JHALX = P_VERSION ;  -- AND JHTYP = P_TYPE;     
DELETE FROM YPRTGAV WHERE TRIM ( JQIPB ) = TRIM ( P_CODEOFFRE ) AND JQALX = P_VERSION ;  -- AND JQTYP = P_TYPE;    
DELETE FROM YPRTLCI WHERE TRIM ( JKIPB ) = TRIM ( P_CODEOFFRE ) AND JKALX = P_VERSION ;  -- AND JKTYP = P_TYPE;      
DELETE FROM YPRTLCT WHERE TRIM ( JMIPB ) = TRIM ( P_CODEOFFRE ) AND JMALX = P_VERSION ;  -- AND JMTYP = P_TYPE;   
DELETE FROM YPRTOBT WHERE TRIM ( KFIPB ) = TRIM ( P_CODEOFFRE ) AND KFALX = P_VERSION ;  -- AND KFTYP = P_TYPE;     
DELETE FROM YPOCONX WHERE TRIM ( PJIPB ) = TRIM ( P_CODEOFFRE ) AND PJALX = P_VERSION AND PJTYP = P_TYPE ; 
DELETE FROM KWADR WHERE TRIM ( W3IPB ) = TRIM ( P_CODEOFFRE ) AND W3ALX = P_VERSION AND W3TYP = P_TYPE ; 
DELETE FROM KPCTRLA WHERE TRIM ( KGTIPB ) = TRIM ( P_CODEOFFRE ) AND KGTALX = P_VERSION AND KGTTYP = P_TYPE ; 
DELETE FROM KCANEV WHERE TRIM ( KGOCNVA ) = TRIM ( P_CODEOFFRE ) AND KGOTYP = P_TYPE ; 
  
END P1  ; 
  
SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","YALBIN" ; 
  

