CREATE PROCEDURE SP_DELOBJETINVEN ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_CODERSQ INTEGER , 
	IN P_CODEOBJ INTEGER , 
	IN P_CODEINVEN INTEGER , 
	IN P_NUMDESCR INTEGER ) 
	LANGUAGE SQL 
	SPECIFIC SP_DELOBJETINVEN 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
DELETE FROM KPINVAPP WHERE KBGKBEID = P_CODEINVEN ; 
DELETE FROM KPINVEN WHERE KBEID = P_CODEINVEN ; 
  
FOR LOOP_INVED AS FREE_LIST CURSOR FOR 
	SELECT KBFID INVEDID , KBFKADFH IDDESFH FROM KPINVED WHERE KBFKBEID = P_CODEINVEN 
DO 
	DELETE FROM KPDESI WHERE KADCHR = IDDESFH ; 
END FOR ; 
  
DELETE FROM KPINVED WHERE KBFKBEID = P_CODEINVEN ; 
DELETE FROM KPDESI WHERE KADCHR = P_NUMDESCR ; 
  
UPDATE KPOBJ SET KACINVEN = 0 WHERE TRIM ( KACIPB ) = TRIM ( P_CODEOFFRE ) AND KACALX = P_VERSION AND KACTYP = P_TYPE AND KACRSQ = P_CODERSQ AND KACOBJ = P_CODEOBJ ; 
  
END P1  ; 
  

  

