CREATE PROCEDURE SP_DELEXPRCOMPLEXE ( 
	IN P_IDEXPR INTEGER , 
	IN P_TYPEEXPR CHAR(9) ) 
	LANGUAGE SQL 
	SPECIFIC SP_DELEXPRCOMPLEXE 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
DECLARE V_IDDESCR INTEGER DEFAULT 0 ; 
  
/*                          SUPPRESSION DE LA DESCRIPTION                          */ 
IF ( P_TYPEEXPR = 'LCI' ) THEN 
SELECT KHGDESI INTO V_IDDESCR FROM KEXPLCI WHERE KHGID = P_IDEXPR ; 
END IF ; 
IF ( P_TYPEEXPR = 'FRANCHISE' ) THEN 
SELECT KHEDESI INTO V_IDDESCR FROM KEXPFRH WHERE KHEID = P_IDEXPR ; 
END IF ; 
  
IF ( V_IDDESCR > 0 ) THEN 
DELETE FROM KDESI WHERE KDWID = V_IDDESCR ; 
END IF ; 
  
/*                          SUPPRESSION DES INFORMATIONS DE L'EXPRESSION COMPLEXE                              */ 
IF ( P_TYPEEXPR = 'LCI' ) THEN 
DELETE FROM KEXPLCI WHERE KHGID = P_IDEXPR ; 
DELETE FROM KEXPLCID WHERE KHHKHGID = P_IDEXPR ; 
END IF ; 
  
IF ( P_TYPEEXPR = 'FRANCHISE' ) THEN 
DELETE FROM KEXPFRH WHERE KHEID = P_IDEXPR ; 
DELETE FROM KEXPFRHD WHERE KHFKHEID = P_IDEXPR ; 
END IF ; 
  
  
END P1  ; 
  

  

