CREATE PROCEDURE SP_DELPARAMFILTRE ( 
	IN P_ORIGINE CHAR(10) , 
	IN P_ID NUMERIC(15, 0) , 
	OUT P_ERREUR CHAR(256) ) 
	LANGUAGE SQL 
	SPECIFIC SP_DELPARAMFILTRE 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
DECLARE V_CODEFILTRE CHAR ( 10 ) DEFAULT '' ; 
  
IF ( P_ORIGINE = 'Filtre' ) THEN 
  
SELECT KGGFILT INTO V_CODEFILTRE 
FROM KFILTRE 
WHERE KGGID = P_ID ; 
  
UPDATE YYYYPAR 
SET TFILT = '' 
WHERE TFILT = V_CODEFILTRE ; 
  
DELETE FROM KFILTRL 
WHERE KGHKGGID = P_ID ; 
  
DELETE FROM KFILTRE 
WHERE KGGID = P_ID ; 
  
END IF ; 
  
IF ( P_ORIGINE = 'Paire' ) THEN 
  
DELETE FROM KFILTRL 
WHERE KGHID = P_ID ; 
  
END IF ; 
END P1  ; 
  

  

