CREATE PROCEDURE SP_GETINFOUSER ( 
	IN P_INFOUSER CHAR(100) , 
	IN P_SPLITCHAR CHAR(1) , 
	OUT P_ISADMIN INTEGER ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_GETINFOUSER 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
	DECLARE V_OBJ_LEFT VARCHAR ( 10 ) DEFAULT '' ; 
	DECLARE V_OBJ_RIGHT VARCHAR ( 90 ) DEFAULT '' ; 
  
	SET P_ISADMIN = 0 ; 
	 
	IF ( P_INFOUSER != '' ) THEN 
	 
		SELECT COUNT ( * ) INTO P_ISADMIN FROM KUSRDRT WHERE TRIM ( KHRUSR ) = TRIM ( P_INFOUSER ) AND ( KHRTYD = 'A' OR KHRTYD = 'M' ) ; 
	 
		 
		/* RÉCUPÉRATION DU CARACTÈRE POUR SAVOIR SI L'UTILISATEUR EST ADMIN OU NON */ 
		/* CALL SP_SPLIT ( P_INFOUSER , P_SPLITCHAR , 'L' , V_OBJ_LEFT ) ;     
		CALL SP_SPLIT ( P_INFOUSER , P_SPLITCHAR , 'R' , V_OBJ_RIGHT ) ;     
		     
		IF ( V_OBJ_LEFT != '' ) THEN     
			SET P_ISADMIN = CAST ( TRIM ( V_OBJ_LEFT ) AS INTEGER ) ;     
		END IF ;  */ 
		 
	END IF ; 
  
END P1  ; 
  

  

