CREATE PROCEDURE SP_GETTYPEINVENTAIRE ( 
	IN P_BRANCHE CHAR(2) , 
	IN P_CIBLE CHAR(10) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_GETTYPEINVENTAIRE 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	DBGVIEW = *SOURCE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
	DECLARE CURSORINVENTAIRE CURSOR FOR 
	SELECT KAGID , KAGTYINV CODE , KAGDESC LIBELLE 
	FROM KINVTYP K 
	WHERE NOT EXISTS ( 
		SELECT * 
			FROM KINVTYP KI 
		INNER JOIN KFILTRL KFR ON KI . KAGKGGID = KFR . KGHKGGID AND KFR . KGHACTF = 'E' 
			WHERE ( KFR . KGHBRA = P_BRANCHE OR KFR . KGHBRA = '*' ) AND ( KFR . KGHCIBLE = P_CIBLE OR KFR . KGHCIBLE = '*' ) AND K . KAGID = KI . KAGID 
	UNION 
		SELECT * 
			FROM KINVTYP KI 
		INNER JOIN KFILTRL KFR ON KI . KAGKGGID = KFR . KGHKGGID AND KFR . KGHACTF = 'I' 
			WHERE ( ( KFR . KGHBRA <> P_BRANCHE AND KFR . KGHBRA <> '*' ) OR ( ( KFR . KGHBRA = P_BRANCHE OR KFR . KGHBRA = '*' ) AND KFR . KGHCIBLE <> P_CIBLE AND KFR . KGHCIBLE <> '*' ) ) 
			AND K . KAGID = KI . KAGID ) 
  
UNION 
  
	SELECT KAGID , KAGTYINV CODE , KAGDESC LIBELLE 
	FROM KINVTYP K 
	WHERE EXISTS ( 
		SELECT * 
			FROM KINVTYP KI 
		INNER JOIN KFILTRL KFR ON KI . KAGKGGID = KFR . KGHKGGID AND KFR . KGHACTF = 'I' 
			WHERE ( KFR . KGHBRA = P_BRANCHE AND ( KFR . KGHCIBLE = P_CIBLE OR KFR . KGHCIBLE = '*' ) ) 
			AND K . KAGID = KI . KAGID ) 
ORDER BY KAGID , CODE ; 
  
	OPEN CURSORINVENTAIRE ; 
	 
END P1  ; 
  

  

