CREATE PROCEDURE SP_GETINFOCOMPQUITTANCE ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_CONCEPT CHAR(5) , 
	IN P_FAMILLE CHAR(5) , 
	IN P_CODE CHAR(15) , 
	IN P_USER CHAR(10) , 
	IN P_DATENOW INTEGER , 
	IN P_HEURENOW INTEGER , 
	IN P_VALIDQUITTANCE CHAR(1) , 
	IN P_ACTEGESTION CHAR(5) , 
	OUT P_DISPLAYEMISSION INTEGER , 
	OUT P_AEMISSION INTEGER ) 
	LANGUAGE SQL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
	DECLARE V_VALABSOLUE NUMERIC ( 15 , 3 ) DEFAULT 0 ; 
	DECLARE V_QUITTANCEHT NUMERIC ( 15 , 3 ) DEFAULT 0 ; 
	DECLARE V_COUNT INTEGER DEFAULT 0 ; 
	DECLARE V_NEWID INTEGER DEFAULT 0 ; 
  
	SET P_CODEOFFRE = F_PADLEFT( 9 , TRIM ( P_CODEOFFRE ) );
	SET P_DISPLAYEMISSION = 0 ; 
	SET P_AEMISSION = 0 ; 
	SET V_VALABSOLUE = 0 ; 
	SET V_QUITTANCEHT = 0 ; 
	SET V_COUNT = 0 ; 
	SET V_NEWID = 0 ; 
	 
	/* PAR DÉFAUT LA CASE À COCHER EST COCHÉE => INSERTION DE LA TRACE DANS KPAVTRC */ 
	IF ( P_VALIDQUITTANCE != 'O' ) THEN 
	IF ( TRIM ( P_ACTEGESTION ) = 'REGUL' ) THEN 
		DELETE FROM KPAVTRC WHERE  KHOIPB = P_CODEOFFRE AND KHOALX = P_VERSION AND KHOTYP = P_TYPE AND KHOPERI = 'COT' AND KHOOEF = 'NR' ; 
		ELSE 
		DELETE FROM KPAVTRC WHERE  KHOIPB = P_CODEOFFRE AND KHOALX = P_VERSION AND KHOTYP = P_TYPE AND KHOPERI = 'COT' AND KHOOEF = 'NG' ; 
		END IF ; 
	END IF ; 
	/* CALL SP_NCHRONO ( 'KHOID' , V_NEWID ) ;          
	INSERT INTO KPAVTRC          
		( KHOID , KHOTYP , KHOIPB , KHOALX , KHOPERI , KHOOEF , KHOCRU , KHOCRD , KHOCRH )          
	VALUES          
		( V_NEWID , P_TYPE , P_CODEOFFRE , P_VERSION , 'COT' , 'NG' , P_USER , P_DATENOW , P_HEURENOW ) ;  */ 
	   
	/* RÉCUPÉRATION DE LA VALEUR ABSOLUE */ 
	SELECT TPCN1 INTO V_VALABSOLUE FROM YYYYPAR WHERE TCON = TRIM ( P_CONCEPT ) AND  TFAM  = TRIM ( P_FAMILLE ) AND  TRIM(TCOD)  = TRIM ( P_CODE ) ; 
	/* SUPPRESSION DU TEST DE L'HT QUITTANCE <> 0 */ 
	IF ( V_QUITTANCEHT <= V_VALABSOLUE ) THEN 
		SET P_DISPLAYEMISSION = 1 ; 
		
	/* RÉCUPÉRATION DU HT DE LA QUITTANCE */ 
	IF ( TRIM ( P_ACTEGESTION ) = 'AVNRG' OR TRIM ( P_ACTEGESTION ) = 'REGUL' ) THEN 
		SELECT ABSVAL ( PKKHT ) INTO V_QUITTANCEHT FROM YPRIRES WHERE  PKIPB = P_CODEOFFRE AND PKALX = P_VERSION ; 
	ELSE 
		SELECT ABSVAL ( PKKHT ) INTO V_QUITTANCEHT FROM YPRIPES WHERE  PKIPB = P_CODEOFFRE AND PKALX = P_VERSION ; 
	END IF ; 
	 

	 
	IF ( TRIM ( P_ACTEGESTION ) = 'REGUL' ) THEN 
		SELECT COUNT ( * ) INTO V_COUNT FROM KPAVTRC WHERE  KHOIPB = P_CODEOFFRE AND KHOALX = P_VERSION AND KHOTYP = P_TYPE AND KHOPERI = 'COT' AND KHOOEF = 'NR' ; 
		ELSE 
		SELECT COUNT ( * ) INTO V_COUNT FROM KPAVTRC WHERE  KHOIPB = P_CODEOFFRE AND KHOALX = P_VERSION AND KHOTYP = P_TYPE AND KHOPERI = 'COT' AND KHOOEF = 'NG' ; 
		END IF ; 
	 
		 
		IF ( V_COUNT = 0 ) THEN 
			SET P_AEMISSION = 1 ; 
		END IF ; 
		 
	END IF ;	 
  
END P1  ; 
