CREATE OR REPLACE PROCEDURE SP_GTLSTMR (
	IN P_CODEOFFRE CHAR(9) ,
	IN P_VERSION INTEGER ,
	IN P_TYPE CHAR(1) ,
	IN P_CODEAVT INTEGER )
	DYNAMIC RESULT SETS 1
	LANGUAGE SQL
	SPECIFIC SP_GTLSTMR
	NOT DETERMINISTIC
	MODIFIES SQL DATA
	CALLED ON NULL INPUT
	SET OPTION  ALWBLK = *ALLREAD ,
	ALWCPYDTA = *OPTIMIZE ,
	COMMIT = *CHG ,
	CLOSQLCSR = *ENDMOD ,
	DECRESULT = (31, 31, 00) ,
	DFTRDBCOL = ZALBINKHEO ,
	DYNDFTCOL = *YES ,
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' ,
	DYNUSRPRF = *USER ,
	SRTSEQ = *HEX
	P1 : BEGIN ATOMIC

DECLARE V_JOINYPAR VARCHAR ( 1000 ) DEFAULT '' ;
DECLARE V_QUERY VARCHAR ( 8000 ) DEFAULT '' ;
DECLARE CURSORMNTREF CURSOR WITH RETURN FOR SQL_STATEMENT ;


IF ( P_CODEAVT > 0 ) THEN
	/* CHANGEMENT DES CHAMPS DE PERIODE SUIVANT LE DOC NOTESFDPOURZBO.DOCX 2015-02-16 */
	SET V_QUERY = 'SELECT PBPER CODEPERIODICITE, TPLIB LIBPERIODICITE, PBECJ ECHEANCEJOUR, PBECM ECHEANCEMOIS,
								  JDPEJ NEXTECHEANCEJOUR, JDPEM NEXTECHEANCEMOIS, JDPEA NEXTECHEANCEANNEE,
								  CASE PBPER WHEN ''U'' || ''E'' || ''R'' THEN PBAVJ ELSE JDDPJ END PERIODEDEBJOUR,
								  CASE PBPER WHEN ''U'' || ''E'' || ''R'' THEN PBAVM ELSE JDDPM END PERIODEDEBMOIS,
								  CASE PBPER WHEN ''U'' || ''E'' || ''R'' THEN PBAVA ELSE JDDPA END PERIODEDEBANNEE,
								  CASE PBPER WHEN ''U'' || ''E'' || ''R'' THEN PBFEJ ELSE JDFPJ END PERIODEFINJOUR,
								  CASE PBPER WHEN ''U'' || ''E'' || ''R'' THEN PBFEM ELSE JDFPM END PERIODEFINMOIS,
								  CASE PBPER WHEN ''U'' || ''E'' || ''R'' THEN PBFEA ELSE JDFPA END PERIODEFINANNEE,
								  JDAFC FRAISACC, JDAFR MNTFRAISACC, JDATT TAXEATTENTAT,
								  KDAALPHA LETTREFORM, KDBFOR CODEFORM, KDBDESC LIBFORM, KDDRSQ CODERSQ, KABDESC LIBRSQ,
					   KDBTMC MNTCALCULE, KDBTFF MNTFORCE, KDBACQ MNTACQUIS,KDBPRO MNTPROVI,
								  JDTMC TOTALMNTCALCULE, JDTFF TOTALMNTFORCE, JDACQ TOTALMNTACQUIS,JDPRO TOTALMNTPROVI,
								  KAAOBSF CODEOBSV, KAJOBSV OBSV,
								  PBCTD DUREEGARANTIE, PBCTU UNITETEMPS
								  FROM YPOBASE
												INNER JOIN V_FORMULE_ACTIVE F ON IPB = PBIPB
												INNER JOIN KPENT ON KAATYP = PBTYP AND KAAIPB = PBIPB AND KAAALX = PBALX
												INNER JOIN YPRTENT ON PBIPB = JDIPB AND PBALX = JDALX' ;

	CALL SP_BUILDJOINYPAR ( 'INNER' , 'PRODU' , 'PBPER' , '' , ' AND TCOD = PBPER' , V_JOINYPAR ) ;
	SET V_QUERY = TRIM ( V_QUERY ) CONCAT ' ' CONCAT TRIM ( V_JOINYPAR ) ;

	SET V_QUERY = TRIM ( V_QUERY ) CONCAT '
												INNER JOIN KPRSQ ON PBIPB = KABIPB AND PBALX = KABALX AND PBTYP = KABTYP
												INNER JOIN KPOPTAP ON KDDIPB = KABIPB AND KDDALX = KABALX AND KDDTYP = KABTYP AND KDDRSQ = KABRSQ
												INNER JOIN KPFOR ON KDDIPB = KDAIPB AND KDDALX = KDAALX AND KDDTYP = KDATYP AND KDDFOR = KDAFOR AND F.FOR = KDAFOR
												INNER JOIN KPOPT ON KDBKDAID = KDAID AND KDBOPT = 1
												LEFT JOIN KPOBSV ON KAAOBSF = KAJCHR
				   WHERE PBIPB = ''' CONCAT P_CODEOFFRE CONCAT ''' AND PBALX = ' CONCAT P_VERSION CONCAT ' AND PBTYP = ''' CONCAT P_TYPE CONCAT '''
				   ORDER BY KDACCH' ;
ELSE

	IF ( TRIM ( P_TYPE ) = 'O' ) THEN
		SET V_QUERY = 'SELECT PBPER CODEPERIODICITE, TPLIB LIBPERIODICITE, PBECJ ECHEANCEJOUR, PBECM ECHEANCEMOIS,
									  JDPEJ NEXTECHEANCEJOUR, JDPEM NEXTECHEANCEMOIS, JDPEA NEXTECHEANCEANNEE,
									  PBEFJ PERIODEDEBJOUR, PBEFM PERIODEDEBMOIS, PBEFA PERIODEDEBANNEE,
									  PBFEJ PERIODEFINJOUR, PBFEM PERIODEFINMOIS, PBFEA PERIODEFINANNEE,
									  JDAFC FRAISACC, JDAFR MNTFRAISACC, JDATT TAXEATTENTAT,
									  KDAALPHA LETTREFORM, KDBFOR CODEFORM, KDBDESC LIBFORM, KDDRSQ CODERSQ, KABDESC LIBRSQ,
						   KDBTMC MNTCALCULE, KDBTFF MNTFORCE, KDBACQ MNTACQUIS,KDBPRO MNTPROVI,
									  JDTMC TOTALMNTCALCULE, JDTFF TOTALMNTFORCE, JDACQ TOTALMNTACQUIS,JDPRO TOTALMNTPROVI,
									  KAAOBSF CODEOBSV, KAJOBSV OBSV,
									  PBCTD DUREEGARANTIE, PBCTU UNITETEMPS
									  FROM YPOBASE
													INNER JOIN V_FORMULE_ACTIVE F ON IPB = PBIPB
													INNER JOIN KPENT ON KAATYP = PBTYP AND KAAIPB = PBIPB AND KAAALX = PBALX
													INNER JOIN YPRTENT ON PBIPB = JDIPB AND PBALX = JDALX' ;

		CALL SP_BUILDJOINYPAR ( 'INNER' , 'PRODU' , 'PBPER' , '' , ' AND TCOD = PBPER' , V_JOINYPAR ) ;
		SET V_QUERY = TRIM ( V_QUERY ) CONCAT ' ' CONCAT TRIM ( V_JOINYPAR ) ;

		SET V_QUERY = TRIM ( V_QUERY ) CONCAT '
													INNER JOIN KPRSQ ON PBIPB = KABIPB AND PBALX = KABALX AND PBTYP = KABTYP
													INNER JOIN KPOPTAP ON KDDIPB = KABIPB AND KDDALX = KABALX AND KDDTYP = KABTYP AND KDDRSQ = KABRSQ
													INNER JOIN KPFOR ON KDDIPB = KDAIPB AND KDDALX = KDAALX AND KDDTYP = KDATYP AND KDDFOR = KDAFOR AND F.FOR = KDAFOR
													INNER JOIN KPOPT ON KDBKDAID = KDAID AND KDBOPT = 1
													LEFT JOIN KPOBSV ON KAAOBSF = KAJCHR
					   WHERE PBIPB = ''' CONCAT P_CODEOFFRE CONCAT ''' AND PBALX = ' CONCAT P_VERSION CONCAT ' AND PBTYP = ''' CONCAT P_TYPE CONCAT '''
					   ORDER BY KDACCH' ;
	END IF ;

	IF ( TRIM ( P_TYPE ) = 'P' ) THEN
		/* CHANGEMENT DES CHAMPS DE PERIODE SUIVANT LE DOC NOTESFDPOURZBO.DOCX 2015-02-16 */
		SET V_QUERY = 'SELECT PBPER CODEPERIODICITE, TPLIB LIBPERIODICITE, PBECJ ECHEANCEJOUR, PBECM ECHEANCEMOIS,
									  JDPEJ NEXTECHEANCEJOUR, JDPEM NEXTECHEANCEMOIS, JDPEA NEXTECHEANCEANNEE,
									  PBAVJ PERIODEDEBJOUR, PBAVM PERIODEDEBMOIS, PBAVA PERIODEDEBANNEE,
									  PBFEJ PERIODEFINJOUR, PBFEM PERIODEFINMOIS, PBFEA PERIODEFINANNEE,
									  JDAFC FRAISACC, JDAFR MNTFRAISACC, JDATT TAXEATTENTAT,
									  KDAALPHA LETTREFORM, KDBFOR CODEFORM, KDBDESC LIBFORM, KDDRSQ CODERSQ, KABDESC LIBRSQ,
						   KDBTMC MNTCALCULE, KDBTFF MNTFORCE, KDBACQ MNTACQUIS,KDBPRO MNTPROVI,
									  JDTMC TOTALMNTCALCULE, JDTFF TOTALMNTFORCE, JDACQ TOTALMNTACQUIS,JDPRO TOTALMNTPROVI,
									  KAAOBSF CODEOBSV, KAJOBSV OBSV,
									  PBCTD DUREEGARANTIE, PBCTU UNITETEMPS
									  FROM YPOBASE
													INNER JOIN V_FORMULE_ACTIVE F ON IPB = PBIPB
													INNER JOIN KPENT ON KAATYP = PBTYP AND KAAIPB = PBIPB AND KAAALX = PBALX
													INNER JOIN YPRTENT ON PBIPB = JDIPB AND PBALX = JDALX' ;

		CALL SP_BUILDJOINYPAR ( 'INNER' , 'PRODU' , 'PBPER' , '' , ' AND TCOD = PBPER' , V_JOINYPAR ) ;
		SET V_QUERY = TRIM ( V_QUERY ) CONCAT ' ' CONCAT TRIM ( V_JOINYPAR ) ;

		SET V_QUERY = TRIM ( V_QUERY ) CONCAT '
													INNER JOIN KPRSQ ON PBIPB = KABIPB AND PBALX = KABALX AND PBTYP = KABTYP
													INNER JOIN KPOPTAP ON KDDIPB = KABIPB AND KDDALX = KABALX AND KDDTYP = KABTYP AND KDDRSQ = KABRSQ
													INNER JOIN KPFOR ON KDDIPB = KDAIPB AND KDDALX = KDAALX AND KDDTYP = KDATYP AND KDDFOR = KDAFOR AND F.FOR = KDAFOR
													INNER JOIN KPOPT ON KDBKDAID = KDAID AND KDBOPT = 1
													LEFT JOIN KPOBSV ON KAAOBSF = KAJCHR
					   WHERE PBIPB = ''' CONCAT P_CODEOFFRE CONCAT ''' AND PBALX = ' CONCAT P_VERSION CONCAT ' AND PBTYP = ''' CONCAT P_TYPE CONCAT '''
					   ORDER BY KDACCH' ;
		 --LEFT JOIN YPRTFOR ON JOIPB = KDAIPB AND JOALX = KDAALX AND JORSQ = KABRSQ AND JOFOR = KDAFOR
	END IF ;
END IF ;

PREPARE SQL_STATEMENT FROM V_QUERY ;
OPEN CURSORMNTREF ;


END P1  ;

