
CREATE  PROCEDURE  SP_GETCOTISATIONGARANTIES ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_ONLYGARPORTEUSE CHAR(1) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_GETCOTISATIONGARANTIES 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
	 
	DECLARE CURSORCOTISATIONS CURSOR WITH RETURN FOR 
	SELECT KDNGARAN CODEGARANTIE , GADEA LIBGARANTIE , KDNRSQ CODERISQUE , KDNFOA CODEFORMULE , 
							KDNNUMTAR TARIF , KDGLCIVALA VALEURLCI , KDGLCIUNIT UNITELCI , KDEASVALA VALEURASSIETTE , KDEASUNIT UNITEASSIETTE , 
							KDGPRIVALA VALEURTAUX , KDGPRIUNIT UNITETAUX , KDNMHT COTISHT , KDNMTX COTISTAXE , KDNMTT COTISTTC , KDNKDEID LIENKPGARAN 
					 FROM KPCOTGA 
							INNER JOIN KGARAN ON KDNGARAN = GAGAR 
							INNER JOIN KPGARTAR ON KDNKDGID = KDGID 
							INNER JOIN KPGARAN ON KDNKDEID = KDEID 
							INNER JOIN KPRSQ ON KABRSQ = KDNRSQ AND KABIPB = KDNIPB AND KABALX = KDNALX AND KABTYP = KDNTYP 
							INNER JOIN KPOPTD ON KDCID = KDEKDCID 
							INNER JOIN KVOLET ON KDCKAKID = KAKID 
							INNER JOIN KCATVOLET ON KAKID = KAPKAKID AND KAPCIBLE = KABCIBLE 
							INNER JOIN KCATBLOC ON KAQKAPID = KAPID 
							INNER JOIN KBLOC ON KDCKAEID = KAEID AND KAEID = KAQKAEID  
							LEFT JOIN ZALBINKMOD . YPLTGAR ON C2SEQ = KDESEQ AND C2NIV = KDENIVEAU
							INNER JOIN KCATMODELE ON KARKAQID = KAQID AND KARMODELE = KDCMODELE AND KARID = KDCKARID
					 WHERE KDNIPB =  P_CODEOFFRE  AND KDNALX = P_VERSION AND KDNTYP = P_TYPE
					 AND (P_ONLYGARPORTEUSE <> 'O' OR (KDGPRIVALA <> 0 OR KDGPRIMPRO <> 0))
					 ORDER BY KDNRSQ , KDNFOA , KAPORDRE , KAQORDRE , KARDATEAPP DESC , KDETRI , KDNGARAN
					 ; 
			 
	OPEN CURSORCOTISATIONS ; 
	 
END P1  ; 
  

  

