CREATE PROCEDURE SP_GETPARAMDOCUMENTS ( 
	IN P_IDDOC CHAR(500) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_GETPARAMDOCUMENTS 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
	DECLARE V_QUERY VARCHAR ( 8000 ) DEFAULT '' ; 
	DECLARE CURSOR1 CURSOR WITH RETURN FOR SQL_STATEMENT ; 
	 
	SET P_IDDOC = TRANSLATE ( P_IDDOC , ',' , '|' ) ; 
  
	SET V_QUERY = 'SELECT KEQID IDDOC,KEQNOM NOMDOC, TRIM(KEQCHM) CONCAT TRIM(KEQNOM) CHEMINDOC FROM KPDOC WHERE KEQID IN (' CONCAT TRIM ( P_IDDOC ) CONCAT ')' ; 
  
	PREPARE SQL_STATEMENT FROM V_QUERY ; 
	OPEN CURSOR1 ; 
  
END P1  ; 
  

  

