CREATE PROCEDURE SP_GETAVENANTHIST ( 
	IN P_CODECONTRAT CHAR(9) , 
	IN P_VERSIONCONTRAT INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_CODEAVN INTEGER ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_GETAVENANTHIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *NONE , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
--DECLARE V_QUERY VARCHAR ( 15000 ) DEFAULT '' ; 
--DECLARE V_JOINYPAR VARCHAR ( 1000 ) DEFAULT '' ; 
--DECLARE V_COUNTASSADD INTEGER DEFAULT 0 ; 
--DECLARE CURSOR1 CURSOR WITH RETURN FOR SQL_STATEMENT ; 
/* MODIF ECM 2015-06-25 : INNER JOIN À LA PLACE DE LEFT JOIN POUR NE PAS REMONTER DES VALEURS NULLES QUI SERONT COMPTABILISÉES */ 
  
--SELECT COUNT ( * ) NB INTO V_COUNTASSADD 
--FROM YHPBASE 
--INNER JOIN YHPASSU ON PBIPB = PCIPB AND PBALX = PCALX AND PBTYP = PCTYP AND PBIAS <> PCIAS 
--WHERE TRIM ( PBIPB ) = TRIM ( P_CODECONTRAT ) AND PBALX = P_VERSIONCONTRAT AND PBTYP = P_TYPE AND PBAVN = P_CODEAVN ; 
/* MODIF ZBO 2015-12-30 :  Données entête àpartir d'une vue*/ 
DECLARE CURINFOENTETE CURSOR FOR 
SELECT DESCRIPTIF , CODECONTRAT , VERSCONTRAT , TYPE , TYPECONTRAT , LIBTYPECONTRAT , CONTRATREMP , 
DATEEFFETA , DATEEFFETM , DATEEFFETJ , DATEEFFETJH , 
DATEACCORDA , DATEACCORDM , DATEACCORDJ , 
DATECRA , DATECRM , DATECRJ , 
CODECONTRATREMP , VERSCONTRATREMP , 
OBSERVATIONS , NUMCHRONOOSBV , 
CIBLE , CIBLELIB , 
BRANCHE , BRANCHELIB , 
SOUSBRANCHE , 
CATEGORIE , 
TYPEPOLICE , 
DEVISE , LIBDEVISE , 
CODEMOTSCLEF1 , CODEMOTSCLEF2 , CODEMOTSCLEF3 , 
PERIODICITECODE , PERIODICITENOM , 
ECHJOUR , ECHMOIS , 
PREAVIS , 
INDICEREFERENCE , LIBINDICE , 
INDEXATION , 
VALEUR , 
INTERCALAIREEXISTE , 
LCI , 
ASSIETTE , 
FRANCHISE , 
FINEFFETJOUR , FINEFFETMOIS , FINEFFETANNEE , FINEFFETHEURE , 
DUREEGARANTIE , UNITETEMPS , 
DATESTATISTIQUE , 
NATURECONTRAT , LIBELLENATURECONTRAT , 
PARTALBINGIA , 
APERITEURCODE , APERITEURNOM , 
FRAISAPERITION , 
COUVERTURE , 
SOUSCODE , SOUSNOM , 
GESCODE , GESNOM , 
COURTIERAPPORTEUR , NOMCOURTIERAPPO , VILLEAPPORTEUR , 
COURTIERGESTIONNAIRE , NOMCOURTIERGEST , REFCOURTIER , VILLEGESTIONNAIRE , 
COURTIERPAYEUR , NOMCOURTIERPAYEUR , VILLEPAYEUR , 
CODEINTERLOCUTEUR , NOMINTERLOCUTEUR , 
NOMPRENASSUR , CODEPRENASSUR , PRENEURESTASSURE , 
DEPASSUR , CODEPOSTALASSUR , VILLEASSUR , 
ETAT , SITUATION , LIBETAT , LIBSITUATION , 
ADRESSECONTRAT , 
CODEENCAISSEMENT , LIBENCAISSEMENT , 
NUMINTERNEAVENANT , DATEEFFETAVNJOUR , DATEEFFETAVNMOIS , DATEEFFETAVNANNEE , 
										NUMAVENANT , HEUREAVN , MOTIFAVN , LIBMOTIFAVN , 
CODEOFFREORIGINE , VERSIONOFFREORIGINE , 
CODEREGIME , LIBREGIME , 
SOUMISCATNAT , MONTANTREF1 , MONTANTREF2 , 
PROCHECHJ , PROCHECHM , PROCHECHA , 
HORSCATNAT , CATNAT , TAUXHORSCATNAT , TAUXCATNAT , 
DATEDEBDERNIEREPERIODEJOUR , DATEDEBDERNIEREPERIODEMOIS , DATEDEBDERNIEREPERIODEANNEE , 
DATEFINDERNIEREPERIODEJOUR , DATEFINDERNIEREPERIODEMOIS , DATEFINDERNIEREPERIODEANNEE , 
ZONESTOP , 
DATEAFFAIRENOUVELLEJOUR , DATEAFFAIRENOUVELLEMOIS , DATEAFFAIRENOUVELLEANNEE , 
CODEACTION , LIBACTION , 
DATESITJOUR , DATESITMOIS , DATESITANNEE , 
DATECRJOUR , DATECRMOIS , DATECRANNEE , UCRCODE , UCRNOM , 
DATEUPJOUR , DATEUPMOIS , DATEUPANNEE , UUPCODE , UUPNOM , 
										ANTECEDENT , DESCRIPTION , DESCRAVENANT , 
										PARTAPERITEUR , IDINTERLOCUTEURAPE , LIBINTERLOCUTEURAPE , REFERENCEAPERITEUR , FRAISACCAPERITEUR , COMMISSIONAPERITEUR , 
										TYPERETOUR , LIBRETOUR , PARTBENEF , ( SELECT COUNT ( * ) 
FROM YHPBASE 
INNER JOIN YHPASSU ON PBIPB = PCIPB AND PBALX = PCALX AND PBTYP = PCTYP AND PBIAS <> PCIAS 
WHERE TRIM ( CODECONTRAT ) = TRIM ( P_CODECONTRAT ) AND VERSCONTRAT = P_VERSIONCONTRAT AND TYPE = P_TYPE AND NUMINTERNEAVENANT = P_CODEAVN ) NBASSUADD , 
( SELECT COUNT ( * ) FROM HPOPP WHERE TRIM ( KFPIPB ) = TRIM ( CODECONTRAT ) AND KFPALX = P_VERSIONCONTRAT AND KFPTYP = P_TYPE ) NBOPPBENEF , LTA
FROM V_INFOENTETECTRAVNHIST 
WHERE 
TYPE = P_TYPE AND VERSCONTRAT = P_VERSIONCONTRAT AND LOWER ( TRIM ( CODECONTRAT ) ) = LOWER ( TRIM ( P_CODECONTRAT ) ) AND NUMINTERNEAVENANT = P_CODEAVN ; 
  
  
OPEN CURINFOENTETE ; 
  
  
END P1  ; 
  

  

