CREATE OR REPLACE PROCEDURE SP_GTLSTMRHIST (
	IN P_CODEOFFRE CHAR(9) ,
	IN P_VERSION INTEGER ,
	IN P_TYPE CHAR(1) ,
	IN P_CODEAVENANT INTEGER )
	DYNAMIC RESULT SETS 1
	LANGUAGE SQL
	SPECIFIC SP_GTLSTMRHIST
	NOT DETERMINISTIC
	MODIFIES SQL DATA
	CALLED ON NULL INPUT
	SET OPTION  ALWBLK = *ALLREAD ,
	ALWCPYDTA = *OPTIMIZE ,
	COMMIT = *CHG ,
	CLOSQLCSR = *ENDMOD ,
	DECRESULT = (31, 31, 00) ,
	DFTRDBCOL = ZALBINKHEO ,
	DYNDFTCOL = *YES ,
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' ,
	DYNUSRPRF = *USER ,
	SRTSEQ = *HEX
	P1 : BEGIN ATOMIC

DECLARE V_JOINYPAR VARCHAR ( 1000 ) DEFAULT '' ;

DECLARE V_QUERY VARCHAR ( 8000 ) DEFAULT '' ;
DECLARE CURSORMNTREF CURSOR WITH RETURN FOR SQL_STATEMENT ;

	SET V_QUERY = 'SELECT PBPER CODEPERIODICITE, TPLIB LIBPERIODICITE, PBECJ ECHEANCEJOUR, PBECM ECHEANCEMOIS,
                              JDPEJ NEXTECHEANCEJOUR, JDPEM NEXTECHEANCEMOIS, JDPEA NEXTECHEANCEANNEE,
                              PBEFJ PERIODEDEBJOUR, PBEFM PERIODEDEBMOIS, PBEFA PERIODEDEBANNEE,
                              PBFEJ PERIODEFINJOUR, PBFEM PERIODEFINMOIS, PBFEA PERIODEFINANNEE,
                              JDAFC FRAISACC, JDAFR MNTFRAISACC, JDATT TAXEATTENTAT,
                              KDAALPHA LETTREFORM, KDBFOR CODEFORM, KDBDESC LIBFORM, KDDRSQ CODERSQ, KABDESC LIBRSQ,
							  KDBTMC MNTCALCULE, KDBTFF MNTFORCE, KDBACQ MNTACQUIS,
							  JDTMC TOTALMNTCALCULE, JDTFF TOTALMNTFORCE, JDACQ TOTALMNTACQUIS, KAAOBSF CODEOBSV, KAJOBSV OBSV,
							  PBCTD DUREEGARANTIE, PBCTU UNITETEMPS,KDBPRO MNTPROVI,JDPRO TOTALMNTPROVI
					FROM YHPBASE
					    INNER JOIN V_FORMULE_ACTIVE_HIST F ON IPB = PBIPB AND AVN = PBAVN
						INNER JOIN HPENT ON KAATYP = PBTYP AND KAAIPB = PBIPB AND KAAALX = PBALX AND KAAAVN = PBAVN
						INNER JOIN YHRTENT ON JDIPB = PBIPB AND JDALX = PBALX AND JDAVN = PBAVN' ;

	CALL SP_BUILDJOINYPAR ( 'INNER' , 'PRODU' , 'PBPER' , '' , ' AND TCOD = PBPER' , V_JOINYPAR ) ;
	SET V_QUERY = TRIM ( V_QUERY ) CONCAT ' ' CONCAT TRIM ( V_JOINYPAR ) ;

	SET V_QUERY = TRIM ( V_QUERY ) CONCAT ' INNER JOIN HPRSQ ON PBIPB = KABIPB AND PBALX = KABALX AND PBTYP = KABTYP AND PBAVN = KABAVN 
INNER JOIN HPOPTAP ON KDDIPB = KABIPB AND KDDALX = KABALX AND KDDTYP = KABTYP AND KDDAVN = KABAVN AND KDDRSQ = KABRSQ 
INNER JOIN HPFOR ON KDDIPB = KDAIPB AND KDDALX = KDAALX AND KDDTYP = KDATYP AND KDDFOR = KDAFOR AND KDDAVN = KDAAVN AND F.FOR = KDAFOR 
INNER JOIN HPOPT ON KDBKDAID = KDAID AND KDBOPT = 1 AND KDBAVN = KDAAVN 
LEFT JOIN HPOBSV ON KAAOBSF = KAJCHR AND KAAAVN = KAJAVN 
WHERE PBIPB = ''' CONCAT P_CODEOFFRE CONCAT ''' AND PBALX = ' CONCAT P_VERSION CONCAT ' AND PBTYP = ''' CONCAT P_TYPE CONCAT ''' AND PBAVN = ' CONCAT P_CODEAVENANT CONCAT '
ORDER BY KDACCH ' ;

PREPARE SQL_STATEMENT FROM V_QUERY ;
OPEN CURSORMNTREF ;

END P1  ;


