CREATE PROCEDURE SP_GETAVENANT ( 
	IN P_CODECONTRAT CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_CODEAVN INTEGER ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_GETAVENANT 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
DECLARE V_COUNTASSADD INTEGER DEFAULT 0 ; 

DECLARE CURINFOENTETE CURSOR FOR 
SELECT DESCRIPTIF , CODECONTRAT , VERSCONTRAT , TYPE , TYPECONTRAT , LIBTYPECONTRAT , CONTRATREMP , 
DATEEFFETA , DATEEFFETM , DATEEFFETJ , DATEEFFETJH , 
DATEACCORDA , DATEACCORDM , DATEACCORDJ , 
DATECRA , DATECRM , DATECRJ , 
CODECONTRATREMP , VERSCONTRATREMP , 
OBSERVATIONS , NUMCHRONOOSBV , 
CIBLE , CIBLELIB , 
BRANCHE , BRANCHELIB , 
SOUSBRANCHE , 
CATEGORIE , 
TYPEPOLICE , 
DEVISE , LIBDEVISE , 
CODEMOTSCLEF1 , CODEMOTSCLEF2 , CODEMOTSCLEF3 , 
PERIODICITECODE , PERIODICITENOM , 
ECHJOUR , ECHMOIS , 
PREAVIS , 
INDICEREFERENCE , LIBINDICE , 
INDEXATION , 
VALEUR , 
INTERCALAIREEXISTE , 
LCI , 
ASSIETTE , 
FRANCHISE , 
FINEFFETJOUR , FINEFFETMOIS , FINEFFETANNEE , FINEFFETHEURE , 
DUREEGARANTIE , UNITETEMPS , 
DATESTATISTIQUE , 
NATURECONTRAT , LIBELLENATURECONTRAT , 
PARTALBINGIA , 
APERITEURCODE , APERITEURNOM , 
FRAISAPERITION , 
COUVERTURE , 
SOUSCODE , SOUSNOM , 
GESCODE , GESNOM , 
COURTIERAPPORTEUR , NOMCOURTIERAPPO , VILLEAPPORTEUR , 
COURTIERGESTIONNAIRE , NOMCOURTIERGEST , REFCOURTIER , VILLEGESTIONNAIRE , 
COURTIERPAYEUR , NOMCOURTIERPAYEUR , VILLEPAYEUR , 
CODEINTERLOCUTEUR , NOMINTERLOCUTEUR , 
NOMPRENASSUR , CODEPRENASSUR , PRENEURESTASSURE , 
DEPASSUR , CODEPOSTALASSUR , VILLEASSUR , 
ETAT , SITUATION , LIBETAT , LIBSITUATION , 
ADRESSECONTRAT , 
CODEENCAISSEMENT , LIBENCAISSEMENT , 
NUMINTERNEAVENANT , DATEEFFETAVNJOUR , DATEEFFETAVNMOIS , DATEEFFETAVNANNEE , 
										NUMAVENANT , HEUREAVN , MOTIFAVN , LIBMOTIFAVN , 
CODEOFFREORIGINE , VERSIONOFFREORIGINE , 
CODEREGIME , LIBREGIME , 
SOUMISCATNAT , MONTANTREF1 , MONTANTREF2 , 
PROCHECHJ , PROCHECHM , PROCHECHA , 
HORSCATNAT , CATNAT , TAUXHORSCATNAT , TAUXCATNAT , 
DATEDEBDERNIEREPERIODEJOUR , DATEDEBDERNIEREPERIODEMOIS , DATEDEBDERNIEREPERIODEANNEE , 
DATEFINDERNIEREPERIODEJOUR , DATEFINDERNIEREPERIODEMOIS , DATEFINDERNIEREPERIODEANNEE , 
ZONESTOP , 
DATEAFFAIRENOUVELLEJOUR , DATEAFFAIRENOUVELLEMOIS , DATEAFFAIRENOUVELLEANNEE , 
CODEACTION , LIBACTION , 
DATESITJOUR , DATESITMOIS , DATESITANNEE , 
DATECRJOUR , DATECRMOIS , DATECRANNEE , UCRCODE , UCRNOM , 
DATEUPJOUR , DATEUPMOIS , DATEUPANNEE , UUPCODE , UUPNOM , 
										ANTECEDENT , DESCRIPTION , DESCRAVENANT , 
										PARTAPERITEUR , IDINTERLOCUTEURAPE , LIBINTERLOCUTEURAPE , REFERENCEAPERITEUR , FRAISACCAPERITEUR , COMMISSIONAPERITEUR , 
										TYPERETOUR , LIBRETOUR , PARTBENEF , ( SELECT COUNT ( * ) 
FROM YPOBASE 
INNER JOIN YPOASSU ON PBIPB = PCIPB AND PBALX = PCALX AND PBTYP = PCTYP AND PBIAS <> PCIAS 
WHERE PBIPB  = P_CODECONTRAT AND PBALX = P_VERSION AND PBTYP = P_TYPE 
) NBASSUADD , 
( SELECT COUNT ( * ) FROM KPOPP WHERE  KFPIPB =  CODECONTRAT  AND KFPALX = P_VERSION AND KFPTYP = P_TYPE ) NBOPPBENEF ,
REGULEID , LTA
FROM V_INFOENTETECTRAVN 
WHERE TYPE = P_TYPE AND VERSCONTRAT = P_VERSION AND CODECONTRAT  = P_CODECONTRAT ; 
  
SET P_CODECONTRAT = F_PADLEFT ( 9 , TRIM ( P_CODECONTRAT ) ) ;

OPEN CURINFOENTETE ; 
  
  
END P1  ; 
  

