CREATE PROCEDURE SP_GETLISTRSQREGULECONSULT ( 
	IN P_REGULEID INTEGER , 
	IN P_LOTID INTEGER ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_GETLISTRSQREGULECONSULT 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
			DECLARE CURSORRSQ CURSOR FOR	 
		SELECT JERSQ CODERSQ , KABDESC LIBRSQ , GUGRSQ . KHXDEBP DATEDEBRSQ , GUGRSQ . KHXFINP DATEFINRSQ , KABCIBLE CIBLERSQ , KCIBLERSQ . KAHDESC LIBCIBLERSQ , JERUT TYPEREGULRSQ , IFNULL ( YPARRSQ . TPLIL , '' ) LIBREGULRSQ , 
			JGOBJ CODEOBJ , KACDESC LIBOBJ , SELOBJ . KHVDEB DATEDEBOBJ , SELOBJ . KHVFIN DATEFINOBJ , KACCIBLE CIBLEOBJ , KCIBLEOBJ . KAHDESC LIBCIBLEOBJ , JGRUT TYPREGULOBJ , IFNULL ( YPAROBJ . TPLIL , '' ) LIBREGULOBJ , 
			( SELECT COUNT ( * ) FROM KPRGUG WHERE KHXIPB = GUGRSQ . KHXIPB AND KHXALX = GUGRSQ . KHXALX AND KHXTYP = GUGRSQ . KHXTYP AND KHXRSQ = GUGRSQ . KHXRSQ AND KHXKHWID = P_REGULEID AND KHXSIT = 'V' ) ISRSQUSED 
		FROM KPRGUG GUGRSQ 
			INNER JOIN YPRTRSQ ON GUGRSQ . KHXIPB = JEIPB AND GUGRSQ . KHXALX = JEALX AND GUGRSQ . KHXRSQ = JERSQ 
			INNER JOIN KPRSQ ON JEIPB = KABIPB AND JEALX = KABALX AND JERSQ = KABRSQ 
			LEFT JOIN YYYYPAR YPARRSQ ON YPARRSQ . TCON = 'PRODU' AND YPARRSQ . TFAM = 'JERUT' AND YPARRSQ . TCOD = JERUT 
			INNER JOIN KPSELW SELOBJ ON P_LOTID = SELOBJ . KHVID AND GUGRSQ . KHXRSQ = SELOBJ . KHVRSQ AND SELOBJ . KHVPERI = 'OB' 
			INNER JOIN YPRTOBJ ON SELOBJ . KHVIPB = JGIPB AND SELOBJ . KHVALX = JGALX AND SELOBJ . KHVRSQ = JGRSQ AND SELOBJ . KHVOBJ = JGOBJ 
			INNER JOIN KPOBJ ON JGIPB = KACIPB AND JGALX = KACALX AND JGRSQ = KACRSQ AND JGOBJ = KACOBJ 
			INNER JOIN KCIBLE KCIBLERSQ ON KCIBLERSQ . KAHCIBLE = KABCIBLE 
			INNER JOIN KCIBLE KCIBLEOBJ ON KCIBLEOBJ . KAHCIBLE = KACCIBLE 
			LEFT JOIN YYYYPAR YPAROBJ ON YPAROBJ . TCON = 'PRODU' AND YPAROBJ . TFAM = 'JERUT' AND YPAROBJ . TCOD = JGRUT 
		WHERE GUGRSQ . KHXKHWID = P_REGULEID 
		ORDER BY GUGRSQ . KHXRSQ , SELOBJ . KHVOBJ ; 
		 
		OPEN CURSORRSQ ; 
END P1  ; 
  

  

