CREATE PROCEDURE SP_GTCPVIL ( 
	IN P_MODE CHAR(20) , 
	IN P_VALUE CHAR(50) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_GTCPVIL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
DECLARE V_QUERY VARCHAR ( 8000 ) DEFAULT '' ; 
DECLARE V_WHERE VARCHAR ( 8000 ) DEFAULT '' ; 
DECLARE CURSOR1 CURSOR WITH RETURN FOR SQL_STATEMENT ; 
  
IF ( TRIM ( P_MODE ) = 'CP' ) THEN 
SET V_QUERY = 'SELECT ABLCPO CP, ABLLIB VILLE FROM GENERALE.YHEXLOC WHERE LOWER(ABLCPO) LIKE ''' CONCAT LOWER ( TRIM ( P_VALUE ) ) CONCAT '%'' ORDER BY ABLCPO FETCH FIRST 100 ROWS ONLY' ; 
END IF ; 
  
IF ( TRIM ( P_MODE ) = 'VILLE' ) THEN 
SET V_QUERY = 'SELECT DISTINCT ABLLIB VILLE FROM GENERALE.YHEXLOC WHERE ' CONCAT P_VALUE CONCAT ' ORDER BY ABLLIB FETCH FIRST 100 ROWS ONLY' ; 
END IF ; 
  
PREPARE SQL_STATEMENT FROM V_QUERY ; 
OPEN CURSOR1 ; 
  
END P1  ; 
  

  

