CREATE PROCEDURE SP_GETCOTITABPARTALB ( 
	IN P_CODE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_MODEAFF CHAR(4) , 
	IN P_NUMVISU INTEGER , 
	IN P_ACTEGESTION CHAR(5) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_GETCOTITABPARTALB 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
	 
DECLARE CURSORCOTI CURSOR FOR 
		SELECT 'PartAlb' TYPEVALEUR , IFNULL ( PBAPP , 0 ) PARTALBINGIA , 
				'' CODEGARANTIE , '' LIBELLEGARANTIE , 0 GARHCATNAT , 0 GARCATNAT , 
				0 COMMTAUXHCATNAT , 0 COMMTAUXCATNAT , 0 COMMVALHCATNAT , 
				0 COMMVALCATNAT , 0 FRAISAPERITION , 0 COASSHTHCATNAT , 0 COASSHTCATNAT , 0 COASSCOMMHCATNAT , 0 COASSCOMMCATNAT 
		FROM YPOBASE 
		WHERE TRIM ( PBIPB ) = TRIM ( P_CODE ) AND PBALX = P_VERSION AND PBTYP = P_TYPE 
	UNION ALL 
		SELECT 'Garantie' TYPEVALEUR , 0 PARTALBINGIA , 
		PLGAR CODEGARANTIE , 
		GADES LIBELLEGARANTIE , 
		CAST ( IFNULL ( PLKHT , 0 ) AS DECIMAL ( 11 , 2 ) ) GARHCATNAT , 
		CAST ( IFNULL ( KVKNH , 0 ) AS DECIMAL ( 11 , 2 ) ) GARCATNAT , 0 COMMTAUXHCATNAT , 0 COMMTAUXCATNAT , 0 COMMVALHCATNAT , 
		0 COMMVALCATNAT , 0 FRAISAPERITION , 0 COASSHTHCATNAT , 0 COASSHTCATNAT , 0 COASSCOMMHCATNAT , 0 COASSCOMMCATNAT 
		FROM YPRIPGA 
		INNER JOIN YGARANT ON GAGAR = PLGAR 
		LEFT JOIN YPRIPGK ON KVIPB = PLIPB AND KVALX = PLALX AND KVTYE = PLTYE AND KVGAR = PLGAR 
		WHERE TRIM ( PLIPB ) = TRIM ( P_CODE ) AND PLALX = P_VERSION AND PLTYE = '1' 
	UNION ALL 
		SELECT 'Commission' TYPEVALEUR , 0 PARTALBINGIA , '' CODEGARANTIE , '' LIBELLEGARANTIE , 0 GARHCATNAT , 0 GARCATNAT , 
		CAST ( IFNULL ( PKCOM , 0 ) AS DECIMAL ( 5 , 2 ) ) COMMTAUXHCATNAT , 
		CAST ( IFNULL ( PKCNC , 0 ) AS DECIMAL ( 5 , 2 ) ) COMMTAUXCATNAT , 
		CAST ( IFNULL ( POKCO , 0 ) AS DECIMAL ( 11 , 2 ) ) COMMVALHCATNAT , 
		CAST ( IFNULL ( POKNM , 0 ) AS DECIMAL ( 11 , 2 ) ) COMMVALCATNAT , 
		0 FRAISAPERITION , 0 COASSHTHCATNAT , 0 COASSHTCATNAT , 0 COASSCOMMHCATNAT , 0 COASSCOMMCATNAT 
		FROM YPRIPES 
		LEFT JOIN YPRIPPA ON PKIPB = POIPB AND PKALX = POALX 
		WHERE TRIM ( POIPB ) = TRIM ( P_CODE ) AND POALX = P_VERSION AND POTYE = '1' 
	UNION ALL 
		SELECT 'PartCoassurance' TYPEVALEUR , 0 PARTALBINGIA , '' CODEGARANTIE , '' LIBELLEGARANTIE , 0 GARHCATNAT , 0 GARCATNAT , 0 COMMTAUXHCATNAT , 0 COMMTAUXCATNAT , 0 COMMVALHCATNAT , 0 COMMVALCATNAT , 
		CAST ( IFNULL ( SUM ( POKAP ) , 0 ) AS DECIMAL ( 11 , 2 ) ) FRAISAPERITION , 
		CAST ( IFNULL ( SUM ( POKHT ) - SUM ( POKNH ) , 0 ) AS DECIMAL ( 11 , 2 ) ) COASSHTHCATNAT , 
		CAST ( IFNULL ( SUM ( POKNH ) , 0 ) AS DECIMAL ( 11 , 2 ) ) COASSHTCATNAT , 
		CAST ( IFNULL ( SUM ( POKCO ) , 0 ) AS DECIMAL ( 11 , 2 ) ) COASSCOMMHCATNAT , 
		CAST ( IFNULL ( SUM ( POKNM ) , 0 ) AS DECIMAL ( 11 , 2 ) ) COASSCOMMCATNAT 
		FROM YPRIPPA 
		WHERE TRIM ( POIPB ) = TRIM ( P_CODE ) AND POALX = P_VERSION AND POTYE = '2' ; 
  
DECLARE CURSORCOTI2 CURSOR FOR		 
		SELECT 'PartAlb' TYPEVALEUR , IFNULL ( PBAPP , 0 ) PARTALBINGIA , 
				'' CODEGARANTIE , '' LIBELLEGARANTIE , 0 GARHCATNAT , 0 GARCATNAT , 
				0 COMMTAUXHCATNAT , 0 COMMTAUXCATNAT , 0 COMMVALHCATNAT , 
				0 COMMVALCATNAT , 0 FRAISAPERITION , 0 COASSHTHCATNAT , 0 COASSHTCATNAT , 0 COASSCOMMHCATNAT , 0 COASSCOMMCATNAT 
		FROM YPOBASE 
		WHERE TRIM ( PBIPB ) = TRIM ( P_CODE ) AND PBALX = P_VERSION AND PBTYP = P_TYPE 
	UNION ALL 
		SELECT 'Garantie' TYPEVALEUR , 0 PARTALBINGIA , 
		PLGAR CODEGARANTIE , 
		GADES LIBELLEGARANTIE , 
		CAST ( IFNULL ( PLKHT , 0 ) AS DECIMAL ( 11 , 2 ) ) GARHCATNAT , 
		CAST ( IFNULL ( KVKNH , 0 ) AS DECIMAL ( 11 , 2 ) ) GARCATNAT , 0 COMMTAUXHCATNAT , 0 COMMTAUXCATNAT , 0 COMMVALHCATNAT , 
		0 COMMVALCATNAT , 0 FRAISAPERITION , 0 COASSHTHCATNAT , 0 COASSHTCATNAT , 0 COASSCOMMHCATNAT , 0 COASSCOMMCATNAT 
		FROM YPRIMGA 
		INNER JOIN YGARANT ON GAGAR = PLGAR 
		LEFT JOIN YPRIPGK ON KVIPB = PLIPB AND KVALX = PLALX AND KVTYE = PLTYE AND KVGAR = PLGAR 
		WHERE TRIM ( PLIPB ) = TRIM ( P_CODE ) AND PLALX = P_VERSION AND PLTYE = '1' AND PLIPK = P_NUMVISU 
	UNION ALL 
		SELECT 'Commission' TYPEVALEUR , 0 PARTALBINGIA , '' CODEGARANTIE , '' LIBELLEGARANTIE , 0 GARHCATNAT , 0 GARCATNAT , 
		CAST ( IFNULL ( PKCOM , 0 ) AS DECIMAL ( 5 , 2 ) ) COMMTAUXHCATNAT , 
		CAST ( IFNULL ( PKCNC , 0 ) AS DECIMAL ( 5 , 2 ) ) COMMTAUXCATNAT , 
		CAST ( IFNULL ( POKCO , 0 ) AS DECIMAL ( 11 , 2 ) ) COMMVALHCATNAT , 
		CAST ( IFNULL ( POKNM , 0 ) AS DECIMAL ( 11 , 2 ) ) COMMVALCATNAT , 
		0 FRAISAPERITION , 0 COASSHTHCATNAT , 0 COASSHTCATNAT , 0 COASSCOMMHCATNAT , 0 COASSCOMMCATNAT 
		FROM YPRIMES 
		LEFT JOIN YPRIMPA ON PKIPB = POIPB AND PKALX = POALX AND PKIPK = POIPK 
		WHERE TRIM ( POIPB ) = TRIM ( P_CODE ) AND POALX = P_VERSION AND POTYE = '1' AND PKIPK = P_NUMVISU 
	UNION ALL 
		SELECT 'PartCoassurance' TYPEVALEUR , 0 PARTALBINGIA , '' CODEGARANTIE , '' LIBELLEGARANTIE , 0 GARHCATNAT , 0 GARCATNAT , 0 COMMTAUXHCATNAT , 0 COMMTAUXCATNAT , 0 COMMVALHCATNAT , 0 COMMVALCATNAT , 
		CAST ( IFNULL ( SUM ( POKAP ) , 0 ) AS DECIMAL ( 11 , 2 ) ) FRAISAPERITION , 
		CAST ( IFNULL ( SUM ( POKHT ) - SUM ( POKNH ) , 0 ) AS DECIMAL ( 11 , 2 ) ) COASSHTHCATNAT , 
		CAST ( IFNULL ( SUM ( POKNH ) , 0 ) AS DECIMAL ( 11 , 2 ) ) COASSHTCATNAT , 
		CAST ( IFNULL ( SUM ( POKCO ) , 0 ) AS DECIMAL ( 11 , 2 ) ) COASSCOMMHCATNAT , 
		CAST ( IFNULL ( SUM ( POKNM ) , 0 ) AS DECIMAL ( 11 , 2 ) ) COASSCOMMCATNAT 
		FROM YPRIMPA 
		WHERE TRIM ( POIPB ) = TRIM ( P_CODE ) AND POALX = P_VERSION AND POTYE = '2' AND POIPK = P_NUMVISU ;	 
  
DECLARE CURSORCOTI3 CURSOR FOR 
		SELECT 'PartAlb' TYPEVALEUR , IFNULL ( PBAPP , 0 ) PARTALBINGIA , 
				'' CODEGARANTIE , '' LIBELLEGARANTIE , 0 GARHCATNAT , 0 GARCATNAT , 
				0 COMMTAUXHCATNAT , 0 COMMTAUXCATNAT , 0 COMMVALHCATNAT , 
				0 COMMVALCATNAT , 0 FRAISAPERITION , 0 COASSHTHCATNAT , 0 COASSHTCATNAT , 0 COASSCOMMHCATNAT , 0 COASSCOMMCATNAT 
		FROM YPOBASE 
		WHERE TRIM ( PBIPB ) = TRIM ( P_CODE ) AND PBALX = P_VERSION AND PBTYP = P_TYPE 
	UNION ALL 
		SELECT 'Garantie' TYPEVALEUR , 0 PARTALBINGIA , 
		PLGAR CODEGARANTIE , 
		GADES LIBELLEGARANTIE , 
		CAST ( IFNULL ( PLKHT , 0 ) AS DECIMAL ( 11 , 2 ) ) GARHCATNAT , 
		CAST ( IFNULL ( KVKNH , 0 ) AS DECIMAL ( 11 , 2 ) ) GARCATNAT , 0 COMMTAUXHCATNAT , 0 COMMTAUXCATNAT , 0 COMMVALHCATNAT , 
		0 COMMVALCATNAT , 0 FRAISAPERITION , 0 COASSHTHCATNAT , 0 COASSHTCATNAT , 0 COASSCOMMHCATNAT , 0 COASSCOMMCATNAT 
		FROM YPRIRGA 
		INNER JOIN YGARANT ON GAGAR = PLGAR 
		LEFT JOIN YPRIRGK ON KVIPB = PLIPB AND KVALX = PLALX AND KVTYE = PLTYE AND KVGAR = PLGAR 
		WHERE TRIM ( PLIPB ) = TRIM ( P_CODE ) AND PLALX = P_VERSION AND PLTYE = '1' 
	UNION ALL 
		SELECT 'Commission' TYPEVALEUR , 0 PARTALBINGIA , '' CODEGARANTIE , '' LIBELLEGARANTIE , 0 GARHCATNAT , 0 GARCATNAT , 
		CAST ( IFNULL ( PKCOM , 0 ) AS DECIMAL ( 5 , 2 ) ) COMMTAUXHCATNAT , 
		CAST ( IFNULL ( PKCNC , 0 ) AS DECIMAL ( 5 , 2 ) ) COMMTAUXCATNAT , 
		CAST ( IFNULL ( POKCO , 0 ) AS DECIMAL ( 11 , 2 ) ) COMMVALHCATNAT , 
		CAST ( IFNULL ( POKNM , 0 ) AS DECIMAL ( 11 , 2 ) ) COMMVALCATNAT , 
		0 FRAISAPERITION , 0 COASSHTHCATNAT , 0 COASSHTCATNAT , 0 COASSCOMMHCATNAT , 0 COASSCOMMCATNAT 
		FROM YPRIRES 
		LEFT JOIN YPRIRPA ON PKIPB = POIPB AND PKALX = POALX 
		WHERE TRIM ( POIPB ) = TRIM ( P_CODE ) AND POALX = P_VERSION AND POTYE = '1' 
	UNION ALL 
		SELECT 'PartCoassurance' TYPEVALEUR , 0 PARTALBINGIA , '' CODEGARANTIE , '' LIBELLEGARANTIE , 0 GARHCATNAT , 0 GARCATNAT , 0 COMMTAUXHCATNAT , 0 COMMTAUXCATNAT , 0 COMMVALHCATNAT , 0 COMMVALCATNAT , 
		CAST ( IFNULL ( SUM ( POKAP ) , 0 ) AS DECIMAL ( 11 , 2 ) ) FRAISAPERITION , 
		CAST ( IFNULL ( SUM ( POKHT ) - SUM ( POKNH ) , 0 ) AS DECIMAL ( 11 , 2 ) ) COASSHTHCATNAT , 
		CAST ( IFNULL ( SUM ( POKNH ) , 0 ) AS DECIMAL ( 11 , 2 ) ) COASSHTCATNAT , 
		CAST ( IFNULL ( SUM ( POKCO ) , 0 ) AS DECIMAL ( 11 , 2 ) ) COASSCOMMHCATNAT , 
		CAST ( IFNULL ( SUM ( POKNM ) , 0 ) AS DECIMAL ( 11 , 2 ) ) COASSCOMMCATNAT 
		FROM YPRIRPA 
		WHERE TRIM ( POIPB ) = TRIM ( P_CODE ) AND POALX = P_VERSION AND POTYE = '2' ; 
  
  
IF ( P_MODEAFF <> 'Visu' ) THEN 
	IF ( TRIM ( P_ACTEGESTION ) = 'AVNRG' OR TRIM ( P_ACTEGESTION ) = 'REGUL' ) THEN 
		OPEN CURSORCOTI3 ; 
	ELSE 
		OPEN CURSORCOTI ; 
	END IF ; 
ELSE 
	OPEN CURSORCOTI2 ; 
END IF ; 
END P1  ; 
  

  

