
CREATE PROCEDURE SP_HCOPYEXTRAKHEOTBL (
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_AVN INTEGER , 
	IN P_HIN INTEGER ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_HCOPYEXTRAKHEOTBL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	DBGVIEW = *SOURCE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
P1 : BEGIN ATOMIC  

	-- YPRTAVT -- 
	INSERT INTO YHRTAVT 
	( KHIPB , KHALX , KHAVN , KHHIN , KHCHA , KHRSQ , KHOBJ , KHFOR , KHCHI , KHCTX , KHACT , KHANV , KHNVV , KHCGN , KHAVO , KHOPE , KHCHR ) 
	( SELECT KHIPB , KHALX , CAST ( P_AVN AS DECIMAL(3, 0) ) , CAST ( P_HIN AS DECIMAL(3, 0) ) , KHCHA , KHRSQ , KHOBJ , KHFOR , KHCHI , KHCTX , KHACT , KHANV , KHNVV , KHCGN , KHAVO , KHOPE , KHCHR 
	FROM YPRTAVT WHERE KHIPB = P_CODEOFFRE AND KHALX = P_VERSION ) ; 
	-- YORTCLA -- 
	INSERT INTO YHRTCLA 
	( QEIPB , QEALX , QEAVN , QEHIN , QECHA , QERSQ , QEOBJ , QEFOR , QEOPT , QEGAR , QEOSP , QECTX , QECAR , QECLA , QEIMA , QENTA , QEIL1 , QEIL2 , 
	QEIL3 , QEIL4 , QEIL5 , QEIL6 , QEIL7 , QEIL8 , QEIL9 , QEVER , QEHIA , QEHIM , QEHIJ , QEHIH , QEIMP , QETOP , QEAJT , QECLM , QETVL , QETXL , 
	QEORI , QENAT , QERCP , QETAE , QEDSP , QECHI , QECXI , QECHR , QEAVG , QEAIM , QESPA ) 
	( SELECT QEIPB , QEALX , CAST ( P_AVN AS DECIMAL(3, 0) ) , CAST ( P_HIN AS DECIMAL(3, 0) ) , QECHA , QERSQ , QEOBJ , QEFOR , QEOPT , QEGAR , QEOSP , QECTX , QECAR , QECLA , QEIMA , QENTA , QEIL1 , QEIL2 , 
	QEIL3 , QEIL4 , QEIL5 , QEIL6 , QEIL7 , QEIL8 , QEIL9 , QEVER , QEHIA , QEHIM , QEHIJ , QEHIH , QEIMP , QETOP , QEAJT , QECLM , QETVL , QETXL , 
	QEORI , QENAT , QERCP , QETAE , QEDSP , QECHI , QECXI , QECHR , QEAVG , QEAIM , QESPA 
	FROM YORTCLA WHERE QEIPB = P_CODEOFFRE AND QEALX = P_VERSION ) ; 
	-- YORTCLV -- 
	INSERT INTO YHRTCLV 
	( QFIPB , QFALX , QFAVN , QFHIN , QFILR , QFVAV ) 
	( SELECT QFIPB , QFALX , CAST ( P_AVN AS DECIMAL(3, 0) ) , CAST ( P_HIN AS DECIMAL(3, 0) ) , QFILR , QFVAV 
	FROM YORTCLV WHERE QFIPB = P_CODEOFFRE AND QFALX = P_VERSION ) ; 
	-- YPRTDES -- 
	INSERT INTO YHRTDES 
	( JIIPB , JIALX , JIAVN , JIHIN , JIOJR , JIRSQ , JIOBJ , JIORD , JILDS ) 
	( SELECT JIIPB , JIALX , CAST ( P_AVN AS DECIMAL(3, 0) ) , CAST ( P_HIN AS DECIMAL(3, 0) ) , JIOJR , JIRSQ , JIOBJ , JIORD , JILDS 
	FROM YPRTDES WHERE JIIPB = P_CODEOFFRE AND JIALX = P_VERSION ) ; 
	-- YPRTFNC -- 
	INSERT INTO YHRTFNC 
	( JNIPB , JNALX , JNAVN , JNHIN , JNRSQ , JNOBJ , JNOBP , JNMFI , JNMFR , JNMFB , JNMFA , JNMFM , JNMFJ , JNMFV , JNMFU , JNMFT , JNREL ) 
	( SELECT JNIPB , JNALX , CAST ( P_AVN AS DECIMAL(3, 0) ) , CAST ( P_HIN AS DECIMAL(3, 0) ) , JNRSQ , JNOBJ , JNOBP , JNMFI , JNMFR , JNMFB , JNMFA , JNMFM , JNMFJ , JNMFV , JNMFU , JNMFT , JNREL 
	FROM YPRTFNC WHERE JNIPB = P_CODEOFFRE AND JNALX = P_VERSION ) ; 
	-- YPRTFOR -- 
	INSERT INTO YHRTFOR 
	( JOIPB , JOALX , JOAVN , JOHIN , JORSQ , JOFOR , JODES , JOCCH , JOFRV , JOFSP , JORLE , JOACQ , JOTMC , JOTFF , JOTFP , JOPRO , JOTMI , JOTFM , 
	JOTMA , JOTMG , JOCMC , JOCFO , JOCHT , JOCTT , JOCCP , JOCPA , JOVAL , JOVAA , JOVAW , JOVAT , JOVAU , JOVAH , JOIVO , JOIVA , JOIVW , JOAVE , 
	JOAVA , JOAVM , JOAVJ , JOPAQ , JOEHH , JOEHC , JOEHI , JOCOS , JOTQU ) 
	( SELECT JOIPB , JOALX , CAST ( P_AVN AS DECIMAL(3, 0) ) , CAST ( P_HIN AS DECIMAL(3, 0) ) , JORSQ , JOFOR , JODES , JOCCH , JOFRV , JOFSP , JORLE , JOACQ , JOTMC , JOTFF , JOTFP , JOPRO , JOTMI , JOTFM , 
	JOTMA , JOTMG , JOCMC , JOCFO , JOCHT , JOCTT , JOCCP , JOCPA , JOVAL , JOVAA , JOVAW , JOVAT , JOVAU , JOVAH , JOIVO , JOIVA , JOIVW , JOAVE , 
	JOAVA , JOAVM , JOAVJ , JOPAQ , JOEHH , JOEHC , JOEHI , JOCOS , JOTQU 
	FROM YPRTFOR WHERE JOIPB = P_CODEOFFRE AND JOALX = P_VERSION ) ; 
	-- YPRTFOO -- 
	INSERT INTO YHRTFOO 
	( JPIPB , JPALX , JPAVN , JPHIN , JPRSQ , JPFOR , JPOBJ ) 
	( SELECT JPIPB , JPALX , CAST ( P_AVN AS DECIMAL(3, 0) ) , CAST ( P_HIN AS DECIMAL(3, 0) ) , JPRSQ , JPFOR , JPOBJ 
	FROM YPRTFOO WHERE JPIPB = P_CODEOFFRE AND JPALX = P_VERSION ) ; 
	-- YPRTFRH -- 
	INSERT INTO YHRTFRH 
	( JJIPB , JJALX , JJAVN , JJHIN , JJFHE , JJORD , JJFHV , JJFHU , JJDEV , JJIND , JJFHB , JJMIN , JJMAX , JJLID , JJLIF ) 
	( SELECT JJIPB , JJALX , CAST ( P_AVN AS DECIMAL(3, 0) ) , CAST ( P_HIN AS DECIMAL(3, 0) ) , JJFHE , JJORD , JJFHV , JJFHU , JJDEV , JJIND , JJFHB , JJMIN , JJMAX , JJLID , JJLIF 
	FROM YPRTFRH WHERE JJIPB = P_CODEOFFRE AND JJALX = P_VERSION ) ; 
	-- YPRTFRT -- 
	INSERT INTO YHRTFRT 
	( JLIPB , JLALX , JLAVN , JLHIN , JLFHE , JLORD , JLTXT ) 
	( SELECT JLIPB , JLALX , CAST ( P_AVN AS DECIMAL(3, 0) ) , CAST ( P_HIN AS DECIMAL(3, 0) ) , JLFHE , JLORD , JLTXT 
	FROM YPRTFRT WHERE JLIPB = P_CODEOFFRE AND JLALX = P_VERSION ) ; 
	-- YPRTGAA -- 
	INSERT INTO YHRTGAA 
	( JRIPB , JRALX , JRAVN , JEHIN , JRRSQ , JRFOR , JRGAR , JRTRT , JRAPC , JRAPA , JRAPM , JRAPJ , JRLCV , JRLCU , JRLCE , JRLOV , JRLOU , JRLOE , JRFHV , 
	JRFHU , JRFHE , JRPRV , JRPRU , JRPRG , JRTRA , JRTRM , JRTRJ , JRTRU ) 
	( SELECT JRIPB , JRIPB , CAST ( P_AVN AS DECIMAL(3, 0) ) , CAST ( P_HIN AS DECIMAL(3, 0) ) , JRRSQ , JRFOR , JRGAR , JRTRT , JRAPC , JRAPA , JRAPM , JRAPJ , JRLCV , JRLCU , JRLCE , JRLOV , JRLOU , JRLOE , JRFHV , 
	JRFHU , JRFHE , JRPRV , JRPRU , JRPRG , JRTRA , JRTRM , JRTRJ , JRTRU 
	FROM YPRTGAA WHERE JRIPB = P_CODEOFFRE AND JRALX = P_VERSION ) ; 
	-- YPRTGAR -- 
	INSERT INTO YHRTGAR 
	( JHIPB , JHALX , JHAVN , JHHIN , JHRSQ , JHFOR , JHGAP , JHGAR , JHCAR , JHNAT , JHGAN , JHOBN , JHOB1 , JHOB2 , JHOB3 , JHOB4 , JHOB5 , JHGAV , JHRQV , 
	JHFOV , JHREP , JHTAX , JHLCV , JHLCA , JHLCW , JHLCU , JHLCE , JHLC1 , JHLC2 , JHLC3 , JHLC4 , JHLC5 , JHLOV , JHLOA , JHLOW , JHLOU , JHLOE , JHASV , 
	JHASA , JHASW , JHASU , JHASN , JHFHV , JHFHA , JHFHW , JHFHU , JHFHE , JHPRV , JHPRA , JHPRW , JHPRU , JHPRP , JHPRE , JHPRF , JHCNA , JHINA , JHEFA , 
	JHEFM , JHEFJ , JHEFH , JHFEA , JHFEM , JHFEJ , JHFEH , JHEFD , JHEFU , JHTMC , JHTFF , JHCMC , JHCHT , JHCTT , JHAJT , JHDFG , JHIFC , JHCDA , JHCDM , 
	JHCDJ , JHCFA , JHCFM , JHCFJ , JHAVE , JHAVF ) 
	( SELECT JHIPB , JHALX , CAST ( P_AVN AS DECIMAL(3, 0) ) , CAST ( P_HIN AS DECIMAL(3, 0) ) , JHRSQ , JHFOR , JHGAP , JHGAR , JHCAR , JHNAT , JHGAN , JHOBN , JHOB1 , JHOB2 , JHOB3 , JHOB4 , JHOB5 , JHGAV , JHRQV , 
	JHFOV , JHREP , JHTAX , JHLCV , JHLCA , JHLCW , JHLCU , JHLCE , JHLC1 , JHLC2 , JHLC3 , JHLC4 , JHLC5 , JHLOV , JHLOA , JHLOW , JHLOU , JHLOE , JHASV , 
	JHASA , JHASW , JHASU , JHASN , JHFHV , JHFHA , JHFHW , JHFHU , JHFHE , JHPRV , JHPRA , JHPRW , JHPRU , JHPRP , JHPRE , JHPRF , JHCNA , JHINA , JHEFA , 
	JHEFM , JHEFJ , JHEFH , JHFEA , JHFEM , JHFEJ , JHFEH , JHEFD , JHEFU , JHTMC , JHTFF , JHCMC , JHCHT , JHCTT , JHAJT , JHDFG , JHIFC , JHCDA , JHCDM , 
	JHCDJ , JHCFA , JHCFM , JHCFJ , JHAVE , JHAVF 
	FROM YPRTGAR WHERE JHIPB = P_CODEOFFRE AND JHALX = P_VERSION ) ; 
	-- YPRTGAV -- 
	INSERT INTO YHRTGAV 
	( JQIPB , JQALX , JQAVN , JQHIN , JQRSQ , JQFOR , JQGAR , JQRQH , JQOBH , JQFOH , JQNAT ) 
	( SELECT JQIPB , JQALX , CAST ( P_AVN AS DECIMAL(3, 0) ) , CAST ( P_HIN AS DECIMAL(3, 0) ) , JQRSQ , JQFOR , JQGAR , JQRQH , JQOBH , JQFOH , JQNAT 
	FROM YPRTGAV WHERE JQIPB = P_CODEOFFRE AND JQALX = P_VERSION ) ; 
	-- YPRTLCI -- 
	INSERT INTO YHRTLCI 
	( JKIPB , JKALX , JKAVN , JKHIN , JKLCE , JKORD , JKLCV , JKLCU , JKDEV , JKLCB , JKLOV , JKLOU , JKLOB ) 
	( SELECT JKIPB , JKALX , CAST ( P_AVN AS DECIMAL(3, 0) ) , CAST ( P_HIN AS DECIMAL(3, 0) ) , JKLCE , JKORD , JKLCV , JKLCU , JKDEV , JKLCB , JKLOV , JKLOU , JKLOB 
	FROM YPRTLCI WHERE JKIPB = P_CODEOFFRE AND JKALX = P_VERSION ) ; 
	-- YPRTLCT -- 
	INSERT INTO YHRTLCT 
	( JMIPB , JMALX , JMAVN , JMHIN , JMLCE , JMORD , JMTXT ) 
	( SELECT JMIPB , JMALX , CAST ( P_AVN AS DECIMAL(3, 0) ) , CAST ( P_HIN AS DECIMAL(3, 0) ) , JMLCE , JMORD , JMTXT 
	FROM YPRTLCT WHERE JMIPB = P_CODEOFFRE AND JMALX = P_VERSION ) ; 
	-- YPRTOBT -- 
	INSERT INTO YHRTOBT 
	( KFIPB , KFALX , KFAVN , KFHIN , KFRSQ , KFOBJ , KFDUV , KFDUU , KFDDA , KFDDM , KFDDJ , KFDFA , KFDFM , KFDFJ , KFESV , KFESU , KFEDA , KFEDM , KFEDJ , 
	KFEFA , KFEFM , KFEFJ , KFTDF ) 
	( SELECT KFIPB , KFALX , CAST ( P_AVN AS DECIMAL(3, 0) ) , CAST ( P_HIN AS DECIMAL(3, 0) ) , KFRSQ , KFOBJ , KFDUV , KFDUU , KFDDA , KFDDM , KFDDJ , KFDFA , KFDFM , KFDFJ , KFESV , KFESU , KFEDA , KFEDM , KFEDJ , 
	KFEFA , KFEFM , KFEFJ , KFTDF 
	FROM YPRTOBT WHERE KFIPB = P_CODEOFFRE AND KFALX = P_VERSION ) ; 
	-- KWADR -- 
	INSERT INTO HWADR 
	( W3ORI , W3IDORI , W3TYP , W3IPB , W3ALX , W3AVN , W3HIN , W3NOM , W3AD1 , W3AD2 , W3COM , W3VIL , W3PAY ) 
	( SELECT W3ORI , W3IDORI , W3TYP , W3IPB , W3ALX , CAST ( P_AVN AS DECIMAL(3, 0) ) , CAST ( P_HIN AS DECIMAL(3, 0) ) , W3NOM , W3AD1 , W3AD2 , W3COM , W3VIL , W3PAY 
	FROM KWADR WHERE W3IPB = P_CODEOFFRE AND W3ALX = P_VERSION AND W3TYP = P_TYPE ) ; 
END P1 ; 

