CREATE PROCEDURE SP_INITMONTANTREF ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) ) 
	LANGUAGE SQL 
	SPECIFIC SP_INITMONTANTREF 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
  
DECLARE V_PERIODICITE CHAR ( 1 ) DEFAULT '' ; 
DECLARE V_PERIODEJ INTEGER DEFAULT 0 ; 
DECLARE V_PERIODEM INTEGER DEFAULT 0 ; 
DECLARE V_PERIODEA INTEGER DEFAULT 0 ; 
  
DECLARE V_PERIOFEJ INTEGER DEFAULT 0 ; 
DECLARE V_PERIOFEM INTEGER DEFAULT 0 ; 
DECLARE V_PERIOFEA INTEGER DEFAULT 0 ; 
  
  
SELECT PBPER , PBEFJ , PBEFM , PBEFA , PBFEJ , PBFEM , PBFEA INTO V_PERIODICITE , V_PERIODEJ , V_PERIODEM , V_PERIODEA , V_PERIOFEJ , V_PERIOFEM , V_PERIOFEA FROM YPOBASE WHERE PBIPB = P_CODEOFFRE AND PBALX = P_VERSION AND PBTYP = P_TYPE ; 
  
IF ( V_PERIODICITE = 'U' OR V_PERIODICITE = 'E' ) THEN 
	 
	UPDATE YPRTENT 
	SET JDDPJ = V_PERIODEJ , 
	JDDPM = V_PERIODEM , 
	JDDPA = V_PERIODEA , 
	JDFPJ = V_PERIOFEJ , 
	JDFPM = V_PERIOFEM , 
	JDFPA = V_PERIOFEA 
	WHERE TRIM ( JDIPB ) = TRIM ( P_CODEOFFRE ) AND JDALX = P_VERSION ; 
  
END IF ; 
  
  
END P1  ; 
  

  

