CREATE PROCEDURE SP_INCOPID ( 
	IN P_CODEOFFRE VARCHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE VARCHAR(1) , 
	IN P_TABLE VARCHAR(10) , 
	IN P_CODEID INTEGER , 
	IN P_NEWCODEID INTEGER ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_INCOPID 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
INSERT INTO KPCOPID 
( KFLTYP , KFLIPB , KFLALX , KFLTAB , KFLIDO , KFLIDC ) 
VALUES 
( P_TYPE , P_CODEOFFRE , P_VERSION , P_TABLE , P_CODEID , P_NEWCODEID ) ; 
  
END P1  ; 
  

  

