CREATE PROCEDURE SP_MAJOPVO ( 
	IN P_CODECONTRAT CHAR(9) , 
	IN P_VERSIONCONTRAT INTEGER , 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_CODEFORM INTEGER , 
	IN P_GUIDFORM INTEGER , 
	IN P_CODEOPT INTEGER , 
	IN P_GUIDOPT INTEGER , 
	IN P_GUIDVOL INTEGER , 
	IN P_TYPEOPTION CHAR(1) , 
	IN P_CHECK CHAR(1) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_MAJOPVO 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
DECLARE V_NBVOLCHECKED INTEGER DEFAULT 0 ; 
DECLARE V_CHECKFORMOPT CHAR ( 1 ) DEFAULT '' ; 
  
CASE P_TYPEOPTION 
WHEN 'F' THEN 
IF ( P_CHECK = 'O' ) THEN 
  
UPDATE KPOFOPT 
SET KFJSEL = P_CHECK 
WHERE KFJPOG = P_CODECONTRAT AND KFJALG = P_VERSIONCONTRAT AND KFJIPB = P_CODEOFFRE AND KFJALX = P_VERSION 
AND KFJFOR = P_CODEFORM AND KFJKDAID = P_GUIDFORM AND KFJTENG = P_TYPEOPTION ; 
  
UPDATE KPOFOPT 
SET KFJSEL = P_CHECK 
WHERE KFJPOG = P_CODECONTRAT AND KFJALG = P_VERSIONCONTRAT AND KFJIPB = P_CODEOFFRE AND KFJALX = P_VERSION 
AND KFJFOR = P_CODEFORM AND KFJKDAID = P_GUIDFORM AND KFJOPT = 1 ; 
ELSE 
UPDATE KPOFOPT 
SET KFJSEL = P_CHECK 
WHERE KFJPOG = P_CODECONTRAT AND KFJALG = P_VERSIONCONTRAT AND KFJIPB = P_CODEOFFRE AND KFJALX = P_VERSION 
AND KFJFOR = P_CODEFORM AND KFJKDAID = P_GUIDFORM ; 
END IF ; 
  
WHEN 'O' THEN 
  
UPDATE KPOFOPT 
SET KFJSEL = 'N' 
WHERE KFJPOG = P_CODECONTRAT AND KFJALG = P_VERSIONCONTRAT AND KFJIPB = P_CODEOFFRE AND KFJALX = P_VERSION 
AND KFJFOR = P_CODEFORM AND KFJKDAID = P_GUIDFORM AND KFJOPT > 0 ; 
  
UPDATE KPOFOPT 
SET KFJSEL = P_CHECK 
WHERE KFJPOG = P_CODECONTRAT AND KFJALG = P_VERSIONCONTRAT AND KFJIPB = P_CODEOFFRE AND KFJALX = P_VERSION 
AND KFJFOR = P_CODEFORM AND KFJKDAID = P_GUIDFORM AND KFJTENG = 'F' ; 
  
UPDATE KPOFOPT 
SET KFJSEL = P_CHECK 
WHERE KFJPOG = P_CODECONTRAT AND KFJALG = P_VERSIONCONTRAT AND KFJIPB = P_CODEOFFRE AND KFJALX = P_VERSION 
AND KFJFOR = P_CODEFORM AND KFJKDAID = P_GUIDFORM AND KFJOPT = P_CODEOPT AND KFJKDBID = P_GUIDOPT ; 
  
WHEN 'V' THEN 
UPDATE KPOFOPT 
SET KFJSEL = P_CHECK 
WHERE KFJPOG = P_CODECONTRAT AND KFJALG = P_VERSIONCONTRAT AND KFJIPB = P_CODEOFFRE AND KFJALX = P_VERSION 
AND KFJFOR = P_CODEFORM AND KFJKDAID = P_GUIDFORM AND KFJOPT = P_CODEOPT AND KFJKDBID = P_GUIDOPT AND KFJKAKID = P_GUIDVOL ; 
  
SELECT COUNT ( * ) INTO V_NBVOLCHECKED FROM KPOFOPT 
WHERE KFJPOG = P_CODECONTRAT AND KFJALG = P_VERSION AND KFJIPB = P_CODEOFFRE AND KFJALX = P_VERSION 
AND KFJFOR = P_CODEFORM AND KFJKDAID = P_GUIDFORM AND KFJOPT = P_CODEOPT AND KFJKDBID = P_GUIDOPT AND KFJTENG = 'V' AND KFJSEL = 'O' ; 
  
IF ( V_NBVOLCHECKED = 0 ) THEN 
SET V_CHECKFORMOPT = 'N' ; 
ELSE 
SET V_CHECKFORMOPT = 'O' ; 
END IF ; 
  
UPDATE KPOFOPT 
SET KFJSEL = V_CHECKFORMOPT 
WHERE KFJPOG = P_CODECONTRAT AND KFJALG = P_VERSIONCONTRAT AND KFJIPB = P_CODEOFFRE AND KFJALX = P_VERSION 
AND KFJFOR = P_CODEFORM AND KFJKDAID = P_GUIDFORM AND KFJTENG = 'F' ; 
  
UPDATE KPOFOPT 
SET KFJSEL = V_CHECKFORMOPT 
WHERE KFJPOG = P_CODECONTRAT AND KFJALG = P_VERSIONCONTRAT AND KFJIPB = P_CODEOFFRE AND KFJALX = P_VERSION 
AND KFJFOR = P_CODEFORM AND KFJKDAID = P_GUIDFORM AND KFJOPT = P_CODEOPT AND KFJKDBID = P_GUIDOPT AND KFJTENG = 'O' ; 
  
ELSE 
SET P_TYPEOPTION = '' ; 
  
END CASE ; 
  
END P1  ; 
  

  

