CREATE PROCEDURE SP_MAJTAR ( 
	IN P_CODECONTRAT CHAR(9) , 
	IN P_VERSIONCONTRAT INTEGER , 
	IN P_CODETARIF INTEGER ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_MAJTAR 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
DECLARE V_GUIDGARANTIE VARCHAR ( 10 ) DEFAULT '' ; 
  
SELECT KFKGARAN INTO V_GUIDGARANTIE FROM KPOFTAR WHERE KFKPOG = P_CODECONTRAT AND KFKALG = P_VERSIONCONTRAT AND KFKKDGID = P_CODETARIF ; 
  
UPDATE KPOFTAR 
SET KFKSEL = 'N' 
WHERE KFKPOG = P_CODECONTRAT AND KFKALG = P_VERSIONCONTRAT AND KFKGARAN = V_GUIDGARANTIE ; 
  
UPDATE KPOFTAR 
SET KFKSEL = 'O' 
WHERE KFKPOG = P_CODECONTRAT AND KFKALG = P_VERSIONCONTRAT AND KFKKDGID = P_CODETARIF ; 
  
END P1  ; 
  

  

