CREATE PROCEDURE SP_PGMADR (
	IN P_CLE CHAR(40) ,
	IN P_EXT CHAR(3) ,
	IN P_ACT CHAR(3) ,
	OUT P_NUU CHAR(7),
	OUT P_RET CHAR(3) )
	LANGUAGE RPGLE
	SPECIFIC SP_PGMADR
	NOT DETERMINISTIC
	MODIFIES SQL DATA
	CALLED ON NULL INPUT
	EXTERNAL NAME 'YALBINPGM/YDH105'
	PARAMETER STYLE SQL ;
