CREATE PROCEDURE SP_PGMCHR ( 
	IN P_CLE CHAR(40) , 
	IN P_ACT CHAR(3) , 
	OUT P_NUU CHAR(15) , 
	OUT P_RET CHAR(3) ) 
	LANGUAGE RPGLE 
	SPECIFIC SP_PGMCHR 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	EXTERNAL NAME 'YALBINPGM/KA0001' 
	PARAMETER STYLE SQL ;
