CREATE PROCEDURE SP_RECHERCHESUSPENSION ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_TYPEOFFRE CHAR(1) , 
	IN P_VERSION CHAR(1) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_RECHERCHESUSPENSION 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
P1 : BEGIN ATOMIC

DECLARE V_QUERYSELECT VARCHAR ( 8000 ) DEFAULT '' ;
DECLARE V_WHEREAND VARCHAR ( 10 ) DEFAULT ' WHERE ' ;
DECLARE CURSORSELECT CURSOR WITH RETURN FOR SQL_STATEMENT ;

SET V_QUERYSELECT = 'SELECT SUSP.KICIPB LSUSPVCODE, 
							SUSP.KICALX LSUSPVVERSION, 
							SUSP.KICTYP LSUSPVTYPE, 
							SUSP.KICID LSUSPVID, 
							((IFNULL(LANC.RBDPA, 0) * 10000)+ (IFNULL(LANC.RBDPM, 0) * 100)+ IFNULL(LANC.RBDPJ, 0)) LSUSPVDATEMISE, 
							((SUSP.KICDEBD * 10000) + SUSP.KICDEBH) LSUSPVDATEDEBUT, 
							((SUSP.KICFIND * 10000) + SUSP.KICFINH) LSUSPVDATEFIN, 
							((SUSP.KICRSAD * CAST(1000000 AS BIGINT))+ SUSP.KICRSAH) LSUSPVDATERESIL, 
							SUSP.KICREVD LSUSPVDATEREMISE
                     FROM KPSUSP SUSP
							LEFT JOIN ARELANC LANC ON SUSP.KICNUR = LANC.RBNUR  AND TRIM(SUSP.KICIPB)= LANC.RBIPB AND SUSP.KICALX = LANC.RBALX' ;
					
					
SET V_QUERYSELECT = TRIM ( V_QUERYSELECT ) CONCAT V_WHEREAND CONCAT ' KICTYE = ''S''' ;
SET V_WHEREAND = ' AND ' ;					
					

					--********************** TYPE OFFRE/CONTRAT ************************** 
IF ( P_TYPEOFFRE IS NOT NULL AND P_TYPEOFFRE <> '' ) THEN
SET V_QUERYSELECT = TRIM ( V_QUERYSELECT ) CONCAT V_WHEREAND CONCAT ' KICTYP = ''' CONCAT P_TYPEOFFRE CONCAT '''' ;
SET V_WHEREAND = ' AND ' ;
END IF ;

					--********************** VERSION OFFRE/CONTRAT ************************** 
IF ( P_VERSION IS NOT NULL AND P_VERSION <> '' ) THEN
--SET V_QUERYSELECT = TRIM ( V_QUERYSELECT ) CONCAT V_WHEREAND CONCAT ' KICALX = ''' CONCAT P_VERSION CONCAT '''' ; 
--SET V_WHEREAND = ' AND ' ; 
SET V_QUERYSELECT = TRIM ( V_QUERYSELECT ) CONCAT V_WHEREAND CONCAT ' KICALX = ' CONCAT P_VERSION ;
END IF ;


					--********************** CODE OFFRE/CONTRAT ************************** 
IF ( P_CODEOFFRE IS NOT NULL AND P_CODEOFFRE <> '' ) THEN
SET V_QUERYSELECT = TRIM ( V_QUERYSELECT ) CONCAT V_WHEREAND CONCAT ' TRIM(KICIPB) LIKE ''%' CONCAT TRIM ( P_CODEOFFRE ) CONCAT '%''' ;
SET V_WHEREAND = ' AND ' ;
END IF ;



PREPARE SQL_STATEMENT FROM V_QUERYSELECT ;
OPEN CURSORSELECT ;

END P1 ;
  

