CREATE PROCEDURE SP_RECHERCHEVILLESPARCODEPOSTAL ( 
	IN P_CODEPOSTAL CHAR(5) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_RECHERCHEVILLESPARCODEPOSTAL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
DECLARE CURSORVILLE CURSOR FOR 
SELECT ABLCPO CODE , ABLLIB LIBELLE FROM GENERALE . YHEXLOC WHERE ABLCPO LIKE '' CONCAT P_CODEPOSTAL CONCAT '' ; 
OPEN CURSORVILLE ; 
END P1  ; 
  

  

