CREATE PROCEDURE SP_RESETEXPRCOMPCONDITION ( 
	IN P_CODECONDITION INTEGER , 
	IN P_OLDFRHEXPR INTEGER , 
	IN P_OLDLCIEXPR INTEGER ) 
	LANGUAGE SQL 
	SPECIFIC SP_RESETEXPRCOMPCONDITION 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
	DECLARE V_COUNT INTEGER DEFAULT 0 ; 
	SET V_COUNT = 0 ; 
	 
	SELECT COUNT ( * ) INTO V_COUNT FROM KPEXPFRH WHERE KDKID = P_OLDFRHEXPR ; 
	IF ( V_COUNT = 0 ) THEN 
		SET P_OLDFRHEXPR = 0 ; 
	END IF ; 
  
	SELECT COUNT ( * ) INTO V_COUNT FROM KPEXPLCI WHERE KDIID = P_OLDLCIEXPR ; 
	IF ( V_COUNT = 0 ) THEN 
		SET P_OLDLCIEXPR = 0 ; 
	END IF ; 
  
	UPDATE KPGARTAW SET KDGKDKID = P_OLDFRHEXPR , KDGKDIID = P_OLDLCIEXPR WHERE KDGID = P_CODECONDITION ; 
  
END P1  ; 
  

  

