CREATE PROCEDURE SP_RELOADMOUVTPERIOD ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_CODERSQ INTEGER , 
	IN P_CODEFOR INTEGER , 
	IN P_CODEGAR CHAR(10) , 
	IN P_CODEREGULE INTEGER ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_RELOADMOUVTPERIOD 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
DECLARE CURSOMOUVT CURSOR FOR					 
SELECT KHXID CODE , KHXSIT SITUATION , KHXDEBP DATEDEB , KHXFINP DATEFIN , 
CASE WHEN NULLIF ( KHXCU2 , '' ) IS NULL THEN KHXBAS ELSE KHXCA2 END ASSIETTE , 
CASE WHEN NULLIF ( KHXCU2 , '' ) IS NULL THEN CASE WHEN KHXBAU = 'D' THEN KHXBAM ELSE KHXBAT END ELSE CASE WHEN KHXCU2 = 'D' THEN KHXCP2 ELSE KHXCT2 END END TAUXFORFAITHTVALEUR , 
CASE WHEN NULLIF ( KHXCU2 , '' ) IS NULL THEN KHXBAU ELSE KHXCU2 END TAUXFORFAITHTUNITE , KHXMHT MONTANTREGULHF 
FROM KPRGUG 
WHERE KHXIPB = P_CODEOFFRE AND KHXALX = P_VERSION AND KHXTYP = P_TYPE AND KHXRSQ = P_CODERSQ AND KHXFOR = P_CODEFOR AND KHXKHWID = P_CODEREGULE AND KHXGARAN = P_CODEGAR ;				 
  
OPEN CURSOMOUVT ; 
	 
  
END P1  ; 
  

  

