CREATE PROCEDURE SP_REPLACECOURTIER ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_CODECOURTIER INTEGER , 
	IN P_CODESOUSCRIPTEUR CHAR(10) , 
	IN P_REFERENCE CHAR(25) , 
	IN P_CODEINTERLOCUTEUR INTEGER , 
	IN P_DAYSAISIE INTEGER , 
	IN P_MONTHSAISIE INTEGER , 
	IN P_YEARSAISIE INTEGER , 
	IN P_HOURSAISIE INTEGER , 
	IN P_DAYNOW INTEGER , 
	IN P_MONTHNOW INTEGER , 
	IN P_YEARNOW INTEGER , 
	IN P_SOUSCRIPTEUR CHAR(10) ) 
	LANGUAGE SQL 
	SPECIFIC SP_REPLACECOURTIER 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
	DECLARE V_COURTDIRECT CHAR ( 1 ) DEFAULT '' ; 
	DECLARE V_TYPEENC CHAR ( 1 ) DEFAULT '' ; 
	DECLARE V_CODEENC CHAR ( 1 ) DEFAULT '' ; 
	DECLARE V_NEWCODEENC CHAR ( 1 ) DEFAULT '' ; 
  
	DELETE FROM YPOCOUR 
	WHERE TRIM ( PFIPB ) = TRIM ( P_CODEOFFRE ) AND PFALX = P_VERSION AND PFTYP = P_TYPE AND PFCTI = 'A' 
		AND PFICT = ( SELECT PBCTA FROM YPOBASE WHERE TRIM ( PBIPB ) = TRIM ( P_CODEOFFRE ) AND PBALX = P_VERSION AND PBTYP = P_TYPE ) ; 
  
	UPDATE YPOBASE 
		SET PBCTA = P_CODECOURTIER , PBICT = P_CODECOURTIER , PBSOU = P_CODESOUSCRIPTEUR , PBOCT = P_REFERENCE , PBIN5 = P_CODEINTERLOCUTEUR 
	WHERE TRIM ( PBIPB ) = TRIM ( P_CODEOFFRE ) AND PBALX = P_VERSION AND PBTYP = P_TYPE ; 
	 
	INSERT INTO YPOCOUR 
		( PFIPB , PFALX , PFTYP , PFCTI , PFICT , PFSAA , PFSAM , PFSAJ , PFSAH , PFSIT , PFSTA , PFSTM , PFSTJ , PFGES , PFSOU , PFCOM , PFOCT , PFXCM , PFXCN ) 
	VALUES 
		( P_CODEOFFRE , P_VERSION , P_TYPE , 'A' , P_CODECOURTIER , P_YEARSAISIE , P_MONTHSAISIE , P_DAYSAISIE , P_HOURSAISIE , 'A' , 
		P_YEARNOW , P_MONTHNOW , P_DAYNOW , P_SOUSCRIPTEUR , P_SOUSCRIPTEUR , 100 , '' , 0 , 0 ) ; 
  
	/*TRAITEMENT DU TYPE D'ENCAISSEMENT*/ 
	SELECT TCENC , TCYEN INTO V_COURTDIRECT , V_TYPEENC FROM YCOURTI WHERE TCICT = P_CODECOURTIER ; 
	SELECT JDENC INTO V_CODEENC FROM YPRTENT WHERE TRIM ( JDIPB ) = TRIM ( P_CODEOFFRE ) AND JDALX = P_VERSION ; 
	SET V_NEWCODEENC = V_CODEENC ; 
  
	IF ( TRIM ( V_COURTDIRECT ) = 'O' ) THEN 
		SET V_NEWCODEENC = 'D' ; 
	ELSE 
		IF ( TRIM ( V_CODEENC ) = '' ) THEN 
			SET V_NEWCODEENC = TRIM ( V_TYPEENC ) ; 
		ELSE 
			IF ( TRIM ( P_TYPE ) = 'O' ) THEN 
				SET V_NEWCODEENC = TRIM ( V_TYPEENC ) ; 
			END IF ; 
			IF ( TRIM ( P_TYPE ) = 'P' ) THEN 
				IF ( TRIM ( V_TYPEENC ) = 'D' ) THEN 
					SET V_NEWCODEENC = TRIM ( V_TYPEENC ) ; 
				END IF ; 
			END IF ; 
		END IF ; 
	END IF ; 
	IF ( TRIM ( V_NEWCODEENC ) = '' ) THEN 
		SET V_NEWCODEENC = 'C' ; 
	END IF ; 
  
	UPDATE YPRTENT SET JDENC = V_NEWCODEENC WHERE TRIM ( JDIPB ) = TRIM ( P_CODEOFFRE ) AND JDALX = P_VERSION ; 
		 
END P1  ; 
  

  

