CREATE PROCEDURE SP_RECHERCHECABINETCOURTAGE ( 
	IN P_NOMCABINET CHAR(40) , 
	IN P_STARTLINE INTEGER , 
	IN P_ENDLINE INTEGER , 
	IN P_SORTINGBY CHAR(20) , 
	IN P_ORDERBY CHAR(10) , 
	IN P_MODE CHAR(13) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_RECHERCHECABINETCOURTAGE 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
DECLARE V_QUERY VARCHAR ( 8000 ) DEFAULT '' ; 
DECLARE CURSOR1 CURSOR WITH RETURN FOR SQL_STATEMENT ; 
  
IF ( P_STARTLINE > 0 AND P_ENDLINE > 0 AND P_SORTINGBY IS NOT NULL AND P_SORTINGBY <> '' AND P_ORDERBY IS NOT NULL AND P_ORDERBY <> '' ) THEN 
  
IF ( P_MODE <> 'AUTOCOMPLETE' ) THEN 
		SET V_QUERY = 'SELECT TCICT CODECAB, NOM NOMCAB, NOM2, TCTYP TYPECAB, TCBUR CODEDELEGATION, 
							  BUDBU NOMDELEGATION, ABPVI6 NOMVILLE, ABPDP6 DEPARTEMENT, ABPCHR NUMEROCHRONO, 
							  ABPLG4 NOMVOIE, ABPCP6 CODEPOSTAL, TCGEP DEMARCHECOM, 
							  TCFVJ FINVJOUR, TCFVM FINVMOIS, TCFVA FINVANNEE , TCYEN CODEENCAISSEMENT
						FROM 
									   (
										   SELECT TCICT, courtn1.TNNOM AS NOM, rownumber() OVER (ORDER BY ' CONCAT TRIM ( P_SORTINGBY ) CONCAT ' ' CONCAT TRIM ( P_ORDERBY ) CONCAT ') AS ID_NEXT, 
														MAX(courtn2.TNNOM) AS NOM2, MAX(TCTYP) AS TCTYP, MAX(TCBUR) AS TCBUR, 
														MAX (BUDBU) AS BUDBU, MAX(ABPVI6) AS ABPVI6, MAX(ABPDP6) AS ABPDP6, 
														MAX(ABPCHR) AS ABPCHR, MAX(ABPLG4) AS ABPLG4, MAX(ABPCP6) AS ABPCP6, 
														MAX(TCGEP) AS TCGEP, MAX(TCFVJ) AS TCFVJ, MAX(TCFVM) AS TCFVM, MAX(TCFVA) AS TCFVA,
														MAX(IFNULL(NULLIF(TCYEN, ''''), ''C'')) AS TCYEN
										   FROM YCOURTI 
										   LEFT JOIN YADRESS ON TCADH = ABPCHR 
										   LEFT JOIN YCOURTN courtn1 ON TCICT = courtn1.TNICT AND courtn1.TNXN5 = 0 AND courtn1.TNTNM = ''A'' 
										   LEFT JOIN YCOURTN courtn2 ON TCICT = courtn2.TNICT AND courtn2.TNXN5 = 0 AND courtn2.TNTNM = ''S''
										   LEFT JOIN YBUREAU ON BUIBU = TCBUR 
										   WHERE (courtn1.TNNOM LIKE ''' CONCAT TRIM ( P_NOMCABINET ) CONCAT '%'' OR courtn2.TNNOM LIKE ''' CONCAT TRIM ( P_NOMCABINET ) CONCAT '%'')                                 
										   GROUP BY TCICT, courtn1.TNNOM
										   ORDER BY ' CONCAT TRIM ( P_SORTINGBY ) CONCAT ' ' CONCAT TRIM ( P_ORDERBY ) CONCAT '
									   ) 
									   AS TABLE 
									   WHERE ID_NEXT BETWEEN ' CONCAT P_STARTLINE CONCAT ' AND ' CONCAT P_ENDLINE ; 
									 
									 
ELSE 
		SET V_QUERY = 'SELECT TCICT CODECAB, NOM NOMCAB, NOM2, TCTYP TYPECAB, TCBUR CODEDELEGATION, 
							  BUDBU NOMDELEGATION, ABPVI6 NOMVILLE, ABPDP6 DEPARTEMENT, ABPCHR NUMEROCHRONO, 
							  ABPLG4 NOMVOIE, ABPCP6 CODEPOSTAL, TCGEP DEMARCHECOM, 
							  TCFVJ FINVJOUR, TCFVM FINVMOIS, TCFVA FINVANNEE , TCYEN CODEENCAISSEMENT
						FROM 
									   (
										   SELECT TCICT, courtn1.TNNOM AS NOM, 
														MAX(courtn2.TNNOM) AS NOM2, MAX(TCTYP) AS TCTYP, MAX(TCBUR) AS TCBUR, 
														MAX (BUDBU) AS BUDBU, MAX(ABPVI6) AS ABPVI6, MAX(ABPDP6) AS ABPDP6, 
														MAX(ABPCHR) AS ABPCHR, MAX(ABPLG4) AS ABPLG4, MAX(ABPCP6) AS ABPCP6, 
														MAX(TCGEP) AS TCGEP, MAX(TCFVJ) AS TCFVJ, MAX(TCFVM) AS TCFVM, MAX(TCFVA) AS TCFVA,
														MAX(IFNULL(NULLIF(TCYEN, ''''), ''C'')) AS TCYEN
										   FROM YCOURTI 
										   LEFT JOIN YADRESS ON TCADH = ABPCHR 
										   LEFT JOIN YCOURTN courtn1 ON TCICT = courtn1.TNICT AND courtn1.TNXN5 = 0 AND courtn1.TNTNM = ''A'' 
										   LEFT JOIN YCOURTN courtn2 ON TCICT = courtn2.TNICT AND courtn2.TNXN5 = 0 AND courtn2.TNTNM = ''S''
										   LEFT JOIN YBUREAU ON BUIBU = TCBUR 
										   WHERE (courtn1.TNNOM LIKE ''' CONCAT TRIM ( P_NOMCABINET ) CONCAT '%'' OR courtn2.TNNOM LIKE ''' CONCAT TRIM ( P_NOMCABINET ) CONCAT '%'')                                 
										   GROUP BY TCICT, courtn1.TNNOM
										   ORDER BY ' CONCAT TRIM ( P_SORTINGBY ) CONCAT ' ' CONCAT TRIM ( P_ORDERBY ) CONCAT '
									      FETCH FIRST ' CONCAT P_ENDLINE CONCAT ' ROWS ONLY ) AS TABLE' ; 
									 
									 
									 
									 
									 
END IF ;									 
  
PREPARE SQL_STATEMENT FROM V_QUERY ; 
OPEN CURSOR1 ; 
  
END IF ; 
END P1  ; 
  

  

