CREATE OR REPLACE PROCEDURE SP_SAVERSQ_ADR ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_BATIMENT CHAR(32) , 
	IN P_NUMVOIE CHAR(10) , 
	IN P_NUMVOIE2 CHAR(15) , 
	IN P_EXTVOIE CHAR(1) , 
	IN P_VOIE CHAR(32) , 
	IN P_BP CHAR(32) ,
	IN P_LOC CHAR(5) ,
	IN P_DEP CHAR(2) , 
	IN P_CP CHAR(5) , 
	IN P_VILLE CHAR(26) , 
	IN P_VOIECOMPLETE CHAR(32) , 
	IN P_VILLECOMPLETE CHAR(32) , 
	IN P_CPX CHAR(5) , 
	IN P_VILLEX CHAR(32) , 
	IN P_MATHEX INTEGER ,
	IN P_ISADDRESSEMPTY INTEGER,
	IN P_CODERSQ INTEGER , 
	IN P_CODERISQUEPRINCIPAL INTEGER, 
	IN P_LATITUDE NUMERIC(10, 7) , 
	IN P_LONGITUDE NUMERIC(10, 7) ) 
	
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_SAVERSQ_ADR
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
  
		DECLARE V_NBRSQ INTEGER DEFAULT 0 ; 
	  
		DECLARE V_IDADRESSEOFFRE INTEGER DEFAULT 0 ; 
		DECLARE V_CODERSQ INTEGER DEFAULT - 1 ;
		
		DECLARE V_CHR_FOR_AFFECTATION INTEGER DEFAULT 0 ;
		DECLARE V_CHR INTEGER DEFAULT 0 ; 
		DECLARE V_NUMCHR CHAR ( 40 ) DEFAULT '' ; 
		
		DECLARE V_NUMVOIE INTEGER DEFAULT 0 ; 
		DECLARE V_CP INTEGER DEFAULT 0 ; 
		DECLARE V_CPX INTEGER DEFAULT 0 ; 
				
		DECLARE V_ACTION_YADRESS CHAR (6) DEFAULT '';
		DECLARE V_ACTION_YPRTADR CHAR (12) DEFAULT '';
  
		 --CRÃ‰ATION DES CHAINES D'ADRESSES 
		 -- Bug100: Refactoring into function call to set address 
		SET V_NUMVOIE = CAST ( ('0' CONCAT TRIM(P_NUMVOIE)) AS INTEGER ) ; 
		SET V_CPX = CAST ( ('0' CONCAT TRIM(P_CPX)) AS INTEGER ) ;
		SET V_CP = CAST ( ('0' CONCAT TRIM(P_CP)) AS INTEGER ) ;
  
		 --DÃ‰TERMINATION DE L'ID DE L'ADRESSE DU RISQUE 
		SELECT JFRSQ , IFNULL ( JFADH , - 1 ) INTO V_CODERSQ , V_CHR  FROM YPRTADR WHERE JFIPB = P_CODEOFFRE AND JFALX = P_VERSION AND JFRSQ = P_CODERSQ AND JFOBJ = 0 ; 
		 --ENREGISTREMENT DE L'ADRESSE DU RISQUE 
		IF ( V_CHR != - 1 AND V_CHR != 0 ) THEN  --MISE Ã€ JOUR 
			IF ( P_ISADDRESSEMPTY = 0 ) THEN 
				SET V_CHR_FOR_AFFECTATION = V_CHR;
				SET V_ACTION_YADRESS = 'UPDATE';
			ELSE 
				SET V_ACTION_YADRESS = 'DELETE';
			END IF;
			
			SET V_ACTION_YPRTADR = 'UPDATE_SET';
		ELSE  --CRÃ‰ATION 
			CALL SP_YCHRONO ( 'ADRESSE_CHRONO' , V_NUMCHR ) ; 
			SET V_CHR = CAST ( V_NUMCHR AS INTEGER ) ; 
			IF ( V_CHR != 0 ) THEN 
				IF ( P_ISADDRESSEMPTY = 0 ) THEN 
					SET V_CHR_FOR_AFFECTATION = V_CHR;
					SET V_ACTION_YADRESS = 'CREATE';
				ELSE
					SET V_ACTION_YADRESS = '';				 					
				END IF ; 
				
				IF ( V_CODERSQ = - 1 ) THEN 
					SET V_ACTION_YPRTADR = 'CREATE';
				ELSE 
					SET V_ACTION_YPRTADR = 'UPDATE_SET';
				END IF ; 
			ELSE
				SET V_ACTION_YADRESS = '';
				SET V_ACTION_YPRTADR = '';
			END IF ; 	
		END IF ; 
		 
		
		CALL SP_UPDATE_ADR ( V_ACTION_YADRESS, P_NUMVOIE, P_NUMVOIE2, P_CP, P_CPX, V_CHR, V_CP, V_CPX, 
				P_BATIMENT, P_EXTVOIE, P_VOIE, P_BP, P_LOC, P_DEP, P_VILLE, P_VOIECOMPLETE, P_VILLECOMPLETE, 
				P_VILLEX, P_MATHEX, 1, V_ACTION_YPRTADR, P_CODEOFFRE, P_VERSION, P_TYPE, P_CODERSQ, 0, V_CHR_FOR_AFFECTATION, '', 0, '', '',P_LATITUDE,P_LONGITUDE);
				
		SET V_ACTION_YADRESS = '';
		
		--ENREGISTREMENT DE L'ADRESSE ET LA CIBLE DU RISQUE PRINCIPAL DANS L'OFFRE 
		IF ( P_CODERISQUEPRINCIPAL = P_CODERSQ ) THEN  --SI LE RISQUE EN COURS DE MODIFICATION EST LE RISQUE PRINCIPAL 
			SET V_NBRSQ = 0 ; 
			SELECT COUNT ( * ) INTO V_NBRSQ FROM YPRTRSQ WHERE JEIPB = P_CODEOFFRE AND JEALX = P_VERSION ; 
			/* COPIE DE L'ADRESSE SI L'AFFAIRE EST MONO-RISQUE */ 
			IF ( V_NBRSQ = 1 ) THEN 
				SELECT PBADH INTO V_IDADRESSEOFFRE FROM YPOBASE WHERE PBIPB = P_CODEOFFRE AND PBALX = P_VERSION AND PBTYP = P_TYPE ; 
				SET V_CHR = 0;
				IF ( V_IDADRESSEOFFRE != 0 ) THEN 
					SET V_CHR = V_IDADRESSEOFFRE ; 
					IF ( P_ISADDRESSEMPTY = 0 ) THEN 
						SET V_ACTION_YADRESS = 'UPDATE';
					ELSE 
						SET V_ACTION_YADRESS = 'DELETE'; 
					END IF ; 
				ELSE 
					IF ( P_ISADDRESSEMPTY = 0 ) THEN 
						SET V_NUMCHR = '';
						CALL SP_YCHRONO ( 'ADRESSE_CHRONO' , V_NUMCHR ) ; 
						SET V_CHR = CAST ( V_NUMCHR AS INTEGER ) ; 
						IF ( V_CHR != 0 ) THEN  --SI L'OFFRE N'AVAIT PAS D'ADRESSE 
							SET V_ACTION_YADRESS = 'CREATE';	
						END IF ; 
					END IF ; 
				END IF ; 
				
				CALL SP_UPDATE_ADR ( V_ACTION_YADRESS, P_NUMVOIE, P_NUMVOIE2, P_CP, P_CPX, V_CHR, V_CP, V_CPX, 
				P_BATIMENT, P_EXTVOIE, P_VOIE, P_BP, P_LOC, P_DEP, P_VILLE, P_VOIECOMPLETE, P_VILLECOMPLETE, 
				P_VILLEX, P_MATHEX, 1, '', P_CODEOFFRE, P_VERSION, P_TYPE, P_CODERSQ, 0, 0, 'UPDATE_SET', V_CHR, P_DEP, P_CP,P_LATITUDE,P_LONGITUDE);
				
			END IF ; 
		END IF ; 
	
END P1;
