CREATE PROCEDURE SP_SAVEVALGRILLE ( 
	IN P_CODEGRILLE CHAR(15) , 
	IN P_TYPOLOGIE CHAR(15) , 
	IN P_NIVEAU INTEGER , 
	IN P_NIVEAUMERE INTEGER , 
	IN P_SELVAL1 CHAR(250) , 
	IN P_SELVAL2 CHAR(250) , 
	IN P_SELVAL3 CHAR(250) , 
	IN P_SELVAL4 CHAR(250) , 
	IN P_SELVAL5 CHAR(250) , 
	IN P_SELVAL6 CHAR(250) , 
	IN P_SELVAL7 CHAR(250) , 
	IN P_SELVAL8 CHAR(250) , 
	IN P_SELVAL9 CHAR(250) , 
	IN P_SELVAL10 CHAR(250) , 
	IN P_CHARSEPFIELD CHAR(1) , 
	OUT P_QUERY CHAR(8000) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_SAVEVALGRILLE 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	DBGVIEW = *SOURCE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
	DECLARE V_INFOLEFT VARCHAR ( 250 ) DEFAULT '' ; 
	DECLARE V_INFORIGHT VARCHAR ( 250 ) DEFAULT '' ; 
	 
	DECLARE V_IDNOMENCLATURELIEN INTEGER DEFAULT 0 ; 
	DECLARE V_ORDRENOMEN NUMERIC ( 7 , 2 ) DEFAULT 0 ; 
  
	DECLARE V_DELCODE VARCHAR ( 5000 ) DEFAULT '' ; 
	DECLARE V_COUNT INTEGER DEFAULT 0 ; 
	DECLARE V_QUERY VARCHAR ( 8000 ) DEFAULT '' ; 
  
	DECLARE V_IDDEL INTEGER DEFAULT 0 ; 
	DECLARE AT_END INTEGER DEFAULT 0 ; 
	DECLARE NOT_FOUND CONDITION FOR SQLSTATE '02000' ; 
	 
	DECLARE C1 CURSOR WITH RETURN FOR S1 ; 
	DECLARE CONTINUE HANDLER FOR NOT_FOUND SET AT_END = 1 ;	 
	 --DELETE FROM KNMVALF WHERE KHKNMG = P_CODEGRILLE AND KHKTYPO = P_TYPOLOGIE AND KHKNIV = P_NIVEAU AND KHKMER = P_NIVEAUMERE ; 
	IF ( P_SELVAL1 != '' ) THEN 
		CALL SP_SPLIT ( P_SELVAL1 , P_CHARSEPFIELD , 'L' , V_INFOLEFT ) ; 
		CALL SP_SPLIT ( P_SELVAL1 , P_CHARSEPFIELD , 'R' , V_INFORIGHT ) ; 
		 
		WHILE ( TRIM ( V_INFOLEFT ) != '' ) DO 
		 
			SELECT COUNT ( * ) INTO V_COUNT FROM KNMVALF WHERE KHKNMG = P_CODEGRILLE AND KHKTYPO = P_TYPOLOGIE AND KHKMER = P_NIVEAUMERE AND KHKKHIID = TRIM ( V_INFOLEFT ) ; 
			IF ( V_COUNT = 0 ) THEN 
				SELECT KHINORD INTO V_ORDRENOMEN FROM KNMREF WHERE KHIID = CAST ( TRIM ( V_INFOLEFT ) AS INTEGER ) ; 
					 
				CALL SP_NCHRONO ( 'KHKID' , V_IDNOMENCLATURELIEN ) ; 
						 
				INSERT INTO KNMVALF 
					( KHKID , KHKNMG , KHKTYPO , KHKORDR , KHKNIV , KHKMER , KHKKHIID ) 
				VALUES 
					( V_IDNOMENCLATURELIEN , P_CODEGRILLE , P_TYPOLOGIE , V_ORDRENOMEN , P_NIVEAU , P_NIVEAUMERE , CAST ( TRIM ( V_INFOLEFT ) AS INTEGER ) ) ; 
			END IF ; 
			 
			SET V_DELCODE = TRIM ( V_DELCODE ) CONCAT ''',''' CONCAT TRIM ( V_INFOLEFT ) CONCAT '' ; 
			 
			CALL SP_SPLIT ( V_INFORIGHT , P_CHARSEPFIELD , 'L' , V_INFOLEFT ) ; 
			CALL SP_SPLIT ( V_INFORIGHT , P_CHARSEPFIELD , 'R' , V_INFORIGHT ) ; 
  
		END WHILE ; 
	END IF ; 
	 
	IF ( P_SELVAL2 != '' ) THEN 
		CALL SP_SPLIT ( P_SELVAL2 , P_CHARSEPFIELD , 'L' , V_INFOLEFT ) ; 
		CALL SP_SPLIT ( P_SELVAL2 , P_CHARSEPFIELD , 'R' , V_INFORIGHT ) ; 
		 
		WHILE ( TRIM ( V_INFOLEFT ) != '' ) DO 
				 
			SELECT COUNT ( * ) INTO V_COUNT FROM KNMVALF WHERE KHKNMG = P_CODEGRILLE AND KHKTYPO = P_TYPOLOGIE AND KHKMER = P_NIVEAUMERE AND KHKKHIID = TRIM ( V_INFOLEFT ) ; 
			IF ( V_COUNT = 0 ) THEN 
				SELECT KHINORD INTO V_ORDRENOMEN FROM KNMREF WHERE KHIID = CAST ( TRIM ( V_INFOLEFT ) AS INTEGER ) ; 
				 
				CALL SP_NCHRONO ( 'KHKID' , V_IDNOMENCLATURELIEN ) ; 
						 
				INSERT INTO KNMVALF 
					( KHKID , KHKNMG , KHKTYPO , KHKORDR , KHKNIV , KHKMER , KHKKHIID ) 
				VALUES 
					( V_IDNOMENCLATURELIEN , P_CODEGRILLE , P_TYPOLOGIE , V_ORDRENOMEN , P_NIVEAU , P_NIVEAUMERE , CAST ( TRIM ( V_INFOLEFT ) AS INTEGER ) ) ; 
			END IF ; 
			 
			SET V_DELCODE = TRIM ( V_DELCODE ) CONCAT ''',''' CONCAT TRIM ( V_INFOLEFT ) CONCAT '' ; 
			 
			CALL SP_SPLIT ( V_INFORIGHT , P_CHARSEPFIELD , 'L' , V_INFOLEFT ) ; 
			CALL SP_SPLIT ( V_INFORIGHT , P_CHARSEPFIELD , 'R' , V_INFORIGHT ) ; 
  
		END WHILE ; 
	END IF ; 
	 
	IF ( P_SELVAL3 != '' ) THEN 
		CALL SP_SPLIT ( P_SELVAL3 , P_CHARSEPFIELD , 'L' , V_INFOLEFT ) ; 
		CALL SP_SPLIT ( P_SELVAL3 , P_CHARSEPFIELD , 'R' , V_INFORIGHT ) ; 
		 
		WHILE ( TRIM ( V_INFOLEFT ) != '' ) DO 
		 
			SELECT COUNT ( * ) INTO V_COUNT FROM KNMVALF WHERE KHKNMG = P_CODEGRILLE AND KHKTYPO = P_TYPOLOGIE AND KHKMER = P_NIVEAUMERE AND KHKKHIID = TRIM ( V_INFOLEFT ) ; 
			IF ( V_COUNT = 0 ) THEN 
				SELECT KHINORD INTO V_ORDRENOMEN FROM KNMREF WHERE KHIID = CAST ( TRIM ( V_INFOLEFT ) AS INTEGER ) ; 
				 
				CALL SP_NCHRONO ( 'KHKID' , V_IDNOMENCLATURELIEN ) ; 
						 
				INSERT INTO KNMVALF 
					( KHKID , KHKNMG , KHKTYPO , KHKORDR , KHKNIV , KHKMER , KHKKHIID ) 
				VALUES 
					( V_IDNOMENCLATURELIEN , P_CODEGRILLE , P_TYPOLOGIE , V_ORDRENOMEN , P_NIVEAU , P_NIVEAUMERE , CAST ( TRIM ( V_INFOLEFT ) AS INTEGER ) ) ; 
			END IF ; 
			 
			SET V_DELCODE = TRIM ( V_DELCODE ) CONCAT ''',''' CONCAT TRIM ( V_INFOLEFT ) CONCAT '' ; 
  
			CALL SP_SPLIT ( V_INFORIGHT , P_CHARSEPFIELD , 'L' , V_INFOLEFT ) ; 
			CALL SP_SPLIT ( V_INFORIGHT , P_CHARSEPFIELD , 'R' , V_INFORIGHT ) ; 
  
		END WHILE ; 
	END IF ; 
	 
	IF ( P_SELVAL4 != '' ) THEN 
		CALL SP_SPLIT ( P_SELVAL4 , P_CHARSEPFIELD , 'L' , V_INFOLEFT ) ; 
		CALL SP_SPLIT ( P_SELVAL4 , P_CHARSEPFIELD , 'R' , V_INFORIGHT ) ; 
		 
		WHILE ( TRIM ( V_INFOLEFT ) != '' ) DO 
		 
			SELECT COUNT ( * ) INTO V_COUNT FROM KNMVALF WHERE KHKNMG = P_CODEGRILLE AND KHKTYPO = P_TYPOLOGIE AND KHKMER = P_NIVEAUMERE AND KHKKHIID = TRIM ( V_INFOLEFT ) ; 
			IF ( V_COUNT = 0 ) THEN 
				SELECT KHINORD INTO V_ORDRENOMEN FROM KNMREF WHERE KHIID = CAST ( TRIM ( V_INFOLEFT ) AS INTEGER ) ; 
				 
				CALL SP_NCHRONO ( 'KHKID' , V_IDNOMENCLATURELIEN ) ; 
						 
				INSERT INTO KNMVALF 
					( KHKID , KHKNMG , KHKTYPO , KHKORDR , KHKNIV , KHKMER , KHKKHIID ) 
				VALUES 
					( V_IDNOMENCLATURELIEN , P_CODEGRILLE , P_TYPOLOGIE , V_ORDRENOMEN , P_NIVEAU , P_NIVEAUMERE , CAST ( TRIM ( V_INFOLEFT ) AS INTEGER ) ) ; 
			END IF ; 
  
			SET V_DELCODE = TRIM ( V_DELCODE ) CONCAT ''',''' CONCAT TRIM ( V_INFOLEFT ) CONCAT '' ; 
			 
			CALL SP_SPLIT ( V_INFORIGHT , P_CHARSEPFIELD , 'L' , V_INFOLEFT ) ; 
			CALL SP_SPLIT ( V_INFORIGHT , P_CHARSEPFIELD , 'R' , V_INFORIGHT ) ; 
  
		END WHILE ; 
	END IF ; 
	 
	IF ( P_SELVAL5 != '' ) THEN 
		CALL SP_SPLIT ( P_SELVAL5 , P_CHARSEPFIELD , 'L' , V_INFOLEFT ) ; 
		CALL SP_SPLIT ( P_SELVAL5 , P_CHARSEPFIELD , 'R' , V_INFORIGHT ) ; 
		 
		WHILE ( TRIM ( V_INFOLEFT ) != '' ) DO 
				 
			SELECT COUNT ( * ) INTO V_COUNT FROM KNMVALF WHERE KHKNMG = P_CODEGRILLE AND KHKTYPO = P_TYPOLOGIE AND KHKMER = P_NIVEAUMERE AND KHKKHIID = TRIM ( V_INFOLEFT ) ; 
			IF ( V_COUNT = 0 ) THEN 
				SELECT KHINORD INTO V_ORDRENOMEN FROM KNMREF WHERE KHIID = CAST ( TRIM ( V_INFOLEFT ) AS INTEGER ) ; 
				 
				CALL SP_NCHRONO ( 'KHKID' , V_IDNOMENCLATURELIEN ) ; 
						 
				INSERT INTO KNMVALF 
					( KHKID , KHKNMG , KHKTYPO , KHKORDR , KHKNIV , KHKMER , KHKKHIID ) 
				VALUES 
					( V_IDNOMENCLATURELIEN , P_CODEGRILLE , P_TYPOLOGIE , V_ORDRENOMEN , P_NIVEAU , P_NIVEAUMERE , CAST ( TRIM ( V_INFOLEFT ) AS INTEGER ) ) ; 
			END IF ; 
  
			SET V_DELCODE = TRIM ( V_DELCODE ) CONCAT ''',''' CONCAT TRIM ( V_INFOLEFT ) CONCAT '' ; 
			 
			CALL SP_SPLIT ( V_INFORIGHT , P_CHARSEPFIELD , 'L' , V_INFOLEFT ) ; 
			CALL SP_SPLIT ( V_INFORIGHT , P_CHARSEPFIELD , 'R' , V_INFORIGHT ) ; 
  
		END WHILE ; 
	END IF ; 
	 
	IF ( P_SELVAL6 != '' ) THEN 
		CALL SP_SPLIT ( P_SELVAL6 , P_CHARSEPFIELD , 'L' , V_INFOLEFT ) ; 
		CALL SP_SPLIT ( P_SELVAL6 , P_CHARSEPFIELD , 'R' , V_INFORIGHT ) ; 
		 
		WHILE ( TRIM ( V_INFOLEFT ) != '' ) DO 
				 
			SELECT COUNT ( * ) INTO V_COUNT FROM KNMVALF WHERE KHKNMG = P_CODEGRILLE AND KHKTYPO = P_TYPOLOGIE AND KHKMER = P_NIVEAUMERE AND KHKKHIID = TRIM ( V_INFOLEFT ) ; 
			IF ( V_COUNT = 0 ) THEN 
				SELECT KHINORD INTO V_ORDRENOMEN FROM KNMREF WHERE KHIID = CAST ( TRIM ( V_INFOLEFT ) AS INTEGER ) ; 
				 
				CALL SP_NCHRONO ( 'KHKID' , V_IDNOMENCLATURELIEN ) ; 
						 
				INSERT INTO KNMVALF 
					( KHKID , KHKNMG , KHKTYPO , KHKORDR , KHKNIV , KHKMER , KHKKHIID ) 
				VALUES 
					( V_IDNOMENCLATURELIEN , P_CODEGRILLE , P_TYPOLOGIE , V_ORDRENOMEN , P_NIVEAU , P_NIVEAUMERE , CAST ( TRIM ( V_INFOLEFT ) AS INTEGER ) ) ; 
			END IF ; 
			 
			SET V_DELCODE = TRIM ( V_DELCODE ) CONCAT ''',''' CONCAT TRIM ( V_INFOLEFT ) CONCAT '' ; 
			 
			CALL SP_SPLIT ( V_INFORIGHT , P_CHARSEPFIELD , 'L' , V_INFOLEFT ) ; 
			CALL SP_SPLIT ( V_INFORIGHT , P_CHARSEPFIELD , 'R' , V_INFORIGHT ) ; 
  
		END WHILE ; 
	END IF ; 
	 
	IF ( P_SELVAL7 != '' ) THEN 
		CALL SP_SPLIT ( P_SELVAL7 , P_CHARSEPFIELD , 'L' , V_INFOLEFT ) ; 
		CALL SP_SPLIT ( P_SELVAL7 , P_CHARSEPFIELD , 'R' , V_INFORIGHT ) ; 
		 
		WHILE ( TRIM ( V_INFOLEFT ) != '' ) DO 
				 
			SELECT COUNT ( * ) INTO V_COUNT FROM KNMVALF WHERE KHKNMG = P_CODEGRILLE AND KHKTYPO = P_TYPOLOGIE AND KHKMER = P_NIVEAUMERE AND KHKKHIID = TRIM ( V_INFOLEFT ) ; 
			IF ( V_COUNT = 0 ) THEN 
				SELECT KHINORD INTO V_ORDRENOMEN FROM KNMREF WHERE KHIID = CAST ( TRIM ( V_INFOLEFT ) AS INTEGER ) ; 
				 
				CALL SP_NCHRONO ( 'KHKID' , V_IDNOMENCLATURELIEN ) ; 
									 
				INSERT INTO KNMVALF 
					( KHKID , KHKNMG , KHKTYPO , KHKORDR , KHKNIV , KHKMER , KHKKHIID ) 
				VALUES 
					( V_IDNOMENCLATURELIEN , P_CODEGRILLE , P_TYPOLOGIE , V_ORDRENOMEN , P_NIVEAU , P_NIVEAUMERE , CAST ( TRIM ( V_INFOLEFT ) AS INTEGER ) ) ; 
			END IF ; 
			 
			SET V_DELCODE = TRIM ( V_DELCODE ) CONCAT ''',''' CONCAT TRIM ( V_INFOLEFT ) CONCAT '' ; 
			 
			CALL SP_SPLIT ( V_INFORIGHT , P_CHARSEPFIELD , 'L' , V_INFOLEFT ) ; 
			CALL SP_SPLIT ( V_INFORIGHT , P_CHARSEPFIELD , 'R' , V_INFORIGHT ) ; 
  
		END WHILE ; 
	END IF ; 
	 
	IF ( P_SELVAL8 != '' ) THEN 
		CALL SP_SPLIT ( P_SELVAL8 , P_CHARSEPFIELD , 'L' , V_INFOLEFT ) ; 
		CALL SP_SPLIT ( P_SELVAL8 , P_CHARSEPFIELD , 'R' , V_INFORIGHT ) ; 
		 
		WHILE ( TRIM ( V_INFOLEFT ) != '' ) DO 
				 
			SELECT COUNT ( * ) INTO V_COUNT FROM KNMVALF WHERE KHKNMG = P_CODEGRILLE AND KHKTYPO = P_TYPOLOGIE AND KHKMER = P_NIVEAUMERE AND KHKKHIID = TRIM ( V_INFOLEFT ) ; 
			IF ( V_COUNT = 0 ) THEN 
				SELECT KHINORD INTO V_ORDRENOMEN FROM KNMREF WHERE KHIID = CAST ( TRIM ( V_INFOLEFT ) AS INTEGER ) ; 
				 
				CALL SP_NCHRONO ( 'KHKID' , V_IDNOMENCLATURELIEN ) ; 
						 
				INSERT INTO KNMVALF 
					( KHKID , KHKNMG , KHKTYPO , KHKORDR , KHKNIV , KHKMER , KHKKHIID ) 
				VALUES 
					( V_IDNOMENCLATURELIEN , P_CODEGRILLE , P_TYPOLOGIE , V_ORDRENOMEN , P_NIVEAU , P_NIVEAUMERE , CAST ( TRIM ( V_INFOLEFT ) AS INTEGER ) ) ; 
			END IF ; 
  
			SET V_DELCODE = TRIM ( V_DELCODE ) CONCAT ''',''' CONCAT TRIM ( V_INFOLEFT ) CONCAT '' ; 
			 
			CALL SP_SPLIT ( V_INFORIGHT , P_CHARSEPFIELD , 'L' , V_INFOLEFT ) ; 
			CALL SP_SPLIT ( V_INFORIGHT , P_CHARSEPFIELD , 'R' , V_INFORIGHT ) ; 
  
		END WHILE ; 
	END IF ; 
	 
	IF ( P_SELVAL9 != '' ) THEN 
		CALL SP_SPLIT ( P_SELVAL9 , P_CHARSEPFIELD , 'L' , V_INFOLEFT ) ; 
		CALL SP_SPLIT ( P_SELVAL9 , P_CHARSEPFIELD , 'R' , V_INFORIGHT ) ; 
		 
		WHILE ( TRIM ( V_INFOLEFT ) != '' ) DO 
				 
			SELECT COUNT ( * ) INTO V_COUNT FROM KNMVALF WHERE KHKNMG = P_CODEGRILLE AND KHKTYPO = P_TYPOLOGIE AND KHKMER = P_NIVEAUMERE AND KHKKHIID = TRIM ( V_INFOLEFT ) ; 
			IF ( V_COUNT = 0 ) THEN 
				SELECT KHINORD INTO V_ORDRENOMEN FROM KNMREF WHERE KHIID = CAST ( TRIM ( V_INFOLEFT ) AS INTEGER ) ; 
				 
				CALL SP_NCHRONO ( 'KHKID' , V_IDNOMENCLATURELIEN ) ; 
									 
				INSERT INTO KNMVALF 
					( KHKID , KHKNMG , KHKTYPO , KHKORDR , KHKNIV , KHKMER , KHKKHIID ) 
				VALUES 
					( V_IDNOMENCLATURELIEN , P_CODEGRILLE , P_TYPOLOGIE , V_ORDRENOMEN , P_NIVEAU , P_NIVEAUMERE , CAST ( TRIM ( V_INFOLEFT ) AS INTEGER ) ) ; 
			END IF ; 
  
			SET V_DELCODE = TRIM ( V_DELCODE ) CONCAT ''',''' CONCAT TRIM ( V_INFOLEFT ) CONCAT '' ; 
			 
			CALL SP_SPLIT ( V_INFORIGHT , P_CHARSEPFIELD , 'L' , V_INFOLEFT ) ; 
			CALL SP_SPLIT ( V_INFORIGHT , P_CHARSEPFIELD , 'R' , V_INFORIGHT ) ; 
  
		END WHILE ; 
	END IF ; 
	 
	IF ( P_SELVAL10 != '' ) THEN 
		CALL SP_SPLIT ( P_SELVAL10 , P_CHARSEPFIELD , 'L' , V_INFOLEFT ) ; 
		CALL SP_SPLIT ( P_SELVAL10 , P_CHARSEPFIELD , 'R' , V_INFORIGHT ) ; 
		 
		WHILE ( TRIM ( V_INFOLEFT ) != '' ) DO 
				 
			SELECT COUNT ( * ) INTO V_COUNT FROM KNMVALF WHERE KHKNMG = P_CODEGRILLE AND KHKTYPO = P_TYPOLOGIE AND KHKMER = P_NIVEAUMERE AND KHKKHIID = TRIM ( V_INFOLEFT ) ; 
			IF ( V_COUNT = 0 ) THEN 
				SELECT KHINORD INTO V_ORDRENOMEN FROM KNMREF WHERE KHIID = CAST ( TRIM ( V_INFOLEFT ) AS INTEGER ) ; 
				 
				CALL SP_NCHRONO ( 'KHKID' , V_IDNOMENCLATURELIEN ) ; 
						 
				INSERT INTO KNMVALF 
					( KHKID , KHKNMG , KHKTYPO , KHKORDR , KHKNIV , KHKMER , KHKKHIID ) 
				VALUES 
					( V_IDNOMENCLATURELIEN , P_CODEGRILLE , P_TYPOLOGIE , V_ORDRENOMEN , P_NIVEAU , P_NIVEAUMERE , CAST ( TRIM ( V_INFOLEFT ) AS INTEGER ) ) ; 
			END IF ; 
  
			SET V_DELCODE = TRIM ( V_DELCODE ) CONCAT ''',''' CONCAT TRIM ( V_INFOLEFT ) CONCAT '' ; 
			 
			CALL SP_SPLIT ( V_INFORIGHT , P_CHARSEPFIELD , 'L' , V_INFOLEFT ) ; 
			CALL SP_SPLIT ( V_INFORIGHT , P_CHARSEPFIELD , 'R' , V_INFORIGHT ) ; 
  
		END WHILE ; 
	END IF ; 
	 
	SET AT_END = 0 ; 
	 
	IF ( TRIM ( V_DELCODE ) != '' ) THEN 
		SET V_QUERY = 'SELECT KHKID FROM KNMVALF WHERE TRIM(KHKNMG) = ''' CONCAT TRIM ( P_CODEGRILLE ) CONCAT ''' AND TRIM(KHKTYPO) = ''' CONCAT TRIM ( P_TYPOLOGIE ) CONCAT ''' AND KHKMER = ' CONCAT P_NIVEAUMERE CONCAT ' AND KHKKHIID NOT IN (' CONCAT SUBSTR ( TRIM ( V_DELCODE ) , 3 ) CONCAT ''')' ; 
	ELSE 
		SET V_QUERY = 'SELECT KHKID FROM KNMVALF WHERE TRIM(KHKNMG) = ''' CONCAT TRIM ( P_CODEGRILLE ) CONCAT ''' AND TRIM(KHKTYPO) = ''' CONCAT TRIM ( P_TYPOLOGIE ) CONCAT ''' AND KHKMER = ' CONCAT P_NIVEAUMERE CONCAT ' AND KHKKHIID NOT IN (0)' ; 
	END IF ; 
  
	PREPARE S1 FROM V_QUERY ; 
	OPEN C1 ; 
	DEL_LOOP : LOOP 
		FETCH C1 INTO V_IDDEL ; 
		 
		IF AT_END = 1 THEN 
			LEAVE DEL_LOOP ; 
		END IF ; 
  
		FOR CURDEL2 AS FREE_LIST CURSOR FOR 
			SELECT KHKID IDDEL2 FROM KNMVALF WHERE KHKMER = V_IDDEL 
		DO 
			FOR CURDEL3 AS FREE_LIST CURSOR FOR 
				SELECT KHKID IDDEL3 FROM KNMVALF WHERE KHKMER = IDDEL2 
			DO 
				FOR CURDEL4 AS FREE_LIST CURSOR FOR 
					SELECT KHKID IDDEL4 FROM KNMVALF WHERE KHKMER = IDDEL3 
				DO 
					DELETE FROM KNMVALF WHERE KHKID = IDDEL4 OR KHKMER = IDDEL4 ; 
				END FOR ; 
				DELETE FROM KNMVALF WHERE KHKID = IDDEL3 ; 
			END FOR ; 
			DELETE FROM KNMVALF WHERE KHKID = IDDEL2 ; 
		END FOR ; 
		DELETE FROM KNMVALF WHERE KHKID = V_IDDEL ; 
		 
	END LOOP ; 
	CLOSE C1 ; 
		 
	SET P_QUERY = V_QUERY ; 
END P1  ; 
  

  

