CREATE OR REPLACE PROCEDURE  SP_SAVCONT ( 
	IN P_CODECONTRAT CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_UPDATEMODE CHAR(1) , 
	IN P_DATENOW INTEGER , 
	IN P_BRANCHE CHAR(2) , 
	IN P_CIBLE CHAR(10) , 
	IN P_PRENEURASS INTEGER , 
	IN P_DESCRIPTIF CHAR(40) , 
	IN P_COURTIERGEST INTEGER , 
	IN P_INTERLOCUTEUR INTEGER , 
	IN P_REFCOURTIER CHAR(25) , 
	IN P_ANNEEACCORD INTEGER , 
	IN P_MOISACCORD INTEGER , 
	IN P_JOURACCORD INTEGER , 
	IN P_HEURENOW INTEGER , 
	IN P_MOTCLE1 CHAR(10) , 
	IN P_MOTCLE2 CHAR(10) , 
	IN P_MOTCLE3 CHAR(10) , 
	IN P_SOUSCRIPTEUR CHAR(10) , 
	IN P_GESTIONNAIRE CHAR(10) , 
	IN P_ANNEEEFFET INTEGER , 
	IN P_MOISEFFET INTEGER , 
	IN P_JOUREFFET INTEGER , 
	IN P_HEUREEFFET INTEGER , 
	IN P_COURTIERAPP INTEGER , 
	IN P_TYPECONTRAT CHAR(1) , 
	IN P_USER CHAR(10) , 
	IN P_COURTIERPAY INTEGER , 
	IN P_CODEREMP CHAR(1) , 
	IN P_ADRCHR INTEGER , 
	IN P_OBSERVATION CHAR(5000) , 
	IN P_OBSVCHR INTEGER , 
	IN P_ENCAISSEMENT CHAR(1) , 
	IN P_CONTRATREMPLACE CHAR(1) , 
	IN P_CONXCHR INTEGER , 
	IN P_CODEREMPLACE CHAR(9) , 
	IN P_VERSIONREMPLACE INTEGER , 
	IN P_BRANCHEREMPLACE CHAR(2) , 
	IN P_INSADR CHAR(1) , 
	IN P_ADRBATIMENT CHAR(32) , 
	IN P_ADRNUMVOIE CHAR(10) , 
	IN P_ADRNUMVOIE2 CHAR(15) , 
	IN P_ADREXTVOIE CHAR(1) , 
	IN P_ADRNOMVOIE CHAR(32) , 
	IN P_ADRBP CHAR(32) , 
	IN P_ADRCP CHAR(5) , 
	IN P_ADRDEP CHAR(2) , 
	IN P_ADRVILLE CHAR(26) , 
	IN P_ADRCPX CHAR(5) , 
	IN P_ADRVILLEX CHAR(32) , 
	IN P_ADRMATHEX INTEGER , 
	IN P_PRENEURESTASSURE CHAR(1) , 
	IN P_AVENANT INTEGER , 
	IN P_TYPEAVT CHAR(10) , 
	IN P_ANNEEEFFETAVENANT INTEGER , 
	IN P_MOISEFFETAVENANT INTEGER , 
	IN P_JOUREFFETAVENANT INTEGER , 
	IN P_HEUREEFFETAVENANT INTEGER , 
	IN P_ISADDRESSEMPTY INTEGER , 
	IN P_ADRLATITUDE NUMERIC(10, 7) , 
	IN P_ADRLONGITUDE NUMERIC(10, 7) , 
	IN P_INSRSQOBJ INTEGER ,  
	OUT P_OUTCODECONTRAT CHAR(9) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_SAVCONT 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	DBGVIEW = *SOURCE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
	 
	DECLARE V_COUNT INTEGER DEFAULT 0 ; 
	DECLARE V_COUNTOBSV INTEGER DEFAULT 0 ; 
	DECLARE V_CODE_RISQUE INTEGER DEFAULT 0 ; 
	DECLARE V_CODE_OBJET INTEGER DEFAULT 0 ; 
	 
	 
	DECLARE V_ERROR CHAR ( 128 ) DEFAULT '' ; 
	 
	DECLARE V_DAYNOW CHAR ( 2 ) DEFAULT '' ; 
	DECLARE V_MONTHNOW CHAR ( 2 ) DEFAULT '' ; 
	DECLARE V_YEARNOW CHAR ( 4 ) DEFAULT '' ; 
	 
	DECLARE V_OBSVCHR INTEGER DEFAULT 0 ; 
	 
	DECLARE V_COUNTPRENEUR INTEGER DEFAULT 0 ; 
	DECLARE V_INTERLOCUTEURTYPE CHAR ( 1 ) DEFAULT '' ; 
	 
	DECLARE V_SOUSBRA CHAR ( 3 ) DEFAULT '' ; 
	DECLARE V_CATEGO CHAR ( 5 ) DEFAULT '' ; 
	 
  
	DECLARE V_MONTFRAISACC DECIMAL ( 7 , 0 ) DEFAULT 0 ; 
	DECLARE V_APPTAXEATT CHAR ( 1 ) DEFAULT '' ; 
	DECLARE V_TXCOMCATNAT DECIMAL ( 5 , 3 ) DEFAULT 0 ; 
	DECLARE V_INDEXATION CHAR ( 1 ) DEFAULT '' ; 
	DECLARE V_CODEINDICE CHAR ( 3 ) DEFAULT '' ; 
	DECLARE V_INDEXCAPITAUX CHAR ( 1 ) DEFAULT '' ; 
	DECLARE V_INDEXFRANCHISE CHAR ( 1 ) DEFAULT '' ; 
	DECLARE V_INDEXLCI CHAR ( 1 ) DEFAULT '' ; 
	DECLARE V_INDEXPRIME CHAR ( 1 ) DEFAULT '' ; 
	DECLARE V_CNA DECIMAL ( 5 , 3 ) DEFAULT 0 ; 
	DECLARE V_SOUMISCATNAT CHAR ( 1 ) DEFAULT '' ; 
	 
	DECLARE V_VALINDICEORIG DECIMAL ( 7 , 2 ) DEFAULT 0 ; 
	 
	 
	DECLARE V_OLDCOURTGES INTEGER DEFAULT 0 ; 
	DECLARE V_OLDCOURTAPP INTEGER DEFAULT 0 ; 
	DECLARE V_OLDCOURTPAY INTEGER DEFAULT 0 ; 
	 
	 
	DECLARE V_COURTDIRECT CHAR ( 1 ) DEFAULT '' ; 
	DECLARE V_TYPEENC CHAR ( 1 ) DEFAULT '' ; 
	DECLARE V_CODEENC CHAR ( 1 ) DEFAULT '' ; 
	DECLARE V_NEWCODEENC CHAR ( 1 ) DEFAULT '' ; 
	DECLARE V_PBORK CHAR ( 3 ) DEFAULT '' ; 
	 
	DECLARE V_DESIASSU INTEGER DEFAULT 0 ; 
	 
	DECLARE V_NBRSQ INTEGER DEFAULT 0 ; 
	DECLARE V_RSQADH INTEGER DEFAULT 0 ; 
	DECLARE V_CODERSQ INTEGER DEFAULT 0 ; 
  
	DECLARE V_NBOBJ INTEGER DEFAULT 0 ; 
	DECLARE V_OBJADH INTEGER DEFAULT 0 ; 
	DECLARE V_CODEOBJ INTEGER DEFAULT 0 ; 
  
	DECLARE V_ADRCHR INTEGER DEFAULT 0 ; 
	DECLARE V_NUMCHR CHAR ( 40 ) DEFAULT '' ; 
	 
	SET P_CODECONTRAT = LPAD ( TRIM ( P_CODECONTRAT ) , 9 , ' ');

	IF ( P_DATENOW > 0 ) THEN 
		SET V_YEARNOW = ABSVAL ( P_DATENOW / 10000 ) ; 
		SET V_MONTHNOW = ABSVAL ( ( P_DATENOW - ( V_YEARNOW * 10000 ) ) / 100 ) ; 
		SET V_DAYNOW = P_DATENOW - ( V_YEARNOW * 10000 ) - ( V_MONTHNOW * 100 ) ; 
	END IF ; 
	 
	IF ( TRIM ( P_CODECONTRAT ) LIKE 'CV%' ) THEN 
		SET V_PBORK = 'KVS' ; 
	ELSE 
		SET V_PBORK = 'KHE' ; 
	END IF ; 
  
  
	SELECT KAISBR , KAICAT INTO V_SOUSBRA , V_CATEGO 
		FROM KCIBLEF 
	WHERE KAICIBLE = P_CIBLE AND KAIBRA = P_BRANCHE ; 
  
	IF ( P_INTERLOCUTEUR <> 0 ) THEN 
		SET V_INTERLOCUTEURTYPE = 'T' ; 
	END IF ; 
	 
	 
	 
	IF ( P_UPDATEMODE = 'O' ) THEN 
		SELECT PBICT , PBCTA , PBCTP INTO V_OLDCOURTGES , V_OLDCOURTAPP , V_OLDCOURTPAY 
		FROM YPOBASE 
		WHERE PBIPB = P_CODECONTRAT AND PBALX = P_VERSION AND PBTYP = P_TYPE ; 
	 
		UPDATE YPOBASE 
			SET PBIAS = P_PRENEURASS , PBREF = P_DESCRIPTIF , PBSBR = V_SOUSBRA , PBCAT = V_CATEGO , PBICT = P_COURTIERGEST , 
				PBTIL = V_INTERLOCUTEURTYPE , PBIN5 = P_INTERLOCUTEUR , PBOCT = P_REFCOURTIER , 
				 
				PBSAA = P_ANNEEACCORD , PBSAM = P_MOISACCORD , PBSAJ = P_JOURACCORD , PBSAH = P_HEURENOW , 
				PBMO1 = P_MOTCLE1 , PBMO2 = P_MOTCLE2 , PBMO3 = P_MOTCLE3 , 
				PBSOU = P_SOUSCRIPTEUR , PBGES = P_GESTIONNAIRE , 
				PBEFA = P_ANNEEEFFET , PBEFM = P_MOISEFFET , PBEFJ = P_JOUREFFET , PBEFH = P_HEUREEFFET , 
				PBCTA = P_COURTIERAPP , PBAVA = P_ANNEEEFFETAVENANT , PBAVM = P_MOISEFFETAVENANT , PBAVJ = P_JOUREFFETAVENANT , 
				PBMER = P_TYPECONTRAT , PBMJU = P_USER , PBMJA = V_YEARNOW , PBMJM = V_MONTHNOW , PBMJJ = V_DAYNOW , 
				PBCTP = P_COURTIERPAY , PBPOR = P_CODEREMP				 
		WHERE PBIPB = P_CODECONTRAT AND PBALX = P_VERSION AND PBTYP = P_TYPE ; 
  
	ELSE 
		 
		INSERT INTO YPOBASE 
			( PBTYP , PBIPB , PBALX , PBTBR , PBIAS , PBREF , PBBRA , PBSBR , PBCAT , 
				PBICT , PBTIL , PBIN5 , PBOCT , 
				PBAD1 , 
				PBAD2 , PBDEP , PBCPO , PBVIL , PBPAY , 
				PBSAA , PBSAM , PBSAJ , PBSAH , PBAPR , PBAPP , 
				PBMO1 , PBMO2 , PBMO3 , PBCLE , PBANT , PBCTD , PBCTU , PBAPO , PBDUR , 
				PBREL , PBRLD , PBATT , PBRMP , PBVRF , PBOLV , PBFOA , PBFOM , PBCOU , 
				PBFOE , PBDEV , PBRGT , PBTCO , PBNAT , PBDST , PBLIE , 
				PBGES , PBSOU , PBORI , PBMAI , PBEFA , PBEFM , PBEFJ , PBOFF , PBOFV , 
				PBIPA , PBALA , PBECM , PBECJ , PBPCV , PBCTA , PBNRQ , PBNPL , 
				PBPER , PBAVN , PBAVC , PBAVA , PBAVM , PBAVJ , PBRSC , 
				PBRSA , PBRSM , PBRSJ , PBMER , PBETA , PBSIT , PBSTA , PBSTM , PBSTJ , 
				PBSTQ , PBEDT , PBTAC , PBTAA , PBTAM , PBTAJ , PBCRU , 
				PBCRA , PBCRM , PBCRJ , PBMJU , PBMJA , PBMJM , PBMJJ , PBDEU , 
				PBDEA , PBDEM , PBDEJ , PBCTP , PBEFH , PBFEA , PBFEM , PBFEJ , PBFEH , 
				PBSTP , PBNVA , PBFEC , PBPOR , PBCON , PBTTR , PBAVK , PBADH , PBSTF , PBORK ) 
		VALUES 
			( P_TYPE , P_CODECONTRAT , P_VERSION , P_BRANCHE , P_PRENEURASS , P_DESCRIPTIF , P_BRANCHE , V_SOUSBRA , V_CATEGO , 
				P_COURTIERGEST , V_INTERLOCUTEURTYPE , P_INTERLOCUTEUR , P_REFCOURTIER , 
				'' , 
				'' , '' , '' , '' , '' , 
				P_ANNEEACCORD , P_MOISACCORD , P_JOURACCORD , P_HEURENOW , '' , 100 , 
				P_MOTCLE1 , P_MOTCLE2 , P_MOTCLE3 , 'O' , '' , 0 , '' , '' , 0 , 
				'' , 0 , 0 , '' , 0 , 0 , 0 , '' , 0 , 
				'' , 'EUR' , '1' , '' , '' , '' , '' , 
				P_GESTIONNAIRE , P_SOUSCRIPTEUR , '' , 0 , P_ANNEEEFFET , P_MOISEFFET , P_JOUREFFET , '' , 0 , 
				'' , 0 , 0 , 0 , 100 , P_COURTIERAPP , '' , '' , 
				'' , 0 , '' , P_ANNEEEFFETAVENANT , P_MOISEFFETAVENANT , P_JOUREFFETAVENANT , '' , 
				0 , 0 , 0 , P_TYPECONTRAT , 'N' , 'A' , V_YEARNOW , V_MONTHNOW , V_DAYNOW , 
				'P' , 'N' , 'N' , 0 , 0 , 0 , P_USER , 
				V_YEARNOW , V_MONTHNOW , V_DAYNOW , P_USER , V_YEARNOW , V_MONTHNOW , V_DAYNOW , 'SPRINKS' , 
				V_YEARNOW , V_MONTHNOW , V_DAYNOW , P_COURTIERPAY , P_HEUREEFFET , 0 , 0 , 0 , 0 , 
				'' , '' , '' , P_CODEREMP , '' , 'AFFNV' , 0 , 0 , '' , V_PBORK ) ; 
	 
	END IF ; 
	 
	SELECT COUNT ( * ) INTO V_COUNTPRENEUR 
		FROM YPOASSU 
	WHERE PCTYP = P_TYPE AND PCIPB = P_CODECONTRAT AND PCALX = P_VERSION AND PCPRI = 'O' ; 
	 
	IF ( V_COUNTPRENEUR > 0 ) THEN 

		/* GESTION DU PRENEUR D'ASSURANCE 2015-02-26 */ 
		/* SUPPRESSION DU CO-ASSUREUR SI CELUI-CI DEVIENT LE PRENEUR PRINCIPAL */ 
		SELECT COUNT ( * ) INTO V_COUNTPRENEUR 
			FROM YPOASSU 
		WHERE PCTYP = P_TYPE AND PCIPB = P_CODECONTRAT AND PCALX = P_VERSION AND PCIAS = P_PRENEURASS AND PCPRI = 'N' ; 
		IF ( V_COUNTPRENEUR > 0 ) THEN 
			SELECT PCDESI INTO V_DESIASSU FROM YPOASSU WHERE PCTYP = P_TYPE AND PCIPB = P_CODECONTRAT AND PCALX = P_VERSION AND PCIAS = P_PRENEURASS AND PCPRI = 'N' ; 
			DELETE FROM KPDESI WHERE KADCHR = V_DESIASSU ; 
			DELETE FROM YPOASSU WHERE PCTYP = P_TYPE AND PCIPB = P_CODECONTRAT AND PCALX = P_VERSION AND PCIAS = P_PRENEURASS AND PCPRI = 'N' ; 
		END IF ; 

		/* FIN DE GESTION DU PRENEUR D'ASSURANCE */ 
		UPDATE YPOASSU 
			SET PCIAS = P_PRENEURASS 
		WHERE PCTYP = P_TYPE AND PCIPB = P_CODECONTRAT AND PCALX = P_VERSION AND PCPRI = 'O' ; 
	ELSE 
		INSERT INTO YPOASSU 
			( PCTYP , PCIPB , PCALX , PCIAS , PCPRI , PCQL1 , PCQL2 , PCQL3 , PCQLD , PCCNR , PCASS , PCSCP ) 
		VALUES 
			( P_TYPE , P_CODECONTRAT , P_VERSION , P_PRENEURASS , 'O' , '' , '' , '' , '' , 'N' , 'O' , 'O' ) ; 
	END IF ;	 
	/* GESTION DES COURTIERS 2015-02-12 ECM*/ 
	CALL SP_GESTIONCOURTIER ( P_CODECONTRAT , P_VERSION , P_TYPE , P_COURTIERGEST , V_OLDCOURTGES , P_COURTIERAPP , V_OLDCOURTAPP , P_COURTIERPAY , V_OLDCOURTPAY ) ; 
	/* FIN DE GESTION DES COURTIERS */ 

  
	SELECT COUNT ( * ) INTO V_COUNTOBSV FROM KPOBSV WHERE KAJCHR = P_OBSVCHR ; 
	IF ( P_UPDATEMODE = 'O' AND P_OBSVCHR <> 0 AND V_COUNTOBSV > 0 ) THEN 
	 
		SET V_OBSVCHR = P_OBSVCHR ; 
	 
		UPDATE KPOBSV 
			SET KAJOBSV = P_OBSERVATION 
		WHERE KAJCHR = V_OBSVCHR ; 
		 
	ELSE 
	 
		CALL SP_NCHRONO ( 'KAJCHR' , V_OBSVCHR ) ; 
		INSERT INTO KPOBSV 
			( KAJCHR , KAJIPB , KAJALX , KAJTYP , KAJTYPOBS , KAJOBSV ) 
		VALUES 
			( V_OBSVCHR , P_CODECONTRAT , P_VERSION , P_TYPE , 'GENERALE' , P_OBSERVATION ) ; 
	 
	END IF ; 
	SELECT CAAFR , CAATT , CACNC , CAINA , CAIND , CAIXC , CAIXF , CAIXL , CAIXP , CACNP 
				INTO V_MONTFRAISACC , V_APPTAXEATT , V_TXCOMCATNAT , V_INDEXATION , V_CODEINDICE , V_INDEXCAPITAUX , V_INDEXFRANCHISE , V_INDEXLCI , V_INDEXPRIME , V_CNA 
		FROM YCATEGO 
	WHERE CABRA = P_BRANCHE AND CASBR = V_SOUSBRA AND CACAT = V_CATEGO ; 
	 
	IF ( V_CNA <> 0 ) THEN 
	SET V_SOUMISCATNAT = 'O' ; 
	ELSE SET V_SOUMISCATNAT = 'N' ; 
	END IF ; 
	 
	IF ( V_INDEXATION = 'O' AND V_CODEINDICE <> '' ) THEN 
		SELECT GIIDV INTO V_VALINDICEORIG 
			FROM YINDICE 
		WHERE GIIND = V_CODEINDICE 
			AND ( GIIPA * 10000 + GIIPM * 100 + GIIPJ ) <= ( CAST ( P_ANNEEEFFET AS INTEGER ) * 10000 + CAST ( P_MOISEFFET AS INTEGER ) * 100 + CAST ( P_JOUREFFET AS INTEGER ) ) 
		ORDER BY GIIPA * 10000 + GIIPM * 100 + GIIPJ DESC 
		FETCH FIRST 1 ROWS ONLY ; 
	END IF ; 
	 
  
	IF ( P_UPDATEMODE = 'N' ) THEN 
	 
		INSERT INTO YPRTENT 
			( JDIPB , JDALX , JDENC , JDITC , JDVAL , JDVAA , JDVAW , JDVAT , JDVAU , JDVAH , 
				JDDRQ , JDNBR , JDTXL , JDTRR , JDXCM , JDNEX , JDNPA , JDAFC , JDAFR , JDATT , JDCNA , JDCNC , JDINA , 
				JDIND , JDIXC , JDIXF , JDIXL , JDIXP , JDIVO , JDIVA , JDIVW , JDMHT , JDREA , JDREB , JDREH , JDDPV , 
				JDGAU , JDGVL , JDGUN , JDPBN , JDPBS , JDPBR , JDPBT , JDPBC , JDPBP , 
				JDPBA , JDRCG , JDCCG , JDRCS , JDCCS , JDCLV , JDAGM , JDLCV , JDLCA , JDLCW , JDLCU , JDLCE , JDDPA , 
				JDDPM , JDDPJ , JDFPA , JDFPM , JDFPJ , JDPEA , JDPEM , JDPEJ , JDACQ , 
				JDTMC , JDTFO , JDTFT , JDTFF , JDTFP , JDPRO , JDTMI , JDTFM , JDTMA , JDTMG , JDCMC , JDCFO , JDCFT , 
				JDCFH , JDCHT , JDCTT , JDCCP , JDEHH , JDEHC , JDSMP , JDIVX , JDTCR , 
				JDNPG , JDEDI , JDEDN , JDEDA , JDEDM , JDEDJ , JDEHI , JDIAX , JDTED , JDDOO , JDRUA , JDRUM , JDRUJ , 
				JDECG , JDECP , JDAPT , JDAPR , JDAAT , JDAAR , JDACR , JDACV , JDAXT , 
				JDAXC , JDAXF , JDAXM , JDAXG , JDATA , JDATX , JDAUT , JDAUF , JDSHT ) 
		VALUES 
			( P_CODECONTRAT , P_VERSION , P_ENCAISSEMENT , '' , 0 , 0 , 0 , '' , '' , '' , 
				1 , 1 , 0 , '' , 0 , 0 , 0 , 'S' , V_MONTFRAISACC , V_APPTAXEATT , V_SOUMISCATNAT , V_TXCOMCATNAT , V_INDEXATION , 
				V_CODEINDICE , V_INDEXCAPITAUX , V_INDEXFRANCHISE , V_INDEXLCI , V_INDEXPRIME , 0 , 0 , 0 , 0 , '' , 0 , '' , 0 , 
				'' , 0 , '' , '' , 0 , 0 , 0 , 0 , 0 , 
				0 , '' , '' , '' , '' , '' , 0 , 0 , 0 , 0 , '' , '' , 0 , 
				0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 
				0 , '' , '' , 0 , 0 , '' , '' , '' , 0 , 0 , 0 , '' , '' , 
				'' , 0 , 0 , 0 , 0 , 0 , 0 , '' , '' , 
				0 , '' , 0 , 0 , 0 , 0 , 0 , '' , '' , '' , 0 , 0 , 0 , 
				'' , '' , '' , '' , '' , '' , '' , 0 , 0 , 
				0 , 0 , 0 , 0 , '' , 0 , 0 , 0 , 'H' ) ; 
	 
		INSERT INTO KPENT 
			( KAATYP , KAAIPB , KAAALX , KAADESI , KAAOBSV , KAAKDIID , KAAKDKID , KAAAND , KAAASS , KAACIBLE ) 
		VALUES 
			( P_TYPE , P_CODECONTRAT , P_VERSION , 0 , V_OBSVCHR , 0 , 0 , 0 , P_PRENEURESTASSURE , P_CIBLE ) ; 
			 
	ELSE 
	 
		UPDATE YPRTENT 
			SET JDENC = P_ENCAISSEMENT 
		WHERE JDIPB = P_CODECONTRAT AND JDALX = P_VERSION ; 
	 
		UPDATE KPENT 
			SET KAAASS = P_PRENEURESTASSURE , KAAOBSV = V_OBSVCHR 
		WHERE P_TYPE = KAATYP AND KAAIPB = P_CODECONTRAT AND KAAALX = P_VERSION ; 
	 
	END IF ; 

	/*TRAITEMENT DU TYPE D'ENCAISSEMENT 2015-02-12*/ 
	SELECT TCENC , TCYEN INTO V_COURTDIRECT , V_TYPEENC FROM YCOURTI WHERE TCICT = P_COURTIERAPP ; 
	SELECT JDENC INTO V_CODEENC FROM YPRTENT WHERE JDIPB = P_CODECONTRAT AND JDALX = P_VERSION ; 
  
	SET V_NEWCODEENC = V_CODEENC ; 
	IF ( V_COURTDIRECT = 'O' ) THEN 
		SET V_NEWCODEENC = 'D' ; 
	ELSE 
		IF ( V_CODEENC = '' ) THEN 
			IF ( V_TYPEENC = '' ) THEN 
				SET V_NEWCODEENC = 'C' ; 
			ELSE 
				SET V_NEWCODEENC = V_TYPEENC ; 
			END IF ; 
		ELSE 
			IF ( V_TYPEENC = 'D' ) THEN 
				SET V_NEWCODEENC = V_TYPEENC ; 
			END IF ; 
		END IF ; 
	END IF ; 
	UPDATE YPRTENT SET JDENC = V_NEWCODEENC WHERE JDIPB = P_CODECONTRAT AND JDALX = P_VERSION ; 
	IF ( P_CONTRATREMPLACE = 'O' ) THEN 
	 
		DELETE FROM YPOCONX 
			WHERE PJCNX = P_CONXCHR ; 
			 
		INSERT INTO YPOCONX 
			( PJTYP , PJCCX , PJCNX , PJIPB , PJALX , PJBRA , PJSBR , PJCAT ) 
		VALUES 
			( P_TYPE , '01' , P_CONXCHR , P_CODECONTRAT , P_VERSION , P_BRANCHE , '' , '' ) ; 
	 
		INSERT INTO YPOCONX 
			( PJTYP , PJCCX , PJCNX , PJIPB , PJALX , PJBRA , PJSBR , PJCAT ) 
		VALUES 
			( P_TYPE , '01' , P_CONXCHR , P_CODEREMPLACE , P_VERSIONREMPLACE , P_BRANCHEREMPLACE , '' , '' ) ; 
	 
	END IF ; 
	 
	IF ( P_UPDATEMODE = 'N' AND P_INSRSQOBJ = 1 ) THEN 
	 
		INSERT INTO YPRTRSQ 
			( JEIPB , JEALX , JERSQ , JECCH , JEBRA , JEOBJ , JEDRO , JENBO , JERGT , JECNA , JESBR , JECAT ) 
		VALUES 
			( P_CODECONTRAT , P_VERSION , 1 , 1 , P_BRANCHE , 1 , 1 , 1 , '1' , V_SOUMISCATNAT , V_SOUSBRA , V_CATEGO ) ; 
  
		INSERT INTO KPRSQ 
			( KABIPB , KABALX , KABTYP , KABRSQ , KABCIBLE , KABDESI , KABOBSV ) 
		VALUES 
			( P_CODECONTRAT , P_VERSION , P_TYPE , 1 , P_CIBLE , 0 , 0 ) ; 
			 
		INSERT INTO YPRTOBJ 
			( JGIPB , JGALX , JGRSQ , JGOBJ , JGCCH , JGBRA , JGSBR , JGCAT ) 
		VALUES 
			( P_CODECONTRAT , P_VERSION , 1 , 1 , 1 , P_BRANCHE , V_SOUSBRA , V_CATEGO ) ; 
  
		INSERT INTO KPOBJ 
			( KACIPB , KACALX , KACTYP , KACRSQ , KACOBJ , KACCIBLE , KACINVEN , KACDESI , KACOBSV ) 
		VALUES 
			( P_CODECONTRAT , P_VERSION , P_TYPE , 1 , 1 , P_CIBLE , 0 , 0 , 0 ) ; 
	 
	END IF ;	 
	 
	SET P_OUTCODECONTRAT = P_CODECONTRAT ; 
  
	/* ----------------------------------------------- */ 
	/* MODIFICATION DE LA SAUVEGARDE DE L'ADRESSE V4.1 */ 
	/* ----------------------------------------------- */ 
CALL SP_SAVCONT_ADR ( P_CODECONTRAT , P_VERSION , P_TYPE , P_ADRCHR , P_INSADR , P_ADRBATIMENT , P_ADRNUMVOIE , P_ADRNUMVOIE2 , P_ADREXTVOIE , P_ADRNOMVOIE , P_ADRBP , P_ADRCP , P_ADRDEP , P_ADRVILLE , P_ADRCPX , P_ADRVILLEX , P_ADRMATHEX , P_ISADDRESSEMPTY , P_ADRLATITUDE, P_ADRLONGITUDE) ; 
	/* ------------------------------------------------------ */ 
	/* FIN DE MODIFICATION DE LA SAUVEGARDE DE L'ADRESSE V4.1 */ 
	/* ------------------------------------------------------ */ 
  
	IF ( P_TYPEAVT > '' ) THEN 
		CALL SP_CHECKTRACE ( P_CODECONTRAT , P_VERSION , P_TYPE , P_AVENANT , 'BAS' , 
					'' , '' , '' , '' , '' , '' , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , '' , 0 , '' , '' , 0 , 0 , 0 , '' , 
					P_COURTIERGEST , P_ENCAISSEMENT , P_COURTIERPAY , P_PRENEURASS , P_PRENEURESTASSURE , P_ADRCP , P_ADRDEP , P_ADRVILLE , 
			P_USER , V_DAYNOW , V_MONTHNOW , V_YEARNOW , P_HEURENOW ) ; 
	END IF ; 
  
END P1  ; 

