CREATE PROCEDURE SP_SAVEQUITTANCESANNULEES ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_LISTEQUITT CHAR(1000) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_SAVEQUITTANCESANNULEES 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
	 
	DECLARE V_OBJ_LEFT VARCHAR ( 1000 ) DEFAULT '' ; 
	DECLARE V_OBJ_RIGHT VARCHAR ( 1000 ) DEFAULT '' ; 
	DECLARE V_LISTEQUITT VARCHAR ( 1000 ) DEFAULT '' ; 
	 
	 --Suppression des anciennes quittances annulées 
	DELETE FROM YWRTANP WHERE TRIM ( WWIPB ) = TRIM ( P_CODEOFFRE ) AND WWALX = P_VERSION ; 
	 
	CALL SP_SPLIT ( P_LISTEQUITT , '|' , 'L' , V_OBJ_LEFT ) ; 
	CALL SP_SPLIT ( P_LISTEQUITT , '|' , 'R' , V_OBJ_RIGHT ) ; 
	 
	WHILE ( TRIM ( V_OBJ_LEFT ) != '' ) DO 
		 
		INSERT INTO YWRTANP ( WWIPB , WWALX , WWIPK ) VALUES ( P_CODEOFFRE , P_VERSION , TRIM ( V_OBJ_LEFT ) ) ; 
	 
		SET V_LISTEQUITT = V_OBJ_RIGHT ; 
		CALL SP_SPLIT ( V_LISTEQUITT , '|' , 'L' , V_OBJ_LEFT ) ; 
		CALL SP_SPLIT ( V_LISTEQUITT , '|' , 'R' , V_OBJ_RIGHT ) ; 
	 
	END WHILE ; 
	 
	END P1  ; 
  

  

