CREATE PROCEDURE SP_SAVEROWDETAILEXPRCOMPLEXE ( 
	IN P_IDEXPR INTEGER , 
	IN P_TYPEEXPCOMPLEXE CHAR(9) , 
	IN P_IDROWEXPR INTEGER , 
	IN P_VALEXPR DECIMAL(13, 2) , 
	IN P_UNITEXPR CHAR(3) , 
	IN P_TYPEEXPR CHAR(3) , 
	IN P_CONCUVALEXPR DECIMAL(13, 2) , 
	IN P_CONCUUNITEXPR CHAR(3) , 
	IN P_CONCUTYPEEXPR CHAR(3) , 
	IN P_VALMINEXPR DECIMAL(13, 2) , 
	IN P_VALMAXEXPR DECIMAL(13, 2) , 
	IN P_DEBFRH INTEGER , 
	IN P_FINFRH INTEGER ) 
	LANGUAGE SQL 
	SPECIFIC SP_SAVEROWDETAILEXPRCOMPLEXE 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
DECLARE V_MAXORDRE INTEGER DEFAULT 1 ; 
  
IF ( P_TYPEEXPCOMPLEXE = 'LCI' ) THEN 
IF ( P_IDROWEXPR = 0 ) THEN 
CALL SP_NCHRONO ( 'KHHID' , P_IDROWEXPR ) ; 
SELECT IFNULL ( MAX ( KHHORDRE ) , 0 ) + 1 INTO V_MAXORDRE FROM KEXPLCID WHERE KHHKHGID = P_IDEXPR ; 
INSERT INTO KEXPLCID 
( KHHID , KHHKHGID , KHHORDRE , KHHLCVAL , KHHLCVAU , KHHLCBASE , KHHLOVAL , KHHLOVAU , KHHLOBASE ) 
VALUES 
( P_IDROWEXPR , P_IDEXPR , V_MAXORDRE , P_VALEXPR , P_UNITEXPR , P_TYPEEXPR , P_CONCUVALEXPR , P_CONCUUNITEXPR , P_CONCUTYPEEXPR ) ; 
ELSE 
UPDATE KEXPLCID 
SET KHHLCVAL = P_VALEXPR , KHHLCVAU = P_UNITEXPR , KHHLCBASE = P_TYPEEXPR , KHHLOVAL = P_CONCUVALEXPR , KHHLOVAU = P_CONCUUNITEXPR , KHHLOBASE = P_CONCUTYPEEXPR 
WHERE KHHID = P_IDROWEXPR ; 
END IF ; 
END IF ; 
  
IF ( P_TYPEEXPCOMPLEXE = 'FRANCHISE' ) THEN 
IF ( P_IDROWEXPR = 0 ) THEN 
CALL SP_NCHRONO ( 'KHFID' , P_IDROWEXPR ) ; 
SELECT IFNULL ( MAX ( KHFORDRE ) , 0 ) + 1 INTO V_MAXORDRE FROM KEXPFRHD WHERE KHFKHEID = P_IDEXPR ; 
INSERT INTO KEXPFRHD 
( KHFID , KHFKHEID , KHFORDRE , KHFFHVAL , KHFFHVAU , KHFBASE , KHFFHMINI , KHFFHMAXI , KHFLIMDEB , KHFLIMFIN ) 
VALUES 
( P_IDROWEXPR , P_IDEXPR , V_MAXORDRE , P_VALEXPR , P_UNITEXPR , P_TYPEEXPR , P_VALMINEXPR , P_VALMAXEXPR , P_DEBFRH , P_FINFRH ) ; 
ELSE 
UPDATE KEXPFRHD 
SET KHFFHVAL = P_VALEXPR , KHFFHVAU = P_UNITEXPR , KHFBASE = P_TYPEEXPR , KHFFHMINI = P_VALMINEXPR , KHFFHMAXI = P_VALMAXEXPR , KHFLIMDEB = P_DEBFRH , KHFLIMFIN = P_FINFRH 
WHERE KHFID = P_IDROWEXPR ; 
END IF ; 
END IF ; 
  
END P1  ; 
  

  

