CREATE PROCEDURE SP_SAVENOMENCLATURE ( 
	IN P_IDNOMENCLATURE INTEGER , 
	IN P_CODENOMENCLATURE CHAR(15) , 
	IN P_ORDRENOMENCLATURE NUMERIC(7, 2) , 
	IN P_LIBELLENOMENCLATURE CHAR(60) , 
	IN P_TYPOLOGIE CHAR(15) , 
	OUT P_RETURN CHAR(500) ) 
	LANGUAGE SQL 
	SPECIFIC SP_SAVENOMENCLATURE 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
	DECLARE V_COUNT INTEGER DEFAULT 0 ; 
	DECLARE V_ORDRE NUMERIC ( 7 , 2 ) DEFAULT 0 ; 
	 
	SET P_RETURN = '' ; 
	 
	SELECT COUNT ( * ) INTO V_COUNT FROM KNMREF WHERE KHIID = P_IDNOMENCLATURE ; 
	IF ( V_COUNT > 0 ) THEN 
	 
		SELECT COUNT ( * ) INTO V_COUNT FROM KNMREF WHERE TRIM ( KHITYPO ) = TRIM ( P_TYPOLOGIE ) AND KHINORD = P_ORDRENOMENCLATURE AND KHIID <> P_IDNOMENCLATURE ; 
		IF ( V_COUNT > 0 ) THEN 
			SET P_RETURN = 'ERRORNuméro d''ordre déjà présent pour cette typologie' ; 
		END IF ; 
		IF ( TRIM ( P_RETURN ) = '' ) THEN 
  
			UPDATE KNMREF 
				SET KHIDESI = TRIM ( P_LIBELLENOMENCLATURE ) , KHINORD = P_ORDRENOMENCLATURE 
			WHERE KHIID = P_IDNOMENCLATURE ; 
			 
			SET P_RETURN = CAST ( P_IDNOMENCLATURE AS CHAR ( 500 ) ) ; 
		END IF ;	 
  
	ELSE 
	 
		SELECT COUNT ( * ) INTO V_COUNT FROM KNMREF WHERE TRIM ( KHITYPO ) = TRIM ( P_TYPOLOGIE ) AND TRIM ( KHINMC ) = TRIM ( P_CODENOMENCLATURE ) ; 
		IF ( V_COUNT > 0 ) THEN 
			SET P_RETURN = 'ERRORCode déjà présent pour cette typologie' ; 
		END IF ; 
		 
		IF ( TRIM ( P_RETURN ) = '' ) THEN 
			SELECT COUNT ( * ) INTO V_COUNT FROM KNMREF WHERE TRIM ( KHITYPO ) = TRIM ( P_TYPOLOGIE ) AND KHINORD = P_ORDRENOMENCLATURE ; 
			IF ( V_COUNT > 0 ) THEN 
				SET P_RETURN = 'ERRORNuméro d''ordre déjà présent pour cette typologie' ; 
			END IF ; 
		END IF ; 
		 
		IF ( TRIM ( P_RETURN ) = '' ) THEN	 
  
			CALL SP_NCHRONO ( 'KHIID' , P_IDNOMENCLATURE ) ; 
			INSERT INTO KNMREF 
				( KHIID , KHITYPO , KHINMC , KHIDESI , KHINORD ) 
			VALUES 
				( P_IDNOMENCLATURE , TRIM ( P_TYPOLOGIE ) , TRIM ( P_CODENOMENCLATURE ) , TRIM ( P_LIBELLENOMENCLATURE ) , P_ORDRENOMENCLATURE ) ; 
				 
			SET P_RETURN = CAST ( P_IDNOMENCLATURE AS CHAR ( 500 ) ) ; 
		END IF ; 
  
	END IF ; 
	 
	/* Réordonnancement des nomenclatures */ 
	IF ( LOCATE ( 'ERROR' , P_RETURN ) = 0 ) THEN 
		SET V_ORDRE = 1 ; 
		FOR LOOP_DELUPD AS FREE_LIST CURSOR FOR 
			SELECT KHIID IDREF FROM KNMREF WHERE TRIM ( KHITYPO ) = TRIM ( P_TYPOLOGIE ) ORDER BY KHINORD 
		DO 
			UPDATE KNMREF SET KHINORD = V_ORDRE WHERE KHIID = IDREF ; 
			SET V_ORDRE = V_ORDRE + 1 ; 
		END FOR ; 
	END IF ; 
		 
END P1  ; 
  

  

