CREATE PROCEDURE SP_SAVEXPCOMPGENRSQ ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_CODERISQUE INTEGER , 
	IN P_CODEEXPR INTEGER , 
	IN P_TYPEAPPEL CHAR(20) , 
	IN P_TYPEVUE CHAR(20) , 
	IN P_UNITE CHAR(3) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_SAVEXPCOMPGENRSQ 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
DECLARE V_NBOBJ INTEGER DEFAULT 0 ; 
  
IF ( P_TYPEAPPEL = 'Generale' ) THEN 
IF ( P_TYPEVUE = 'LCI' ) THEN 
UPDATE KPENT SET KAAKDIID = P_CODEEXPR , KAALCIUNIT = P_UNITE 
WHERE KAATYP = P_TYPE AND KAAIPB = P_CODEOFFRE AND KAAALX = P_VERSION ; 
END IF ; 
IF ( P_TYPEVUE = 'Franchise' ) THEN 
UPDATE KPENT SET KAAKDKID = P_CODEEXPR , KAAFRHUNIT = P_UNITE 
WHERE KAATYP = P_TYPE AND KAAIPB = P_CODEOFFRE AND KAAALX = P_VERSION ; 
END IF ; 
  
  
END IF ; 
  
IF ( P_TYPEAPPEL = 'Risque' ) THEN 
SELECT COUNT ( * ) INTO V_NBOBJ FROM KPOBJ 
WHERE KACTYP = P_TYPE AND KACIPB = P_CODEOFFRE AND KACALX = P_VERSION AND KACRSQ = P_CODERISQUE ; 
  
IF ( P_TYPEVUE = 'LCI' ) THEN 
UPDATE KPRSQ SET KABKDIID = P_CODEEXPR , KABLCIUNIT = P_UNITE 
WHERE KABTYP = P_TYPE AND KABIPB = P_CODEOFFRE AND KABALX = P_VERSION AND KABRSQ = P_CODERISQUE ; 
--Si risque est monoobjet, les informations Franchise et LCI doivent être répliquées dans lobjet. 
IF ( V_NBOBJ = 1 ) THEN 
UPDATE KPOBJ SET KACKDIID = P_CODEEXPR , KACLCIUNIT = P_UNITE 
WHERE KACTYP = P_TYPE AND KACIPB = P_CODEOFFRE AND KACALX = P_VERSION AND KACRSQ = P_CODERISQUE ; 
END IF ; 
END IF ; 
  
IF ( P_TYPEVUE = 'Franchise' ) THEN 
UPDATE KPRSQ SET KABKDKID = P_CODEEXPR , KABFRHUNIT = P_UNITE 
WHERE KABTYP = P_TYPE AND KABIPB = P_CODEOFFRE AND KABALX = P_VERSION AND KABRSQ = P_CODERISQUE ; 
--Si risque est monoobjet, les informations Franchise et LCI doivent être répliquées dans lobjet. 
IF ( V_NBOBJ = 1 ) THEN 
UPDATE KPOBJ SET KACKDKID = P_CODEEXPR , KACFRHUNIT = P_UNITE 
WHERE KACTYP = P_TYPE AND KACIPB = P_CODEOFFRE AND KACALX = P_VERSION AND KACRSQ = P_CODERISQUE ; 
END IF ; 
END IF ; 
END IF ; 
  
END P1  ; 
  

  

