CREATE PROCEDURE SP_SAVECLAUSELIBRE ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_CODEAVT INTEGER , 
	IN P_CONTEXTE CHAR(10) , 
	IN P_ETAPE CHAR(10) , 
	IN P_DATE INTEGER , 
	IN P_CODERISQUE INTEGER , 
	IN P_CODEFORMULE INTEGER , 
	IN P_CODEOPTION INTEGER , 
	IN P_CODEOBJ INTEGER , 
	IN P_EMPLACEMENT CHAR(10) , 
	IN P_SOUSEMPLACEMENT CHAR(10) , 
	IN P_ORDRE DECIMAL(7, 3) , 
	OUT P_IDCLAUSE INTEGER ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_SAVECLAUSELIBRE 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
	DECLARE V_IDCLAUSE INTEGER DEFAULT 0 ; 
	DECLARE V_RUBRIQUE CHAR ( 5 ) DEFAULT '' ; 
	DECLARE V_SOUSRUBRIQUE CHAR ( 5 ) DEFAULT '' ; 
	DECLARE V_ORDREREF INTEGER DEFAULT 0 ; 
DECLARE V_RUBRIQUELIBRE INTEGER DEFAULT 0 ; 
	 
	SELECT KEIMDT1 , KEIMDT2 , KEIMDT3 INTO V_RUBRIQUE , V_SOUSRUBRIQUE , V_ORDREREF 
		FROM KALCONT 
		WHERE KEISERV = 'PRODU' AND KEIACTG = '**' AND KEIETAPE = P_ETAPE AND KEICTX = P_CONTEXTE ; 
  
	 --Recup num ordre max 
	SELECT IFNULL ( MAX ( CAST ( KCACLNM1 AS INTEGER ) ) , 0 ) INTO V_RUBRIQUELIBRE FROM KPCLAUSE 
	WHERE KCATYP = P_TYPE AND TRIM ( KCAIPB ) = TRIM ( P_CODEOFFRE ) AND KCAALX = P_VERSION AND KCACLNM2 = V_SOUSRUBRIQUE AND KCACLNM3 = V_ORDREREF AND KCAETAFF = P_ETAPE 
	AND LOWER ( KCACLNM1 ) = UPPER ( KCACLNM1 ) ;  --ON RÉCUPÈRE QUE LES KCACLNM1 CONVERTIBLES EN NUMÉRIQUE  
	SET V_RUBRIQUELIBRE = V_RUBRIQUELIBRE + 1 ; 
	 
	SET V_RUBRIQUE = RIGHT ( REPEAT ( '0' , 2 ) || V_RUBRIQUELIBRE , 2 ) ; 
	 
	CALL SP_NCHRONO ( 'KCAID' , V_IDCLAUSE ) ; 
  
	INSERT INTO KPCLAUSE 
		( KCAID , KCATYP , KCAIPB , KCAALX , KCAETAFF , KCAPERI , KCARSQ , KCAOBJ , 
			KCAINVEN , KCAINLGN , KCAFOR , KCAOPT , KCAGAR , KCACTX , KCAAJT , KCANTA , 
			KCACLNM1 , KCACLNM2 , KCACLNM3 , KCAVER , KCATXL , KCAMER , KCADOC , KCACHI , KCACHIS , KCAIMP , 
			KCACXI , KCAIAN , KCAIAC , KCASIT , KCASITD , KCAAVNC , KCACRD , KCAAVNM , 
			KCAMAJD , KCASPA , KCATYPO , KCAAIM , KCATAE , KCAXTL , KCAXTLM ) 
	VALUES 
		( V_IDCLAUSE , P_TYPE , P_CODEOFFRE , P_VERSION , P_ETAPE , P_ETAPE , P_CODERISQUE , P_CODEOBJ , 
			0 , 0 , P_CODEFORMULE , P_CODEOPTION , '' , P_CONTEXTE , 'O' , '' , 
			V_RUBRIQUE , V_SOUSRUBRIQUE , V_ORDREREF , 0 , 0 , 0 , 'CP' , P_EMPLACEMENT , P_SOUSEMPLACEMENT , 0 , 
			P_ORDRE , 'N' , '' , 'V' , P_DATE , P_CODEAVT , P_DATE , P_CODEAVT , 
			P_DATE , 'N' , '' , 'O' , '' , 'O' , 'O' ) ;	 
  
	SET P_IDCLAUSE = V_IDCLAUSE ; 
  
END P1  ; 
  

  

