CREATE PROCEDURE SP_SAVELCIFRHRSQ ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_LCIVALEURRISQUE NUMERIC(13, 2) , 
	IN P_LCIUNITERISQUE CHAR(3) , 
	IN P_LCITYPERISQUE CHAR(3) , 
	IN P_FRHVALEURRISQUE NUMERIC(13, 2) , 
	IN P_FRHUNITERISQUE CHAR(3) , 
	IN P_FRHTYPERISQUE CHAR(3) , 
	IN P_CODERISQUE INTEGER , 
	IN P_LIENCPXLCIRISQUE NUMERIC(15, 0) , 
	IN P_LIENCPXFRANCHISERISQUE NUMERIC(15, 0) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_SAVELCIFRHRSQ 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
DECLARE V_NBOBJ INTEGER DEFAULT 0 ; 
  
--Région LCIFranchise                               
UPDATE KPRSQ SET KABLCIVALO = P_LCIVALEURRISQUE , KABLCIVALA = P_LCIVALEURRISQUE , KABLCIUNIT = P_LCIUNITERISQUE , KABLCIBASE = P_LCITYPERISQUE , 
KABFRHVALO = P_FRHVALEURRISQUE , KABFRHVALA = P_FRHVALEURRISQUE , KABFRHUNIT = P_FRHUNITERISQUE , KABFRHBASE = P_FRHTYPERISQUE , 
KABKDIID = P_LIENCPXLCIRISQUE , KABKDKID = P_LIENCPXFRANCHISERISQUE 
WHERE KABTYP = P_TYPE AND KABIPB = P_CODEOFFRE AND KABALX = P_VERSION AND KABRSQ = P_CODERISQUE ; 
  
SELECT COUNT ( * ) INTO V_NBOBJ FROM KPOBJ 
WHERE KACTYP = P_TYPE AND KACIPB = P_CODEOFFRE AND KACALX = P_VERSION AND KACRSQ = P_CODERISQUE ; 
--Si risque est monoobjet, les informations Franchise et LCI doivent être répliquées dans lobjet. 
IF ( V_NBOBJ = 1 ) THEN 
UPDATE KPOBJ SET KACLCIVALO = P_LCIVALEURRISQUE , KACLCIVALA = P_LCIVALEURRISQUE , KACLCIUNIT = P_LCIUNITERISQUE , KACLCIBASE = P_LCITYPERISQUE , 
KACFRHVALO = P_FRHVALEURRISQUE , KACFRHVALA = P_FRHVALEURRISQUE , KACFRHUNIT = P_FRHUNITERISQUE , KACFRHBASE = P_FRHTYPERISQUE , 
KACKDIID = P_LIENCPXLCIRISQUE , KACKDKID = P_LIENCPXFRANCHISERISQUE 
WHERE KACTYP = P_TYPE AND KACIPB = P_CODEOFFRE AND KACALX = P_VERSION AND KACRSQ = P_CODERISQUE ; 
END IF ; 
  
END P1  ; 
  

  

