CREATE PROCEDURE SP_SAVEDETAILSDESTINATAIRE ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_SERVICE CHAR(10) , 
	IN P_ACTEGES CHAR(10) , 
	IN P_USER CHAR(10) , 
	IN P_DATENOW INTEGER , 
	IN P_HOURNOW INTEGER , 
	IN P_LOTID INTEGER , 
	IN P_TYPEDOC CHAR(10) , 
	IN P_COURRIERTYPE INTEGER , 
	IN P_CODEDOCUMENT INTEGER , 
	IN P_ID INTEGER , 
	IN P_ISPRINCIPAL CHAR(1) , 
	IN P_TYPEDESTINATAIRE CHAR(5) , 
	IN P_TYPEINTERVENANT CHAR(2) , 
	IN P_CODEDESTINATAIRE INTEGER , 
	IN P_CODEINTERLOCUTEUR INTEGER , 
	IN P_TYPEENVOI CHAR(2) , 
	IN P_NBEXEMPLAIRE INTEGER , 
	IN P_TAMPON CHAR(1) , 
	IN P_LETTREACC INTEGER , 
	IN P_LOTMAIL INTEGER , 
	IN P_ISGENERE CHAR(1) , 
	OUT P_NEWCODELOTD INTEGER ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_SAVEDETAILSDESTINATAIRE 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
	 
	DECLARE V_NEWIDDOCW1 NUMERIC ( 15 , 0 ) DEFAULT 0 ; 
	DECLARE V_NEWIDDOCLDW NUMERIC ( 15 , 0 ) DEFAULT 0 ; 
	DECLARE V_NEWIDDOCLW NUMERIC ( 15 , 0 ) DEFAULT 0 ; 
	DECLARE V_NUMORDRE INTEGER DEFAULT 0 ; 
	DECLARE V_ICT INTEGER DEFAULT 0 ; 
	DECLARE V_INL INTEGER DEFAULT 0 ; 
	DECLARE V_AVN INTEGER DEFAULT 0 ; 
	DECLARE V_IAS INTEGER DEFAULT 0 ; 
	DECLARE V_IDLETTRETYPE INTEGER DEFAULT 0 ; 
	DECLARE V_CHEMIN CHAR ( 150 ) DEFAULT '' ; 
	DECLARE V_LIBRE CHAR ( 1 ) DEFAULT '' ; 
	DECLARE V_PRINT CHAR ( 1 ) DEFAULT '' ; 
	DECLARE V_LIBELLE CHAR ( 60 ) DEFAULT '' ; 
	 
	DECLARE V_LIBDOC CHAR ( 60 ) DEFAULT '' ; 
	DECLARE V_CODEDOC CHAR ( 15 ) DEFAULT '' ; 
	 
	SET P_NEWCODELOTD = 0 ; 
	 
	IF ( P_ID < 1 ) THEN  --MODE CRÉATION 
		SELECT IFNULL ( MAX ( KEMORD ) , 0 ) INTO V_NUMORDRE FROM KPDOCLDW ; 
		SET V_NUMORDRE = V_NUMORDRE + 1 ; 
		 
		SELECT PBICT , PBIN5 , PBAVN , PBIAS INTO V_ICT , V_INL , V_AVN , V_IAS FROM YPOBASE WHERE TRIM ( PBIPB ) = TRIM ( P_CODEOFFRE ) AND PBALX = P_VERSION AND PBTYP = P_TYPE ; 
  
		SET V_CHEMIN = '' ; 
		SELECT '//' CONCAT TRIM ( KHMSRV ) CONCAT '/' CONCAT TRIM ( KHMRAC ) CONCAT '/' CONCAT TRIM ( KHMENV ) CONCAT TRIM ( KHMCHM ) CONCAT '/' INTO V_CHEMIN FROM KCHEMIN WHERE KHMCLE = 'DOC_LETTYP' ; 
		SET V_CHEMIN = REPLACE ( V_CHEMIN , '\\' , '/' ) ; 
  
		SELECT TPCA1 , TPCA2 INTO V_PRINT , V_LIBRE FROM YYYYPAR WHERE TCON = 'KHEOP' AND TFAM = 'TDOC' AND TRIM ( TCOD ) = TRIM ( P_TYPEDOC ) ; 
  
		SELECT TRIM ( KDULIB ) , TRIM ( KDUNM1 ) CONCAT '_' CONCAT TRIM ( KDUNM2 ) CONCAT '_' CONCAT TRIM ( KDUNM3 ) INTO V_LIBDOC , V_CODEDOC 
			FROM KCLAUSE WHERE KDUID = P_COURRIERTYPE ; 
		 
		/* SELECT KEQID INTO V_IDLETTRETYPE FROM KPDOCW WHERE TRIM ( KEQIPB ) = TRIM ( P_CODEOFFRE ) AND KEQALX = P_VERSION AND KEQTYP = P_TYPE AND TRIM ( KEQTDOC ) = 'LETTYP' ;  */ 
  
		IF ( P_LOTID = 0 ) THEN 
			/* INSERTION DANS KPDOCLW */ 
			SELECT TPLIL INTO V_LIBELLE FROM YYYYPAR WHERE TCON = 'KHEOP' AND TFAM = 'ACTGS' AND TCOD = P_ACTEGES ; 
			CALL SP_NCHRONO ( 'KELID' , V_NEWIDDOCLW ) ; 
			INSERT INTO KPDOCLW 
				( KELID , KELTYP , KELIPB , KELALX , KELSUA , KELNUM , KELSBR , KELSERV , KELACTG , KELACTN , KELAVN , KELLIB , KELSTU , KELSIT , KELSTD , KELSTH , KELCRU , KELCRD , KELCRH , KELMAJU , KELMAJD , KELMAJH , KELEMI , KELIPK ) 
			VALUES 
				( V_NEWIDDOCLW , P_TYPE , P_CODEOFFRE , P_VERSION , 0 , 0 , '' , P_SERVICE , P_ACTEGES , 1 , V_AVN , V_LIBELLE , P_USER , 'A' , P_DATENOW , P_HOURNOW , P_USER , P_DATENOW , P_HOURNOW , P_USER , P_DATENOW , P_HOURNOW , '' , 0 ) ; 
			SET P_LOTID = V_NEWIDDOCLW ; 
		END IF ; 
		 
		 
		/* INSERTION DANS KPDOCW */ 
		CALL SP_NCHRONO ( 'KEQID' , V_NEWIDDOCW1 ) ; 
		INSERT INTO KPDOCW 
			( KEQID , KEQTYP , KEQIPB , KEQALX , KEQSUA , KEQNUM , KEQSBR , KEQSERV , KEQACTG , KEQACTN , KEQECO , KEQAVN , KEQETAP , KEQKEMID , KEQORD , KEQTDOC , KEQKESID , KEQAJT , KEQTRS , KEQMAIT , KEQLIEN , 
				KEQCDOC , KEQVER , KEQLIB , KEQNTA , KEQDACC , KEQTAE , KEQNOM , KEQCHM , KEQSTU , KEQSIT , KEQSTD , KEQSTH , KEQENVU , KEQENVD , KEQENVH , KEQTEDI , KEQORID , KEQTYDS , KEQTYI , KEQIDS , KEQINL , 
				KEQNBEX , KEQCRU , KEQCRD , KEQCRH , KEQMAJU , KEQMAJD , KEQMAJH , KEQSTG , KEQDIMP , KEQTGL ) 
		VALUES 
			( V_NEWIDDOCW1 , P_TYPE , P_CODEOFFRE , P_VERSION , 0 , 0 , 0 , P_SERVICE , P_ACTEGES , 1 , 'O' , V_AVN , 'FIN' , 0 , 1 , P_TYPEDOC , 0 , 'O' , 'N' , '' , 0 , 
			V_CODEDOC , 0 , V_LIBDOC , '' , 'N' , '' , '' , V_CHEMIN , P_USER , 'V' , P_DATENOW , P_HOURNOW , P_USER , P_DATENOW , P_HOURNOW , 'O' , 0 , P_TYPEDESTINATAIRE , P_TYPEINTERVENANT , P_CODEDESTINATAIRE , P_CODEINTERLOCUTEUR , 
			0 , P_USER , P_DATENOW , P_HOURNOW , P_USER , P_DATENOW , P_HOURNOW , 'N' , V_PRINT , V_LIBRE ) ; 
		 
		/* INSERTION DANS KPDOCLDW */ 
		CALL SP_NCHRONO ( 'KEMID' , V_NEWIDDOCLDW ) ; 
		INSERT INTO KPDOCLDW 
			( KEMID , KEMKELID , KEMORD , KEMTYPD , KEMTYPL , KEMTYENV , KEMTAMP , KEMTYDS , KEMTYI , KEMIDS , KEMINL , KEMNBEX , KEMDOCA , KEMTYDIF , KEMLMAI , KEMAEMO , KEMAEM , KEMKESID , 
				KEMSTU , KEMSIT , KEMSTD , KEMSTH , KEMENVU , KEMENVD , KEMENVH ) 
		VALUES 
			( V_NEWIDDOCLDW , P_LOTID , V_NUMORDRE , 'G' , V_NEWIDDOCW1 , P_TYPEENVOI , P_TAMPON , P_TYPEDESTINATAIRE , P_TYPEINTERVENANT , P_CODEDESTINATAIRE , P_CODEINTERLOCUTEUR , 1 , 0 , 'COUR' , P_LOTMAIL , '' , '' , 0 , 
				P_USER , 'O' , P_DATENOW , P_HOURNOW , '' , 0 , 0 ) ; 
		 
		SET P_NEWCODELOTD = V_NEWIDDOCLDW ; 
	ELSE  --MODE MISE À JOUR 
		SELECT KEMTYPL INTO V_NEWIDDOCW1 FROM KPDOCLDW WHERE KEMID = P_ID ; 
		 
		SET V_CHEMIN = '' ; 
		SELECT '//' CONCAT TRIM ( KHMSRV ) CONCAT '/' CONCAT TRIM ( KHMRAC ) CONCAT '/' CONCAT TRIM ( KHMENV ) CONCAT TRIM ( KHMCHM ) CONCAT '/' INTO V_CHEMIN FROM KCHEMIN WHERE KHMCLE = 'DOC_LETTYP' ; 
		SET V_CHEMIN = REPLACE ( V_CHEMIN , '\\' , '/' ) ; 
  
		SELECT TPCA1 , TPCA2 INTO V_PRINT , V_LIBRE FROM YYYYPAR WHERE TCON = 'KHEOP' AND TFAM = 'TDOC' AND TCOD = TRIM ( P_TYPEDOC ) ; 
  
		SELECT TRIM ( KDULIB ) , TRIM ( KDUNM1 ) CONCAT '_' CONCAT TRIM ( KDUNM2 ) CONCAT '_' CONCAT TRIM ( KDUNM3 ) INTO V_LIBDOC , V_CODEDOC 
			FROM KCLAUSE WHERE KDUID = P_COURRIERTYPE ; 
  
		UPDATE KPDOCW 
			SET KEQTYDS = P_TYPEDESTINATAIRE , KEQTYI = P_TYPEINTERVENANT , KEQIDS = P_CODEDESTINATAIRE , KEQINL = P_CODEINTERLOCUTEUR , 
				KEQLIB = V_LIBDOC , KEQCDOC = V_CODEDOC  --, KEQNOM = '' , KEQSTG = 'N' 
		WHERE KEQID = V_NEWIDDOCW1 ; 
		 
		UPDATE KPDOCLDW 
			SET KEMDSTP = P_ISPRINCIPAL , KEMTYDS = P_TYPEDESTINATAIRE , KEMIDS = P_CODEDESTINATAIRE , KEMINL = P_CODEINTERLOCUTEUR , 
			KEMTYENV = P_TYPEENVOI , KEMNBEX = P_NBEXEMPLAIRE , KEMTAMP = P_TAMPON , KEMDOCA = P_LETTREACC , KEMLMAI = P_LOTMAIL , KEMSIT = 'O' 
		WHERE KEMID = P_ID ; 
		 
		SET P_NEWCODELOTD = P_ID ; 
	END IF ; 
	 
END P1  ; 
  

  

