CREATE PROCEDURE SP_SAVEINTERVENANT ( 
	IN P_MODE CHAR(10) , 
	IN P_CODE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_CODEAVENANT INTEGER , 
	IN P_GUIDID INTEGER , 
	IN P_TYPEINTERV CHAR(2) , 
	IN P_IDINTERV INTEGER , 
	IN P_CODEINTERLOC INTEGER , 
	IN P_REFERENCE CHAR(60) , 
	IN P_ISPRINCIPAL CHAR(1) , 
	IN P_ISMEDECINCONSEIL CHAR(1) , 
	IN P_USER CHAR(10) , 
	IN P_DATENOW INTEGER , 
	IN P_HEURENOW INTEGER ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_SAVEINTERVENANT 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
		 
		DECLARE V_ACT CHAR ( 1 ) DEFAULT '' ; 
		DECLARE V_NEWCODE INTEGER DEFAULT 0 ; 
		DECLARE V_NEWCODEINTER INTEGER DEFAULT 0 ; 
		 
	IF ( TRIM ( P_MODE ) = 'INSERT' ) THEN 
	 --MODE CRÉATION		 
		CALL SP_NCHRONO ( 'KHBID' , V_NEWCODEINTER ) ; 
	 
		INSERT INTO KPINTER 
			( KHBID , KHBTYP , KHBIPB , KHBALX , KHBTYI , KHBIIN , KHBINL , KHBREF , KHBPRP , KHBMDC ) 
		VALUES 
			( V_NEWCODEINTER , P_TYPE , P_CODE , P_VERSION , P_TYPEINTERV , P_IDINTERV , P_CODEINTERLOC , P_REFERENCE , P_ISPRINCIPAL , P_ISMEDECINCONSEIL ) ; 
		SET V_ACT = 'C' ; 
		SET P_GUIDID = V_NEWCODEINTER ; 
	ELSE 
	 --MODE MISE À JOUR 
		UPDATE KPINTER 
			SET KHBINL = P_CODEINTERLOC , 
			KHBREF = P_REFERENCE , 
			KHBPRP = P_ISPRINCIPAL , 
			KHBMDC = P_ISMEDECINCONSEIL 
		WHERE KHBTYP = P_TYPE 
			AND TRIM ( KHBIPB ) = TRIM ( P_CODE ) 
			AND KHBALX = P_VERSION 
			AND KHBID = P_GUIDID ; 
		 
		SET V_ACT = 'M' ; 
	END IF ; 
	 
	IF ( P_ISPRINCIPAL = 'O' ) THEN 
		UPDATE KPINTER 
			SET KHBPRP = 'N' 
		WHERE KHBTYP = P_TYPE 
			AND TRIM ( KHBIPB ) = TRIM ( P_CODE ) 
			AND KHBALX = P_VERSION 
			AND KHBID <> P_GUIDID AND KHBID <> V_NEWCODEINTER 
			AND KHBTYI = P_TYPEINTERV ; 
	END IF ; 
  
	IF ( P_ISMEDECINCONSEIL = 'O' ) THEN 
		UPDATE KPINTER 
			SET KHBMDC = 'N' 
		WHERE KHBTYP = P_TYPE 
			AND TRIM ( KHBIPB ) = TRIM ( P_CODE ) 
			AND KHBALX = P_VERSION 
			AND KHBID <> P_GUIDID ; 
	END IF ; 
  
	IF ( P_CODEAVENANT > 0 ) THEN 
		CALL SP_NCHRONO ( 'KHOID' , V_NEWCODE ) ; 
	 
		DELETE FROM KPAVTRC WHERE TRIM ( KHOIPB ) = TRIM ( P_CODE ) AND KHOALX = P_VERSION AND KHOTYP = P_TYPE AND TRIM ( KHOPERI ) = 'INTERVE' AND KHOACT = V_ACT ; 
		INSERT INTO KPAVTRC 
			( KHOID , KHOIPB , KHOALX , KHOTYP , KHOPERI , KHOETAPE , KHOACT , KHOCRU , KHOCRD , KHOCRH ) 
		VALUES 
			( V_NEWCODE , P_CODE , P_VERSION , P_TYPE , 'INTERVE' , '**********' , V_ACT , P_USER , P_DATENOW , P_HEURENOW ) ; 
	END IF ; 
	 
				 
END P1  ; 
  

  

