CREATE PROCEDURE SP_SECOPID ( 
	IN P_CODEOFFRE VARCHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE VARCHAR(1) , 
	IN P_TABLE VARCHAR(10) , 
	IN P_CODEID INTEGER , 
	OUT P_NEWCODEID INTEGER ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_SECOPID 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
SET P_NEWCODEID = 0 ; 
  
SELECT IFNULL ( KFLIDC , 0 ) INTO P_NEWCODEID FROM KPCOPID 
WHERE KFLTYP = P_TYPE AND KFLIPB = P_CODEOFFRE AND KFLALX = P_VERSION AND KFLTAB = P_TABLE AND KFLIDO = P_CODEID ; 
  
END P1  ; 
  

  

