CREATE PROCEDURE SP_SETTRACEDELETEPARAM ( 
	IN P_PARAM CHAR(10) , 
	IN P_CODEPARAM CHAR(50) , 
	IN P_TABLE CHAR(10) , 
	IN P_INFOUSER CHAR(100) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_SETTRACEDELETEPARAM 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
/* 	INSERT INTO TABLETRACEDELETE        
		(ID, PARAM, CODE, TABLE, INFOUSER)        
	VALUES        
		(V_NEWID, P_PARAM, P_CODEPARAM, P_TABLE, P_INFOUSER); */ 
END P1  ; 
  

  

