CREATE PROCEDURE SP_SUPPRINVENTAIRE ( 
	IN P_IDINVENTAIRE INTEGER , 
	OUT P_RETURN INTEGER ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_SUPPRINVENTAIRE 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	DBGVIEW = *SOURCE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
		DECLARE V_NBLIGN INTEGER DEFAULT 0 ; 
		DECLARE CURSORINVENTAIRE CURSOR FOR SELECT * 
		FROM KINVTYP 
		ORDER BY KAGTYINV ; 
  
		SET V_NBLIGN = 0 ; 
  
		SELECT COUNT ( * ) INTO V_NBLIGN 
		FROM KPINVEN 
		WHERE KBEKAGID = P_IDINVENTAIRE ; 
		 
	IF ( V_NBLIGN > 0 ) THEN 
		SET P_RETURN = 0 ; 
	ELSE 
		DELETE FROM KINVTYP WHERE KAGID = P_IDINVENTAIRE ; 
		SET P_RETURN = 1 ; 
		END IF ; 
		 
		OPEN CURSORINVENTAIRE ; 
		 
END P1  ; 
  

  

