CREATE PROCEDURE SP_UPFRACC ( 
	IN P_ID_OFFRE CHAR(9) , 
	IN P_TYPE_OFFRE CHAR(1) , 
	IN P_VERSION_OFFRE NUMERIC(5, 0) , 
	IN P_TYPEFRAIS CHAR(1) , 
	IN P_FRAIS_RETENUS NUMERIC(7, 0) , 
	IN P_TAXE_ATTENTAT CHAR(1) , 
	IN P_COMMENTAIRES CHAR(5000) , 
	IN P_CODE_COMMENTAIRES INTEGER , 
	IN P_ACTEGESTION CHAR(5) , 
	IN P_ISHORSAVN INTEGER , 
	OUT P_ERREUR CHAR(128) ) 
	LANGUAGE SQL 
	SPECIFIC SP_UPFRACC 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
DECLARE V_NUMAVENANT DECIMAL ( 3 , 0 ) DEFAULT 0 ; 
DECLARE V_PKMHT DECIMAL ( 11 , 2 ) DEFAULT 0 ; 
  
SELECT PBAVN INTO V_NUMAVENANT 
FROM YPOBASE 
WHERE TRIM ( PBIPB ) = TRIM ( P_ID_OFFRE ) AND PBALX = P_VERSION_OFFRE AND PBTYP = P_TYPE_OFFRE ; 
IF ( P_ISHORSAVN = 0 ) THEN 
  
		IF ( TRIM ( P_ACTEGESTION ) = 'AVNRG' OR TRIM ( P_ACTEGESTION ) = 'REGUL' ) THEN 
		SELECT PKMHT INTO V_PKMHT FROM YPRIRES WHERE TRIM ( PKIPB ) = TRIM ( P_ID_OFFRE ) AND PKALX = P_VERSION_OFFRE AND PKAVN = V_NUMAVENANT ; 
		ELSE 
		SELECT PKMHT INTO V_PKMHT FROM YPRIPES WHERE TRIM ( PKIPB ) = TRIM ( P_ID_OFFRE ) AND PKALX = P_VERSION_OFFRE AND PKAVN = V_NUMAVENANT ; 
		END IF ; 
ELSE 
		SELECT PKMHT INTO V_PKMHT 
		FROM YPRIMES 
		WHERE TRIM ( PKIPB ) = TRIM ( P_ID_OFFRE ) 
				AND PKALX = P_VERSION_OFFRE 
				AND PKAVN = V_NUMAVENANT 
				ORDER BY PKIPK DESC 
				FETCH FIRST 1 ROWS ONLY ; 
END IF ; 
  
IF ( V_PKMHT < 0 AND P_TAXE_ATTENTAT = 'O' AND V_NUMAVENANT <> 0 ) THEN 
SET P_ERREUR = 'Il ne peut pas y avoir de FGA sur une ristourne' ; 
ELSE 
IF ( P_TYPEFRAIS = 'P' AND P_FRAIS_RETENUS = 0 ) THEN 
SET P_ERREUR = 'Frais retenus doit être supérieur à 0' ; 
ELSE IF ( ( P_TYPEFRAIS = 'P' OR P_TYPEFRAIS = 'N' ) AND P_COMMENTAIRES = '' AND P_TYPE_OFFRE = 'P' ) THEN 
SET P_ERREUR = 'Commentaires obligatoires' ; 
ELSE 
IF ( P_CODE_COMMENTAIRES = 0 AND P_COMMENTAIRES != '' ) THEN 
CALL SP_NCHRONO ( 'KAJCHR' , P_CODE_COMMENTAIRES ) ; 
INSERT INTO KPOBSV ( KAJCHR , KAJTYP , KAJIPB , KAJALX , KAJTYPOBS , KAJOBSV ) 
VALUES ( P_CODE_COMMENTAIRES , P_TYPE_OFFRE , P_ID_OFFRE , P_VERSION_OFFRE , 'GENERALE' , TRIM ( P_COMMENTAIRES ) ) ; 
ELSE IF ( P_CODE_COMMENTAIRES != 0 ) THEN 
UPDATE KPOBSV 
SET KAJOBSV = TRIM ( P_COMMENTAIRES ) 
WHERE KAJCHR = P_CODE_COMMENTAIRES ; 
END IF ; 
END IF ; 
UPDATE KPENT 
SET  --KAAAFS = P_FRAIS_SPECIFIQUES , 
KAAOBSC = P_CODE_COMMENTAIRES 
WHERE TRIM ( KAAIPB ) = TRIM ( P_ID_OFFRE ) AND KAAALX = P_VERSION_OFFRE ; 
  
--bug 2567 
UPDATE YPRTENT 
SET JDAFC = P_TYPEFRAIS , 
JDAFR = P_FRAIS_RETENUS , 
JDATT = P_TAXE_ATTENTAT 
WHERE TRIM ( JDIPB ) = TRIM ( P_ID_OFFRE ) AND JDALX = P_VERSION_OFFRE ; 
  
END IF ; 
END IF ; 
END IF ; 
END P1  ;
  

  

