CREATE PROCEDURE SP_UPDATT ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_FIELD CHAR(3) , 
	IN P_VALUE NUMERIC(13, 2) , 
	IN P_COMMENTFORCE CHAR(5000) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_UPDATT 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
DECLARE V_IDCOMMENT INTEGER DEFAULT 0 ; 
  
SELECT KAAOBSA INTO V_IDCOMMENT FROM KPENT WHERE KAATYP = P_TYPE AND KAAIPB = P_CODEOFFRE AND KAAALX = P_VERSION ; 
  
IF ( V_IDCOMMENT != 0 ) THEN 
UPDATE KPOBSV SET KAJOBSV = P_COMMENTFORCE 
WHERE KAJCHR = V_IDCOMMENT ; 
ELSE 
CALL SP_NCHRONO ( 'KAJCHR' , V_IDCOMMENT ) ; 
INSERT INTO KPOBSV 
( KAJCHR , KAJIPB , KAJALX , KAJTYP , KAJOBSV ) 
VALUES 
( V_IDCOMMENT , P_CODEOFFRE , P_VERSION , P_TYPE , P_COMMENTFORCE ) ; 
END IF ; 
  
CASE P_FIELD 
WHEN 'REC' THEN 
UPDATE KPENT SET KAAATGCAF = P_VALUE , KAAOBSA = V_IDCOMMENT WHERE KAAIPB = P_CODEOFFRE AND KAAALX = P_VERSION AND KAATYP = P_TYPE ; 
WHEN 'COM' THEN 
UPDATE KPENT SET KAAATGTCM = P_VALUE , KAAOBSA = V_IDCOMMENT WHERE KAAIPB = P_CODEOFFRE AND KAAALX = P_VERSION AND KAATYP = P_TYPE ; 
ELSE 
UPDATE KPENT SET KAAATGCAF = P_VALUE , KAAOBSA = V_IDCOMMENT WHERE KAAIPB = P_CODEOFFRE AND KAAALX = P_VERSION AND KAATYP = P_TYPE ; 
END CASE ; 
  
  
END P1  ; 
  

  

