CREATE PROCEDURE SP_UPDATEKGRPTRG ( 
	IN P_TYP CHAR(1) , 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION NUMERIC(5, 0) , 
	IN P_TRIGREDTABLE CHAR(20) , 
	IN P_TRIGREDFILEDS CHAR(20) ) 
	LANGUAGE SQL 
	SPECIFIC SP_UPDATEKGRPTRG 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *NONE , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
DECLARE V_COUNT INTEGER DEFAULT 0 ; 
DECLARE V_PBMJA INTEGER DEFAULT 0 ; 
DECLARE V_PBMJM INTEGER DEFAULT 0 ; 
DECLARE V_PBMJJ INTEGER DEFAULT 0 ; 
DECLARE V_TIMEMODIF CHAR ( 26 ) DEFAULT '' ; 
  
--SELECT PBMJA , PBMJM , PBMJJ INTO V_PBMJA , V_PBMJM , V_PBMJJ 
--FROM YPOBASE 
--WHERE PBTYP = P_TYP AND QSYS2 . TRIM ( PBIPB ) = QSYS2 . TRIM ( P_CODEOFFRE ) AND PBALX = P_VERSION ; 
SELECT COUNT ( * ) INTO V_COUNT 
FROM KGRPTRG 
WHERE KDZTYP = P_TYP AND QSYS2 . TRIM ( KDZIPB ) = QSYS2 . TRIM ( P_CODEOFFRE ) AND KDZALX = P_VERSION AND KDZTRT = 'N' ; 
  
IF ( V_COUNT = 0 ) THEN 
INSERT INTO KGRPTRG 
( KDZTYP , KDZIPB , KDZALX , KDZTRT , KDZMAJA , KDZMAJM , KDZMAJJ , KDZACT , KDZOBS ) 
VALUES 
( P_TYP , QSYS2 . RIGHT ( QSYS2 . REPEAT ( ' ' , 9 ) || P_CODEOFFRE , 9 ) , P_VERSION , 'N' , V_PBMJA , V_PBMJM , V_PBMJJ , 'M' , '' ) ; 
ELSE 
UPDATE KGRPTRG 
SET KDZTRT = 'N' , KDZMAJA = V_PBMJA , KDZMAJM = V_PBMJM , KDZMAJJ = V_PBMJJ , KDZACT = 'M' , KDZOBS = '' 
WHERE KDZTYP = P_TYP AND QSYS2 . TRIM ( KDZIPB ) = QSYS2 . TRIM ( P_CODEOFFRE ) AND KDZALX = P_VERSION ; 
END IF ; 
SET V_TIMEMODIF = CAST ( QSYS2 . NOW ( ) AS CHAR ( 26 ) ) ; 
INSERT INTO KGRJRNS ( KGRJIPB , KGRJALX , KGRJTYP , KGRJDAT , KGRJTBM , KGRJCMM ) 
VALUES ( P_CODEOFFRE , P_VERSION , P_TYP , V_TIMEMODIF , P_TRIGREDTABLE , P_TRIGREDFILEDS ) ; 
--INSERT INTO KGRJRNS (KGRJIPB,KGRJALX,KGRJTYP,KGRJDAT,KGRJTBM,KGRJCMM) 
--VALUES ('TEST',0,'0',V_TIMEMODIF,'T1','T1'); 
--call ZBOTEST(); 
END P1  ; 
  

  

