CREATE PROCEDURE SP_UPDENG ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_LCIVALEUR NUMERIC(13, 2) , 
	IN P_LCIUNITE CHAR(3) , 
	IN P_LCITYPE CHAR(3) , 
	IN P_LCIINDEXEE CHAR(1) , 
	IN P_PARTALB NUMERIC(5, 2) , 
	IN P_COMMENTFORCE CHAR(5000) , 
	IN P_MODECOMMENTONLY CHAR(1) , 
	IN P_LIENCPXLCIGENERALE NUMERIC(13, 2) , 
	IN P_CODEPERIODE INTEGER ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_UPDENG 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
DECLARE V_IDCOMMENT INTEGER DEFAULT 0 ; 
  
IF ( P_MODECOMMENTONLY = 'N' ) THEN 
  
UPDATE KPENT SET KAALCIVALO = P_LCIVALEUR , KAALCIVALA = P_LCIVALEUR , KAALCIUNIT = P_LCIUNITE , 
KAALCIBASE = P_LCITYPE , KAALCIINA = P_LCIINDEXEE , KAAKDIID = P_LIENCPXLCIGENERALE 
WHERE KAAIPB = P_CODEOFFRE AND KAAALX = P_VERSION AND KAATYP = P_TYPE ; 
  
UPDATE YPOBASE SET PBAPP = P_PARTALB 
WHERE PBIPB = P_CODEOFFRE AND PBALX = P_VERSION AND PBTYP = P_TYPE ; 
  
END IF ; 
  
IF ( P_CODEPERIODE = 0 ) THEN 
	SELECT MAX ( KDOOBSV ) INTO V_IDCOMMENT FROM KPENG WHERE KDOTYP = P_TYPE AND KDOIPB = P_CODEOFFRE AND KDOALX = P_VERSION ; 
ELSE 
	SELECT KDOOBSV INTO V_IDCOMMENT FROM KPENG WHERE KDOID = P_CODEPERIODE ; 
END IF ; 
  
  
IF ( V_IDCOMMENT <> 0 AND V_IDCOMMENT IS NOT NULL ) THEN 
	UPDATE KPOBSV SET KAJOBSV = TRIM ( P_COMMENTFORCE ) 
	WHERE KAJCHR = V_IDCOMMENT ; 
ELSE 
	CALL SP_NCHRONO ( 'KAJCHR' , V_IDCOMMENT ) ; 
	INSERT INTO KPOBSV 
	( KAJCHR , KAJIPB , KAJALX , KAJTYP , KAJOBSV ) 
	VALUES 
	( V_IDCOMMENT , P_CODEOFFRE , P_VERSION , P_TYPE , TRIM ( P_COMMENTFORCE ) ) ; 
	 
	IF ( P_CODEPERIODE = 0 ) THEN 
		UPDATE KPENG SET KDOOBSV = V_IDCOMMENT WHERE KDOTYP = P_TYPE AND KDOIPB = P_CODEOFFRE AND KDOALX = P_VERSION ; 
	ELSE 
		UPDATE KPENG SET KDOOBSV = V_IDCOMMENT WHERE KDOID = P_CODEPERIODE ; 
	END IF ; 
END IF ; 
  
  
  
END P1  ; 
  

  

