CREATE PROCEDURE SP_UPDCOMM ( 
	IN P_ID_OFFRE CHAR(9) , 
	IN P_VERSION_OFFRE INTEGER , 
	IN P_TYPE_OFFRE CHAR(1) , 
	IN P_TAUX_CONTRAT_HCAT DECIMAL(5, 2) , 
	IN P_TAUX_CONTRAT_CAT DECIMAL(5, 2) , 
	IN P_IS_HORSCATNAT CHAR(1) , 
	IN P_IS_CATNAT CHAR(1) , 
	IN P_OBSV CHAR(5000) ) 
	LANGUAGE SQL 
	SPECIFIC SP_UPDCOMM 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
DECLARE V_OBSV_REF INTEGER DEFAULT 0 ; 
  
UPDATE YPRTENT 
SET 
JDXCM = P_TAUX_CONTRAT_HCAT , 
JDCNC = P_TAUX_CONTRAT_CAT 
WHERE JDIPB = P_ID_OFFRE 
AND JDALX = P_VERSION_OFFRE ; 
  
IF ( P_OBSV <> '' ) THEN 
SELECT KAAOBSC INTO V_OBSV_REF 
FROM KPENT 
WHERE KAAALX = P_VERSION_OFFRE 
AND KAAIPB = P_ID_OFFRE 
AND KAATYP = P_TYPE_OFFRE ; 
  
IF ( V_OBSV_REF = 0 ) THEN 
CALL SP_NCHRONO ( 'KAJCHR' , V_OBSV_REF ) ; 
  
INSERT INTO KPOBSV ( KAJCHR , KAJTYP , KAJIPB , KAJALX , KAJTYPOBS , KAJOBSV ) 
VALUES ( V_OBSV_REF , P_TYPE_OFFRE , P_ID_OFFRE , P_VERSION_OFFRE , '' , P_OBSV ) ; 
  
ELSE 
UPDATE KPOBSV 
SET 
KAJOBSV = P_OBSV 
WHERE 
KAJCHR = V_OBSV_REF ; 
END IF ; 
END IF ; 
  
UPDATE KPENT 
SET 
KAAXCMS = P_IS_HORSCATNAT , 
KAACNCS = P_IS_CATNAT , 
KAAOBSC = V_OBSV_REF 
WHERE KAAALX = P_VERSION_OFFRE 
AND KAAIPB = P_ID_OFFRE 
AND KAATYP = P_TYPE_OFFRE ; 
  
  
  
END P1  ; 
  

  

