CREATE PROCEDURE SP_UPDATEINDEXATION ( 
	IN P_CODEOFFRE CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) ) 
	LANGUAGE SQL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
	 
	DECLARE V_JDINA CHAR ( 1 ) DEFAULT 'N' ; 
	DECLARE V_VALEURCOURANTE DECIMAL ( 7 , 2 ) DEFAULT 0 ; 
	DECLARE V_VALEURREF DECIMAL ( 7 , 2 ) DEFAULT 0 ; 
	DECLARE V_CODEINDEX CHAR ( 3 ) DEFAULT '' ; 
	DECLARE V_DATEEFFJ INTEGER DEFAULT 0 ; 
	DECLARE V_DATEEFFM INTEGER DEFAULT 0 ; 
	DECLARE V_DATEEFFA INTEGER DEFAULT 0 ; 
	DECLARE V_NBLIGNE INTEGER DEFAULT 0 ; 
	 
	SET P_CODEOFFRE = F_PADLEFT( 9 , RTRIM ( P_CODEOFFRE ) );

	SELECT JDIND , PBEFA , PBEFM , PBEFJ , JDIVO INTO V_CODEINDEX , V_DATEEFFA , V_DATEEFFM , V_DATEEFFJ , V_VALEURCOURANTE 
	FROM YPOBASE 
	INNER JOIN YPRTENT ON JDIPB = PBIPB AND JDALX = PBALX 
	WHERE  PBIPB  = P_CODEOFFRE AND PBALX = P_VERSION AND PBTYP = P_TYPE ; 
	 
	IF ( V_CODEINDEX <> '' AND V_DATEEFFJ > 0 AND V_DATEEFFM > 0 AND V_DATEEFFA > 0 ) THEN 
		 
		SET V_JDINA = 'O' ;	 

			SELECT GIIDV INTO V_VALEURREF FROM YINDICE 
			WHERE GIIND = V_CODEINDEX AND 
			(GIIPA * 10000 + GIIPM * 100 + GIIPJ) <= (V_DATEEFFA * 10000 + V_DATEEFFM * 100 + V_DATEEFFJ)
			ORDER BY GIIPA * 10000 + GIIPM * 100 + GIIPJ DESC FETCH FIRST 1 ROWS ONLY ;						 
			 
	END IF ; 
	 
	--YPRTENT 
	UPDATE YPRTENT 
	SET JDIND = V_CODEINDEX , JDIVA = V_VALEURREF ,					 
		JDINA = V_JDINA , JDIVO = V_VALEURREF , JDIVW = 0 
	WHERE JDIPB  = P_CODEOFFRE  AND JDALX = P_VERSION ; 
	 
	--YPRTOBJ 
	UPDATE YPRTOBJ 
	SET JGIVO = V_VALEURREF , 
	JGIVA = V_VALEURREF , 
	JGIVW = 0 
	WHERE JGIPB = P_CODEOFFRE AND JGALX = P_VERSION ; 
	 
	--KPOPT 
	UPDATE KPOPT 
	SET KDBIVO = V_VALEURREF , 
	KDBIVA = V_VALEURREF , 
	KDBIVW = 0 
	WHERE KDBIPB = P_CODEOFFRE AND KDBALX = P_VERSION AND KDBTYP = P_TYPE ; 
	 
END P1  ; 
