CREATE PROCEDURE SP_VALIDSELECTIONGAR ( 
	IN P_CODECONTRAT CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_LOTID INTEGER , 
	IN P_SELGARANTIES CHAR(500) , 
	IN P_USER CHAR(10) , 
	IN P_DATENOW INTEGER ) 
	LANGUAGE SQL 
	SPECIFIC SP_VALIDSELECTIONGAR 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
	DECLARE V_RIGHT CHAR ( 500 ) DEFAULT '' ; 
	DECLARE V_LEFT CHAR ( 500 ) DEFAULT '' ; 
	DECLARE V_ATTESTID INTEGER DEFAULT 0 ; 
	DECLARE V_FORMID INTEGER DEFAULT 0 ; 
		 
	SET V_ATTESTID = 0 ; 
	SELECT KHTID INTO V_ATTESTID FROM KPATT WHERE KHTID = P_LOTID AND TRIM ( KHTIPB ) = TRIM ( P_CODECONTRAT ) AND KHTALX = P_VERSION AND KHTTYP = P_TYPE ; 
	 
	IF ( V_ATTESTID > 0 ) THEN 
		UPDATE KPATTF SET KHUSIT = 'A' WHERE KHUKHTID = V_ATTESTID AND KHUPERI IN ( 'FO' , 'GA' ) ; 
		 
		CALL SP_SPLIT ( P_SELGARANTIES , ';' , 'L' , V_LEFT ) ; 
		CALL SP_SPLIT ( P_SELGARANTIES , ';' , 'R' , V_RIGHT ) ; 
		WHILE ( TRIM ( V_LEFT ) != '' ) DO 
			SET V_FORMID = 0 ; 
			SELECT KHUFOR INTO V_FORMID FROM KPATTF WHERE KHUKHTID = P_LOTID AND KHUPERI = 'GA' AND KHUKDEID = CAST ( TRIM ( V_LEFT ) AS INTEGER ) ; 
			UPDATE KPATTF SET KHUSIT = 'V' WHERE KHUPERI = 'FO' AND KHUFOR = V_FORMID ; 
			 
			UPDATE KPATTF SET KHUSIT = 'V' WHERE KHUPERI = 'GA' AND KHUKDEID = CAST ( TRIM ( V_LEFT ) AS INTEGER ) ; 
		 
			CALL SP_SPLIT ( V_RIGHT , ';' , 'L' , V_LEFT ) ; 
			CALL SP_SPLIT ( V_RIGHT , ';' , 'R' , V_RIGHT ) ; 
		END WHILE ; 
		UPDATE KPATT SET KHTGAF = 'O' , KHTMAJU = P_USER , KHTMAJD = P_DATENOW WHERE KHTID = V_ATTESTID ; 
	END IF ; 
END P1  ; 
  

  

