CREATE PROCEDURE SP_VALIDSELECTIONRSQ ( 
	IN P_CODECONTRAT CHAR(9) , 
	IN P_VERSION INTEGER , 
	IN P_TYPE CHAR(1) , 
	IN P_LOTID INTEGER , 
	IN P_SELRSQOBJ CHAR(500) , 
	IN P_USER CHAR(10) , 
	IN P_DATENOW INTEGER ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SP_VALIDSELECTIONRSQ 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	DBGVIEW = *SOURCE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
	DECLARE V_KHTID NUMERIC ( 15 ) DEFAULT 0 ; 
	DECLARE V_CHAINE_LEFT VARCHAR ( 500 ) DEFAULT '' ; 
	DECLARE V_CHAINE_RIGHT VARCHAR ( 500 ) DEFAULT '' ; 
	DECLARE V_OBJ_LEFT VARCHAR ( 500 ) DEFAULT '' ; 
	DECLARE V_OBJ_RIGHT VARCHAR ( 500 ) DEFAULT '' ; 
	DECLARE V_RQ_LEFT VARCHAR ( 500 ) DEFAULT '' ; 
	DECLARE V_RQ_RIGHT VARCHAR ( 500 ) DEFAULT '' ; 
	 
	SELECT KHTID INTO V_KHTID FROM KPATT WHERE KHTID = P_LOTID AND TRIM ( KHTIPB ) = TRIM ( P_CODECONTRAT ) AND KHTALX = P_VERSION AND KHTTYP = P_TYPE ; 
  
	UPDATE KPATTF SET KHUSIT = 'A' WHERE KHUKHTID = V_KHTID AND KHUPERI IN ( 'RQ' , 'OB' ) ; 
  
	CALL SP_SPLIT ( P_SELRSQOBJ , ';' , 'L' , V_CHAINE_LEFT ) ; 
	CALL SP_SPLIT ( P_SELRSQOBJ , ';' , 'R' , V_CHAINE_RIGHT ) ; 
  
	WHILE ( TRIM ( V_CHAINE_LEFT ) != '' ) DO 
  
		CALL SP_SPLIT ( V_CHAINE_LEFT , '_' , 'L' , V_RQ_LEFT ) ; 
		CALL SP_SPLIT ( V_CHAINE_LEFT , '_' , 'R' , V_RQ_RIGHT ) ; 
  
		UPDATE KPATTF SET KHUSIT = 'V' WHERE KHUKHTID = V_KHTID AND KHURSQ = V_RQ_LEFT AND KHUPERI = 'RQ' ; 
		 
		WHILE ( TRIM ( V_RQ_RIGHT ) != '' ) DO 
	 
			CALL SP_SPLIT ( V_RQ_RIGHT , '$' , 'L' , V_OBJ_LEFT ) ; 
			CALL SP_SPLIT ( V_RQ_RIGHT , '$' , 'R' , V_RQ_RIGHT ) ; 
	 
			UPDATE KPATTF SET KHUSIT = 'V' WHERE KHUKHTID = V_KHTID AND KHURSQ = V_RQ_LEFT AND KHUPERI = 'OB' AND KHUOBJ = V_OBJ_LEFT ;		 
			 
			 
		END WHILE ; 
  
		CALL SP_SPLIT ( V_CHAINE_RIGHT , ';' , 'L' , V_CHAINE_LEFT ) ; 
		CALL SP_SPLIT ( V_CHAINE_RIGHT , ';' , 'R' , V_CHAINE_RIGHT ) ; 
		 
	END WHILE ; 
	 
	UPDATE KPATT SET KHTROF = 'O' , KHTMAJU = P_USER , KHTMAJD = P_DATENOW WHERE KHTID = V_KHTID ; 
	 
END P1  ; 
  

  

