CREATE PROCEDURE SP_VALIDSUPPRDOC ( 
	IN P_SELECTDOC CHAR(250) , 
	IN P_UNSELECTDOC CHAR(250) , 
	IN P_CHARSEPFIELD CHAR(1) ) 
	LANGUAGE SQL 
	SPECIFIC SP_VALIDSUPPRDOC 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CHG , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ZALBINKHEO , 
	DYNDFTCOL = *YES , 
	SQLPATH = 'ZALBINKHEO, ZALBINKMOD' , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN ATOMIC 
  
	DECLARE V_INFOLEFT VARCHAR ( 250 ) DEFAULT '' ; 
	DECLARE V_INFORIGHT VARCHAR ( 250 ) DEFAULT '' ; 
  
	IF ( TRIM ( P_SELECTDOC ) != '' ) THEN 
		CALL SP_SPLIT ( P_SELECTDOC , P_CHARSEPFIELD , 'L' , V_INFOLEFT ) ; 
		CALL SP_SPLIT ( P_SELECTDOC , P_CHARSEPFIELD , 'R' , V_INFORIGHT ) ; 
		WHILE ( TRIM ( V_INFOLEFT ) != '' ) DO 
			UPDATE KPDOCH SET KEQSIT = 'V' WHERE KEQID = CAST ( TRIM ( V_INFOLEFT ) AS INTEGER ) ; 
			 
			CALL SP_SPLIT ( V_INFORIGHT , P_CHARSEPFIELD , 'L' , V_INFOLEFT ) ; 
			CALL SP_SPLIT ( V_INFORIGHT , P_CHARSEPFIELD , 'R' , V_INFORIGHT ) ; 
		END WHILE ; 
	END IF ; 
  
	IF ( TRIM ( P_UNSELECTDOC ) != '' ) THEN 
		CALL SP_SPLIT ( P_UNSELECTDOC , P_CHARSEPFIELD , 'L' , V_INFOLEFT ) ; 
		CALL SP_SPLIT ( P_UNSELECTDOC , P_CHARSEPFIELD , 'R' , V_INFORIGHT ) ; 
		WHILE ( TRIM ( V_INFOLEFT ) != '' ) DO 
			UPDATE KPDOCH SET KEQSIT = 'X' WHERE KEQID = CAST ( TRIM ( V_INFOLEFT ) AS INTEGER ) ; 
			 
			CALL SP_SPLIT ( V_INFORIGHT , P_CHARSEPFIELD , 'L' , V_INFOLEFT ) ; 
			CALL SP_SPLIT ( V_INFORIGHT , P_CHARSEPFIELD , 'R' , V_INFORIGHT ) ; 
		END WHILE ; 
	END IF ; 
  
END P1  ; 
  

  

