CREATE TABLE ZALBINKMOD.YPLTGAA ( 
--  SQL150B   10   REUSEDLT(*NO) de la table YPLTGAA de ZALBINKMOD ignoré. 
	C5TYP CHAR(1) CCSID 297 NOT NULL DEFAULT '' , 
	C5SEQ NUMERIC(10, 0) NOT NULL DEFAULT 0 , 
	C5SEM NUMERIC(10, 0) NOT NULL DEFAULT 0 )   
	RCDFMT FPLTGAA    ; 
  
LABEL ON COLUMN ZALBINKMOD.YPLTGAA 
( C5TYP IS 'Type' , 
	C5SEQ IS 'Séq. gar1' , 
	C5SEM IS 'Séq. gar. 2' ) ; 
  
LABEL ON COLUMN ZALBINKMOD.YPLTGAA 
( C5TYP TEXT IS 'Type' , 
	C5SEQ TEXT IS 'Séquence garantie 1' , 
	C5SEM TEXT IS 'Séquence garantie 2' ) ; 
  
