using ALBINGIA.Framework.Common;
using System.Runtime.Serialization;

namespace OP.WSAS400.DTO {
    [DataContract]
    public enum ContextStepName {
        [EnumMember]
        Inconnue = 0,
        [EnumMember]
        Recherche = 1,
        [EnumMember]
        Creation,
        [EnumMember]
        EtablirAffaireNouvelle,
        [EnumMember]
        NouvelleAffaire,
        [EnumMember]
        ConsulterOuEditer,
        [EnumMember]
        ConsulterRegule,
        [EnumMember]
        DoubleSaisie,
        [EnumMember]
        Edition,
        [EnumMember]
        [BusinessCode("SAISIE")]
        EditionInfosBase,
        [EnumMember]
        [BusinessCode("GEN")]
        EditionInfosGenerales,
        [EnumMember]
        EditionCoAssureurs,
        [EnumMember]
        EditionCommissions,
        [EnumMember]
        CreationAvenant,
        [EnumMember]
        EditionParitelle,
        [EnumMember]
        ConfirmerOffre,
        [EnumMember]
        RetourPieces,
        [EnumMember]
        EditionAvenant,
        [EnumMember]
        EditionInfosAvenant,
        [EnumMember]
        CreationRegularisation,
        [EnumMember]
        EditionRegularisation,
        [EnumMember]
        EditionRegularisationEtAvenant,
        [EnumMember]
        CreationPB,
        [EnumMember]
        CreationBNS,
        [EnumMember]
        EditionResiliation,
        [EnumMember]
        EditionRemiseEnVigueur,
        [EnumMember]
        ChoixClauses,
        [EnumMember]
        MatriceRisque,
        [EnumMember]
        MatriceFormule,
        [EnumMember]
        MatriceGarantie,
        [EnumMember]
        DetailsRisque,
        [EnumMember]
        DetailsObjetRisque,
        [EnumMember]
        InformationsSpecifiquesRisque,
        [EnumMember]
        InformationsComplementairesRisque,
        [EnumMember]
        InformationsSpecifiquesObjets,
        [EnumMember]
        EditionInventaires,
        [EnumMember]
        [BusinessCode("OPT")]
        EditionOption,
        [EnumMember]
        InformationsSpecifiquesGarantie,
        [EnumMember]
        [BusinessCode("GAR")]
        ConditionsGarantie,
        [EnumMember]
        [BusinessCode("ENG")]
        EditionEngagements,
        [EnumMember]
        EngagementPeriodes,
        [EnumMember]
        [BusinessCode("ATT")]
        EditionMontantsReference,
        [EnumMember]
        [BusinessCode("COT")]
        EditionQuittance,
        [EnumMember]
        AnnulationQuittances,
        [EnumMember]
        GestionDocuments,
        [EnumMember]
        InfosFinOffre,
        [EnumMember]
        [BusinessCode("FIN")]
        ControleFin,
        [EnumMember]
        Validation,
        [EnumMember]
        Deverrouiller,
        [EnumMember]
        Attestation,
        [EnumMember]
        PrisePosition,
        [EnumMember]
        ClassementSansSuite,
        [EnumMember]
        EditionBNS,
        [EnumMember]
        BlocageDeblocageTermes,
        [BusinessCode("ATTENT")]
        Attentat,
        [EnumMember]
        EditionPB,
        [EnumMember]
        ConsulterPB
    }
}
