CREATE OR REPLACE VIEW ZALBINKHEO.V_LISTCONTEXTESTD ( 
	ORIGINEFILTRE FOR COLUMN ORIGI00001 , 
	CONTEXTE , 
	ETATTITRE , 
	ORIGINE ) 
	AS 
	(  
								SELECT ORIGINEFILTRE,CONTEXTE, ETATTITRE, ORIGINE  
								FROM ZALBINKHEO.V_LISTCLAUSESTD  
										  
										  
							 ) ; 
  
LABEL ON COLUMN ZALBINKHEO.V_LISTCONTEXTESTD 
( ORIGINEFILTRE IS 'Ajoutée O/N' , 
	CONTEXTE IS 'Contexte' , 
	ETATTITRE IS 'Nature de la clause' ) ; 
  
LABEL ON COLUMN ZALBINKHEO.V_LISTCONTEXTESTD 
( ORIGINEFILTRE TEXT IS 'Ajoutée O/N' , 
	CONTEXTE TEXT IS 'Contexte' , 
	ETATTITRE TEXT IS 'Nature de la clause' ) ; 
  
