CREATE OR REPLACE VIEW ZALBINKHEO.V_RECHERCHESUIVIDOC ( 
	CURAVN , 
	LOTID , 
	LOTLIB , 
	CODEUTILISATEUR FOR COLUMN CODEU00001 , 
	NOMUTILISATEUR FOR COLUMN NOMUT00001 , 
	PRENOMUTILISATEUR FOR COLUMN PRENO00001 , 
	UNITESERVICE FOR COLUMN UNITE00001 , 
	TYPEAFFAIRE FOR COLUMN TYPEA00001 , 
	CODEOFFRE , 
	"VERSION" , 
	LOTDETAILID FOR COLUMN LOTDE00001 , 
	CODESITUATION FOR COLUMN CODES00001 , 
	DATESITUATION FOR COLUMN DATES00001 , 
	HEURESITUATION FOR COLUMN HEURE00001 , 
	UTILISATEURSITUATION FOR COLUMN UTILI00001 , 
	ACTEGESTION FOR COLUMN ACTEG00001 , 
	ACTEGESTIONLIB FOR COLUMN ACTEG00002 , 
	NUMINTERNE , 
	NUMEXTERNE , 
	NOMDOC , 
	CHEMINDOC , 
	DOCID , 
	TYPEDOC , 
	EMPTYLINE , 
	CODEDOC , 
	SERVDOC , 
	CREATEDOC , 
	MODIFDOC , 
	TYPEGENDOC , 
	TYPOEDITDOC FOR COLUMN TYPOE00001 , 
	TYPEDOCLIB , 
	TYPEDESTINATAIRE FOR COLUMN TYPED00001 , 
	TYPEINTERVENANT FOR COLUMN TYPEI00001 , 
	CODEDESTINATAIRE FOR COLUMN CODED00001 , 
	NOMDESTINATAIRE FOR COLUMN NOMDE00001 , 
	CODEINTERLOCUTEUR FOR COLUMN CODEI00001 , 
	NOMINTERLOCUTEUR FOR COLUMN NOMIN00001 , 
	CODEDIFFUSION FOR COLUMN CODED00002 , 
	LIBDIFFUSION FOR COLUMN LIBDI00001 , 
	DOCEXT ) 
	AS 
	(SELECT YPO.PBAVN CURAVN, KELID LOTID, IFNULL(KELLIB, '') LOTLIB, IFNULL(KELCRU, '') CODEUTILISATEUR, IFNULL(UTNOM, '') NOMUTILISATEUR, IFNULL(UTPNM , '') PRENOMUTILISATEUR, IFNULL(UTUSC, '') UNITESERVICE,  
														IFNULL(KELTYP, '') TYPEAFFAIRE, IFNULL(KELIPB, '') CODEOFFRE, KELALX VERSION, KEMID LOTDETAILID, IFNULL(KEMSIT, '') CODESITUATION, KEMSTD DATESITUATION, KEMSTH HEURESITUATION, IFNULL(KEMSTU, '') UTILISATEURSITUATION,  
														IFNULL(KELACTG, '') ACTEGESTION, IFNULL(ACTG.TPLIL, '') ACTEGESTIONLIB, KELAVN NUMINTERNE, CASE KELAVN WHEN YPO.PBAVN THEN YPO.PBAVK WHEN YHP.PBAVN THEN YHP.PBAVK ELSE 0 END NUMEXTERNE,  
														IFNULL(KEQNOM, '') NOMDOC, IFNULL(KEQCHM, '') CHEMINDOC, IFNULL(KEQID, 0) DOCID, IFNULL(KEQTDOC, '') TYPEDOC, IFNULL(TDOC.TPCN2, 0) EMPTYLINE, IFNULL(KEQCDOC, '') CODEDOC, IFNULL(KEQSERV, '') SERVDOC, IFNULL(KEQCRD, 0) CREATEDOC, IFNULL(KEQMAJD, 0) MODIFDOC, IFNULL(KEQTGL, '') TYPEGENDOC,  
														IFNULL(KEQTEDI, '') TYPOEDITDOC, IFNULL(TDOC.TPLIL, '') TYPEDOCLIB, IFNULL(KEMTYDS, '') TYPEDESTINATAIRE, IFNULL(KEMTYI, '') TYPEINTERVENANT,  
														KEMIDS CODEDESTINATAIRE, CASE KEMTYDS WHEN 'CT' THEN IFNULL(COURTIER.TNNOM, '') WHEN 'AS' THEN IFNULL(ANNOM, '') WHEN 'CI' THEN IFNULL(CINOM, '') WHEN 'IN' THEN IFNULL(INTERV.IMNOM, '') ELSE '' END NOMDESTINATAIRE,  
														KEMINL CODEINTERLOCUTEUR, CASE KEMTYDS WHEN 'CT' THEN IFNULL(INTERLOCUTEUR.TNNOM, '') WHEN 'CI' THEN IFNULL(CLNOM, '') WHEN 'IN' THEN IFNULL(INTERVINL.IMNOM, '') ELSE '' END NOMINTERLOCUTEUR,  
														KEMTYDIF CODEDIFFUSION, IFNULL(TDIF.TPLIL, '') LIBDIFFUSION, CASE KEMTYPD WHEN 'E' THEN 1 ELSE 0 END DOCEXT  
													FROM ZALBINKHEO.KPDOCLD  
														INNER JOIN ZALBINKHEO.KPDOCL ON KELID = KEMKELID  
														LEFT JOIN ZALBINKHEO.KPDOC ON KEQID = KEMTYPL  
														LEFT JOIN ZALBINKHEO.KPDOCEXT ON KERID = KEMTYPL AND KEMTYPD = 'E'  
														LEFT JOIN ZALBINKHEO.YPOBASE YPO ON YPO.PBIPB = KELIPB AND YPO.PBALX = KELALX AND YPO.PBTYP = KELTYP  
														LEFT JOIN ZALBINKHEO.YHPBASE YHP ON YHP.PBIPB = KELIPB AND YHP.PBALX = KELALX AND YHP.PBTYP = KELTYP AND YHP.PBAVN = KELAVN AND YHP.PBHIN = 1  
														INNER JOIN ZALBINKHEO.YUTILIS ON UTIUT = KELCRU  
														LEFT JOIN ZALBINKHEO.YGESUSG ON UNUGC = UTUSC  
														LEFT JOIN ZALBINKHEO.YYYYPAR ACTG ON ACTG.TCON = 'KHEOP' AND ACTG.TFAM = 'ACTGS' AND ACTG.TCOD = KELACTG  
														LEFT JOIN ZALBINKHEO.YYYYPAR TDOC ON TDOC.TCON = 'KHEOP' AND TDOC.TFAM = 'TDOC' AND TDOC.TCOD = KEQTDOC  
														LEFT JOIN ZALBINKHEO.YYYYPAR TDIF ON TDIF.TCON = 'KHEOP' AND TDIF.TFAM = 'TYDIF' AND TDIF.TCOD = KEMTYDIF  
														LEFT JOIN ZALBINKHEO.YCOURTI ON TCICT = KEMIDS AND KEMTYDS = 'CT'  
														LEFT JOIN ZALBINKHEO.YCOURTN COURTIER ON COURTIER.TNICT = TCICT AND COURTIER.TNXN5 = 0 AND COURTIER.TNTNM = 'A' AND KEMTYDS = 'CT'  
														LEFT JOIN ZALBINKHEO.YCOURTN INTERLOCUTEUR ON INTERLOCUTEUR.TNICT = KEMIDS AND INTERLOCUTEUR.TNXN5 = KEMINL AND INTERLOCUTEUR.TNTNM = 'A' AND KEMTYDS = 'CT' AND KEMINL <> 0  
														LEFT JOIN ZALBINKHEO.YASSURE ON ASIAS = KEMIDS AND KEMTYDS = 'AS'  
														LEFT JOIN ZALBINKHEO.YASSNOM ON ANIAS = KEMIDS AND ANINL = 0 AND ANTNM = 'A' AND KEMTYDS = 'AS'  
														LEFT JOIN ZALBINKHEO.YCOMPA ON CIICN = KEMIDS AND KEMTYDS = 'CI'  
														LEFT JOIN ZALBINKHEO.YCOMPAL ON CLICI = CIICI AND CLIN5 = KEMINL AND KEMTYDS = 'CI'  
														LEFT JOIN ZALBINKHEO.YINTERV ON INIIN = KEMIDS AND KEMTYDS = 'IN'  
														LEFT JOIN ZALBINKHEO.YINTNOM INTERV ON INTERV.IMIIN = KEMIDS AND INTERV.IMINL = 0 AND INTERV.IMTNM = 'A' AND KEMTYDS = 'IN'  
														LEFT JOIN ZALBINKHEO.YINTNOM INTERVINL ON INTERVINL.IMIIN = KEMIDS AND INTERVINL.IMINL = KEMINL AND INTERVINL.IMTNM = 'A' AND KEMTYDS = 'IN' AND KEMINL <> 0) ; 
  
LABEL ON COLUMN ZALBINKHEO.V_RECHERCHESUIVIDOC 
( CURAVN IS 'N° avenant' , 
	LOTID IS 'ID unique' , 
	"VERSION" IS 'ALX' , 
	LOTDETAILID IS 'ID unique' , 
	DATESITUATION IS 'Situation Date' , 
	HEURESITUATION IS 'Situation Heure' , 
	NUMINTERNE IS 'N° Avenant' , 
	CODEDESTINATAIRE IS 'ID destinantaire' , 
	CODEINTERLOCUTEUR IS 'Code interlocuteur' , 
	CODEDIFFUSION IS 'Type diffusion' ) ; 
  
LABEL ON COLUMN ZALBINKHEO.V_RECHERCHESUIVIDOC 
( CURAVN TEXT IS 'N° avenant' , 
	LOTID TEXT IS 'ID unique' , 
	"VERSION" TEXT IS 'ALX' , 
	LOTDETAILID TEXT IS 'ID unique' , 
	DATESITUATION TEXT IS 'Situation Date' , 
	HEURESITUATION TEXT IS 'Situation Heure' , 
	NUMINTERNE TEXT IS 'N° Avenant' , 
	CODEDESTINATAIRE TEXT IS 'Identifiant Destinataire' , 
	CODEINTERLOCUTEUR TEXT IS 'Code interlocuteur' , 
	CODEDIFFUSION TEXT IS 'Type diffusion (Cour,Mail...)' ) ; 
  
