//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.RadEditor {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez le projet Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadEditor.Main", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add Custom Color....
        /// </summary>
        internal static string AddCustomColor {
            get {
                return ResourceManager.GetString("AddCustomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add Hex Color....
        /// </summary>
        internal static string AddCustomHexColor {
            get {
                return ResourceManager.GetString("AddCustomHexColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à successfully added to dictionary.
        /// </summary>
        internal static string AddCustomWordSuccess {
            get {
                return ResourceManager.GetString("AddCustomWordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add to dictionary.
        /// </summary>
        internal static string AddToDictionary {
            get {
                return ResourceManager.GetString("AddToDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The content you are trying to paste has MS Word formatting.
        ///Would you like to clean it?.
        /// </summary>
        internal static string AskWordCleaning {
            get {
                return ResourceManager.GetString("AskWordCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string CancelTable {
            get {
                return ResourceManager.GetString("CancelTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cell Properties.
        /// </summary>
        internal static string CellProperties {
            get {
                return ResourceManager.GetString("CellProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please, select a cell to set its properties!.
        /// </summary>
        internal static string CellWarning {
            get {
                return ResourceManager.GetString("CellWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change Manually.
        /// </summary>
        internal static string ChangeWordString {
            get {
                return ResourceManager.GetString("ChangeWordString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CSS Class.
        /// </summary>
        internal static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All HTML Tags.
        /// </summary>
        internal static string ClearAllHtmlTags {
            get {
                return ResourceManager.GetString("ClearAllHtmlTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear Class.
        /// </summary>
        internal static string ClearClass {
            get {
                return ResourceManager.GetString("ClearClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cascading Style Sheets.
        /// </summary>
        internal static string ClearCssFormatting {
            get {
                return ResourceManager.GetString("ClearCssFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Font Tags.
        /// </summary>
        internal static string ClearFontTags {
            get {
                return ResourceManager.GetString("ClearFontTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear Formatting.
        /// </summary>
        internal static string ClearFormatting {
            get {
                return ResourceManager.GetString("ClearFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Span Tags.
        /// </summary>
        internal static string ClearSpanTags {
            get {
                return ResourceManager.GetString("ClearSpanTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear Style.
        /// </summary>
        internal static string ClearStyle {
            get {
                return ResourceManager.GetString("ClearStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Microsoft Word Formatting.
        /// </summary>
        internal static string ClearWordFormatting {
            get {
                return ResourceManager.GetString("ClearWordFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spelling Changes.
        /// </summary>
        internal static string CorrectSpelling {
            get {
                return ResourceManager.GetString("CorrectSpelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create Link.
        /// </summary>
        internal static string CreateLink {
            get {
                return ResourceManager.GetString("CreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dialogs.
        /// </summary>
        internal static string DialogToolbar {
            get {
                return ResourceManager.GetString("DialogToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dropdowns.
        /// </summary>
        internal static string DropdownToolbar {
            get {
                return ResourceManager.GetString("DropdownToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enhanced Edit.
        /// </summary>
        internal static string EnhancedEditToolbar {
            get {
                return ResourceManager.GetString("EnhancedEditToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The added HTML code exceeded the character limit.
        /// </summary>
        internal static string ExceededHtmlLength {
            get {
                return ResourceManager.GetString("ExceededHtmlLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The added text exceeded the character limit.
        /// </summary>
        internal static string ExceededTextLength {
            get {
                return ResourceManager.GetString("ExceededTextLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open file...
        /// </summary>
        internal static string FileOpen {
            get {
                return ResourceManager.GetString("FileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save as....
        /// </summary>
        internal static string FileSaveAs {
            get {
                return ResourceManager.GetString("FileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Button.
        /// </summary>
        internal static string FormButton {
            get {
                return ResourceManager.GetString("FormButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Checkbox.
        /// </summary>
        internal static string FormCheckbox {
            get {
                return ResourceManager.GetString("FormCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Form.
        /// </summary>
        internal static string FormForm {
            get {
                return ResourceManager.GetString("FormForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hidden.
        /// </summary>
        internal static string FormHidden {
            get {
                return ResourceManager.GetString("FormHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        internal static string FormPassword {
            get {
                return ResourceManager.GetString("FormPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Radio button.
        /// </summary>
        internal static string FormRadio {
            get {
                return ResourceManager.GetString("FormRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset.
        /// </summary>
        internal static string FormReset {
            get {
                return ResourceManager.GetString("FormReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select.
        /// </summary>
        internal static string FormSelect {
            get {
                return ResourceManager.GetString("FormSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Submit.
        /// </summary>
        internal static string FormSubmit {
            get {
                return ResourceManager.GetString("FormSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Textbox.
        /// </summary>
        internal static string FormText {
            get {
                return ResourceManager.GetString("FormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Textarea.
        /// </summary>
        internal static string FormTextarea {
            get {
                return ResourceManager.GetString("FormTextarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HTML Mode.
        /// </summary>
        internal static string HtmlMode {
            get {
                return ResourceManager.GetString("HtmlMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ignore All.
        /// </summary>
        internal static string IgnoreAllString {
            get {
                return ResourceManager.GetString("IgnoreAllString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ignore.
        /// </summary>
        internal static string IgnoreString {
            get {
                return ResourceManager.GetString("IgnoreString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please, select an image to set its image map properties!.
        /// </summary>
        internal static string ImageMapWarning {
            get {
                return ResourceManager.GetString("ImageMapWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Indent HTML.
        /// </summary>
        internal static string IndentHtml {
            get {
                return ResourceManager.GetString("IndentHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert.
        /// </summary>
        internal static string InsertToolbar {
            get {
                return ResourceManager.GetString("InsertToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Main Toolbar.
        /// </summary>
        internal static string MainToolbar {
            get {
                return ResourceManager.GetString("MainToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This word occurs more than once in the text. Would you like to replace all instances?.
        /// </summary>
        internal static string MoreThanOnceMessage {
            get {
                return ResourceManager.GetString("MoreThanOnceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move.
        /// </summary>
        internal static string MoveCommand {
            get {
                return ResourceManager.GetString("MoveCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No mistakes found..
        /// </summary>
        internal static string NoSpellingMistakes {
            get {
                return ResourceManager.GetString("NoSpellingMistakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (no suggestions).
        /// </summary>
        internal static string NoSuggestions {
            get {
                return ResourceManager.GetString("NoSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please, provide the custom color HEX value:.
        /// </summary>
        internal static string PromptColor {
            get {
                return ResourceManager.GetString("PromptColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Design.
        /// </summary>
        internal static string RadEditorDesignMode {
            get {
                return ResourceManager.GetString("RadEditorDesignMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HTML.
        /// </summary>
        internal static string RadEditorHtmlMode {
            get {
                return ResourceManager.GetString("RadEditorHtmlMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preview.
        /// </summary>
        internal static string RadEditorPreviewMode {
            get {
                return ResourceManager.GetString("RadEditorPreviewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please, reduce the content of the field.
        /// </summary>
        internal static string ReduceTheConentLength {
            get {
                return ResourceManager.GetString("ReduceTheConentLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please, do not delete this string. RadEditor needs it to determine if an external resource file is present in App_GlobalResources..
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resize Object.
        /// </summary>
        internal static string ResizeCommand {
            get {
                return ResourceManager.GetString("ResizeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set HTML.
        /// </summary>
        internal static string SetHtml {
            get {
                return ResourceManager.GetString("SetHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show toolbar.
        /// </summary>
        internal static string ShowToolbarTooltip {
            get {
                return ResourceManager.GetString("ShowToolbarTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Spell Check is complete!.
        /// </summary>
        internal static string SpellCheckComplete {
            get {
                return ResourceManager.GetString("SpellCheckComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finish spellchecking.
        /// </summary>
        internal static string SpellCheckEnd {
            get {
                return ResourceManager.GetString("SpellCheckEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spelling Change.
        /// </summary>
        internal static string SpellingChange {
            get {
                return ResourceManager.GetString("SpellingChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spell checking in progress....
        /// </summary>
        internal static string SpellingInProgress {
            get {
                return ResourceManager.GetString("SpellingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spell checking mode. Misspelled words are highlighted in yellow..
        /// </summary>
        internal static string SpellingMode {
            get {
                return ResourceManager.GetString("SpellingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table.
        /// </summary>
        internal static string TableToolbar {
            get {
                return ResourceManager.GetString("TableToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please, select a table to set its properties!.
        /// </summary>
        internal static string TableWarning {
            get {
                return ResourceManager.GetString("TableWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RadEditor Toolbar.
        /// </summary>
        internal static string ToolbarCaption {
            get {
                return ResourceManager.GetString("ToolbarCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This tool is not supported by Mozilla/Netscape browsers..
        /// </summary>
        internal static string ToolNotSupportedByNetscape {
            get {
                return ResourceManager.GetString("ToolNotSupportedByNetscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Typing....
        /// </summary>
        internal static string Typing {
            get {
                return ResourceManager.GetString("Typing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You cannot undo further while in spellcheck mode. Please finish spellchecking first..
        /// </summary>
        internal static string UndoDisabledMessage {
            get {
                return ResourceManager.GetString("UndoDisabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update.
        /// </summary>
        internal static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please use Ctrl+C to Copy.
        /// </summary>
        internal static string UseCtrlC {
            get {
                return ResourceManager.GetString("UseCtrlC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please use Ctrl+V to Paste.
        /// </summary>
        internal static string UseCtrlV {
            get {
                return ResourceManager.GetString("UseCtrlV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please use Ctrl+X to Cut.
        /// </summary>
        internal static string UseCtrlX {
            get {
                return ResourceManager.GetString("UseCtrlX", resourceCulture);
            }
        }
    }
}
