//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.RadEditor {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez le projet Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Modules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Modules() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadEditor.Modules", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action.
        /// </summary>
        internal static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alignment.
        /// </summary>
        internal static string align {
            get {
                return ResourceManager.GetString("align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ToolTip.
        /// </summary>
        internal static string alt {
            get {
                return ResourceManager.GetString("alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Background.
        /// </summary>
        internal static string bgColor {
            get {
                return ResourceManager.GetString("bgColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Window.
        /// </summary>
        internal static string blank {
            get {
                return ResourceManager.GetString("blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Border Width.
        /// </summary>
        internal static string border {
            get {
                return ResourceManager.GetString("border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Border color.
        /// </summary>
        internal static string borderColor {
            get {
                return ResourceManager.GetString("borderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CellPadding.
        /// </summary>
        internal static string cellPadding {
            get {
                return ResourceManager.GetString("cellPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CellSpacing.
        /// </summary>
        internal static string cellSpacing {
            get {
                return ResourceManager.GetString("cellSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Classname.
        /// </summary>
        internal static string className {
            get {
                return ResourceManager.GetString("className", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Columns.
        /// </summary>
        internal static string cols {
            get {
                return ResourceManager.GetString("cols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select Doctype.
        /// </summary>
        internal static string Doctype {
            get {
                return ResourceManager.GetString("Doctype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RemoveElement.
        /// </summary>
        internal static string DomInspectorRemoveElement {
            get {
                return ResourceManager.GetString("DomInspectorRemoveElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expand Report Pane.
        /// </summary>
        internal static string ExpandValidator {
            get {
                return ResourceManager.GetString("ExpandValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Height.
        /// </summary>
        internal static string height {
            get {
                return ResourceManager.GetString("height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à URL.
        /// </summary>
        internal static string href {
            get {
                return ResourceManager.GetString("href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Id.
        /// </summary>
        internal static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Media Pane.
        /// </summary>
        internal static string media {
            get {
                return ResourceManager.GetString("media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid value. Please enter a number..
        /// </summary>
        internal static string NodeInspectorInvalidValue {
            get {
                return ResourceManager.GetString("NodeInspectorInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The selected element is .
        /// </summary>
        internal static string NodeInspectorSelectedElement {
            get {
                return ResourceManager.GetString("NodeInspectorSelectedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nowrap.
        /// </summary>
        internal static string noWrap {
            get {
                return ResourceManager.GetString("noWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parent Window.
        /// </summary>
        internal static string parent {
            get {
                return ResourceManager.GetString("parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tag Inspector.
        /// </summary>
        internal static string RadEditorDomInspector {
            get {
                return ResourceManager.GetString("RadEditorDomInspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Real-Time HTML View.
        /// </summary>
        internal static string RadEditorHtmlInspector {
            get {
                return ResourceManager.GetString("RadEditorHtmlInspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Properties Inspector.
        /// </summary>
        internal static string RadEditorNodeInspector {
            get {
                return ResourceManager.GetString("RadEditorNodeInspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statistics.
        /// </summary>
        internal static string RadEditorStatistics {
            get {
                return ResourceManager.GetString("RadEditorStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XHTML Validator.
        /// </summary>
        internal static string RadEditorXhtmlValidator {
            get {
                return ResourceManager.GetString("RadEditorXhtmlValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please, do not delete this string. RadEditor needs it to determine if an external resource file is present in App_GlobalResources..
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rows.
        /// </summary>
        internal static string rows {
            get {
                return ResourceManager.GetString("rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search Pane.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Same Window.
        /// </summary>
        internal static string self {
            get {
                return ResourceManager.GetString("self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Characters:.
        /// </summary>
        internal static string StatisticsCharacters {
            get {
                return ResourceManager.GetString("StatisticsCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Words:.
        /// </summary>
        internal static string StatisticsWords {
            get {
                return ResourceManager.GetString("StatisticsWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target.
        /// </summary>
        internal static string target {
            get {
                return ResourceManager.GetString("target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ToolTip.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Browser Window.
        /// </summary>
        internal static string top {
            get {
                return ResourceManager.GetString("top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validate XHTML.
        /// </summary>
        internal static string ValidateXHTML {
            get {
                return ResourceManager.GetString("ValidateXHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vertical Alignment.
        /// </summary>
        internal static string vAlign {
            get {
                return ResourceManager.GetString("vAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Value.
        /// </summary>
        internal static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Width.
        /// </summary>
        internal static string width {
            get {
                return ResourceManager.GetString("width", resourceCulture);
            }
        }
    }
}
