//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.RadEditor {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez le projet Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Tools {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tools() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadEditor.Tools", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About RadEditor.
        /// </summary>
        internal static string AboutDialog {
            get {
                return ResourceManager.GetString("AboutDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set Absolute Position.
        /// </summary>
        internal static string AbsolutePosition {
            get {
                return ResourceManager.GetString("AbsolutePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AJAX Spellchecker.
        /// </summary>
        internal static string AjaxSpellCheck {
            get {
                return ResourceManager.GetString("AjaxSpellCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Apply CSS Class.
        /// </summary>
        internal static string ApplyClass {
            get {
                return ResourceManager.GetString("ApplyClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Background Color.
        /// </summary>
        internal static string BackColor {
            get {
                return ResourceManager.GetString("BackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bold.
        /// </summary>
        internal static string Bold {
            get {
                return ResourceManager.GetString("Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Convert to lower case.
        /// </summary>
        internal static string ConvertToLower {
            get {
                return ResourceManager.GetString("ConvertToLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Convert to upper case.
        /// </summary>
        internal static string ConvertToUpper {
            get {
                return ResourceManager.GetString("ConvertToUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compliance Check.
        /// </summary>
        internal static string CSDialog {
            get {
                return ResourceManager.GetString("CSDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cut.
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decrease Size.
        /// </summary>
        internal static string DecreaseSize {
            get {
                return ResourceManager.GetString("DecreaseSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Cell.
        /// </summary>
        internal static string DeleteCell {
            get {
                return ResourceManager.GetString("DeleteCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Column.
        /// </summary>
        internal static string DeleteColumn {
            get {
                return ResourceManager.GetString("DeleteColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Row.
        /// </summary>
        internal static string DeleteRow {
            get {
                return ResourceManager.GetString("DeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Table.
        /// </summary>
        internal static string DeleteTable {
            get {
                return ResourceManager.GetString("DeleteTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Document Manager.
        /// </summary>
        internal static string DocumentManager {
            get {
                return ResourceManager.GetString("DocumentManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter Pressed.
        /// </summary>
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find And Replace.
        /// </summary>
        internal static string FindAndReplace {
            get {
                return ResourceManager.GetString("FindAndReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Flash Manager.
        /// </summary>
        internal static string FlashManager {
            get {
                return ResourceManager.GetString("FlashManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Font Name.
        /// </summary>
        internal static string FontName {
            get {
                return ResourceManager.GetString("FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Size.
        /// </summary>
        internal static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Foreground Color.
        /// </summary>
        internal static string ForeColor {
            get {
                return ResourceManager.GetString("ForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paragraph Style.
        /// </summary>
        internal static string FormatBlock {
            get {
                return ResourceManager.GetString("FormatBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format Code Block.
        /// </summary>
        internal static string FormatCodeBlock {
            get {
                return ResourceManager.GetString("FormatCodeBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format Stripper.
        /// </summary>
        internal static string FormatStripper {
            get {
                return ResourceManager.GetString("FormatStripper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image Editor.
        /// </summary>
        internal static string ImageEditor {
            get {
                return ResourceManager.GetString("ImageEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image Manager.
        /// </summary>
        internal static string ImageManager {
            get {
                return ResourceManager.GetString("ImageManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image Map Editor.
        /// </summary>
        internal static string ImageMapDialog {
            get {
                return ResourceManager.GetString("ImageMapDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Increase Size.
        /// </summary>
        internal static string IncreaseSize {
            get {
                return ResourceManager.GetString("IncreaseSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Indent.
        /// </summary>
        internal static string Indent {
            get {
                return ResourceManager.GetString("Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert Anchor.
        /// </summary>
        internal static string InsertAnchor {
            get {
                return ResourceManager.GetString("InsertAnchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert Column to the Left.
        /// </summary>
        internal static string InsertColumnLeft {
            get {
                return ResourceManager.GetString("InsertColumnLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert Column to the Right.
        /// </summary>
        internal static string InsertColumnRight {
            get {
                return ResourceManager.GetString("InsertColumnRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Custom Links.
        /// </summary>
        internal static string InsertCustomLink {
            get {
                return ResourceManager.GetString("InsertCustomLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert Date.
        /// </summary>
        internal static string InsertDate {
            get {
                return ResourceManager.GetString("InsertDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert Email Link.
        /// </summary>
        internal static string InsertEmailLink {
            get {
                return ResourceManager.GetString("InsertEmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert Button.
        /// </summary>
        internal static string InsertFormButton {
            get {
                return ResourceManager.GetString("InsertFormButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert Checkbox.
        /// </summary>
        internal static string InsertFormCheckbox {
            get {
                return ResourceManager.GetString("InsertFormCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert Form Element.
        /// </summary>
        internal static string InsertFormElement {
            get {
                return ResourceManager.GetString("InsertFormElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert Form.
        /// </summary>
        internal static string InsertFormForm {
            get {
                return ResourceManager.GetString("InsertFormForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert Hidden.
        /// </summary>
        internal static string InsertFormHidden {
            get {
                return ResourceManager.GetString("InsertFormHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert Password.
        /// </summary>
        internal static string InsertFormPassword {
            get {
                return ResourceManager.GetString("InsertFormPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert Radio.
        /// </summary>
        internal static string InsertFormRadio {
            get {
                return ResourceManager.GetString("InsertFormRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert Reset.
        /// </summary>
        internal static string InsertFormReset {
            get {
                return ResourceManager.GetString("InsertFormReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert Select.
        /// </summary>
        internal static string InsertFormSelect {
            get {
                return ResourceManager.GetString("InsertFormSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert Submit.
        /// </summary>
        internal static string InsertFormSubmit {
            get {
                return ResourceManager.GetString("InsertFormSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert Textbox.
        /// </summary>
        internal static string InsertFormText {
            get {
                return ResourceManager.GetString("InsertFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert Textarea.
        /// </summary>
        internal static string InsertFormTextarea {
            get {
                return ResourceManager.GetString("InsertFormTextarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert Groupbox.
        /// </summary>
        internal static string InsertGroupbox {
            get {
                return ResourceManager.GetString("InsertGroupbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Horizontal Rule.
        /// </summary>
        internal static string InsertHorizontalRule {
            get {
                return ResourceManager.GetString("InsertHorizontalRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert Image.
        /// </summary>
        internal static string InsertImage {
            get {
                return ResourceManager.GetString("InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert Link.
        /// </summary>
        internal static string InsertLink {
            get {
                return ResourceManager.GetString("InsertLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numbered List.
        /// </summary>
        internal static string InsertOrderedList {
            get {
                return ResourceManager.GetString("InsertOrderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Paragraph.
        /// </summary>
        internal static string InsertParagraph {
            get {
                return ResourceManager.GetString("InsertParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert Row Above.
        /// </summary>
        internal static string InsertRowAbove {
            get {
                return ResourceManager.GetString("InsertRowAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert Row Below.
        /// </summary>
        internal static string InsertRowBelow {
            get {
                return ResourceManager.GetString("InsertRowBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert Code Snippet.
        /// </summary>
        internal static string InsertSnippet {
            get {
                return ResourceManager.GetString("InsertSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert Symbol.
        /// </summary>
        internal static string InsertSymbol {
            get {
                return ResourceManager.GetString("InsertSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert Table.
        /// </summary>
        internal static string InsertTable {
            get {
                return ResourceManager.GetString("InsertTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert Table.
        /// </summary>
        internal static string InsertTableLight {
            get {
                return ResourceManager.GetString("InsertTableLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert Time.
        /// </summary>
        internal static string InsertTime {
            get {
                return ResourceManager.GetString("InsertTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bullet List.
        /// </summary>
        internal static string InsertUnorderedList {
            get {
                return ResourceManager.GetString("InsertUnorderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Italic.
        /// </summary>
        internal static string Italic {
            get {
                return ResourceManager.GetString("Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Align Center.
        /// </summary>
        internal static string JustifyCenter {
            get {
                return ResourceManager.GetString("JustifyCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Justify.
        /// </summary>
        internal static string JustifyFull {
            get {
                return ResourceManager.GetString("JustifyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Align Left.
        /// </summary>
        internal static string JustifyLeft {
            get {
                return ResourceManager.GetString("JustifyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove alignment.
        /// </summary>
        internal static string JustifyNone {
            get {
                return ResourceManager.GetString("JustifyNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Align Right.
        /// </summary>
        internal static string JustifyRight {
            get {
                return ResourceManager.GetString("JustifyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hyperlink Manager.
        /// </summary>
        internal static string LinkManager {
            get {
                return ResourceManager.GetString("LinkManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Media Manager.
        /// </summary>
        internal static string MediaManager {
            get {
                return ResourceManager.GetString("MediaManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merge Cells Horizontally.
        /// </summary>
        internal static string MergeColumns {
            get {
                return ResourceManager.GetString("MergeColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merge Cells Vertically.
        /// </summary>
        internal static string MergeRows {
            get {
                return ResourceManager.GetString("MergeRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Module Manager.
        /// </summary>
        internal static string ModuleManager {
            get {
                return ResourceManager.GetString("ModuleManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Outdent.
        /// </summary>
        internal static string Outdent {
            get {
                return ResourceManager.GetString("Outdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Page Properties.
        /// </summary>
        internal static string PageProperties {
            get {
                return ResourceManager.GetString("PageProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paste.
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paste As Html.
        /// </summary>
        internal static string PasteAsHtml {
            get {
                return ResourceManager.GetString("PasteAsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paste from Word.
        /// </summary>
        internal static string PasteFromWord {
            get {
                return ResourceManager.GetString("PasteFromWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paste from Word, strip font.
        /// </summary>
        internal static string PasteFromWordNoFontsNoSizes {
            get {
                return ResourceManager.GetString("PasteFromWordNoFontsNoSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paste Html.
        /// </summary>
        internal static string PasteHtml {
            get {
                return ResourceManager.GetString("PasteHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paste Plain Text.
        /// </summary>
        internal static string PastePlainText {
            get {
                return ResourceManager.GetString("PastePlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paste Options.
        /// </summary>
        internal static string PasteStrip {
            get {
                return ResourceManager.GetString("PasteStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Real font size.
        /// </summary>
        internal static string RealFontSize {
            get {
                return ResourceManager.GetString("RealFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Redo.
        /// </summary>
        internal static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repeat Last Command.
        /// </summary>
        internal static string RepeatLastCommand {
            get {
                return ResourceManager.GetString("RepeatLastCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please, do not delete this string. RadEditor needs it to determine if an external resource file is present in App_GlobalResources..
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select All.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cell Properties.
        /// </summary>
        internal static string SetCellProperties {
            get {
                return ResourceManager.GetString("SetCellProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Properties....
        /// </summary>
        internal static string SetImageProperties {
            get {
                return ResourceManager.GetString("SetImageProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Properties....
        /// </summary>
        internal static string SetLinkProperties {
            get {
                return ResourceManager.GetString("SetLinkProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table Properties.
        /// </summary>
        internal static string SetTableProperties {
            get {
                return ResourceManager.GetString("SetTableProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Silverlight Manager.
        /// </summary>
        internal static string SilverlightManager {
            get {
                return ResourceManager.GetString("SilverlightManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spellchecker.
        /// </summary>
        internal static string SpellCheck {
            get {
                return ResourceManager.GetString("SpellCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Split Cell Vertically.
        /// </summary>
        internal static string SplitCell {
            get {
                return ResourceManager.GetString("SplitCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Split Cell Horizontally.
        /// </summary>
        internal static string SplitCellHorizontal {
            get {
                return ResourceManager.GetString("SplitCellHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Strikethrough.
        /// </summary>
        internal static string StrikeThrough {
            get {
                return ResourceManager.GetString("StrikeThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Strip All Formatting.
        /// </summary>
        internal static string StripAll {
            get {
                return ResourceManager.GetString("StripAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Strip Css Formatting.
        /// </summary>
        internal static string StripCss {
            get {
                return ResourceManager.GetString("StripCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Strip Font Elements.
        /// </summary>
        internal static string StripFont {
            get {
                return ResourceManager.GetString("StripFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Strip Span Elements.
        /// </summary>
        internal static string StripSpan {
            get {
                return ResourceManager.GetString("StripSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Strip Word Formatting.
        /// </summary>
        internal static string StripWord {
            get {
                return ResourceManager.GetString("StripWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Style Builder.
        /// </summary>
        internal static string StyleBuilder {
            get {
                return ResourceManager.GetString("StyleBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subscript.
        /// </summary>
        internal static string Subscript {
            get {
                return ResourceManager.GetString("Subscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SuperScript.
        /// </summary>
        internal static string Superscript {
            get {
                return ResourceManager.GetString("Superscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table Wizard.
        /// </summary>
        internal static string TableWizard {
            get {
                return ResourceManager.GetString("TableWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Template Manager.
        /// </summary>
        internal static string TemplateManager {
            get {
                return ResourceManager.GetString("TemplateManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dock all Floating Toolbars/Modules.
        /// </summary>
        internal static string ToggleDocking {
            get {
                return ResourceManager.GetString("ToggleDocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toggle Floating Toolbar.
        /// </summary>
        internal static string ToggleFloatingToolbar {
            get {
                return ResourceManager.GetString("ToggleFloatingToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toggle Full Screen Mode.
        /// </summary>
        internal static string ToggleScreenMode {
            get {
                return ResourceManager.GetString("ToggleScreenMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show/Hide Border.
        /// </summary>
        internal static string ToggleTableBorder {
            get {
                return ResourceManager.GetString("ToggleTableBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Track Changes.
        /// </summary>
        internal static string TrackChangesDialog {
            get {
                return ResourceManager.GetString("TrackChangesDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Underline.
        /// </summary>
        internal static string Underline {
            get {
                return ResourceManager.GetString("Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Undo.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove Link.
        /// </summary>
        internal static string Unlink {
            get {
                return ResourceManager.GetString("Unlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XHTML Validator.
        /// </summary>
        internal static string XhtmlValidator {
            get {
                return ResourceManager.GetString("XhtmlValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom.
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
