//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.RadGrid {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez le projet Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadGrid.Main", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string AddNewRecordImageUrl {
            get {
                return ResourceManager.GetString("AddNewRecordImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add new record.
        /// </summary>
        internal static string AddNewRecordText {
            get {
                return ResourceManager.GetString("AddNewRecordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Between.
        /// </summary>
        internal static string BetweenText {
            get {
                return ResourceManager.GetString("BetweenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Page size:.
        /// </summary>
        internal static string ChangePageSizeLabelText {
            get {
                return ResourceManager.GetString("ChangePageSizeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change.
        /// </summary>
        internal static string ChangePageSizeLinkButtonText {
            get {
                return ResourceManager.GetString("ChangePageSizeLinkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        internal static string CloseText {
            get {
                return ResourceManager.GetString("CloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collapse group.
        /// </summary>
        internal static string CollapseTooltip {
            get {
                return ResourceManager.GetString("CollapseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Width: &lt;strong&gt;{0}&lt;/strong&gt; &lt;em&gt;pixels&lt;/em&gt;.
        /// </summary>
        internal static string ColumnResizeTooltipFormatString {
            get {
                return ResourceManager.GetString("ColumnResizeTooltipFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contains.
        /// </summary>
        internal static string ContainsText {
            get {
                return ResourceManager.GetString("ContainsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Custom.
        /// </summary>
        internal static string CustomText {
            get {
                return ResourceManager.GetString("CustomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DoesNotContain.
        /// </summary>
        internal static string DoesNotContainText {
            get {
                return ResourceManager.GetString("DoesNotContainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drag to group or reorder.
        /// </summary>
        internal static string DragToGroupOrReorder {
            get {
                return ResourceManager.GetString("DragToGroupOrReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drag to resize.
        /// </summary>
        internal static string DragToResize {
            get {
                return ResourceManager.GetString("DragToResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drop here to reorder.
        /// </summary>
        internal static string DropHereToReorder {
            get {
                return ResourceManager.GetString("DropHereToReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit.
        /// </summary>
        internal static string EditText {
            get {
                return ResourceManager.GetString("EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EndsWith.
        /// </summary>
        internal static string EndsWithText {
            get {
                return ResourceManager.GetString("EndsWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EqualTo.
        /// </summary>
        internal static string EqualToText {
            get {
                return ResourceManager.GetString("EqualToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expand group.
        /// </summary>
        internal static string ExpandTooltip {
            get {
                return ResourceManager.GetString("ExpandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string ExportToCsvImageUrl {
            get {
                return ResourceManager.GetString("ExportToCsvImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export to CSV.
        /// </summary>
        internal static string ExportToCsvText {
            get {
                return ResourceManager.GetString("ExportToCsvText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string ExportToExcelImageUrl {
            get {
                return ResourceManager.GetString("ExportToExcelImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export to Excel.
        /// </summary>
        internal static string ExportToExcelText {
            get {
                return ResourceManager.GetString("ExportToExcelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string ExportToPdfImageUrl {
            get {
                return ResourceManager.GetString("ExportToPdfImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export to PDF.
        /// </summary>
        internal static string ExportToPdfText {
            get {
                return ResourceManager.GetString("ExportToPdfText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string ExportToWordImageUrl {
            get {
                return ResourceManager.GetString("ExportToWordImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export to Word.
        /// </summary>
        internal static string ExportToWordText {
            get {
                return ResourceManager.GetString("ExportToWordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string FilterExpression {
            get {
                return ResourceManager.GetString("FilterExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter.
        /// </summary>
        internal static string FilterImageToolTip {
            get {
                return ResourceManager.GetString("FilterImageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string FirstPageText {
            get {
                return ResourceManager.GetString("FirstPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à First Page.
        /// </summary>
        internal static string FirstPageToolTip {
            get {
                return ResourceManager.GetString("FirstPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Page:.
        /// </summary>
        internal static string GoToPageLabelText {
            get {
                return ResourceManager.GetString("GoToPageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go.
        /// </summary>
        internal static string GoToPageLinkButtonText {
            get {
                return ResourceManager.GetString("GoToPageLinkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à GreaterThanOrEqualTo.
        /// </summary>
        internal static string GreaterThanOrEqualToText {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à GreaterThan.
        /// </summary>
        internal static string GreaterThanText {
            get {
                return ResourceManager.GetString("GreaterThanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ; .
        /// </summary>
        internal static string GroupByFieldsSeparator {
            get {
                return ResourceManager.GetString("GroupByFieldsSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ... group continued from the previous page. .
        /// </summary>
        internal static string GroupContinuedFormatString {
            get {
                return ResourceManager.GetString("GroupContinuedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Group continues on the next page..
        /// </summary>
        internal static string GroupContinuesFormatString {
            get {
                return ResourceManager.GetString("GroupContinuesFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drag a column header and drop it here to group by that column.
        /// </summary>
        internal static string GroupPanelText {
            get {
                return ResourceManager.GetString("GroupPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Showing {0} of {1} items..
        /// </summary>
        internal static string GroupSplitDisplayFormat {
            get {
                return ResourceManager.GetString("GroupSplitDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  ({0}).
        /// </summary>
        internal static string GroupSplitFormat {
            get {
                return ResourceManager.GetString("GroupSplitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aggregates.
        /// </summary>
        internal static string HeaderContextMenuAggregates {
            get {
                return ResourceManager.GetString("HeaderContextMenuAggregates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à And.
        /// </summary>
        internal static string HeaderContextMenuAndLabel {
            get {
                return ResourceManager.GetString("HeaderContextMenuAndLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Avg.
        /// </summary>
        internal static string HeaderContextMenuAvgAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuAvgAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Best Fit.
        /// </summary>
        internal static string HeaderContextMenuBestFitText {
            get {
                return ResourceManager.GetString("HeaderContextMenuBestFitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear Filter.
        /// </summary>
        internal static string HeaderContextMenuClearButton {
            get {
                return ResourceManager.GetString("HeaderContextMenuClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Columns.
        /// </summary>
        internal static string HeaderContextMenuColumns {
            get {
                return ResourceManager.GetString("HeaderContextMenuColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Count.
        /// </summary>
        internal static string HeaderContextMenuCountAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuCountAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CountDistinct.
        /// </summary>
        internal static string HeaderContextMenuCountDistinctAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuCountDistinctAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Custom.
        /// </summary>
        internal static string HeaderContextMenuCustomAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuCustomAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter.
        /// </summary>
        internal static string HeaderContextMenuFilterButton {
            get {
                return ResourceManager.GetString("HeaderContextMenuFilterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter.
        /// </summary>
        internal static string HeaderContextMenuFilterItemText {
            get {
                return ResourceManager.GetString("HeaderContextMenuFilterItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à First.
        /// </summary>
        internal static string HeaderContextMenuFirstAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuFirstAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Group By.
        /// </summary>
        internal static string HeaderContextMenuGroupBy {
            get {
                return ResourceManager.GetString("HeaderContextMenuGroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last.
        /// </summary>
        internal static string HeaderContextMenuLastAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuLastAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Max.
        /// </summary>
        internal static string HeaderContextMenuMaxAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuMaxAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Min.
        /// </summary>
        internal static string HeaderContextMenuMinAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuMinAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à None.
        /// </summary>
        internal static string HeaderContextMenuNoneAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuNoneAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show rows with value that.
        /// </summary>
        internal static string HeaderContextMenuRowsLabel {
            get {
                return ResourceManager.GetString("HeaderContextMenuRowsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sort Ascending.
        /// </summary>
        internal static string HeaderContextMenuSortAsc {
            get {
                return ResourceManager.GetString("HeaderContextMenuSortAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear Sorting.
        /// </summary>
        internal static string HeaderContextMenuSortClear {
            get {
                return ResourceManager.GetString("HeaderContextMenuSortClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sort Descending.
        /// </summary>
        internal static string HeaderContextMenuSortDesc {
            get {
                return ResourceManager.GetString("HeaderContextMenuSortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sum.
        /// </summary>
        internal static string HeaderContextMenuSumAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuSumAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ungroup.
        /// </summary>
        internal static string HeaderContextMenuUnGroupBy {
            get {
                return ResourceManager.GetString("HeaderContextMenuUnGroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collapse.
        /// </summary>
        internal static string HierarchyCollapseTooltip {
            get {
                return ResourceManager.GetString("HierarchyCollapseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expand.
        /// </summary>
        internal static string HierarchyExpandTooltip {
            get {
                return ResourceManager.GetString("HierarchyExpandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Self reference collapse.
        /// </summary>
        internal static string HierarchySelfCollapseTooltip {
            get {
                return ResourceManager.GetString("HierarchySelfCollapseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Self reference expand.
        /// </summary>
        internal static string HierarchySelfExpandTooltip {
            get {
                return ResourceManager.GetString("HierarchySelfExpandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert.
        /// </summary>
        internal static string InsertText {
            get {
                return ResourceManager.GetString("InsertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IsEmpty.
        /// </summary>
        internal static string IsEmptyText {
            get {
                return ResourceManager.GetString("IsEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IsNull.
        /// </summary>
        internal static string IsNullText {
            get {
                return ResourceManager.GetString("IsNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string LastPageText {
            get {
                return ResourceManager.GetString("LastPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last Page.
        /// </summary>
        internal static string LastPageToolTip {
            get {
                return ResourceManager.GetString("LastPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LessThanOrEqualTo.
        /// </summary>
        internal static string LessThanOrEqualToText {
            get {
                return ResourceManager.GetString("LessThanOrEqualToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LessThan.
        /// </summary>
        internal static string LessThanText {
            get {
                return ResourceManager.GetString("LessThanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading....
        /// </summary>
        internal static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Next Pages.
        /// </summary>
        internal static string NextPagesToolTip {
            get {
                return ResourceManager.GetString("NextPagesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string NextPageText {
            get {
                return ResourceManager.GetString("NextPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Next Page.
        /// </summary>
        internal static string NextPageToolTip {
            get {
                return ResourceManager.GetString("NextPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No child records to display..
        /// </summary>
        internal static string NoDetailRecordsText {
            get {
                return ResourceManager.GetString("NoDetailRecordsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NoFilter.
        /// </summary>
        internal static string NoFilterText {
            get {
                return ResourceManager.GetString("NoFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No records to display..
        /// </summary>
        internal static string NoMasterRecordsText {
            get {
                return ResourceManager.GetString("NoMasterRecordsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NotBetween.
        /// </summary>
        internal static string NotBetweenText {
            get {
                return ResourceManager.GetString("NotBetweenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NotEqualTo.
        /// </summary>
        internal static string NotEqualToText {
            get {
                return ResourceManager.GetString("NotEqualToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NotIsEmpty.
        /// </summary>
        internal static string NotIsEmptyText {
            get {
                return ResourceManager.GetString("NotIsEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NotIsNull.
        /// </summary>
        internal static string NotIsNullText {
            get {
                return ResourceManager.GetString("NotIsNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à of {0}.
        /// </summary>
        internal static string PageOfLabelText {
            get {
                return ResourceManager.GetString("PageOfLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change page: {4} &amp;nbsp;Page &lt;strong&gt;{0}&lt;/strong&gt; of &lt;strong&gt;{1}&lt;/strong&gt;, items &lt;strong&gt;{2}&lt;/strong&gt; to &lt;strong&gt;{3}&lt;/strong&gt; of &lt;strong&gt;{5}&lt;/strong&gt;..
        /// </summary>
        internal static string PagerTextFormat {
            get {
                return ResourceManager.GetString("PagerTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Page &lt;strong&gt;{0}&lt;/strong&gt; of &lt;strong&gt;{1}&lt;/strong&gt;.
        /// </summary>
        internal static string PagerTooltipFormatString {
            get {
                return ResourceManager.GetString("PagerTooltipFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Page size:.
        /// </summary>
        internal static string PageSizeLabelText {
            get {
                return ResourceManager.GetString("PageSizeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Previous Pages.
        /// </summary>
        internal static string PrevPagesToolTip {
            get {
                return ResourceManager.GetString("PrevPagesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string PrevPageText {
            get {
                return ResourceManager.GetString("PrevPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Previous Page.
        /// </summary>
        internal static string PrevPageToolTip {
            get {
                return ResourceManager.GetString("PrevPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string RefreshImageUrl {
            get {
                return ResourceManager.GetString("RefreshImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please do not remove this key..
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sorted asc.
        /// </summary>
        internal static string SortedAscToolTip {
            get {
                return ResourceManager.GetString("SortedAscToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sorted desc.
        /// </summary>
        internal static string SortedDescToolTip {
            get {
                return ResourceManager.GetString("SortedDescToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to sort.
        /// </summary>
        internal static string SortToolTip {
            get {
                return ResourceManager.GetString("SortToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à StartsWith.
        /// </summary>
        internal static string StartsWithText {
            get {
                return ResourceManager.GetString("StartsWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ready.
        /// </summary>
        internal static string StatusReadyText {
            get {
                return ResourceManager.GetString("StatusReadyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here to ungroup.
        /// </summary>
        internal static string UnGroupButtonTooltip {
            get {
                return ResourceManager.GetString("UnGroupButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drag out of the bar to ungroup.
        /// </summary>
        internal static string UnGroupTooltip {
            get {
                return ResourceManager.GetString("UnGroupTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update.
        /// </summary>
        internal static string UpdateText {
            get {
                return ResourceManager.GetString("UpdateText", resourceCulture);
            }
        }
    }
}
