CREATE TRIGGER ZALBINKHEO.INSERTYAPRMAN 
	AFTER INSERT ON ZALBINKHEO.YAPRMAN 
	REFERENCING NEW AS NOUVLINE 
	FOR EACH ROW 
	MODE DB2SQL 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN ATOMIC 
  
DECLARE V_TYP CHAR ( 1 ) DEFAULT '' ; 
DECLARE V_IPB CHAR ( 9 ) DEFAULT '' ; 
DECLARE V_VERSION NUMERIC DEFAULT 0 ; 
  
SET SQLP_L2 . V_VERSION = NOUVLINE . ABRALX ; 
SET SQLP_L2 . V_IPB = NOUVLINE . ABRIPB ; 
SELECT YALBINFILE . YPOBASE . PBTYP INTO SQLP_L2 . V_TYP FROM YALBINFILE . YPOBASE WHERE 
QSYS2 . TRIM ( YALBINFILE . YPOBASE . PBIPB ) = QSYS2 . TRIM ( SQLP_L2 . V_IPB ) AND YALBINFILE . YPOBASE . PBALX = SQLP_L2 . V_VERSION ; 
  
CALL YALBINFILE . SP_UPDATEKGRPTRG ( SQLP_L2 . V_TYP , SQLP_L2 . V_IPB , SQLP_L2 . V_VERSION , 'YAPRMAN' , 'INSERT-*' ) ; 
END  ; 
  
