CREATE TRIGGER ZALBINKHEO.INSERTYPOSTAT 
	AFTER INSERT ON ZALBINKHEO.YPOSTAT 
	REFERENCING NEW AS NOUVLINE 
	FOR EACH ROW 
	MODE DB2SQL 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN ATOMIC 
  
DECLARE V_TYP CHAR ( 1 ) DEFAULT '' ; 
DECLARE V_IPB CHAR ( 9 ) DEFAULT '' ; 
DECLARE V_VERSION NUMERIC DEFAULT 0 ; 
  
SET SQLP_L2 . V_VERSION = NOUVLINE . AAPALX ; 
SET SQLP_L2 . V_IPB = NOUVLINE . AAPIPB ; 
SET SQLP_L2 . V_TYP = NOUVLINE . AAPTYP ; 
  
CALL YALBINFILE . SP_UPDATEKGRPTRG ( SQLP_L2 . V_TYP , SQLP_L2 . V_IPB , SQLP_L2 . V_VERSION , 'YPOSTAT' , 'INSERT-*' ) ; 
END  ; 
  
