CREATE TRIGGER ZALBINKHEO.TESTU 
	AFTER UPDATE ON ZALBINKHEO.YPOBAS0005 
	REFERENCING OLD AS ANCLINE 
	NEW AS NOUVLINE 
	FOR EACH ROW 
	MODE DB2ROW 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN ATOMIC 
INSERT INTO ZALBINKHEO . KGRPTRG ( KDZTYP , KDZIPB , KDZALX , KDZTRT , KDZMAJA , KDZMAJM , KDZMAJJ , KDZACT , KDZOBS ) 
VALUES ( NOUVLINE . PBTYP , QSYS2 . RIGHT ( QSYS2 . REPEAT ( ' ' , 9 ) || NOUVLINE . PBIPB , 9 ) , NOUVLINE . PBALX , 'N' , NOUVLINE . PBMJA , NOUVLINE . PBMJM , NOUVLINE . PBMJJ , 'M' , '' ) ; 
END  ; 
  
LABEL ON TABLE ZALBINKHEO.YPOBAS0005 
	IS 'Ancien nom YPOBASE de ZALBINKHEO, propr ALBINGIA.' ; 
  
LABEL ON COLUMN ZALBINKHEO.YPOBAS0005 
( PBTYP IS 'Type                O/P' , 
	PBIPB IS 'N° de police / Offre' , 
	PBALX IS 'N° Aliment / connexe' , 
	PBTBR IS 'CO ou RT' , 
	PBIAS IS 'Identifiant Assuré' , 
	PBREF IS 'Référence' , 
	PBBRA IS 'Branche' , 
	PBSBR IS 'Sous-branche' , 
	PBCAT IS 'Catégorie' , 
	PBICT IS 'Courtier' , 
	PBTIL IS 'Type interlocuteur' , 
	PBINL IS 'Code interlocuteur' , 
	PBOCT IS 'Référence police' , 
	PBAD1 IS 'Adresse 1 du risque' , 
	PBAD2 IS 'Adresse 2 du risque' , 
	PBDEP IS 'Département  risque' , 
	PBCPO IS 'Code postal risque' , 
	PBVIL IS 'Ville du risque' , 
	PBPAY IS 'Code pays du risque' , 
	PBSAA IS 'Année saisie /accord' , 
	PBSAM IS 'Mois saisie / accord' , 
	PBSAJ IS 'Jour saisie / accord' , 
	PBSAH IS 'Heure de saisie' , 
	PBAPR IS 'Apériteur' , 
	PBAPP IS '% Apérition Albingia' , 
	PBMO1 IS 'Mot clé 1' , 
	PBMO2 IS 'Mot clé 2' , 
	PBMO3 IS 'Mot clé 3' , 
	PBCLE IS 'Gestion clauses O/N' , 
	PBANT IS 'Code antécédent' , 
	PBCTD IS 'Durée Police' , 
	PBCTU IS 'Unité de la durée' , 
	PBAPO IS 'Adressée apérit.O/N' , 
	PBDUR IS 'Durée de l''offre' , 
	PBREL IS 'Relance de l''offre' , 
	PBRLD IS 'Délai de la relance' , 
	PBATT IS 'Délai attente offre' , 
	PBRMP IS 'Version remplacée   O/N' , 
	PBVRF IS 'N° version référence' , 
	PBOLV IS 'N° version modifiée' , 
	PBFOA IS 'Action fin d''offre' , 
	PBFOM IS 'Motif de l''action' , 
	PBCOU IS 'N° de courrier' , 
	PBFOE IS 'Entête libre O/N' , 
	PBDEV IS 'Code devise' , 
	PBRGT IS 'Régime de taxe' , 
	PBTCO IS 'Type de construction' , 
	PBNAT IS 'Nature des travaux' , 
	PBDST IS 'Code destination' , 
	PBLIE IS 'Top O/N' , 
	PBGES IS 'Gestionnaire' , 
	PBSOU IS 'Souscripteur' , 
	PBORI IS 'Code origine' , 
	PBMAI IS 'N° de mailing' , 
	PBEFA IS 'Année Date effet pol' , 
	PBEFM IS 'Mois Date effet pol' , 
	PBEFJ IS 'Jour Date effet pol.' , 
	PBOFF IS 'N° Offre si police' , 
	PBOFV IS 'N° Version Offre' , 
	PBIPA IS 'N° police Associée' , 
	PBALA IS 'Aliment police assoc' , 
	PBECM IS 'Echéance Princ: Mois' , 
	PBECJ IS 'Echéance princi:Jour' , 
	PBPCV IS '% couvert' , 
	PBCTA IS 'Id courtier apport' , 
	PBNRQ IS 'Nature du risque' , 
	PBNPL IS 'Nature Police' , 
	PBPER IS 'Code périodicité' , 
	PBAVN IS 'N° avenant' , 
	PBAVC IS 'Motif avenant' , 
	PBAVA IS 'Année effet avenant' , 
	PBAVM IS 'Mois  effet avenant' , 
	PBAVJ IS 'Jour effet avenant' , 
	PBRSC IS 'Motif résiliat/Susp' , 
	PBRSA IS 'Année résiliat/susp' , 
	PBRSM IS 'Mois résiliat/susp' , 
	PBRSJ IS 'Jour résiliat/susp' , 
	PBMER IS 'Police mère M/A' , 
	PBETA IS 'Etat police' , 
	PBSIT IS 'Code situation' , 
	PBSTA IS 'Année de situation' , 
	PBSTM IS 'Mois de situation' , 
	PBSTJ IS 'Jour de situation' , 
	PBSTQ IS 'Qualité situation' , 
	PBEDT IS 'Police éditéé O/N' , 
	PBTAC IS 'Type accord' , 
	PBTAA IS 'Année accord' , 
	PBTAM IS 'Mois Accord' , 
	PBTAJ IS 'Jour accord' , 
	PBCRU IS 'User Création' , 
	PBCRA IS 'Année création' , 
	PBCRM IS 'Mois création' , 
	PBCRJ IS 'Jour création' , 
	PBMJU IS 'User Màj' , 
	PBMJA IS 'Année Màj' , 
	PBMJM IS 'Mois Màj' , 
	PBMJJ IS 'Jour Màj' , 
	PBDEU IS 'User Date entrée' , 
	PBDEA IS 'Année Date Entrée' , 
	PBDEM IS 'Mois Date Entrée' , 
	PBDEJ IS 'Jour Date Entrée' , 
	PBCTP IS 'Etablissemnt payeur' , 
	PBEFH IS 'Début effet Heure' , 
	PBFEA IS 'Année Fin Effet' , 
	PBFEM IS 'Mois Fin Effet' , 
	PBFEJ IS 'Jour Fin Effet' , 
	PBFEH IS 'Heure Fin effet' , 
	PBSTP IS 'Top stop' , 
	PBNVA IS 'Motif non validation' , 
	PBFEC IS 'Cause fin de garanti' , 
	PBPOR IS 'Remplacement Police' , 
	PBCON IS 'Code contentieux' , 
	PBTTR IS 'Type de traitement' , 
	PBAVK IS 'N° Avenant Externe' , 
	PBADH IS 'N° Chrono Adresse' , 
	PBSTF IS 'Motif de situation' , 
	PBPIM IS 'Code périmètre' , 
	PBIN5 IS 'Code interlocuteur' , 
	PBORK IS 'KHEOPS statut' ) ; 
  
LABEL ON COLUMN ZALBINKHEO.YPOBAS0005 
( PBTYP TEXT IS 'Type  O Offre  P Police' , 
	PBIPB TEXT IS 'N° de Police / Offre' , 
	PBALX TEXT IS 'N° Aliment ou Connexe et version' , 
	PBTBR TEXT IS 'CO ou RT' , 
	PBIAS TEXT IS 'Identifiant Assuré 10/00' , 
	PBREF TEXT IS 'Référence' , 
	PBBRA TEXT IS 'Branche' , 
	PBSBR TEXT IS 'Sous-branche' , 
	PBCAT TEXT IS 'Catégorie' , 
	PBICT TEXT IS 'Courtier' , 
	PBTIL TEXT IS 'Type interlocuteur' , 
	PBINL TEXT IS 'Interlocuteur' , 
	PBOCT TEXT IS 'Référence chez courtier' , 
	PBAD1 TEXT IS 'Adresse 1 du risque' , 
	PBAD2 TEXT IS 'Adresse 2 du risque' , 
	PBDEP TEXT IS 'Département du risque' , 
	PBCPO TEXT IS '3 dern.car.code postal du risque' , 
	PBVIL TEXT IS 'Ville du risque' , 
	PBPAY TEXT IS 'Code pays du risque' , 
	PBSAA TEXT IS 'Année de saisie Cie ou accord' , 
	PBSAM TEXT IS 'Mois de saisie ou accord' , 
	PBSAJ TEXT IS 'Jour de saisie ou accord' , 
	PBSAH TEXT IS 'Heure de saisie' , 
	PBAPR TEXT IS 'Apériteur' , 
	PBAPP TEXT IS '% Apérition  Albingia' , 
	PBMO1 TEXT IS 'Mot clé 1' , 
	PBMO2 TEXT IS 'Mot clé 2' , 
	PBMO3 TEXT IS 'Mot clé 3' , 
	PBCLE TEXT IS 'Gestion des clauses O/N' , 
	PBANT TEXT IS 'Code antécédent' , 
	PBCTD TEXT IS 'Durée de la police' , 
	PBCTU TEXT IS 'Unité de la durée de police' , 
	PBAPO TEXT IS 'Offre adressée à l''apériteur O/N' , 
	PBDUR TEXT IS 'Offre Durée en jour' , 
	PBREL TEXT IS 'Offre Relance O/N' , 
	PBRLD TEXT IS 'Offre Délai de la relance en jour' , 
	PBATT TEXT IS 'Offre Délai attente' , 
	PBRMP TEXT IS 'Offre Version remplacée O/N' , 
	PBVRF TEXT IS 'Offre N° Version de référence' , 
	PBOLV TEXT IS 'Offre N° Version modifiée' , 
	PBFOA TEXT IS 'Offre Action de fin d''offre' , 
	PBFOM TEXT IS 'Offre Motif de l''action' , 
	PBCOU TEXT IS 'Offre N° de courrier' , 
	PBFOE TEXT IS 'Offre Entête libre O/N let.Accomp.' , 
	PBDEV TEXT IS 'Code devise' , 
	PBRGT TEXT IS 'Régime de taxe' , 
	PBTCO TEXT IS 'Type de construction' , 
	PBNAT TEXT IS 'Nature des travaux' , 
	PBDST TEXT IS 'Code destination' , 
	PBLIE TEXT IS 'Autres courtiers O/N Lien si refus' , 
	PBGES TEXT IS 'Gestionnaire' , 
	PBSOU TEXT IS 'Souscripteur' , 
	PBORI TEXT IS 'Code origine' , 
	PBMAI TEXT IS 'Numéro de mailing' , 
	PBEFA TEXT IS 'Année Date effet police' , 
	PBEFM TEXT IS 'Mois  Date effet police' , 
	PBEFJ TEXT IS 'Jour  Date effet police' , 
	PBOFF TEXT IS 'N° Offre si police' , 
	PBOFV TEXT IS 'N° version de l''offre si police' , 
	PBIPA TEXT IS 'N° de Police Associée' , 
	PBALA TEXT IS 'N° aliment Police associée' , 
	PBECM TEXT IS 'Echéance principale : Mois' , 
	PBECJ TEXT IS 'Echéance principale : jour' , 
	PBPCV TEXT IS '% Couvert' , 
	PBCTA TEXT IS 'Id courtier Apporteur' , 
	PBNRQ TEXT IS 'Nature du risque' , 
	PBNPL TEXT IS 'Nature Police' , 
	PBPER TEXT IS 'Code périodicité' , 
	PBAVN TEXT IS 'N° avenant' , 
	PBAVC TEXT IS 'Motif avenant' , 
	PBAVA TEXT IS 'Année effet avenant' , 
	PBAVM TEXT IS 'Mois  effet avenant' , 
	PBAVJ TEXT IS 'Jour  effet avenant' , 
	PBRSC TEXT IS 'Motif résiliation/Suspension' , 
	PBRSA TEXT IS 'Année résiliation/suspension' , 
	PBRSM TEXT IS 'Mois résiliation/suspension' , 
	PBRSJ TEXT IS 'Jour résiliation/suspension' , 
	PBMER TEXT IS 'Police mère ou aliment (M/A/ )' , 
	PBETA TEXT IS 'Etat police (V validé A / N / R)' , 
	PBSIT TEXT IS 'Code situation' , 
	PBSTA TEXT IS 'Année de situation' , 
	PBSTM TEXT IS 'Mois de situation' , 
	PBSTJ TEXT IS 'Jour de situation' , 
	PBSTQ TEXT IS 'Qualité sit Police-Fini-Régul-Note.c' , 
	PBEDT TEXT IS 'Police éditée O/N' , 
	PBTAC TEXT IS 'Type accord S Signée N Non signée ..' , 
	PBTAA TEXT IS 'Année accord' , 
	PBTAM TEXT IS 'Mois Accord' , 
	PBTAJ TEXT IS 'Jour accord' , 
	PBCRU TEXT IS 'User Création (Validation souscript)' , 
	PBCRA TEXT IS 'Année Création(Validation souscript)' , 
	PBCRM TEXT IS 'Mois création (Validation souscript)' , 
	PBCRJ TEXT IS 'Jour création (Validation souscript)' , 
	PBMJU TEXT IS 'User Màj' , 
	PBMJA TEXT IS 'Année Màj' , 
	PBMJM TEXT IS 'Mois Màj' , 
	PBMJJ TEXT IS 'Jour Màj' , 
	PBDEU TEXT IS 'Entrée en machine : User' , 
	PBDEA TEXT IS 'Entrée en machine : Année' , 
	PBDEM TEXT IS 'Entrée en machine : Mois' , 
	PBDEJ TEXT IS 'Entrée en machine : Jour' , 
	PBCTP TEXT IS 'Etablissement Payeur (Courtier)' , 
	PBEFH TEXT IS 'Début Effet : Heure' , 
	PBFEA TEXT IS 'Date Fin Effet Année' , 
	PBFEM TEXT IS 'Date Fin Effet Mois' , 
	PBFEJ TEXT IS 'Date Fin Effet Jour' , 
	PBFEH TEXT IS 'Fin effet : Heure' , 
	PBSTP TEXT IS 'Top stop' , 
	PBNVA TEXT IS 'Motif de non Validation' , 
	PBFEC TEXT IS 'Cause de fin de garantie' , 
	PBPOR TEXT IS 'Remplacement de police O/'' '' POCONX' , 
	PBCON TEXT IS 'Code contentieux' , 
	PBTTR TEXT IS 'Type de traitement (Affnouv/avenant)' , 
	PBAVK TEXT IS 'N° Avenant Externe SPAL' , 
	PBADH TEXT IS 'Numéro chrono Adresse' , 
	PBSTF TEXT IS 'Motif de situation (Refus ...)' , 
	PBPIM TEXT IS 'Code périmètre' , 
	PBIN5 TEXT IS 'Code interlocuteur sur 5' , 
	PBORK TEXT IS 'KHEOPS Statut ''  '' ''REC'' ''REP'' ''KHE''' ) ; 
  
