CREATE TRIGGER ZALBINKHEO.TR_AFTERINSERTYPAR 
	AFTER INSERT ON ZALBINKHEO.YYYYPAR 
	REFERENCING NEW AS NEWLINE 
	FOR EACH ROW 
	MODE DB2SQL 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN ATOMIC 
DECLARE V_NBELEM INTEGER DEFAULT 0 ; 
  
SELECT COUNT ( * ) INTO SQLP_L2 . V_NBELEM FROM YKPREDTA . YYYYPAR WHERE YKPREDTA . YYYYPAR . TCON = NEWLINE . TCON AND YKPREDTA . YYYYPAR . TFAM = NEWLINE . TFAM AND YKPREDTA . YYYYPAR . TCOD = NEWLINE . TCOD ; 
  
	IF ( SQLP_L2 . V_NBELEM > 0 ) THEN 
		DELETE FROM YKPREDTA . YYYYPAR WHERE YKPREDTA . YYYYPAR . TCON = NEWLINE . TCON AND YKPREDTA . YYYYPAR . TFAM = NEWLINE . TFAM AND YKPREDTA . YYYYPAR . TCOD = NEWLINE . TCOD ; 
	END IF ; 
  
	INSERT INTO YKPREDTA . YYYYPAR ( TCON , TFAM , TCOD , TPLIB , TPCN1 , TPCN2 , TPCA1 , TPCA2 , TPTYP , TPLIL , TFILT ) SELECT YALBINFILE . YYYYPAR . TCON , YALBINFILE . YYYYPAR . TFAM , YALBINFILE . YYYYPAR . TCOD , YALBINFILE . YYYYPAR . TPLIB , YALBINFILE . YYYYPAR . TPCN1 , YALBINFILE . YYYYPAR . TPCN2 , YALBINFILE . YYYYPAR . TPCA1 , YALBINFILE . YYYYPAR . TPCA2 , YALBINFILE . YYYYPAR . TPTYP , YALBINFILE . YYYYPAR . TPLIL , YALBINFILE . YYYYPAR . TFILT FROM YALBINFILE . YYYYPAR WHERE YALBINFILE . YYYYPAR . TCON = NEWLINE . TCON AND YALBINFILE . YYYYPAR . TFAM = NEWLINE . TFAM AND YALBINFILE . YYYYPAR . TCOD = NEWLINE . TCOD ; 
  
END  ; 
  
