CREATE FUNCTION ZALBINKHEO.F_GETANNEEREF ( 
	P_ANNEE INTEGER ) 
	RETURNS INTEGER   
	LANGUAGE SQL 
	SPECIFIC ZALBINKHEO.F_GETANNEEREF 
	NOT DETERMINISTIC 
	READS SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
	 
	DECLARE V_ANNEERETURN INTEGER DEFAULT 0 ; 
	 
	SET V_ANNEERETURN = 0 ; 
	 
	SELECT IFNULL ( MAX ( ANNEE ) , 0 ) INTO V_ANNEERETURN FROM ZALBINKHEO . KPANNEEREF WHERE ANNEE <= P_ANNEE ; 
	 
	RETURN IFNULL ( V_ANNEERETURN , 0 ) ; 
	 
END  ; 
  
SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","YALBIN" ; 
  
