CREATE FUNCTION ZALBINKHEO.F_PADLEFT ( 
	P_COUNT INTEGER , 
	P_VALUE VARCHAR(200) ) 
	RETURNS VARCHAR(200)   
	LANGUAGE SQL 
	SPECIFIC ZALBINKHEO.F_PADLEFT 
	DETERMINISTIC 
	READS SQL DATA 
	RETURNS NULL ON NULL INPUT 
	NO EXTERNAL ACTION 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
BEGIN 
    DECLARE V_VALUE VARCHAR ( 200 ) ; 
    SET V_VALUE = ( REPEAT ( ' ' , P_COUNT - LENGTH ( TRIM ( P_VALUE ) ) ) || TRIM ( P_VALUE ) ) ; 
    RETURN V_VALUE ; 
END  ;
