CREATE FUNCTION ZALBINKHEO.F_REQINFOENTETE ( ) 
	RETURNS VARCHAR(10000)   
	LANGUAGE SQL 
	SPECIFIC ZALBINKHEO.F_REQINFOENTETE 
	NOT DETERMINISTIC 
	READS SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
	DECLARE P_RETURN VARCHAR ( 10000 ) ; 
	SET P_RETURN = 'SELECT PBIPB CODEOFFRE, PBIN5 CODEINTERLOCUTEUR, PBIAS CODEASSURE, PBICT CODECABINETCOURTAGE, PBSOU CODESOUSCRIPTEUR, UT1.UTNOM NOMSOUSCRIPTEUR, PBGES CODEGESTIONNAIRE, 
	UT2.UTNOM NOMGESTIONNAIRE, PBALX VERSIONOFFRE, PBTYP TYPEOFFRE, PBDEV DEVISE, PBECJ ECHEANCEPRINCIPALEJOUR, PBECM ECHEANCEPRINCIPALEMOIS, PBCTD DUREEGARANTIE, 
	PBCTU UNITETEMPS, JDIND INDICEREFERENCE, JDIVA VALEUR, PBREF DESCRIPTIF, PBOCT REFCOURTIER,PBETA ETATOFFRE,ETAT.TPLIL ETATLIB,
    PBEFJ DATEEFFETGARANTIEJOUR, PBEFM DATEEFFETGARANTIEMOIS, PBEFA DATEEFFETGARANTIEANNEE, PBEFH DATEEFFETGARANTIEHEURE, 
    PBNPL CODENATURECONTRAT,NATURE.TPLIL LIBELLENATURECONTRAT, PBAPP PARTALBINGIA, PBPCV COUVERTURE, PHAPP, PHTXF FRAISAPERITION, JDITC INTERCALAIREEXISTE, CIICI CODEAPERITEUR, CINOM NOMAPERITEUR,
    PBPER PERIODICITE, PBBRA CODEBRANCHE, YP.TPLIB NOMBRANCHE, 
    ABPLG3 BATIMENT, ABPNUM NUMEROVOIE, ABPEXT EXTENSIONVOIE, ABPLG4 NOMVOIE, ABPLG5 BOITEPOSTALE, ABPDP6 DEPARTEMENT, ABPCP6 CODEPOSTAL,
    ABPVI6 NOMVILLE, ABPPAY CODEPAYS, ABPCDX TYPECEDEX, CPAYS.TPLIB NOMPAYS,
    PBSAA DATESAISIEANNEE, PBSAM DATESAISIEMOIS, PBSAJ DATESAISIEJOUR, PBSAH DATESAISIEHEURE, PBADH NUMEROCHRONO, PBSIT SITUATION, PBMO1 CODEMOTSCLEF1, PBMO2 CODEMOTSCLEF2, 
	PBMO3 CODEMOTSCLEF3, PBFEJ FINEFFETGARANTIEJOUR, PBFEM FINEFFETGARANTIEMOIS,
    PBFEA FINEFFETGARANTIEANNEE, PBFEH FINEFFETGARANTIEHEURE,
    KAACIBLE CODECIBLE, KAHDESC NOMCIBLE, KAJOBSV OBSERVATION, PBDEA DATEENREGISTREMENTANNEE, PBDEM DATEENREGISTREMENTMOIS, PBDEJ DATEENREGISTREMENTJOUR, PBRGT CODEREGIME, RG.TPLIB REGIMLIB,             
    JDCNA SOUMISCATNAT, JDTFF MONTANTREF1, JDTMC MONTANTREF2, JDINA INDEXATION, JDIXL LCI, JDIXC ASSIETTE,
    JDIXF FRANCHISE, JDDPV PREAVIS, PBSTF CONCAT '' - '' CONCAT IFNULL(MOTIF.TPLIB, '''') PBSTF,
    PBTTR CODEACTION, TR.TPLIB LIBACTION, SIT.TPLIB LIBSITUATION, PBSTJ DATESITJOUR, PBSTM DATESITMOIS, PBSTA DATESITANNEE,
    PBDEU UCRCODE, UCR.UTNOM UCRNOM, PBMJU UUPCODE, UUP.UTNOM UUPNOM,
    PBMJA DATEMAJANNEE, PBMJM DATEMAJMOIS, PBMJJ DATEMAJJOUR,
    KAADSTA DATESTATISTIQUE, JDPBN PARTBENEF,KAAASS PRENEURESTASSURE
    FROM ZALBINKHEO.YPOBASE 
    LEFT JOIN ZALBINKHEO.YADRESS ON PBADH = ABPCHR 
    LEFT JOIN ZALBINKHEO.YPRTENT ON PBIPB = JDIPB AND PBALX = JDALX 
    LEFT JOIN ZALBINKHEO.KPENT ON KAAIPB = PBIPB AND KAAALX = PBALX AND KAATYP = PBTYP 
    LEFT JOIN ZALBINKHEO.YPOCOAS ON PBIPB = PHIPB AND PBALX = PHALX 
    LEFT JOIN ZALBINKHEO.KPOBJ ON PBIPB = KACIPB AND PBALX = KACALX 
    LEFT JOIN ZALBINKHEO.KPOBSV ON KAJCHR = KAAOBSV
    LEFT JOIN ZALBINKHEO.YUTILIS UT1 ON PBSOU = UT1.UTIUT AND UT1.UTSOU =''O'' 
    LEFT JOIN ZALBINKHEO.YUTILIS UT2 ON PBGES = UT2.UTIUT AND UT2.UTGEP =''O'' 
    LEFT JOIN ZALBINKHEO.YUTILIS UCR ON PBDEU = UCR.UTIUT 
    LEFT JOIN ZALBINKHEO.YUTILIS UUP ON PBMJU = UUP.UTIUT 
    LEFT JOIN ZALBINKHEO.YCOMPA ON CIICI = PHCIE 
    LEFT JOIN ZALBINKHEO.KCIBLE ON KAACIBLE = KAHCIBLE ' 
	CONCAT ZALBINKHEO . F_BUILDJOINYPAR ( 'LEFT' , 'GENER' , 'BRCHE' , 'YP' , ' AND YP.TCOD = PBBRA AND YP.TPCN2 = 1' ) CONCAT ' ' 
CONCAT ZALBINKHEO . F_BUILDJOINYPAR ( 'LEFT' , 'GENER' , 'TAXRG' , 'RG' , ' AND RG.TCOD = PBRGT' ) CONCAT ' ' 
CONCAT ZALBINKHEO . F_BUILDJOINYPAR ( 'LEFT' , 'PRODU' , 'PBTTR' , 'TR' , ' AND TR.TCOD = PBTTR' ) CONCAT ' ' 
CONCAT ZALBINKHEO . F_BUILDJOINYPAR ( 'LEFT' , 'PRODU' , 'PBSTF' , 'MOTIF' , ' AND MOTIF.TCOD = PBSTF' ) CONCAT ' ' 
CONCAT ZALBINKHEO . F_BUILDJOINYPAR ( 'LEFT' , 'PRODU' , 'PBSIT' , 'SIT' , ' AND SIT.TCOD = PBSIT' ) CONCAT ' ' 
CONCAT ZALBINKHEO . F_BUILDJOINYPAR ( 'LEFT' , 'PRODU' , 'PBNPL' , 'NATURE' , ' AND PBNPL = NATURE.TCOD' ) CONCAT ' ' 
CONCAT ZALBINKHEO . F_BUILDJOINYPAR ( 'LEFT' , 'PRODU' , 'PBETA' , 'ETAT' , ' AND ETAT.TCOD = PBETA' ) CONCAT ' ' 
CONCAT ZALBINKHEO . F_BUILDJOINYPAR ( 'LEFT' , 'GENER' , 'CPAYS' , 'CPAYS' , ' AND CPAYS.TCOD = ABPPAY' ) CONCAT ' ' ; 
  
RETURN TRIM ( P_RETURN ) ; 
END  ; 
  
SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","YALBIN" ; 
  
