CREATE FUNCTION ZALBINKHEO.F_SPLIT ( 
	P_SPT VARCHAR(200) , 
	P_SPLITCHAR VARCHAR(1) , 
	P_PART VARCHAR(1) ) 
	RETURNS VARCHAR(200)   
	LANGUAGE SQL 
	SPECIFIC ZALBINKHEO.F_SPLIT 
	NOT DETERMINISTIC 
	READS SQL DATA 
	CALLED ON NULL INPUT 
	NO EXTERNAL ACTION 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
  
  
DECLARE V_RETVAL VARCHAR ( 200 ) DEFAULT '' ; 
  
DECLARE V_POSITION INTEGER DEFAULT 0 ; 
SET V_POSITION = LOCATE ( P_SPLITCHAR , P_SPT ) ; 
IF ( LOCATE ( P_SPLITCHAR , P_SPT ) = 0 ) THEN 
SET V_RETVAL = '' ; 
--RETURN '' ; 
END IF ; 
  
IF ( P_PART = 'L' ) THEN 
SET V_RETVAL = SUBSTR ( P_SPT , 1 , LOCATE ( P_SPLITCHAR , P_SPT ) - 1 ) ; 
--RETURN SUBSTR ( P_SPT , 1 , LOCATE ( P_SPLITCHAR , P_SPT ) - 1 ) ; 
ELSE 
SET V_RETVAL = SUBSTR ( P_SPT , V_POSITION + 1 , LENGTH ( P_SPT ) - LOCATE ( P_SPLITCHAR , P_SPT ) ) ; 
--RETURN SUBSTR ( P_SPT , V_POSITION + 1 , LENGTH ( P_SPT ) - LOCATE ( P_SPLITCHAR , P_SPT ) ) ; 
END IF ; 
  
RETURN V_RETVAL ; 
  
END  ; 
  
