CREATE OR REPLACE FUNCTION ZALBINKHEO.F_TO_TIMESTAMP_SAFE (VAL DECIMAL(19))
RETURNS TIMESTAMP
DETERMINISTIC
NO EXTERNAL ACTION CONTAINS SQL
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '22018' -- ON CONVERSION ERROR
    RETURN NULL;
  DECLARE CONTINUE HANDLER FOR SQLSTATE '22007' -- ON CONVERSION ERROR
    RETURN NULL;
  RETURN CAST(CONCAT(CAST(IFNULL(VAL , 0) AS VARCHAR(20)) , '000000') AS TIMESTAMP);
END;